Repository symfony/symfony-docs, pull requests merged in 2018-07, with the labels that each got.

#9990 Tell about ServiceLocatorTagPass::register()
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#9992 ChoiceValidator : remove 'strict' option
  reference/constraints/Choice.rst
Labels: Status: Reviewed, Validator

#9984 [Cache] Add note about lazy=true option
  components/cache/adapters/redis_adapter.rst
Labels: Cache, Status: Reviewed

#9997 More fixes about Twig classes namespaces
  best_practices/templates.rst
  components/form.rst
  service_container.rst
Labels: Status: Needs Review

#10002 Fixed a minor sorting error
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10003 Fixed another issue cause by options reorganization
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10005 Removed the full config dump of FrameworkBundle
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10006 Fixed more sorting issues in config options
  reference/configuration/framework.rst
  reference/configuration/swiftmailer.rst
Labels: Status: Needs Review

#10007 Fixed a nested option syntax issue
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10008 Fixed some nested options issues
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10009 Added key env processor to docs
  configuration/external_parameters.rst
Labels: DependencyInjection, Missing Documentation, Status: Reviewed

#9989 Tell about controllers in doc about service subscribers
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#10010 Simplify Apache config with FallbackResource
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#10014 Removed the code of the PHP templates
  controller/upload_file.rst
  doctrine/registration_form.rst
  form/action_method.rst
  form/create_custom_field_type.rst
  form/create_form_type_extension.rst
  form/dynamic_form_modification.rst
  form/embedded.rst
  form/form_collections.rst
  form/form_customization.rst
  form/form_themes.rst
  form/rendering.rst
  http_cache/esi.rst
  routing/generate_url_javascript.rst
  security/csrf_in_login_form.rst
  security/form_login.rst
  security/form_login_setup.rst
  security/impersonating_user.rst
  security/remember_me.rst
  templating/app_variable.rst
  templating/embedding_controllers.rst
  templating/escaping.rst
  templating/formats.rst
  templating/hinclude.rst
  templating/render_without_controller.rst
Labels: Status: Needs Review

#10019 [Messenger] Minor wording tweak regarding factories
  messenger.rst
Labels: Messenger, Status: Reviewed

#10024 Removed the PHP templates from Symfony 4.0 docs
  translation/debug.rst
Labels: Status: Needs Review

#9996 Tell about ProcessorInterface in logging/processors
  logging/processors.rst
Labels: Monolog, Status: Reviewed

#9985 [Cache] add Redis options compression and tcp_keepalive
  components/cache/adapters/redis_adapter.rst
Labels: Cache, Status: Reviewed

#10026 Mention the DoctrineTestBundle for tests that interact with the database
  testing/database.rst
Labels: Status: Reviewed, Testing

#9987 json-login-ldap
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#10033 update Twig documentation links
  best_practices/configuration.rst
  best_practices/templates.rst
  components/form.rst
  contributing/documentation/standards.rst
  create_framework/http_foundation.rst
  introduction/from_flat_php_to_symfony2.rst
  page_creation.rst
  quick_tour/the_big_picture.rst
  quick_tour/the_view.rst
  reference/configuration/twig.rst
  reference/dic_tags.rst
  reference/forms/twig_reference.rst
  reference/twig_reference.rst
  templating.rst
  templating/escaping.rst
  templating/twig_extension.rst
Labels: Status: Reviewed

#10036 fix code block indentation
  form/form_themes.rst
Labels: Status: Needs Review

#10037 render versionadded directive outside the code block
  templating/twig_extension.rst
Labels: Status: Needs Review

#10032 remove remaining AppBundle references
  reference/twig_reference.rst
  service_container/service_decoration.rst
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed

#10039 update the serializer cache description
  reference/configuration/framework.rst
  serializer.rst
Labels: Serializer, Status: Reviewed

#10041 Add section about anonymous services in YAML
  service_container/alias_private.rst
Labels: DependencyInjection, Status: Reviewed

#10040 remove reference to Assetic
  frontend.rst
Labels: Status: Reviewed

#10031 the product category must be nullable
  doctrine/associations.rst
Labels: Status: Needs Review

#10030 Update routing.rst, Replace Controller by AbstractController
  routing.rst
Labels: Status: Reviewed

#10045 Replace more occurrences of Controller by AbstractController
  controller.rst
  controller/forwarding.rst
  security/csrf.rst
Labels: Status: Needs Review

#10048 Remove redundant example configuration value
  service_container/alias_private.rst
Labels: DependencyInjection, Status: Reviewed

#10047 Moved PHP-related code from Forms to the PHP templating page
  form/form_customization.rst
  templating/PHP.rst
Labels: Form, Status: Needs Review

#10044 [Messenger] add XML and PHP code blocks
  messenger.rst
Labels: Messenger, Status: Reviewed

#9757 [Messenger] Add the Envelope in the documentation
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10059 hide Assetic pages from TOC
  _build/redirection_map
  frontend.rst
  frontend/assetic/index.rst
  frontend/encore/versus-assetic.rst
Labels: Front-end, Status: Reviewed

#10049 Mention how to inject a specific Monolog service
  logging/channels_handlers.rst
Labels: DependencyInjection, Status: Needs Review

#10050 Minor reword of deployment article when using Flex
  deployment.rst
Labels: Status: Needs Review

#10051 Added a caution note about race conditions in EntityType
  reference/constraints/UniqueEntity.rst
Labels: Doctrine, Status: Needs Review

#10052 Link to the env vars article from the Best Practices
  best_practices/configuration.rst
Labels: Status: Needs Review

#10054 Improved the section about overriding bundle services
  bundles/override.rst
  service_container/compiler_passes.rst
Labels: Status: Needs Review

#10061 Fix How to dynamically Generate Forms Based on user Data
  form/dynamic_form_modification.rst
Labels: Form, Status: Reviewed

#10066 Refactor a security code example to make it easier to understand
  security/custom_provider.rst
Labels: Security, Status: Reviewed

#10056 Fixed the default value of php_errors.log option
  reference/configuration/framework.rst
Labels: Bug, Status: Needs Review

#10072 Fixed the preferred_choices option for Enttiy type
  reference/forms/types/entity.rst
Labels: Form, Status: Reviewed

#10078 Fixing syntax error
  components/asset.rst
Labels: Status: Reviewed, Webpack Encore

#10079 Fixed a syntax issue
  components/serializer.rst
Labels: Status: Needs Review

#10077 [Security] Remember me: samesite cookie
  security/remember_me.rst
Labels: Security, Status: Reviewed

#10075 Add missing colon to reserved chars
  components/cache/cache_items.rst
Labels: Cache, Status: Reviewed

#10082 Doctrine server_version should always be a string
  reference/configuration/doctrine.rst
Labels: Doctrine, Status: Reviewed

#10084 Fix the YAML syntax highlighting
  console/request_context.rst
Labels: Bug, Console, Status: Needs Review

#10083 Fix typo in remember_me chapter
  security/remember_me.rst
Labels: Status: Reviewed

#10085 Remove occurrences of "performant"
  components/cache/adapters/php_array_cache_adapter.rst
  http_cache.rst
Labels: Status: Needs Review

#10087 Fixed some wrong examples about service config
  service_container.rst
  service_container/service_subscribers_locators.rst
Labels: Bug, Status: Needs Review

#10089 Merged the output of another command with its command line
  routing.rst
Labels: Status: Needs Review

#10090 Show console table examples in a console terminal
  components/console/helpers/table.rst
Labels: Status: Needs Review

#10086 Replace entry/section by "article"
  components/http_foundation/session_configuration.rst
  components/security/firewall.rst
  deployment.rst
  doctrine/event_listeners_subscribers.rst
  doctrine/repository.rst
  form/create_custom_field_type.rst
  form/dynamic_form_modification.rst
  form/form_collections.rst
  introduction/http_fundamentals.rst
  routing.rst
  security/acl.rst
  security/api_key_authentication.rst
  security/custom_authentication_provider.rst
  security/custom_password_authenticator.rst
  security/custom_provider.rst
  security/entity_provider.rst
  service_container/scopes.rst
  setup/new_project_git.rst
  setup/new_project_svn.rst
Labels: Status: Needs Review

#10088 Showed the output of the command in the same CLI window
  service_container.rst
Labels: Status: Needs Review

#10092 [Messenger] Transport not mandatory
  messenger.rst
Labels: Messenger, Status: Reviewed

#10106 Updated the Symfony Flex server
  page_creation.rst
  quick_tour/flex_recipes.rst
Labels: Status: Needs Review

#10103 Documented the findByCodes() validation method
  components/validator.rst
Labels: Missing Documentation, Status: Needs Review, Validator

#10095 Documented the enableExceptionOnInvalidIndex() method
  components/property_access.rst
Labels: Missing Documentation, PropertyAccess, Status: Needs Review

#10098 Documented the catchExceptions() method
  testing.rst
Labels: Missing Documentation, Status: Needs Review, Testing

#10099 Update the argument value resolver article
  controller/argument_value_resolver.rst
Labels: Status: Needs Review

#10107 Fixed some config file paths for Flex and Symfony 4
  controller/argument_value_resolver.rst
  reference/configuration/security.rst
Labels: Status: Needs Review

#10112 [Cache] minor tweaks
  components/cache.rst
  components/cache/adapters/pdo_doctrine_dbal_adapter.rst
  components/cache/cache_invalidation.rst
  components/cache/cache_pools.rst
Labels: Cache, Status: Reviewed

#10111 [Cache] tell about PDO configuration and table autocreation
  components/cache/adapters/pdo_doctrine_dbal_adapter.rst
  reference/configuration/framework.rst
Labels: Cache, Missing Documentation, Status: Reviewed

#10100 Fixed the code of the custom password authenticator example
  security/custom_password_authenticator.rst
Labels: Bug, Security, Status: Needs Review

#10096 Documented PHPUnit data providers
  best_practices/tests.rst
  form/unit_testing.rst
  testing.rst
Labels: Status: Needs Review, Testing

#9983 [Routing] do not install SensioFrameworkExtraBundle
  routing.rst
Labels: Routing, Status: Reviewed

#10115 Add file_relative function to the Twig reference
  reference/twig_reference.rst
Labels: Missing Documentation, Status: Reviewed, Twig

#10053 Explain another option to override bundle's entity mapping
  bundles/override.rst
Labels: Status: Reviewed

#10038 [Finder] Add documentation and code on array as method parameter
  components/finder.rst
Labels: Finder, Status: Reviewed

#10123 Updated one screencast URL for Symfony 4
  security.rst
Labels: Status: Needs Review

#10125 Use callable classes for custom Monolog processors
  logging/processors.rst
Labels: Status: Reviewed

#10126 Improve the docs about custom form theme config
  form/form_themes.rst
Labels: Form, Status: Needs Review

#10124 Mentioned the audit_trail workflow option
  workflow/usage.rst
Labels: Missing Documentation, Status: Needs Review, Workflow

#10070 Remove example of register a service where its id match to its class
  service_container/definitions.rst
Labels: DependencyInjection, Status: Reviewed
