Repository symfony/symfony-docs, pull requests merged in 2018-06, with the labels that each got.

#9862 [Routing] Add documentation for prefixing i18n routes with a locale
  routing.rst
Labels: Routing, Status: Reviewed

#9671 [Finder] Described "use natural sort" option
  components/finder.rst
Labels: Finder, Missing Documentation, Status: Reviewed

#9868 Fix the page title for the mbstring polyfill
  components/polyfill_mbstring.rst
Labels: Status: Reviewed

#9869 Use version number in installer command
  setup.rst
Labels: Bug, Status: Reviewed

#9873 [Serializer] Fix the interface/abstract classes documentation
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#9872 Fix typo in Memcached adapter documentation
  components/cache/adapters/memcached_adapter.rst
Labels: Cache, Status: Reviewed

#9652 Add doc for framework.cache.pools.tags
  reference/configuration/framework.rst
Labels: Cache, FrameworkBundle, Missing Documentation, Status: Needs Review

#9880 Add composer require symfony/webpack-encore-pack
  frontend/encore/installation.rst
Labels: Status: Reviewed, Webpack Encore

#9877 Reword the intro of a console article
  components/console/console_arguments.rst
Labels: Console, Status: Needs Review

#9883 Change code file location
  console/commands_as_services.rst
Labels: Bug, Console, Status: Reviewed

#9882 Update upgrade_major.rst
  setup/upgrade_major.rst
Labels: Status: Reviewed

#9871 add missing XML and PHP code examples
  configuration/external_parameters.rst
Labels: Status: Reviewed

#9896 remove not existent label_attr options from buttons
  reference/forms/types/reset.rst
  reference/forms/types/submit.rst
Labels: Bug, Form, Status: Reviewed

#9900 Update Git setup
  setup.rst
Labels: Status: Reviewed

#9904 [Filesystem] Improved the code of an example
  components/filesystem.rst
Labels: Filesystem, Status: Needs Review

#9892 Use <button> instead of <a> for JavaScript interactive buttons
  form/form_collections.rst
  reference/forms/types/collection.rst
Labels: Status: Reviewed

#9911 Use matching closing tag
  form/form_collections.rst
  reference/forms/types/collection.rst
Labels: Bug, Status: Reviewed

#9913 Mistake in http_foundation.rst
  components/http_foundation.rst
Labels: Bug, HttpFoundation, Status: Reviewed

#9925 Fix a configuration block in the Doctrine Associations page
  doctrine/associations.rst
Labels: Status: Reviewed

#9899 Mentioned Debian explicitly
  components/http_foundation/session_configuration.rst
Labels: Status: Reviewed, Waiting feedback

#9932 Fixed typos
  components/cache/adapters/chain_adapter.rst
  components/cache/cache_pools.rst
  frontend/encore/legacy-apps.rst
  security/ldap.rst
Labels: Status: Reviewed

#9921 Security - Fix numbering on 4.*
  security.rst
Labels: Security, Status: Reviewed

#9919 use is_granted() instead of deprecated has_role()
  best_practices/security.rst
  security.rst
  security/access_control.rst
  security/expressions.rst
Labels: Deprecation, Security, Status: Reviewed

#9937 Update Best Practices about service config format
  best_practices/business-logic.rst
Labels: DependencyInjection

#9938 add legacy labels
  security.rst
Labels: Bug, Security

#9940 Updated the default values of some Cache config options
  reference/configuration/framework.rst
Labels: Bug, Cache, Status: Reviewed

#9859 [OptionsResolver] Document setDeprecated method
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#9943 Fix configuration-block not working
  routing/redirect_in_config.rst
Labels: Bug, Status: Reviewed

#9942 Change form.xxx_bind to form.xxx_submit
  form/events.rst
Labels: Form, Status: Reviewed

#9950 Added a missing versionadded directive for 307/308 redirects
  routing/redirect_in_config.rst
Labels: Status: Reviewed

#9953 Formatting: Apply PSR-2 formatting to code example
  doctrine/registration_form.rst
Labels: Status: Reviewed

#9959 bugfixes should be placed for the 2.8 branch
  README.markdown
  contributing/code/patches.rst
  reference/forms/types/choice.rst
Labels: Status: Needs Review

#9956 Fixed minor typo
  service_container.rst
Labels: Status: Reviewed

#9916 [Form] Ability to clear form errors
  components/form.rst
Labels: Form, Status: Reviewed

#9964 Added a note about hidden questions, windows and tests
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Reviewed, Testing

#9968 Install component for dev environment
  components/var_dumper.rst
Labels: Bug, Status: Reviewed, VarDumper

#8914 Add new serializer empty_data feature doc
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#9969 Explained some issues about command constructors and configure
  console.rst
Labels: Console, Status: Reviewed

#9972 Use the ReadTheDocs theme as the default Sphinx theme
  _build/_theme/_templates/globaltoc.html
  _build/_theme/_templates/layout.html
  _build/_theme/_templates/localtoc.html
  _build/_theme/assets/css/app.css
  _build/_theme/assets/css/doc.css
  _build/_theme/assets/js/app.js
  _build/_theme/assets/js/doc.js
  _build/_theme/assets/js/manifest.js
  _build/_themes/_exts/symfonycom/__init__.py
  _build/_themes/_exts/symfonycom/sphinx/__init__.py
  _build/_themes/_exts/symfonycom/sphinx/lexer.py
  _build/_themes/sphinx_rtd_theme/__init__.py
  _build/_themes/sphinx_rtd_theme/breadcrumbs.html
  _build/_themes/sphinx_rtd_theme/footer.html
  _build/_themes/sphinx_rtd_theme/layout.html
  _build/_themes/sphinx_rtd_theme/search.html
  _build/_themes/sphinx_rtd_theme/searchbox.html
  _build/_themes/sphinx_rtd_theme/static/css/badge_only.css
  _build/_themes/sphinx_rtd_theme/static/css/theme.css
  _build/_themes/sphinx_rtd_theme/static/fonts/FontAwesome.otf
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.eot
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.ttf
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff2
  _build/_themes/sphinx_rtd_theme/static/js/modernizr.min.js
  _build/_themes/sphinx_rtd_theme/static/js/theme.js
  _build/_themes/sphinx_rtd_theme/theme.conf
  _build/_themes/sphinx_rtd_theme/versions.html
  _build/conf.py
Labels: Status: Needs Review

#9971 Added a note about command aliases and services
  console/commands_as_services.rst
Labels: Console, Missing Documentation, Status: Needs Review

#9975 Fix typo in the Twig article
  reference/configuration/twig.rst
Labels: Bug, Status: Reviewed, Twig

#9973 [DoctrineBridge] update doctrine event listeners doc for Symfony 4.2 change
  doctrine/event_listeners_subscribers.rst
Labels: Doctrine, Status: Reviewed

#9974 [testing] tell about self::$container
  testing.rst
Labels: Status: Reviewed, Testing
