Repository symfony/symfony-docs, pull requests merged in 2018-02, with the labels that each got.

#9242 Documented the name prefix feature for YAML, XML and PHP files
  routing/external_resources.rst
Labels: Routing, Status: Needs Review

#9243 Fixed a missing reference
  security/form_login_setup.rst
Labels: Bug, Status: Needs Review

#9244 Updated the Guard diagram to add the new supports() method
  _images/security/authentication-guard-methods.svg
  _images/sources/security/authentication-guard-methods.dia
Labels: Security, Status: Needs Review

#9245 Added a note about the dangers of dumping $_SERVER and $_ENV
  best_practices/configuration.rst
  configuration/external_parameters.rst
Labels: Security, Status: Reviewed

#9255 fix code block syntax
  service_container.rst
Labels: Status: Reviewed

#9209 Clearer wording of allow_delete template behavior
  form/form_collections.rst
Labels: Form, Status: Reviewed

#9258 Fix: Typo
  testing/database.rst
Labels: Status: Reviewed

#9260 Use HTTPS instead of HTTP outside XML
  best_practices/business-logic.rst
  best_practices/creating-the-project.rst
  bundles/best_practices.rst
  components/class_loader.rst
  components/class_loader/cache_class_loader.rst
  components/class_loader/class_loader.rst
  components/class_loader/class_map_generator.rst
  components/class_loader/map_class_loader.rst
  components/class_loader/psr4_class_loader.rst
  components/console/logger.rst
  components/event_dispatcher.rst
  components/finder.rst
  components/http_foundation/session_configuration.rst
  components/http_kernel.rst
  components/intl.rst
  components/phpunit_bridge.rst
  components/process.rst
  components/psr7.rst
  components/serializer.rst
  contributing/code/bc.rst
  contributing/code/bugs.rst
  contributing/code/patches.rst
  contributing/code/standards.rst
  contributing/community/releases.rst
  controller/soap_web_service.rst
  create_framework/http_foundation.rst
  create_framework/http_kernel_controller_resolver.rst
  create_framework/templating.rst
  create_framework/unit_testing.rst
  deployment/azure-website.rst
  doctrine/dbal.rst
  forms.rst
  performance.rst
  reference/constraints/GreaterThan.rst
  reference/constraints/GreaterThanOrEqual.rst
  reference/constraints/LessThan.rst
  reference/constraints/LessThanOrEqual.rst
  reference/constraints/Range.rst
  reference/constraints/Type.rst
  reference/forms/types/datetime.rst
  reference/forms/types/options/_date_limitation.rst.inc
  reference/forms/types/options/date_format.rst.inc
  reference/forms/types/options/model_timezone.rst.inc
  reference/forms/types/options/view_timezone.rst.inc
  setup.rst
  setup/built_in_web_server.rst
  setup/homestead.rst
  setup/new_project_git.rst
  setup/new_project_svn.rst
  setup/web_server_configuration.rst
  testing.rst
Labels: Status: Reviewed

#9261 Remember me: replace a reference to Symfony SE
  security/remember_me.rst
Labels: Status: Reviewed

#9262 Framework config: remove a reference to Symfony SE
  reference/configuration/framework.rst
Labels: Status: Reviewed

#9263 Custom route loader: remove a ref to Symfony SE
  routing/custom_route_loader.rst
Labels: Status: Reviewed

#9265 Duplicate import in sample service.rst
  controller/service.rst
Labels: Status: Reviewed

#9269 Mention that argon2i doesn't need a salt either
  security/entity_provider.rst
Labels: Status: Needs Review

#9270 Fix in line numbering
  doctrine.rst
Labels: Status: Reviewed

#9273 ExtractorInterface instead of Extractor (page not found)
  reference/dic_tags.rst
Labels: Status: Reviewed

#9276 Fixed a minor error in form collections example
  reference/forms/types/collection.rst
Labels: Form, Status: Needs Review

#9279 Deprecated the AdvancedUserInterface
  security/entity_provider.rst
Labels: Security, Status: Needs Review

#9282 Controller naming habits
  controller.rst
Labels: Status: Reviewed

#9297 Use "setAttribute" method
  components/ldap.rst
Labels: Bug, Ldap, Status: Reviewed

#9292 Documented the default values of Accept headers
  components/http_foundation.rst
Labels: HttpFoundation, Missing Documentation, Status: Needs Review

#9286 Use 308 to ensure http method is preserved
  routing/redirect_trailing_slash.rst
Labels: Status: Reviewed

#9303 Mentioned the new "box" console style
  components/console/helpers/table.rst
Labels: Console, Status: Needs Review

#9302 Added the name attribute to XLIFF 2 documents
  components/translation/usage.rst
Labels: Status: Needs Review, Translation

#9311 [Form] Fix typo
  components/form.rst
Labels: Form, Status: Reviewed

#9248 [Validator] Add docs for "canonicalize" option at `Locale` validation constraint
  reference/constraints/Locale.rst
Labels: Status: Reviewed

#9318 [PHPUnit Bridge] fixing second stopwatch example
  components/phpunit_bridge.rst
Labels: Status: Reviewed

#9316 fix console script path
  configuration/multiple_kernels.rst
  reference/events.rst
  translation/lint.rst
Labels: Status: Needs Review

#9315 improve validation groups references
  validation/groups.rst
  validation/sequence_provider.rst
Labels: Status: Needs Review

#9319 fix console script path
  configuration/multiple_kernels.rst
  reference/configuration/framework.rst
  reference/events.rst
Labels: Status: Reviewed

#9323 advise to use user checkers instead
  security/entity_provider.rst
Labels: Security, Status: Reviewed

#9326 [#9248] some minor tweaks
  reference/constraints/Locale.rst
Labels: Status: Reviewed, Validator

#9327 Fixed a versionadded directive
  components/translation/usage.rst
Labels: Status: Needs Review

#9325 remove old versionadded directives
  components/security/firewall.rst
  components/translation/usage.rst
  components/yaml.rst
  routing/custom_route_loader.rst
  service_container.rst
  validation/sequence_provider.rst
Labels: Status: Needs Review

#9328 Markup in Config Validation example
  components/config/definition.rst
Labels: Status: Reviewed

#9335 Update requirements.rst
  reference/requirements.rst
Labels: Status: Reviewed

#9334 Fix static method call
  components/console/helpers/progressbar.rst
Labels: Status: Reviewed

#9341 fix PHP code
  service_container.rst
Labels: Status: Needs Review

#9350 Update flex.rst - Add step in migration-process
  setup/flex.rst
Labels: Status: Reviewed

#9267 Update Documentation excluded_ajax_paths sf4
  reference/configuration/web_profiler.rst
Labels: Status: Reviewed

#9355 use diff code block
  setup/flex.rst
Labels: Status: Reviewed
