Repository symfony/symfony-docs, pull requests merged in 2018-10, with the labels that each got.

#10416 Update routing.rst
  routing.rst
Labels: Status: Reviewed

#10421 fix code example
  deployment/proxies.rst
Labels: Status: Reviewed

#10424 Mention vscode on IDE config
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10427 [Serializer] Add an option to skip null values
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#10429 Replace "set leave" with leave only
  reference/constraints/Image.rst
Labels: Status: Reviewed

#10425 Improved the explanation of naming in PHP and Twig
  contributing/code/standards.rst
Labels: Status: Needs Review

#10434 clarify the datetime format option
  reference/forms/types/datetime.rst
Labels: Form, Status: Reviewed

#10446 Added link to bcrypt (Wikipedia)
  doctrine/registration_form.rst
Labels: Status: Reviewed

#10437 Added a caution note about the checkMX option
  reference/constraints/Email.rst
Labels: Status: Needs Review, Validator

#10154 [Command] No need to register the command manually
  console.rst
Labels: Status: Reviewed

#10178 Resolve T_STRING
  doctrine/reverse_engineering.rst
Labels: Status: Reviewed

#10448 Fixed the logic of the custom password authenticator
  security/custom_password_authenticator.rst
Labels: Status: Reviewed

#10452 fix the command output
  service_container.rst
Labels: Status: Reviewed

#10455 fix the server:status command description
  setup/built_in_web_server.rst
Labels: Status: Reviewed

#10454 Updated class reference in Callback validator from the deprecated to the current class.
  reference/constraints/Callback.rst
Labels: Status: Reviewed

#10456 Added 'Default' validation group
  form/validation_groups.rst
Labels: Status: Reviewed

#10457 [Form][Validation] User $user instead of $users
  form/validation_groups.rst
Labels: Form, Status: Reviewed

#10463 Update form_login_setup.rst
  security/form_login_setup.rst
Labels: Status: Reviewed

#10458 [VarDumper] Enhance the ServerDumper documentation
  components/var_dumper.rst
  reference/configuration/debug.rst
Labels: Status: Reviewed, VarDumper

#10469 [VarDumper] Add missing use statements
  components/var_dumper.rst
Labels: Status: Reviewed, VarDumper

#10449 fix #310430: DomCrawler component selectButton() docs update
  components/dom_crawler.rst
Labels: DOMCrawler, Status: Reviewed

#10420 Update routing.rst
  routing.rst
Labels: Bug, Routing, Status: Reviewed

#10359 [Security] - Document the port in access_control
  security/access_control.rst
Labels: Security, Status: Reviewed

#10473 [Messenger] Fix messenger.routing send_and_handle config
  messenger.rst
Labels: Messenger, Status: Reviewed

#10439 [OptionsResolver] Documenting Options argument for closure deprecation func
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#10445 Add deprecation notice for --env and --no-debug
  configuration/environments.rst
  deployment.rst
  email/spool.rst
  testing/bootstrap.rst
Labels: Status: Reviewed

#10488 Fix function name in expression
  security/expressions.rst
Labels: Bug, Security, Status: Reviewed

#10491 Improved the docs of the instanceof config
  service_container/tags.rst
Labels: DependencyInjection, Status: Needs Review

#10492 Add some lines of doc for waitUntil() (Process)
  components/process.rst
Labels: Process, Status: Reviewed

#10493 Some punctuation not properly placed
  frontend/encore/simple-example.rst
Labels: Status: Reviewed

#10499 Note how to use multiple Guard Authenticators with different User Providers
  security/multiple_guard_authenticators.rst
Labels: Security, Status: Reviewed

#10470 Update conditions.rst
  routing/conditions.rst
Labels: Routing, Status: Reviewed

#10508 Fix typo
  security/form_login_setup.rst
Labels: Status: Reviewed

#10513 Fixed minor syntax issues
  security.rst
Labels: Status: Reviewed

#10516 Fixing bad logic, caused by merge originally
  security/guard_authentication.rst
Labels: Status: Needs Review

#10509 Mentioned user_checkers in the main security config reference
  reference/configuration/security.rst
Labels: Security, Status: Needs Review

#10519 fix spacing
  configuration/external_parameters.rst
Labels: Status: Reviewed

#10524 Removed an unnecessary (and outdated) reference
  security/multiple_guard_authenticators.rst
Labels: Bug, Status: Needs Review

#10518 fixed use statement
  security.rst
Labels: Status: Reviewed

#10522 Fix base.html.twig path
  frontend/encore/simple-example.rst
Labels: Status: Reviewed

#10532 Corrected variable name to $security
  security/voters.rst
Labels: Bug, Security, Status: Reviewed

#10537 fix redirection
  _build/redirection_map
Labels: Status: Reviewed

#10531 review "getting started" chapter for belittling words
  controller.rst
  routing.rst
  setup.rst
  templating.rst
Labels: Status: Reviewed

#10533 review "best practice" chapter for belittling words
  best_practices/business-logic.rst
  best_practices/controllers.rst
  best_practices/introduction.rst
  best_practices/templates.rst
  best_practices/tests.rst
Labels: Status: Reviewed

#10500 Deprecating support for legacy templates directory
  reference/configuration/twig.rst
Labels: Status: Reviewed

#10515 [Serializer] Document Normalizers
  serializer/custom_normalizer.rst
  serializer/normalizers.rst
Labels: Serializer, Status: Reviewed

#10540 Update dispatch example
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10543 [Serializer] update doc for 3.4 about normalizer
  serializer/custom_normalizer.rst
Labels: Serializer, Status: Reviewed

#10544 Documented the framework.session.enabled option
  reference/configuration/framework.rst
Labels: Status: Needs Review

#10548 Clarifying that .env can be used on production
  deployment.rst
Labels: Status: Reviewed

#10546 fix the event subscriber code example
  session/locale_sticky_session.rst
Labels: Status: Reviewed

#10549 Update external_parameters.rst
  configuration/external_parameters.rst
Labels: Config, Status: Reviewed

#10556 Add missing container argument for ServiceLocatorTagPass::register() call
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed

#10558 Fix a configuration-block not rendered
  configuration/environments.rst
Labels: Status: Reviewed

#10557 Fixed the versionadded directive (RST syntax)
  logging/monolog_exclude_http_codes.rst
Labels: Status: Reviewed

#10422 Document metadata aware name conversion
  components/serializer.rst
Labels: Status: Reviewed

#10347 Added docs for different protocols as asset base_url
  components/asset.rst
Labels: Status: Reviewed

#10555 fix order of member vars
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10578 Mentioned the checkMX and checkHost deprecation
  reference/constraints/Email.rst
Labels: Status: Needs Review, Validator

#10579 Documented the HeaderUtils::makeDisposition() method
  components/http_foundation.rst
Labels: HttpFoundation, Status: Needs Review

#10582 Fix Use Class
  messenger.rst
Labels: Status: Reviewed

#10580 fix RoleVoter behaviour description
  reference/twig_reference.rst
Labels: Bug, Security, Status: Reviewed

#10581 Deprecated the kernel.name parameter
  reference/configuration/kernel.rst
Labels: HttpKernel, Status: Needs Review

#10507 Added explanation how non-scalar or non-unique choice values are handled
  reference/forms/types/choice.rst
Labels: Form, Status: Reviewed

#10583 Added documentation for the Finder::reverseSorting() method
  components/finder.rst
Labels: Status: Reviewed

#10587 [Form] Deprecated timezone regions option
  reference/forms/types/timezone.rst
Labels: Form, Status: Reviewed

#10585 review single doc pages for belittling words
  bundles.rst
  deployment.rst
  doctrine.rst
  email.rst
  event_dispatcher.rst
  forms.rst
  logging.rst
  routing.rst
  security.rst
  service_container.rst
  testing.rst
  translation.rst
  validation.rst
Labels: Status: Needs Review

#10586 Review components chapter
  components/asset.rst
  components/console/changing_default_command.rst
  components/console/helpers/formatterhelper.rst
  components/console/helpers/progressbar.rst
  components/console/single_command_tool.rst
  components/console/usage.rst
  components/debug.rst
  components/dependency_injection.rst
  components/dependency_injection/compilation.rst
  components/dom_crawler.rst
  components/event_dispatcher.rst
  components/event_dispatcher/generic_event.rst
  components/form.rst
  components/http_foundation.rst
  components/http_foundation/session_configuration.rst
  components/http_foundation/session_testing.rst
  components/http_foundation/sessions.rst
  components/http_kernel.rst
  components/messenger.rst
  components/options_resolver.rst
  components/routing.rst
  components/security/authentication.rst
  components/security/authorization.rst
  components/serializer.rst
  components/stopwatch.rst
  components/templating.rst
  components/translation.rst
  components/translation/custom_formats.rst
  components/translation/usage.rst
  components/using_components.rst
  components/var_dumper/advanced.rst
  components/yaml.rst
Labels: Status: Reviewed

#10596 [Security] The logout_on_user_change firewall option is deprecated
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#10594 Fixes var name in callback
  components/serializer.rst
Labels: Bug, Serializer, Status: Reviewed

#10592 Deprecating support for legacy translations directory
  translation.rst
Labels: Status: Reviewed, Translation

#10590 Revert a change related to flash messages and sessions
  session/avoid_session_start.rst
Labels: Status: Reviewed

#10597 Minor table layout fix
  reference/constraints/File.rst
Labels: Status: Reviewed

#10598 review bundles chapter for belittling words
  bundles/configuration.rst
Labels: Status: Reviewed

#10364 [PHPUnitBridge] Describes how to disable DebugClassLoader
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Reviewed

#10600 Added missing chapters to TOC in file constraints reference
  reference/constraints/File.rst
Labels: Form, Status: Reviewed

#10462 Add option for configuring default UTF-8 encoding for routes
  reference/configuration/framework.rst
Labels: FrameworkBundle, Routing, Status: Reviewed

#10618 [WebLink] Fix composer package and name
  components/weblink.rst
  weblink.rst
Labels: Status: Reviewed

#10619 [Console] Remove invalid note about empty input options
  console/input.rst
Labels: Console, Status: Reviewed

#10617 Added documentation for constraint message parameters
  reference/constraints/Bic.rst
  reference/constraints/Blank.rst
  reference/constraints/CardScheme.rst
  reference/constraints/Choice.rst
  reference/constraints/Collection.rst
  reference/constraints/Count.rst
  reference/constraints/Country.rst
  reference/constraints/Currency.rst
  reference/constraints/Date.rst
  reference/constraints/DateTime.rst
  reference/constraints/Email.rst
  reference/constraints/EqualTo.rst
  reference/constraints/Expression.rst
  reference/constraints/GreaterThan.rst
  reference/constraints/GreaterThanOrEqual.rst
  reference/constraints/Iban.rst
  reference/constraints/IdenticalTo.rst
  reference/constraints/Image.rst
  reference/constraints/Ip.rst
  reference/constraints/IsFalse.rst
  reference/constraints/IsNull.rst
  reference/constraints/IsTrue.rst
  reference/constraints/Isbn.rst
  reference/constraints/Issn.rst
  reference/constraints/Language.rst
  reference/constraints/Length.rst
  reference/constraints/LessThan.rst
  reference/constraints/LessThanOrEqual.rst
  reference/constraints/Locale.rst
  reference/constraints/Luhn.rst
  reference/constraints/NotBlank.rst
  reference/constraints/NotEqualTo.rst
  reference/constraints/NotIdenticalTo.rst
  reference/constraints/NotNull.rst
  reference/constraints/Range.rst
  reference/constraints/Regex.rst
  reference/constraints/Time.rst
  reference/constraints/Type.rst
  reference/constraints/UniqueEntity.rst
  reference/constraints/Url.rst
  reference/constraints/UserPassword.rst
  reference/constraints/Uuid.rst
Labels: Form, Missing Documentation, Status: Reviewed

#10623 Fixed a minor RST syntax issue
  templating/twig_extension.rst
Labels: Bug, Status: Needs Review

#10622 [Validator] Added documentation for message parameters added between 2.8 and 3.4
  reference/constraints/Image.rst
Labels: Missing Documentation, Status: Reviewed, Validator
