Repository symfony/symfony-docs, pull requests merged in 2018-11, with the labels that each got.

#10630 Fix typo
  security.rst
Labels: Security, Status: Reviewed

#10633 Update percent.rst
  reference/forms/types/percent.rst
Labels: Form, Status: Reviewed

#10635 Fixed a formatting issue in WebLink article
  weblink.rst
Labels: Status: Needs Review, WebLink

#10637 Update IsTrue.rst
  reference/constraints/IsTrue.rst
Labels: Bug, Status: Reviewed, Validator

#10625 Update autowiring.rst
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#10483 [Monolog] Move ProcessorInterface to Monolog
  logging/processors.rst
Labels: Status: Reviewed

#10657 Revert "minor #9898 [HttpFoundation] Add info for getAcceptableFormat…
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#10644 [Messenger] Fix documentation after 4.2 BC Breaks
  components/messenger.rst
  messenger.rst
Labels: Messenger, Status: Reviewed

#10639 Update configuration_organization.rst
  configuration/configuration_organization.rst
Labels: Status: Reviewed

#10496 [OptionsResolver] Add some notes about trigger deprecation
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#10658 Update processors.rst
  logging/processors.rst
Labels: Bug, Monolog, Status: Reviewed

#10655 Reduce potential confusion in priority explanation
  components/event_dispatcher.rst
Labels: Status: Reviewed

#10550 [standards] Document "phpdoc_types_order"
  contributing/code/standards.rst
Labels: Status: Reviewed

#10666 Replace SensioLabsConnect by SymfonyConnect
  best_practices/introduction.rst
  contributing/code_of_conduct/care_team.rst
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#10670 Replace connect.sensiolabs.com by connect.symfony.com
  service_container/3.3-di-changes.rst
Labels: Status: Reviewed

#10659 Update doc for Process v4.2
  components/process.rst
Labels: Process, Status: Reviewed

#10653 [Workflow] Update image to reflect given state machine configuration
  _images/components/workflow/pull_request.png
Labels: Status: Reviewed, Workflow

#10678 Remove typo in command
  setup/flex.rst
Labels: Status: Reviewed

#10677 [Messenger] Added handled & sent stamps
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10676 Removed useless parentheses in Assert annotations
  best_practices/forms.rst
  components/validator/resources.rst
  doctrine/registration_form.rst
  form/embedded.rst
  forms.rst
  reference/constraints/Bic.rst
  reference/constraints/Blank.rst
  reference/constraints/Country.rst
  reference/constraints/Date.rst
  reference/constraints/DateTime.rst
  reference/constraints/IsNull.rst
  reference/constraints/Language.rst
  reference/constraints/Locale.rst
  reference/constraints/NotBlank.rst
  reference/constraints/NotNull.rst
  reference/constraints/Time.rst
  reference/constraints/UniqueEntity.rst
  reference/constraints/Url.rst
  reference/constraints/Valid.rst
  validation.rst
  validation/sequence_provider.rst
Labels: Status: Reviewed

#10441 [Encore] Add a section about the configureRuntimeEnvironment method
  frontend/encore/advanced-config.rst
Labels: Status: Needs Review, Webpack Encore

#10682 Remove beta command since skeleton isn't tagged
  setup/unstable_versions.rst
Labels: Status: Reviewed

#10686 [Encore] Fixed code example for SplitChunks
  frontend/encore/split-chunks.rst
Labels: Status: Reviewed

#10693 Moving bootstrap.php to config
  configuration/dot-env-changes.rst
Labels: Status: Needs Review

#10709 [#10664] minor tweaks after merging into 4.2 (bis)
  components/messenger.rst
  messenger.rst
Labels: Messenger, Status: Reviewed

#10401 Update uglifyjs.rst
  frontend/assetic/uglifyjs.rst
Labels: Assetic, Status: Reviewed

#10690 Rename UserFixture to UserFixtures
  security.rst
Labels: Status: Reviewed

#10712 Duplicate composer require in Your First Functional Test chapter
  testing.rst
Labels: Bug, Status: Reviewed, Testing

#10480 Update to micro_kernel_trait.rst
  configuration/micro_kernel_trait.rst
Labels: Status: Reviewed

#10704 Don't recommend requiring with Composer
  setup.rst
Labels: Status: Reviewed
