Repository symfony/symfony-docs, pull requests merged in 2018-09, with the labels that each got.

#10247 [HttpFoundation] Small fixes on some examples
  components/http_foundation.rst
Labels: Bug, HttpFoundation, Status: Reviewed

#10245 [Asset Component] Adding a semicolon at the end of a PHP statement
  components/asset.rst
Labels: Status: Reviewed

#10243 Fixed Modifying Rendered Tables example
  components/console/helpers/table.rst
Labels: Bug, Console, Status: Reviewed

#10225 [HttpFoundation] Broken nginx XSendfile link
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#10248 [RST] Use SCSS instead of CSS for code block
  frontend/encore/bootstrap.rst
Labels: Status: Reviewed

#10252 [URL] Update link to use latest Laravel docs version
  frontend.rst
Labels: Status: Reviewed

#10122 Update translator fallback example to include ICU parents
  components/translation.rst
Labels: Status: Reviewed, Translation

#10108 [Routing] Add locale fallback to internationalized routes
  routing.rst
Labels: Routing, Status: Reviewed

#9568 Document the DotEnv::overload() method
  components/dotenv.rst
Labels: Dotenv, Status: Reviewed

#10257 Remove the changelog file
  changelog.rst
Labels: Status: Reviewed

#10256 Remove Romain as part of the core team
  contributing/code/core_team.rst
Labels: Status: Needs Review

#10239 Adding check for environments
  profiler/matchers.rst
Labels: Status: Needs Review

#10258 Added docs for cookie_samesite option
  reference/configuration/framework.rst
Labels: HttpFoundation, Status: Needs Review

#10260 Fixed the default value of cookie_samesite
  reference/configuration/framework.rst
Labels: Bug, HttpFoundation, Status: Needs Review

#10265 Small fix to syntax of Return Type Declaration
  components/messenger.rst
Labels: Status: Reviewed

#10232 Documenting debug:twig command
  templating/debug.rst
  templating/namespaced_paths.rst
  templating/twig_extension.rst
Labels: Status: Reviewed

#10267 [Messenger] Fix syntax of Return Type Declaration
  messenger.rst
Labels: Messenger, Status: Reviewed

#10268 [Messenger] Error in XML configuration
  messenger.rst
Labels: Messenger, Status: Reviewed

#10305 Fix broken link to Security tutorial
  security.rst
Labels: Status: Reviewed

#10303 PhpUnit Bridge: Fixes typo in note
  components/phpunit_bridge.rst
Labels: Status: Reviewed

#10284 Documented the "auto" mode of "cookie_secure"
  reference/configuration/framework.rst
Labels: FrameworkBundle, Security, Status: Needs Review

#10275 Added docs for VAR_DUMPER_FORMAT
  components/var_dumper.rst
Labels: Status: Needs Review, VarDumper

#10306 [Validator] Improve condition in if statement
  components/validator.rst
Labels: Validator

#10314 [Serializer] Allow to specify a single value in @Groups
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#10320 [FrameworkBundle] Improve the DX of TemplateController
  templating/render_without_controller.rst
Labels: FrameworkBundle, Status: Reviewed

#10319 [PropertyInfo] Add an extractor to guess if a property is initializable
  components/property_info.rst
Labels: PropertyInfo, Status: Reviewed

#10318 [Serializer] Allow to access to the context and various other infos in callbacks and max depth handler
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#10317 [Serializer] Allow to access extra infos in name converters
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#10327 Fix link for webpack encore
  deployment.rst
Labels: Status: Reviewed

#10324 Missing root node in yaml example
  components/config/definition.rst
Labels: Bug, Config, Status: Reviewed

#10323 Fix a typo in security/impersonating_user
  security/impersonating_user.rst
Labels: Status: Reviewed

#10328 [flex] use latest skeleton version in example
  setup/flex.rst
Labels: Status: Reviewed

#10329 Fix typo and add weblink in core_team.rst
  contributing/code/core_team.rst
Labels: Status: Reviewed

#10330 Shorten ternary operator in Twig expression
  frontend/encore/server-data.rst
Labels: Front-end, Status: Reviewed

#10316 [Serializer] Cache the normalizer to use when possible
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#10354 correct a typo in a namespace loading
  bundles/extension.rst
Labels: DependencyInjection, Status: Reviewed

#10352 [Fix] Fixed the link to Functional Tests
  testing.rst
Labels: Status: Reviewed, Testing

#10353 There is no public folder in 3.4
  frontend/encore/installation-no-flex.rst
Labels: Status: Reviewed, Webpack Encore

#10356 [Front-end] Change public folder to web for 3.4
  frontend/encore/simple-example.rst
Labels: Status: Needs Review

#10355 [Fix] Updated KnpUniversity links to SymfonyCasts
  doctrine.rst
  doctrine/associations.rst
  forms.rst
  frontend.rst
  page_creation.rst
  security.rst
  service_container.rst
  setup.rst
Labels: Status: Needs Review

#10365 Use cross references for internal links
  best_practices/forms.rst
  reference/forms/types/form.rst
Labels: Best Practices, Form, Status: Reviewed

#10366 Remove obsolete reference
  setup.rst
Labels: Status: Reviewed

#10368 [Translation] Added support for multiple files or directories in XliffLintCommand
  translation/lint.rst
Labels: Status: Reviewed, Translator

#10367 [Yaml] Documenting support for multiple files or directories
  components/yaml.rst
Labels: Status: Reviewed, YAML

#10043 Add documentation for using Zookeeper data store for lock component
  components/lock.rst
Labels: Lock, Status: Reviewed

#10377 [Syntax] Remove unnecessary semicolons
  components/process.rst
  security.rst
  templating/PHP.rst
Labels: Status: Reviewed

#10379 [Demo] Fix Symfony demo link
  setup.rst
Labels: Status: Reviewed

#10376 [Syntax] Change to short php echo tags
  components/process.rst
  components/templating.rst
  components/templating/slotshelper.rst
  create_framework/front_controller.rst
  create_framework/routing.rst
  introduction/from_flat_php_to_symfony2.rst
  reference/forms/types/options/button_label.rst.inc
  reference/forms/types/options/preferred_choices.rst.inc
  templating.rst
  templating/PHP.rst
  templating/escaping.rst
  translation.rst
Labels: Status: Reviewed

#10386 Tweak profiler's docs
  profiler.rst
  profiler/storage.rst
  reference/configuration/framework.rst
  reference/configuration/web_profiler.rst
Labels: Profiler, Status: Reviewed

#10159 Update name of the webpack encore package
  frontend/encore/installation.rst
Labels: Status: Reviewed

#10127 Recommend to install ORM pack instead of Doctrine bundle
  doctrine/dbal.rst
Labels: Doctrine, Status: Reviewed

#10388 Deprecated not passing the root node name to config tree builders
  bundles/configuration.rst
  components/config/definition.rst
  configuration/using_parameters_in_dic.rst
Labels: Config, Deprecation, Status: Reviewed

#10391 Documented the binding of arguments by name and type
  service_container.rst
Labels: DependencyInjection, Missing Documentation, Status: Reviewed

#10394 Documented the setColumnMaxWidth() method
  components/console/helpers/table.rst
Labels: Console, Missing Documentation, Status: Needs Review

#10400 [Dotenv] Advise using the Composer --dev option
  components/dotenv.rst
Labels: Status: Reviewed

#10408 typo fix
  setup/built_in_web_server.rst
Labels: Status: Reviewed

#10411 Fix environment variable name
  messenger.rst
Labels: Messenger, Status: Reviewed

#10414 [Encore] Updates links to babel-preset-env and browserslist
  frontend/encore/postcss.rst
Labels: Status: Reviewed, Webpack Encore
