Repository symfony/symfony-docs, pull requests merged in 2018-12, with the labels that each got.

#10723 Switch to 3.4 as oldest maintained branch
  README.markdown
  contributing/code/patches.rst
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#10726 Update the example how to fetch an envelope stamp
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10730 Update page_creation.rst
  page_creation.rst
Labels: Status: Reviewed

#10728 Use the new HandlersLocator and initialise it correctly.
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10735 Missed setting the return value
  components/config/definition.rst
Labels: Status: Reviewed

#10731 Always use latest Symfony version
  setup/flex.rst
Labels: Status: Reviewed

#10748 Fix syntax error in decorating services example
  service_container/service_decoration.rst
Labels: DependencyInjection, Status: Reviewed

#10750 Migrate PR builds to SymfonyCloud
  .platform/routes.yaml
  .symfony.cloud.yaml
  .symfony/routes.yaml
  .symfony/services.yaml
Labels: Status: Reviewed, Website

#10752 Fixed typos
  components/ldap.rst
Labels: Status: Reviewed

#10753 Update contribution docs to reflect migration to SymfonyCloud
  README.markdown
  _images/contributing/docs-pull-request-platformsh.png
  _images/contributing/docs-pull-request-symfonycloud.png
  contributing/documentation/overview.rst
Labels: Status: Reviewed, Website

#10754 inject to the method instead of using the container
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#10770 Fix app.css comment syntax
  frontend/encore/installation-no-flex.rst
Labels: Status: Reviewed, Webpack Encore

#10766 typo in sample of code
  frontend/encore/simple-example.rst
Labels: Status: Reviewed, Webpack Encore

#10760 [Messenger] Collect all stamps added on Envelope
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#10765 Update property_info.rst - added missing variable $accessExtractors
  components/property_info.rst
Labels: PropertyAccess, Status: Reviewed

#10778 Remove "cache" from example config of framework.yaml
  configuration.rst
Labels: Config, Status: Reviewed

#10784 updating commit range for config/bootstrap.php
  configuration/dot-env-changes.rst
Labels: Status: Reviewed

#10758 [Validator] Added new UnexpectedValueException
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#10768 [Console] Add hyperlinks support
  console/coloring.rst
Labels: Console, Status: Reviewed

#10725 Change setException to setError
  components/console/events.rst
Labels: Console, Status: Reviewed

#10812 Fixed a minor syntax issue in a link
  console/coloring.rst
Labels: Bug, Console, Status: Reviewed

#10349 Validate a BIC along with an IBAN
  reference/constraints/Bic.rst
Labels: Status: Reviewed, Validator

#10816 [Messenger] Fix allow_no_handlers for 4.2
  messenger/multiple_buses.rst
Labels: Messenger, Status: Reviewed

#10821 Added the missing provided functions
  components/polyfill_php73.rst
Labels: Status: Reviewed
