Repository symfony/symfony-docs, pull requests merged in 2019-03, with the labels that each got.

#11077 Minor "Review comments" tweaks
  contributing/community/review-comments.rst
Labels: Status: Reviewed

#10997 [Form] document the NumberType html5 option
  reference/forms/types/number.rst
Labels: Form, Status: Reviewed

#11074 removed versionadded, fixed count and note which behaves like version…
  controller/argument_value_resolver.rst
Labels: Status: Reviewed

#11079 removed obsolete versionadded-directive
  reference/forms/types/number.rst
Labels: Form, Status: Reviewed

#11086 Re-added a note about configuration imports
  configuration/configuration_organization.rst
Labels: Config, Status: Reviewed

#11083 Update create_custom_field_type.rst
  form/create_custom_field_type.rst
Labels: Form, Status: Reviewed

#11082 add form name caution to choice_name option
  reference/forms/types/options/choice_name.rst.inc
Labels: Form, Status: Reviewed

#11081 fixed paragraph about which versionadded directives will be removed
  contributing/documentation/format.rst
Labels: Status: Reviewed

#11089 Some route fixes left after #11085
  components/routing.rst
  routing/hostname_pattern.rst
Labels: Routing, Status: Reviewed

#11091 Remove `allowNull` option
  reference/constraints/NotBlank.rst
Labels: Status: Reviewed, Validator

#11093 Remove Symfony 4.3 features from 4.2 docs
  components/console/helpers/progressbar.rst
  components/dom_crawler.rst
  configuration/external_parameters.rst
  console/coloring.rst
  form/create_custom_field_type.rst
  form/form_themes.rst
  routing.rst
  security/csrf.rst
  service_container/alias_private.rst
Labels: Status: Needs Review

#11054 Added caution-box about special characters
  email.rst
Labels: Status: Reviewed

#11096 Improved the explanation about the forward method
  controller/forwarding.rst
Labels: Status: Needs Review

#11084 Real-time capabilities: add docs for the Mercure Component and Bundle
  _images/mercure/chrome.png
  _images/mercure/discovery.png
  _images/mercure/schema.png
  components/mercure.rst
  index.rst
  mercure.rst
Labels: Status: Reviewed

#11099 Improved the highlighting of JS examples in Mercure docs
  mercure.rst
Labels: Status: Reviewed

#11100 [Mercure] Fix list rendering
  mercure.rst
Labels: Status: Reviewed

#11056 new valid card scheme MIR
  reference/constraints/CardScheme.rst
Labels: Status: Reviewed, Validator

#11094 small wording fixes
  contributing/community/review-comments.rst
Labels: Status: Reviewed

#10868 [Validator] Fix `@Valid` regarding property `traverse`
  reference/constraints/Valid.rst
Labels: Status: Reviewed, Validator

#10982 Added a note about the deprecations of DateTimeType
  reference/forms/types/datetime.rst
Labels: Form, Status: Needs Review, deprecation

#10986 format option deprecation for HTML 5 widgets
  reference/forms/types/date.rst
  reference/forms/types/datetime.rst
Labels: Form, Status: Needs Review, deprecation

#11105 Fix wrong parentheses match in documentation
  workflow/usage.rst
Labels: Status: Reviewed

#11104 [Mercure] Link to the English version of MDN
  mercure.rst
Labels: Status: Reviewed

#11109 Fixed some misc issues
  best_practices/security.rst
  components/serializer.rst
  email.rst
  form/create_custom_field_type.rst
  reference/configuration/framework.rst
  security.rst
  serializer.rst
  templating.rst
  validation.rst
  validation/severity.rst
Labels: Status: Needs Review

#11106 do not mention the internal ControllerTrait
  controller/forwarding.rst
Labels: Status: Reviewed

#11107 remove documentation for features introduced in 4.3
  reference/constraints/CardScheme.rst
  reference/constraints/Choice.rst
  reference/forms/types/form.rst
  reference/forms/types/options/block_prefix.rst.inc
Labels: Status: Reviewed

#11110 Fixed the "applies to" of the Callback constraint
  reference/constraints/Callback.rst
Labels: Status: Needs Review, Validator

#11112 fix removing Dotenv from require-dev
  deployment.rst
Labels: Status: Reviewed

#11111 add missing versionadded directives for Bic options
  reference/constraints/Bic.rst
Labels: Status: Reviewed, Validator

#11125 use .. instead of .. code-block: php
  best_practices/security.rst
  bundles/configuration.rst
  components/property_access.rst
  components/property_info.rst
  components/serializer.rst
  components/var_dumper/advanced.rst
  contributing/code/standards.rst
  deployment/proxies.rst
  form/data_mappers.rst
  form/without_class.rst
  security/user_checkers.rst
  service_container/tags.rst
Labels: Status: Reviewed

#11127 Document Default env processor with null fallback
  configuration/external_parameters.rst
Labels: Status: Reviewed

#11119 Add missing bracket on a php code example
  routing.rst
Labels: Routing, Status: Reviewed

#11131 use terminal instead of bash
  components/dotenv.rst
  components/phpunit_bridge.rst
  configuration/micro_kernel_trait.rst
  frontend/assetic/asset_management.rst
  performance.rst
  security/guard_authentication.rst
Labels: Status: Reviewed

#11116 Add CORS_ALLOWED_ORIGINS to running mercure
  mercure.rst
Labels: Status: Reviewed

#11129 use :: instead of .. code-block:: php
  reference/forms/types/collection.rst
Labels: Status: Reviewed

#11133 Making sentence not show up in code block
  configuration/dot-env-changes.rst
Labels: Status: Reviewed

#11115 Added a note about virtual machine for local build
  README.markdown
Labels: Status: Needs Review

#11136 Minor fix to OPcache regeneration instructions
  performance.rst
Labels: Status: Reviewed

#11137 use :: instead of .. code-block:: php
  bundles/best_practices.rst
Labels: Status: Reviewed

#11138 removed blank lines after filepath
  service_container/factories.rst
Labels: Status: Reviewed

#11141 added missing php before bin/console
  deployment/platformsh.rst
Labels: Status: Reviewed

#11140 remove blank lines after file path
  service_container/factories.rst
Labels: Status: Reviewed

#11143 Update access_control.rst role
  security/access_control.rst
Labels: Status: Reviewed

#11150 updating spacing
  logging/monolog_email.rst
Labels: Monolog, Status: Reviewed

#11153 use :: instead of .. code-block:: php
  components/options_resolver.rst
Labels: Status: Needs Review

#11149 do not mock the validator in form type tests
  form/unit_testing.rst
Labels: Form, Status: Reviewed, Validator

#11148 Document the disallow_search_engine_index option
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#11162 Added Oskar to the Docs Team
  contributing/code/core_team.rst
Labels: Status: Reviewed

#11059 [FrameworkBundle][Routing] allow boolean container parameters for routes
  routing/service_container_parameters.rst
Labels: FrameworkBundle, Routing, Status: Reviewed

#11165 Don't use AbstractController in 3.4 branch
  routing/conditions.rst
  web_link.rst
Labels: Status: Reviewed

#11159 Added the missing annotations to a routing example
  routing/service_container_parameters.rst
Labels: Routing, Status: Needs Review

#11173 regroup some constraints
  reference/constraints/map.rst.inc
Labels: Status: Needs Review, Validator

#11172 typo in comment (php example)
  controller.rst
Labels: Status: Needs Review

#11171 promote AbstractController in 4.2 branch
  http_cache/validation.rst
  routing/conditions.rst
  web_link.rst
Labels: Status: Reviewed

#11164 [Mercure] Fix link to high-level implementations
  mercure.rst
Labels: Status: Reviewed

#11166 [Security] Fix stateless mention
  security/user_provider.rst
Labels: Status: Needs Review

#11174 added missing brackets
  best_practices/templates.rst
  components/class_loader/class_map_generator.rst
  components/console/helpers/formatterhelper.rst
  components/console/helpers/table.rst
  components/css_selector.rst
  components/translation/usage.rst
  logging.rst
  logging/monolog_email.rst
  reference/forms/twig_reference.rst
  security/ldap.rst
  validation.rst
Labels: Status: Needs Review

#11180 Fixing error at Class Constraint Validator
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#11191 fix indention
  components/config/definition.rst
Labels: Config, Status: Reviewed

#11184 Fix typo in http_kernel_controller_resolver.rst
  create_framework/http_kernel_controller_resolver.rst
Labels: Status: Reviewed

#11186 Correct a sentence meaning
  setup/built_in_web_server.rst
Labels: Status: Reviewed

#11188 Add precision on the concerned fields in the Default validation group
  validation/groups.rst
Labels: Status: Reviewed, Validator

#11179 use same order for all configuration-blocks
  components/translation/usage.rst
  reference/constraints/Uuid.rst
Labels: Status: Reviewed

#11181 use :: instead of .. code-block:: php
  components/expression_language/extending.rst
  components/security/authorization.rst
  deployment/proxies.rst
  workflow/usage.rst
Labels: Status: Reviewed

#11194 use correct order of code-blocks
  security.rst
Labels: Status: Reviewed

#11196 use "behavior" instead of "behaviour"
  contributing/code_of_conduct/concrete_example_document.rst
  contributing/diversity/governance.rst
  contributing/documentation/format.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed

#11197 use consistent placeholder comments in yaml, php and xml
  create_framework/http_kernel_httpkernelinterface.rst
  deployment/fortrabbit.rst
  routing.rst
  security/api_key_authentication.rst
  security/guard_authentication.rst
Labels: Status: Reviewed

#11203 Fixed some references
  reference/configuration/security.rst
Labels: Status: Needs Review

#11201 add missing brackets
  form/form_customization.rst
  quick_tour/flex_recipes.rst
  security/access_control.rst
Labels: Status: Reviewed

#11202 use "behavior" instead of "behaviour"
  contributing/code_of_conduct/concrete_example_document.rst
  contributing/diversity/governance.rst
  contributing/documentation/format.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed

#11199 Remove unnecessary backslash escape
  components/form.rst
Labels: Status: Reviewed

#11204 removed blank line and space
  reference/configuration/security.rst
Labels: Status: Reviewed

#11182 Improve now what sentence
  components/using_components.rst
Labels: Status: Reviewed

#11198 Update unit_testing.rst
  create_framework/unit_testing.rst
Labels: Status: Reviewed

#11216 Fixing minor error
  reference/forms/types/entity.rst
Labels: Form, Status: Reviewed

#11170 be keen to newcomers
  create_framework/http_kernel_httpkernelinterface.rst
  forms.rst
  http_cache/esi.rst
  http_cache/expiration.rst
  http_cache/validation.rst
Labels: Status: Reviewed

#11218 use "application(s)" instead of "app(s)"
  _build/redirection_map
  best_practices/configuration.rst
  best_practices/creating-the-project.rst
  best_practices/introduction.rst
  contributing/community/releases.rst
  controller.rst
  email/gmail.rst
  form/form_customization.rst
  frontend.rst
  frontend/encore/faq.rst
  frontend/encore/legacy-applications.rst
  frontend/encore/simple-example.rst
  page_creation.rst
  reference/configuration/framework.rst
  setup.rst
  web_link.rst
Labels: Status: Needs Review

#11219 Remove an extra dot from events.rst
  components/console/events.rst
Labels: Console, Status: Reviewed

#11128 Add `url` and `query_string` processors
  configuration/external_parameters.rst
Labels: DependencyInjection, Status: Reviewed

#11075 Encore (advanced): add documentation for `configureLoaderRule()` method
  frontend/encore/advanced-config.rst
Labels: Status: Needs Review, Waiting Code Merge, front-end

#11224 Adding ignoreVCSIgnored documentation
  components/finder.rst
Labels: Finder, Status: Reviewed

#11217 Remove CustomUserMessageAuthenticationException
  security/user_checkers.rst
Labels: Security, Status: Reviewed

#11113 Improved routing section
  components/routing.rst
  routing.rst
  routing/conditions.rst
  routing/custom_route_loader.rst
  routing/debug.rst
  routing/external_resources.rst
  routing/extra_information.rst
  routing/generate_url_javascript.rst
  routing/hostname_pattern.rst
  routing/optional_placeholders.rst
  routing/requirements.rst
  routing/scheme.rst
  routing/slash_in_parameter.rst
Labels: Routing, Status: Reviewed

#11232 Fix the example about overriding the getProjectDir method
  deployment.rst
Labels: Status: Reviewed

#11227 Correct many-to-many to many-to-one
  form/form_collections.rst
Labels: Form, Status: Reviewed

#11235 clarify datetime type option deprecations
  reference/forms/types/datetime.rst
Labels: Form, Status: Reviewed

#11246 Detailed AMQP dependency
  messenger.rst
Labels: Status: Needs Review, Status: Reviewed

#11242 use UTF-8 instead of utf-8
  components/translation/usage.rst
  doctrine/reverse_engineering.rst
  security/remember_me.rst
  service_container/tags.rst
  workflow/state-machines.rst
  workflow/usage.rst
Labels: Status: Reviewed

#11237 use correct code-block type
  doctrine/registration_form.rst
  page_creation.rst
Labels: Status: Reviewed

#11243 use :: instead of .. code-block:: php
  components/property_info.rst
  components/security/authorization.rst
Labels: PropertyInfo, Security, Status: Reviewed

#11238 remove blank line after filepath
  security/remember_me.rst
Labels: Security, Status: Reviewed

#11248 [Console] uncomment the "Before" code part
  console/style.rst
Labels: Console, Status: Reviewed

#11250 be consistent with ask() example
  console/style.rst
Labels: Console, Status: Reviewed
