Repository symfony/symfony-docs, pull requests merged in 2019-02, with the labels that each got.

#10954 Document the allowNull option for NotBlank constraint
  reference/constraints/NotBlank.rst
Labels: Status: Needs Review, Validator

#10949 [Console] Add documentation for the ProgressBar::iterate method
  components/console/helpers/progressbar.rst
Labels: Console, Status: Reviewed

#10956 Explicitly list _field-name_entry_parts
  form/form_themes.rst
Labels: Form, Status: Reviewed

#10917 Update testing.rst
  email/testing.rst
Labels: Status: Reviewed, Testing

#10960 public access modifier for const
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#10959 Update testing.rst to be compatible with windows
  testing.rst
Labels: Status: Reviewed, Testing

#10957 Fix of old service ids styles to class name
  service_container/service_decoration.rst
Labels: DependencyInjection, Status: Reviewed

#10965 Remove quotes around App\Entity namespace
  doctrine/reverse_engineering.rst
Labels: Doctrine, Status: Reviewed

#10973 Update 4.2 deprecation
  translation.rst
Labels: Status: Reviewed, Translation

#10972 Update web_server_configuration
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#10978 [FormType] Add help_html documentation
  reference/forms/types/birthday.rst
  reference/forms/types/checkbox.rst
  reference/forms/types/choice.rst
  reference/forms/types/collection.rst
  reference/forms/types/color.rst
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/date.rst
  reference/forms/types/dateinterval.rst
  reference/forms/types/datetime.rst
  reference/forms/types/email.rst
  reference/forms/types/entity.rst
  reference/forms/types/file.rst
  reference/forms/types/form.rst
  reference/forms/types/integer.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
  reference/forms/types/money.rst
  reference/forms/types/number.rst
  reference/forms/types/options/help_html.rst.inc
  reference/forms/types/password.rst
  reference/forms/types/percent.rst
  reference/forms/types/radio.rst
  reference/forms/types/range.rst
  reference/forms/types/repeated.rst
  reference/forms/types/search.rst
  reference/forms/types/tel.rst
  reference/forms/types/text.rst
  reference/forms/types/textarea.rst
  reference/forms/types/time.rst
  reference/forms/types/timezone.rst
  reference/forms/types/url.rst
Labels: Form, Status: Reviewed

#10980 changed roles for Nicolas and Christian
  contributing/code/core_team.rst
Labels: Status: Reviewed

#10944 Update the documentation for the PR #30027
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#10987 Fix typo in the profiler article
  profiler.rst
Labels: Profiler, Status: Reviewed

#10993 Use "index" instead of "indexAction"
  create_framework/separation_of_concerns.rst
Labels: Status: Reviewed

#10994 [Security] Added a missing class import in form login article
  security/form_login_setup.rst
Labels: Security, Status: Reviewed

#10984 Added a brief mention about upgrading custom bundle config to Flex
  setup/flex.rst
Labels: Config, Status: Needs Review

#10985 [UI] Flash Message keys
  controller.rst
Labels: Status: Needs Review

#10998 fix type of the grouping option
  reference/forms/types/options/grouping.rst.inc
Labels: Form, Status: Reviewed

#10999 document the parent_form() Twig function
  form/form_customization.rst
Labels: Form, Status: Reviewed

#11004 clarify some DateTimeType widget options
  reference/forms/types/datetime.rst
Labels: Form, Status: Reviewed

#11003 document deprecation of the scale option
  reference/forms/types/integer.rst
Labels: Form, Status: Reviewed

#11011 Replace Controller with AbstractController
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#10996 [Diversity] Reword Diversity Guidance Team Language
  contributing/diversity/governance.rst
Labels: Status: Reviewed, diversity

#11013 Fixed the highlighting of some form Twig code examples
  form/action_method.rst
  form/bootstrap4.rst
  form/form_collections.rst
  form/form_customization.rst
  form/form_themes.rst
Labels: Status: Needs Review

#11010 [Diversity] Add Voting Logic Examples
  contributing/diversity/governance.rst
Labels: Status: Reviewed, diversity

#11018 Improved the explanation of the block_name form option
  reference/forms/types/options/block_name.rst.inc
Labels: Form, Status: Reviewed

#11021 [Form] Mention that form_theme _self only works with template inheritance
  form/form_themes.rst
Labels: Form, Status: Needs Review

#11022 Improved the Fragment Naming for Collections section
  form/form_themes.rst
Labels: Form, Status: Reviewed

#11023 Mentioned the LDAP query scopes
  components/ldap.rst
Labels: Ldap, Status: Needs Review

#11036 be keen to newcomers
  bundles/extension.rst
  bundles/override.rst
  components/debug.rst
  components/http_foundation.rst
  components/http_kernel.rst
  components/stopwatch.rst
  components/templating.rst
  console/input.rst
  console/request_context.rst
  create_framework/dependency_injection.rst
  create_framework/event_dispatcher.rst
  create_framework/front_controller.rst
  create_framework/http_kernel_httpkernel_class.rst
  create_framework/http_kernel_httpkernelinterface.rst
  create_framework/routing.rst
  create_framework/separation_of_concerns.rst
  create_framework/unit_testing.rst
  http_cache.rst
  reference/constraints/Collection.rst
  reference/constraints/IsNull.rst
  reference/constraints/NotBlank.rst
  security.rst
  session/php_bridge.rst
  testing/profiling.rst
  validation/raw_values.rst
  validation/translations.rst
Labels: Status: Reviewed

#11037 removed php open tag
  bundles/best_practices.rst
Labels: Status: Reviewed

#11039 Documented the missing session.use_cookies config option
  reference/configuration/framework.rst
Labels: HttpFoundation, Status: Reviewed

#11031 use .yaml instead of .yml for examples
  routing/external_resources.rst
Labels: Status: Reviewed

#11032 remove obsolete internal references
  best_practices/configuration.rst
Labels: Status: Reviewed

#11033 More improvements of the Session article
  reference/configuration/framework.rst
  session.rst
Labels: HttpFoundation, Status: Needs Review

#11046 Fix typo: if -> of
  form/data_transformers.rst
Labels: Status: Reviewed

#11049 rename parent_form() to form_parent()
  form/form_customization.rst
Labels: Form, Status: Needs Review, Twig

#11051 Uncomment some code in the "Configuring Babel" example
  frontend/encore/babel.rst
Labels: Status: Needs Review

#11058 Update fortrabbit.rst
  deployment/fortrabbit.rst
Labels: Status: Reviewed

#11055 Document the kernel.reset tag
  reference/dic_tags.rst
Labels: DependencyInjection, Status: Reviewed
