Repository symfony/symfony-docs, pull requests merged in 2019-04, with the labels that each got.

#11253 minor - controller in app, rather than in bundle
  security/form_login.rst
Labels: Status: Reviewed

#11239 use application(s) instead of app(s)
  components/mercure.rst
  configuration/front_controllers_and_kernel.rst
  email.rst
  form/form_themes.rst
  frontend/assetic/index.rst
  mercure.rst
  security.rst
  security/user_provider.rst
Labels: Status: Needs Review

#11234 Minor tweak for the debug:router output
  routing/debug.rst
Labels: Routing, Status: Reviewed

#11249 use :: instead of .. code-block:: php
  components/config/definition.rst
Labels: Status: Reviewed

#9807 #27345 Added MongoDbStore Lock Store documentation
  components/lock.rst
Labels: Lock, Status: Reviewed

#11256 move info to a new include
  http_cache/_expiration-and-validation.rst.inc
  http_cache/expiration.rst
  http_cache/validation.rst
Labels: Status: Reviewed

#11264 added blank line and typo fix
  components/lock.rst
Labels: Lock, Status: Reviewed

#11267 use App instead of AppBundle
  doctrine/event_listeners_subscribers.rst
  reference/forms/types/entity.rst
  routing/optional_placeholders.rst
Labels: Status: Reviewed

#11269 small tweaks for Symfony server
  setup/symfony_server.rst
Labels: Status: Reviewed

#11270 removed leading slash in FQCN
  workflow/usage.rst
Labels: Status: Reviewed

#11273 typo
  setup/upgrade_major.rst
Labels: Status: Reviewed

#11263 Add an example to the invokable controllers section
  controller/service.rst
Labels: Status: Reviewed

#11258 Added the docs for the VarExporter component
  components/var_exporter.rst
Labels: Status: Reviewed, VarExporter

#11285 Fixed a typo
  security/multiple_guard_authenticators.rst
Labels: Status: Needs Review

#11282 removed part from xml which is not available in yaml and php code-blocks
  service_container/optional_dependencies.rst
Labels: DependencyInjection, Status: Reviewed

#11283 add namespace, to be able to reuse class in following examples
  components/config/resources.rst
Labels: Config, Status: Reviewed

#11284 renamed a variable
  components/filesystem.rst
Labels: Filesystem, Status: Reviewed

#11287 fix use statement
  doctrine/resolve_target_entity.rst
Labels: Status: Reviewed

#11288 remove blank line after filepath in php code examples
  bundles/configuration.rst
  components/console/changing_default_command.rst
  components/yaml.rst
  configuration/micro_kernel_trait.rst
  doctrine/pdo_session_storage.rst
  doctrine/resolve_target_entity.rst
  form/dynamic_form_modification.rst
  form/form_collections.rst
  form/form_dependencies.rst
  http_cache/cache_invalidation.rst
  security/entity_provider.rst
  service_container/factories.rst
  templating/PHP.rst
  workflow/state-machines.rst
  workflow/usage.rst
Labels: Status: Reviewed

#11289 added use statement and filepath to be consistent
  doctrine/lifecycle_callbacks.rst
Labels: Doctrine, Status: Reviewed

#11290 wrap code example with class
  form/dynamic_form_modification.rst
Labels: Form, Status: Reviewed

#11291 be consistent ´with the following code example
  form/form_collections.rst
Labels: Form, Status: Needs Review

#11292 move the namespace before the use statements
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#11281 try to make the code examples less noisy
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#11286 Update project directory method override
  reference/configuration/kernel.rst
Labels: Status: Reviewed

#11294 Fixed the RST syntax of a serializer article
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#11297 Simplified some docs about getProjectDir
  deployment.rst
  reference/configuration/kernel.rst
Labels: Status: Reviewed

#11298 Fix local proxy URI scheme
  setup/symfony_server.rst
Labels: Status: Reviewed

#10700 [DomCrawler][WIP] Add note about the HTML5 parser library
  components/dom_crawler.rst
Labels: DomCrawler, Status: Reviewed

#11014 [DependencyInjection] Invokable Factory Services
  service_container/configurators.rst
  service_container/factories.rst
Labels: DependencyInjection, Status: Reviewed

#11296 moved XSD to HTTPS - Part 2
  bundles/configuration.rst
  components/dependency_injection/compilation.rst
  components/phpunit_bridge.rst
  components/serializer.rst
  configuration.rst
  configuration/configuration_organization.rst
  configuration/environments.rst
  configuration/external_parameters.rst
  configuration/micro_kernel_trait.rst
  configuration/override_dir_structure.rst
  create_framework/unit_testing.rst
  deployment/fortrabbit.rst
  doctrine.rst
  doctrine/associations.rst
  doctrine/custom_dql_functions.rst
  doctrine/dbal.rst
  doctrine/lifecycle_callbacks.rst
  doctrine/mongodb_session_storage.rst
  doctrine/multiple_entity_managers.rst
  doctrine/pdo_session_storage.rst
  doctrine/repository.rst
  doctrine/resolve_target_entity.rst
  doctrine/reverse_engineering.rst
  email/dev_environment.rst
  form/create_custom_field_type.rst
  form/form_collections.rst
  form/form_themes.rst
  frontend/assetic/apply_to_option.rst
  frontend/assetic/asset_management.rst
  frontend/assetic/jpeg_optimize.rst
  frontend/assetic/php.rst
  frontend/assetic/uglifyjs.rst
  frontend/assetic/yuicompressor.rst
  frontend/custom_version_strategy.rst
  http_cache/esi.rst
  logging.rst
  logging/channels_handlers.rst
  logging/disable_microsecond_precision.rst
  logging/formatter.rst
  logging/monolog_email.rst
  logging/monolog_regex_based_excludes.rst
  logging/processors.rst
  profiler/matchers.rst
  profiler/storage.rst
  reference/configuration/doctrine.rst
  reference/configuration/framework.rst
  reference/configuration/monolog.rst
  reference/configuration/security.rst
  reference/configuration/web_profiler.rst
  security/csrf_in_login_form.rst
  serializer.rst
  session/sessions_directory.rst
  templating/PHP.rst
  templating/hinclude.rst
  testing/profiling.rst
  translation.rst
  translation/locale.rst
  validation.rst
  workflow/state-machines.rst
  workflow/usage.rst
Labels: Status: Reviewed

#11306 Remove GitHub references
  components/asset.rst
  components/browser_kit.rst
  components/cache.rst
  components/config.rst
  components/console.rst
  components/css_selector.rst
  components/debug.rst
  components/dependency_injection.rst
  components/dom_crawler.rst
  components/dotenv.rst
  components/event_dispatcher.rst
  components/expression_language.rst
  components/filesystem.rst
  components/finder.rst
  components/form.rst
  components/http_foundation.rst
  components/http_kernel.rst
  components/intl.rst
  components/ldap.rst
  components/lock.rst
  components/options_resolver.rst
  components/phpunit_bridge.rst
  components/polyfill_apcu.rst
  components/polyfill_ctype.rst
  components/polyfill_iconv.rst
  components/polyfill_intl_grapheme.rst
  components/polyfill_intl_icu.rst
  components/polyfill_intl_idn.rst
  components/polyfill_intl_messageformatter.rst
  components/polyfill_intl_normalizer.rst
  components/polyfill_mbstring.rst
  components/polyfill_php54.rst
  components/polyfill_php55.rst
  components/polyfill_php56.rst
  components/polyfill_php70.rst
  components/polyfill_php71.rst
  components/polyfill_php72.rst
  components/polyfill_php73.rst
  components/process.rst
  components/property_access.rst
  components/property_info.rst
  components/psr7.rst
  components/routing.rst
  components/security.rst
  components/serializer.rst
  components/stopwatch.rst
  components/templating.rst
  components/translation.rst
  components/validator.rst
  components/var_dumper.rst
  components/web_link.rst
  components/workflow.rst
  components/yaml.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11307 Remove GitHub references
  components/mercure.rst
  components/messenger.rst
  components/var_exporter.rst
  components/web_link.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11308 Remove references to github repositories.
  components/mailer.rst
  components/mime.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11309 add back missing file
  frontend/assetic/index.rst
Labels: Status: Needs Review

#11251 Fix template name reference
  bundles/override.rst
Labels: Status: Reviewed

#11310 [Validator] Added documentation for Traverse constraint
  reference/constraints/Traverse.rst
Labels: Status: Reviewed, Validator, ⭐️ EU-FOSSA Hackathon

#11312 [Flex] Replace `SYMFONY_*` env vars with `APP_*`
  setup/flex.rst
Labels: Status: Needs Review

#11303 added requirements for {_format}
  templating/formats.rst
Labels: Status: Reviewed

#11315 Linked the new Traverse article from an index
  reference/constraints.rst
  reference/constraints/map.rst.inc
Labels: Status: Needs Review, Validator

#11305 Fixes typo with reassigning env vars.
  setup/symfony_server.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11300 Added docs for the NotCompromisedPassword constraint
  reference/constraints.rst
  reference/constraints/NotPwned.rst
  reference/constraints/map.rst.inc
Labels: Status: Reviewed, Validator

#11316 Minor improvement in the DomCrawler + HTML5 explanation
  components/dom_crawler.rst
Labels: DomCrawler, Status: Reviewed

#11318 [reference] [constraints] fixes small typo in `Time` validation constraint documentation.
  reference/constraints/Time.rst
Labels: Status: Reviewed, Validator, ⭐️ EU-FOSSA Hackathon

#11311 Adds deprecation for non-string env values.
  configuration/environment_variables.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11319 fix document filename
  reference/constraints/NotCompromisedPassword.rst
Labels: Status: Reviewed

#11320 [Validator] fixed class name of Traverse
  reference/constraints/Traverse.rst
Labels: Status: Needs Review, Validator

#11272 [Form] Add example for createNamed Form
  forms.rst
Labels: Form, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11200 Update dotenv.rst
  components/dotenv.rst
Labels: Dotenv, Status: Needs Review, ⭐️ EU-FOSSA Hackathon

#11156 updated PropertyAccess docs for PR 30536
  components/property_access.rst
  reference/configuration/framework.rst
Labels: PropertyAccess, Status: Needs Review

#11108 Update form_login_setup.rst
  security/form_login_setup.rst
Labels: Security, Status: Needs Review

#11322 fix typo `spaccer` => `spacer`
  components/mime.rst
Labels: Mime, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11314 document the input option of the NumberType
  reference/forms/types/number.rst
Labels: Form, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11336 Fix a typo for the range of allowed attack complexity score values
  contributing/code/security.rst
Labels: Status: Needs Review

#11332 Add doctrine orm installation instructions
  best_practices/business-logic.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11328 Adds documentation for monolog processors.
  logging/processors.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11271 [Testing] Add docs for new WebTestCase assertions
  testing.rst
  testing/functional_tests_assertions.rst
Labels: PHPUnitBridge, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11342 [Routing] Use double colon in custom routing example
  routing/custom_route_loader.rst
Labels: Routing, Status: Needs Review, ⭐️ EU-FOSSA Hackathon

#11345 Added Yaml, XML and PHP examples for invokable controllers
  controller/service.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11343 Made ChoiceType callback parameters consistent
  reference/forms/types/choice.rst
  reference/forms/types/options/choice_attr.rst.inc
  reference/forms/types/options/choice_label.rst.inc
  reference/forms/types/options/group_by.rst.inc
  reference/forms/types/options/preferred_choices.rst.inc
Labels: Status: Needs Review, ⭐️ EU-FOSSA Hackathon

#11348 fix rst link syntax
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#11340 [HttpKernel] Document `trace_level` and `trace_header` config options in `HttpCache`
  http_cache.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11344 [serializer] document DEEP_OBJECT_TO_POPULATE
  components/serializer.rst
Labels: Serializer, Status: Reviewed, Waiting Code Merge, ⭐️ EU-FOSSA Hackathon

#11333 [Routing] Invokable route loader services
  routing/custom_route_loader.rst
Labels: Routing, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11313 Add documentation for the `require` env processor
  configuration/environment_variables.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11351 [Cache] Fixed typos
  cache.rst
Labels: Cache, Status: Reviewed

#11350 Update NotCompromisedPassword.rst
  reference/constraints/NotCompromisedPassword.rst
Labels: Status: Reviewed, Validator

#11352 remove space before self closing tag
  cache.rst
Labels: Cache, Status: Reviewed

#11355 Fix resolve example
  configuration/external_parameters.rst
Labels: Status: Reviewed

#11354 Documented the disable_not_compromised_password option
  reference/configuration/framework.rst
  reference/constraints/NotCompromisedPassword.rst
Labels: Status: Reviewed, Validator

#11276 Fixes escaping of IDE config and adds example for PhpStorm
  reference/configuration/framework.rst
Labels: Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11356 remove blank line after filepath
  page_creation.rst
Labels: Status: Reviewed

#11358 fix indention for twig example
  translation.rst
Labels: Status: Reviewed

#11357 use html+twig instead of twig for some examples
  form/bootstrap4.rst
  frontend/encore/server-data.rst
  frontend/encore/simple-example.rst
  frontend/encore/split-chunks.rst
  frontend/encore/versioning.rst
  quick_tour/the_view.rst
  reference/dic_tags.rst
  reference/forms/twig_reference.rst
  templating.rst
  translation.rst
  web_link.rst
Labels: Status: Reviewed

#11362 Fix tab content displaying
  controller/service.rst
Labels: Status: Reviewed

#11375 [Workflow] rename Twig function
  workflow/usage.rst
Labels: Status: Reviewed, Workflow

#11371 [Cache] Updated invalid pdo service name
  reference/configuration/framework.rst
Labels: Cache, Status: Reviewed

#11374 use code-block twig instead of html+twig
  best_practices/forms.rst
  form/action_method.rst
  form/bootstrap4.rst
  form/form_collections.rst
  form/form_customization.rst
  form/form_themes.rst
  form/rendering.rst
  forms.rst
  quick_tour/the_controller.rst
  reference/forms/types/options/button_label.rst.inc
  templating/escaping.rst
  templating/render_without_controller.rst
Labels: Status: Reviewed

#11373 remove blank line after filepath in php code block
  controller/service.rst
  doctrine.rst
  messenger/multiple_buses.rst
  routing.rst
Labels: Status: Reviewed

#11372 use html+twig instead of twig for some examples
  doctrine/registration_form.rst
  form/form_customization.rst
  quick_tour/flex_recipes.rst
  quick_tour/the_architecture.rst
  security/csrf.rst
  security/form_login_setup.rst
Labels: Status: Reviewed

#11363 Minor change
  controller/upload_file.rst
Labels: Status: Reviewed

#11365 [Cache] Show how to configure lifetime for app.cache
  cache.rst
Labels: Cache, Status: Reviewed

#11370 [Cache] Updated invalid service names
  reference/configuration/framework.rst
Labels: Cache, Status: Reviewed

#11366 streamline the constraints reference
  reference/constraints/All.rst
  reference/constraints/Bic.rst
  reference/constraints/Callback.rst
  reference/constraints/CardScheme.rst
  reference/constraints/Choice.rst
  reference/constraints/Collection.rst
  reference/constraints/Count.rst
  reference/constraints/Country.rst
  reference/constraints/Date.rst
  reference/constraints/DateTime.rst
  reference/constraints/Email.rst
  reference/constraints/Image.rst
  reference/constraints/Ip.rst
  reference/constraints/IsFalse.rst
  reference/constraints/IsTrue.rst
  reference/constraints/Isbn.rst
  reference/constraints/Issn.rst
  reference/constraints/Language.rst
  reference/constraints/Length.rst
  reference/constraints/Locale.rst
  reference/constraints/Range.rst
  reference/constraints/Regex.rst
  reference/constraints/Time.rst
  reference/constraints/Type.rst
  reference/constraints/UniqueEntity.rst
  reference/constraints/Url.rst
  reference/constraints/UserPassword.rst
  reference/constraints/Uuid.rst
  reference/constraints/Valid.rst
Labels: Status: Reviewed, Validator

#10244 Add documentation on new monolog processors
  logging/processors.rst
Labels: Monolog, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11381 Documented the local Symfony server
  setup/symfony_server.rst
Labels: Status: Reviewed

#11382 js -> javascript & jinja -> twig code blocks
  frontend/encore/installation.rst
  reference/twig_reference.rst
  translation/debug.rst
Labels: Status: Reviewed

#11378 use max 2 blank lines
  cache.rst
Labels: Status: Reviewed

#11379 Little layout problem
  security.rst
Labels: Security, Status: Reviewed

#11383 use correct code block for examples
  form/form_customization.rst
  form/form_themes.rst
Labels: Status: Reviewed

#11384 Update serializer.rst
  components/serializer.rst
Labels: Status: Reviewed

#11339 Document how to use named aliases
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed, ⭐️ EU-FOSSA Hackathon

#11386 Update cache.rst
  cache.rst
Labels: Status: Reviewed

#11387 [Cache] Syntax fix
  cache.rst
Labels: Cache, Status: Reviewed

#11389 Swap aliases
  service_container/autowiring.rst
Labels: Status: Reviewed

#11385 Don't use Flex config in 3.4 branch
  cache.rst
  configuration/external_parameters.rst
  form/bootstrap4.rst
  frontend/encore/advanced-config.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed

#11369 [Cache] Show how to list all available pools
  cache.rst
Labels: Cache, Status: Reviewed

#11395 Recommend using form types as data mappers in the docs
  form/data_mappers.rst
Labels: Form, Status: Reviewed

#11402 Minor tweaks in the Timezone validator docs
  reference/constraints/Timezone.rst
Labels: Status: Reviewed, Validator

#11408 Mentioned the Lock expiringDate and isExpired methods
  components/lock.rst
Labels: Lock, Status: Reviewed

#11404 Added the $context argument to supports* methods
  serializer/custom_encoders.rst
  serializer/custom_normalizer.rst
Labels: Serializer, Status: Reviewed

#11405 Fixed a minor issue in Serializer component
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#11410 Add --dev flag to require symfony/debug-bundle
  components/var_dumper.rst
Labels: Status: Reviewed

#11392 Add info about storing remember me tokens in a database
  security/remember_me.rst
Labels: Security, Status: Reviewed

#11413 reword versionadded sentences a bit
  best_practices/configuration.rst
  bundles/extension.rst
  components/config/definition.rst
  components/dependency_injection/compilation.rst
  components/http_foundation.rst
  components/process.rst
  components/serializer.rst
  contributing/documentation/format.rst
  controller.rst
  service_container.rst
Labels: Status: Reviewed

#11420 Fixing broken sentence
  security.rst
Labels: Security, Status: Reviewed

#11414 small improvements
  frontend/encore/vuejs.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#11411 some small improvements to the constraints
  reference/constraints/Locale.rst
  reference/constraints/Luhn.rst
  reference/constraints/Traverse.rst
Labels: Status: Reviewed, Validator

#11415 small improvements
  configuration/override_dir_structure.rst
  messenger/multiple_buses.rst
  security/form_login_setup.rst
Labels: Status: Reviewed

#11412 small constraint improvements
  reference/constraints/Json.rst
  reference/constraints/Timezone.rst
Labels: Status: Reviewed, Validator

#11416 small improvements
  components/mime.rst
  components/property_access.rst
  components/routing.rst
  configuration/environment_variables.rst
  routing.rst
  service_container/configurators.rst
  service_container/factories.rst
Labels: Status: Reviewed

#11403 Move Timezone under Date constraints
  reference/constraints.rst
  reference/constraints/map.rst.inc
Labels: Status: Reviewed, Validator

#11423 Fix typo
  mercure.rst
Labels: Status: Reviewed

#11427 Updated a dependency for security reasons
  _build/.requirements.txt
Labels: Status: Needs Review

#11436 Added a note about UniqueEntity and collections
  reference/constraints/UniqueEntity.rst
Labels: Status: Reviewed, Validator

#11440 Fix format by removing underscore
  messenger.rst
Labels: Messenger, Status: Reviewed

#11434 Added a note about PHPUnit setLocale() method
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Reviewed

#11441 Update kernel.rst
  reference/configuration/kernel.rst
Labels: Status: Reviewed

#11442 Missing square bracket
  components/cache.rst
Labels: Status: Needs Review

#11445 Update outdated info about command name configuration
  console.rst
Labels: Console, Status: Reviewed

#11444 Switch the security-check to the Symfony client one
  security/security_checker.rst
Labels: Status: Needs Review

#11209 Documented the workflow metadata [redux]
  workflow/usage.rst
Labels: Status: Reviewed, Workflow

#11448 Frontend: fix class name when using Vue/JSX/Styles
  frontend/encore/vuejs.rst
Labels: Status: Reviewed, bug, front-end

#11469 Update session.rst
  session.rst
Labels: Status: Needs Review

#11455 renamed Patches to Pull Requests
  contributing/map.rst.inc
Labels: Status: Reviewed

#11456 Update Length constraint description (mb_strlen)
  reference/constraints/Length.rst
Labels: Status: Reviewed, Validator

#11461 feature: move hinclude from template to fragments
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#11449 Document the new Intl exists() methods
  components/intl.rst
Labels: Intl, Status: Reviewed

#11453 fix(console): configure method visiblity
  console.rst
Labels: Console, Status: Reviewed, bug

#11467 Document the SecurityUserValueResolver & Psr7ServerRequestResolver
  controller/argument_value_resolver.rst
Labels: Status: Needs Review

#11468 Document the UserValueResolver
  controller/argument_value_resolver.rst
Labels: HttpKernel, Status: Reviewed

#11474 Improved the Intl component docs
  components/intl.rst
Labels: Intl, Status: Needs Review

#11451 Update psr4_class_loader.rst to fix incorrect path in directory structure
  components/class_loader/psr4_class_loader.rst
Labels: Status: Reviewed

#11245 Improved routing section
  components/routing.rst
  routing.rst
  routing/external_resources.rst
  routing/optional_placeholders.rst
Labels: Routing, Status: Reviewed

#11478 ordered use statements for php code examples
  components/ldap.rst
  components/mercure.rst
  components/messenger.rst
  components/serializer.rst
  components/var_dumper.rst
  doctrine/event_listeners_subscribers.rst
  form/form_themes.rst
  mercure.rst
  messenger.rst
  quick_tour/flex_recipes.rst
  quick_tour/the_architecture.rst
  reference/configuration/swiftmailer.rst
  reference/constraints/Choice.rst
  reference/constraints/DivisibleBy.rst
  reference/constraints/Url.rst
  reference/dic_tags.rst
  security/form_login_setup.rst
  security/user_provider.rst
Labels: Status: Reviewed

#9433 [Validator] Document the "normalizer" option
  reference/constraints/Email.rst
  reference/constraints/Ip.rst
  reference/constraints/Length.rst
  reference/constraints/NotBlank.rst
  reference/constraints/Regex.rst
  reference/constraints/Url.rst
  reference/constraints/Uuid.rst
  reference/constraints/_normalizer-option.rst.inc
Labels: Status: Reviewed, Validator

#11486 Named *autowiring* aliases
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#11482 Typos and repetetive words
  components/cache/adapters/php_files_adapter.rst
  profiler/matchers.rst
  security/custom_password_authenticator.rst
Labels: Status: Reviewed

#11483 Fixed more wrong white spaces
  components/class_loader/class_map_generator.rst
  components/filesystem/lock_handler.rst
  components/ldap.rst
  components/yaml/yaml_format.rst
  deployment.rst
  doctrine/event_listeners_subscribers.rst
  frontend/assetic/php.rst
  reference/configuration/doctrine.rst
  reference/forms/types/entity.rst
  reference/twig_reference.rst
  service_container/3.3-di-changes.rst
  setup/file_permissions.rst
  setup/flex.rst
  templating/twig_extension.rst
Labels: Status: Reviewed

#11488 Change the Blackfire URL to point to the docs instead of the homepage
  profiler.rst
Labels: Status: Needs Review

#11495 [Workflow] Enhance code examples for better understanding
  workflow.rst
Labels: Status: Reviewed, Workflow

#11493 Added a "see also" note in the Redis cache adapter article
  cache.rst
  components/cache/adapters/redis_adapter.rst
Labels: Cache, Status: Reviewed

#11490 Remove whitespace before self closing xml tag
  security/remember_me.rst
Labels: Security, Status: Reviewed

#11476 use use statement instead of namespace
  components/routing.rst
  controller/error_pages.rst
  controller/service.rst
  routing.rst
  routing/conditions.rst
  routing/custom_route_loader.rst
  routing/external_resources.rst
  routing/extra_information.rst
  routing/hostname_pattern.rst
  routing/optional_placeholders.rst
  routing/redirect_in_config.rst
  routing/requirements.rst
  routing/scheme.rst
  routing/service_container_parameters.rst
  routing/slash_in_parameter.rst
  security.rst
  security/form_login.rst
  security/json_login_setup.rst
  templating.rst
  templating/render_without_controller.rst
  translation/locale.rst
Labels: Routing, Status: Reviewed

#10945 Clarify using chained filterXPath
  components/dom_crawler.rst
Labels: Status: Needs Review

#11500 Fix mistake with int processor (yaml)
  configuration/environment_variables.rst
Labels: Status: Reviewed

#11504 fix indention
  best_practices/forms.rst
  bundles/configuration.rst
  components/cache/adapters/pdo_doctrine_dbal_adapter.rst
  components/cache/adapters/proxy_adapter.rst
  components/console/console_arguments.rst
  components/console/single_command_tool.rst
  components/dependency_injection/compilation.rst
  components/dom_crawler.rst
  components/filesystem/lock_handler.rst
  components/serializer.rst
  components/web_link.rst
  configuration/environments.rst
  configuration/external_parameters.rst
  console/commands_as_services.rst
  create_framework/routing.rst
  doctrine/dbal.rst
  email/dev_environment.rst
  email/spool.rst
  quick_tour/the_view.rst
  reference/configuration/doctrine.rst
  reference/constraints/Collection.rst
  reference/constraints/Range.rst
  reference/constraints/Url.rst
  reference/dic_tags.rst
  reference/forms/types/entity.rst
  reference/forms/types/options/label_attr.rst.inc
  reference/forms/types/options/preferred_choices.rst.inc
  routing.rst
  security.rst
Labels: Status: Reviewed

#11498 fix code example for property info
  components/property_info.rst
Labels: PropertyInfo, Status: Reviewed

#11496 HTTP Cache - update for index.php snippet
  http_cache.rst
Labels: Status: Reviewed, bug

#11506 more indention fixes
  cache.rst
  components/cache/adapters/proxy_adapter.rst
  components/dom_crawler.rst
  components/translation/usage.rst
  console/command_in_controller.rst
  event_dispatcher.rst
  form/dynamic_form_modification.rst
  form/without_class.rst
  frontend/assetic/uglifyjs.rst
  introduction/http_fundamentals.rst
  security/custom_authentication_provider.rst
  security/multiple_guard_authenticators.rst
  service_container/3.3-di-changes.rst
  service_container/autowiring.rst
  service_container/debug.rst
  service_container/injection_types.rst
  templating/PHP.rst
  templating/global_variables.rst
  testing/http_authentication.rst
Labels: Status: Reviewed
