Repository symfony/symfony-docs, pull requests merged in 2019-11, with the labels that each got.

#12574 There is no handler file in storage
  doctrine/pdo_session_storage.rst
Labels: Doctrine, Status: Reviewed

#12564 [PHPUnit Bridge] Minor tweaks related to polyfills
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Reviewed

#12513 Use double \ instead of four \ in expression service
  service_container/expression_language.rst
Labels: ExpressionLanguage, Status: Reviewed

#12389 Adapted the HTTPlug integration docs to Async Client
  components/http_client.rst
Labels: HttpClient, Status: Reviewed, Waiting Code Merge

#12576 Fix XML syntax of Routing examples
  routing.rst
Labels: Routing, Status: Reviewed

#12578 s/bahavior/behavior
  components/phpunit_bridge.rst
Labels: Status: Reviewed

#12575 Removing notes about doctrine_clear_entity_manager middleware
  messenger.rst
Labels: Messenger, Status: Reviewed

#12580 Fix log directory parameter
  reference/configuration/kernel.rst
Labels: HttpKernel, Status: Reviewed

#12581 Add missing deprecated directive for kernel.log_dir parameter
  reference/configuration/kernel.rst
Labels: HttpKernel, Status: Needs Review

#12568 Update form_themes.rst
  form/form_themes.rst
Labels: Status: Needs Review

#12588 Fix minor typos in Encore Webpack
  frontend/encore/advanced-config.rst
  frontend/encore/faq.rst
  frontend/encore/postcss.rst
Labels: Status: Reviewed, front-end

#12531 Fix construction of SmtpTransport in Mailer docs
  components/mailer.rst
Labels: Mailer, Status: Reviewed

#12596 Remove hint that redis does not support DelayStamp
  messenger.rst
Labels: Status: Reviewed

#12599 [Security] Minor tweak in the impersonation explanation
  security/impersonating_user.rst
Labels: Security, Status: Reviewed

#12587 Simplify example of GulpBusterVersionStrategy
  frontend/custom_version_strategy.rst
Labels: Status: Reviewed, front-end

#12464 [Form] Documented "Supporting Bootstrap 4 custom switches"
  form/bootstrap4.rst
Labels: Form, Status: Reviewed

#12384 Documented the new REMOTE_ADDR option
  deployment/proxies.rst
Labels: HttpFoundation, Status: Reviewed

#12231 Explain how to add `from_transport` on `messenger.message_handler` tag
  messenger.rst
Labels: Messenger, Status: Reviewed

#12579 Add Composer installation before step 1 for Symfony Flex
  bundles/best_practices.rst
Labels: Status: Reviewed

#12582 Use normalizer context constants everywhere
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#12584 Add new WeekType Documentation
  reference/forms/types.rst
  reference/forms/types/map.rst.inc
  reference/forms/types/options/weeks.rst.inc
  reference/forms/types/week.rst
Labels: Status: Reviewed

#12586 [Messenger] update events for 4.4
  messenger.rst
Labels: Messenger, Status: Reviewed

#12600 [Doctrine] Don't mention invokable listeners in 4.3
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#12601 Update doctrine.rst
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#12603 [mercure] compatibility with v0.8
  components/mercure.rst
  mercure.rst
Labels: Status: Reviewed

#12604 [Console] Update some method names
  components/console/helpers/progressbar.rst
Labels: Console, Status: Reviewed

#12605 [Security] query string can't be used in security.access_control > path
  security/access_control.rst
Labels: Status: Reviewed

#12607 Update mercure.rst
  mercure.rst
Labels: Status: Needs Review

#12538 extra code example
  security.rst
Labels: Status: Needs Review

#12610 [3.4] Fixed many spelling issues found in the docs
  best_practices/controllers.rst
  best_practices/templates.rst
  bundles/best_practices.rst
  components/asset.rst
  components/cache/adapters/php_array_cache_adapter.rst
  components/class_loader/class_loader.rst
  components/config.rst
  components/console/helpers/processhelper.rst
  components/console/helpers/progressbar.rst
  components/console/helpers/questionhelper.rst
  components/console/usage.rst
  components/debug.rst
  components/dependency_injection/compilation.rst
  components/dom_crawler.rst
  components/expression_language.rst
  components/filesystem.rst
  components/intl.rst
  components/process.rst
  components/property_access.rst
  components/property_info.rst
  components/security/authorization.rst
  components/serializer.rst
  components/stopwatch.rst
  components/templating/slotshelper.rst
  components/translation/custom_formats.rst
  components/translation/usage.rst
  components/var_dumper/advanced.rst
  components/yaml.rst
  configuration/external_parameters.rst
  configuration/micro_kernel_trait.rst
  configuration/multiple_kernels.rst
  console/coloring.rst
  contributing/code/conventions.rst
  contributing/code/pull_requests.rst
  contributing/code/security.rst
  contributing/code/standards.rst
  contributing/community/review-comments.rst
  contributing/diversity/governance.rst
  contributing/documentation/format.rst
  contributing/documentation/overview.rst
  controller/argument_value_resolver.rst
  controller/upload_file.rst
Labels: Status: Reviewed

#12617 Update best_practices.rst
  best_practices.rst
Labels: DependencyInjection, Status: Reviewed

#12620 fix some more typos
  components/property_access.rst
  configuration/micro_kernel_trait.rst
Labels: Status: Reviewed

#12616 Tell user about installing twig
  page_creation.rst
Labels: Status: Reviewed

#12619 Update doctrine.rst
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#12614 Simply update the ESI initial specs date (dated 2001)
  http_cache/esi.rst
Labels: Status: Reviewed

#12598 Update documentation for MercureBundle: add enable_profiler option
  _images/mercure/panel.png
  mercure.rst
Labels: Mercure, Profiler, Status: Reviewed

#12625 Update configuration.rst
  configuration.rst
Labels: Status: Reviewed

#12624 Update input.rst
  console/input.rst
Labels: Console, Status: Reviewed

#12626 Update messenger.rst
  messenger.rst
Labels: Messenger, Status: Reviewed

#12623 Update profiler.rst
  profiler.rst
Labels: Profiler, Status: Reviewed

#12627 Update simple-example.rst
  frontend/encore/simple-example.rst
Labels: Status: Reviewed, front-end

#12631 fix some issues
  components/class_loader/class_loader.rst
  contributing/code/conventions.rst
  contributing/code/maintenance.rst
  form/type_guesser.rst
  reference/dic_tags.rst
  translation/debug.rst
Labels: Status: Reviewed

#12622 Add tip for trusted_proxies
  deployment/proxies.rst
Labels: Status: Reviewed

#12640 fix supported installable version formats
  setup.rst
Labels: Status: Reviewed

#12634 remove gender-related terms from HTTP fundamentals diagrams
  _images/http/xkcd-full.png
  _images/http/xkcd-request.png
Labels: Status: Reviewed

#12638 Fix broken link for multiple messenger buses
  messenger/message-recorder.rst
Labels: Messenger, Status: Reviewed

#12628 Replace images by more recent one
  _images/controller/error_pages/errors-in-prod-environment.png
  _images/controller/error_pages/exceptions-in-dev-environment.png
Labels: Status: Reviewed

#12641 Update MySQL column type definition
  doctrine/pdo_session_storage.rst
Labels: Status: Reviewed

#12643 ContainerAwareEventDispatcher was removed
  components/event_dispatcher.rst
Labels: Status: Reviewed

#12542 Change the default mapping type to XML
  doctrine/reverse_engineering.rst
Labels: Doctrine, Status: Reviewed

#12653 improve sentence re: `content-disposition` header
  components/http_foundation.rst
Labels: Status: Reviewed

#12637 Add some links to objects injected by Symfony in expressions
  components/expression_language/syntax.rst
Labels: ExpressionLanguage, Status: Reviewed

#12649 Fix typo in lock.rst
  components/lock.rst
Labels: Lock, Status: Reviewed, Workflow

#12664 #12630 Update .env for "send grid" recipe change
  mailer.rst
Labels: Status: Reviewed

#12663 Documented the IPUtils::anonymize method
  components/http_foundation.rst
Labels: HttpFoundation, Status: Needs Review

#12665 #12662 [SecurityBundle] Wrong note about password encoders
  reference/configuration/security.rst
Labels: SecurityBundle, Status: Needs Review

#12652 remove 'command' from execute argument
  console.rst
Labels: Status: Needs Review

#12668 #12661 Remove outdated service
  security/user_provider.rst
Labels: Status: Reviewed

#12667 [Mailer] Removed mention of Let's Encrypt for S/MIME certificates
  mailer.rst
Labels: Mailer, Status: Needs Review

#12670 Remove deprecation notice block for tagged
  service_container/tags.rst
Labels: Status: Needs Review

#12659 [Messenger] Update version constraint for Redis extension
  messenger.rst
Labels: Messenger, Status: Needs Review

#12672 fix reference
  forms.rst
Labels: Form, Status: Needs Review

#12606 BC promise: only optional arguments can be removed
  contributing/code/bc.rst
Labels: Status: Reviewed, Waiting feedback

#12671 #12633 Update "upgrading" guide for Symfony5
  setup/upgrade_major.rst
Labels: Status: Needs Review

#12646 Update routing.rst
  routing.rst
Labels: Status: Needs Review

#12675 Change 4 to 5 in anticipation of future patch
  setup/upgrade_patch.rst
Labels: Status: Needs Review

#10991 [DIC] Static injection
  components/phpunit_bridge.rst
  routing.rst
  service_container/calls.rst
  service_container/definitions.rst
  service_container/injection_types.rst
Labels: DependencyInjection, Status: Reviewed

#12636 Fixed the explanation of the utf8 router option
  reference/configuration/framework.rst
Labels: Routing, Status: Needs Review

#12679 Fix doctrine page command line break
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#12684 Add container.hot_path to built-in service tags
  reference/dic_tags.rst
Labels: DependencyInjection, Performance, Status: Reviewed

#12694 Fix filename
  session/locale_sticky_session.rst
Labels: Session, Status: Reviewed

#12681 Replace tagged with tagged_iterator for service tagging PHP example
  service_container/tags.rst
Labels: Status: Reviewed

#12677 Removed the docs about Debug
  _build/redirection_map
  components/class_loader.rst
  components/class_loader/debug_class_loader.rst
  components/debug.rst
  configuration/front_controllers_and_kernel.rst
Labels: Debug, Status: Reviewed

#12700 Follow up to remove the debug component
  components/phpunit_bridge.rst
Labels: Debug, Status: Reviewed

#12706 add use statement
  components/mailer.rst
Labels: Mailer, Status: Reviewed

#12710 Add Blackfire Docker support for the local web server
  setup/symfony_server.rst
Labels: Status: Reviewed

#12707 uppercase
  setup.rst
Labels: Status: Reviewed

#12720 Changed names of Intl classes in form types docs
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
Labels: Form, Status: Reviewed

#12712 Tweak the IsTrue validation docs
  reference/constraints/IsTrue.rst
Labels: Status: Reviewed, Validator

#12721 Removed constructor parameters from AuthenticationTrustResolver
  components/security/authorization.rst
Labels: Security, Status: Reviewed

#12723 [minor] Removed simple_form and simple_pre_auth
  security/auth_providers.rst
Labels: Security, Status: Reviewed

#12739 Remove references to the Twig extensions repo
  reference/dic_tags.rst
  reference/twig_reference.rst
Labels: Status: Reviewed, Twig

#12693 Set PHP Version requirement to 7.2.5
  setup.rst
Labels: Status: Reviewed
