Repository symfony/symfony-docs, pull requests merged in 2019-06, with the labels that each got.

#11641 Fix a few minor misprints in Mailer article
  mailer.rst
Labels: Status: Reviewed

#11394 edit normalizer deprecated method on 4.2
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#11635 #11627 Minor/Patch version fix
  setup/upgrade_minor.rst
Labels: Status: Reviewed

#11645 Fix several typos
  cache.rst
  components/var_dumper/advanced.rst
  reference/forms/types/hidden.rst
  reference/forms/types/integer.rst
  testing/profiling.rst
Labels: Status: Reviewed

#11646 Fix several typos
  cache.rst
  components/var_dumper/advanced.rst
  components/workflow.rst
  configuration.rst
  configuration/dot-env-changes.rst
  mailer.rst
  reference/forms/types/hidden.rst
  testing/profiling.rst
Labels: Status: Reviewed

#11642 #11607 Removed IBAN docs, not available in version 4.2
  reference/constraints/Bic.rst
Labels: Validator, bug

#11639 Tweaks to messenger docs based on feedback from @Tobion
  messenger.rst
Labels: Messenger, Status: Reviewed

#11596 Update installation.rst
  frontend/encore/installation.rst
Labels: Status: Reviewed, front-end

#11648 [HttpClient] Service name
  components/http_client.rst
Labels: HttpClient, Status: Reviewed, bug

#11655 fix constraint reference YAML config syntax
  reference/constraints/Negative.rst
  reference/constraints/NegativeOrZero.rst
  reference/constraints/Positive.rst
  reference/constraints/PositiveOrZero.rst
Labels: Status: Reviewed, Validator, bug

#11651 [Mailer] Sort providers alphabetically
  mailer.rst
Labels: Mailer, Status: Reviewed

#11650 [HttpClient] improve doc again
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#11653 Fixing docs about switch_user and custom voters
  security/impersonating_user.rst
Labels: Security, Status: Reviewed

#11663 [HttpClient] Documented the cancel() method
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#11669 Clarifying that you can't override real env vars
  configuration/dot-env-changes.rst
Labels: DependencyInjection, Status: Reviewed

#11672 Remvove space before self-closing xml tag
  security/impersonating_user.rst
Labels: Security, Status: Reviewed

#11673 Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Reviewed

#11683 Use .xlf extension
  translation/debug.rst
Labels: Status: Needs Review, Translator

#11687 Use .yaml instead of .yml
  translation/message_format.rst
Labels: Status: Reviewed, Translator

#11677 Update mailer.rst - replace twig filter tag with apply tag
  mailer.rst
Labels: Status: Reviewed

#11676 [Reference][HttpClient] Auth basic is a scalar type
  reference/configuration/framework.rst
Labels: HttpClient, Status: Reviewed

#11682 Show DomCrawler results consistent
  components/dom_crawler.rst
Labels: DomCrawler, Status: Reviewed

#11689 Fix markup
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#11688 Update mailer.rst - fix twig path configuration
  mailer.rst
Labels: Status: Reviewed

#11680 Removed blank line after filepath
  bundles/best_practices.rst
Labels: Status: Reviewed

#11679 Ordered use statements
  components/http_client.rst
  doctrine.rst
Labels: Status: Reviewed

#11678 Blank line after directive and no blank line after filepath
  mailer.rst
  messenger.rst
Labels: Status: Reviewed

#11330 Create a migration guide in the docs.
  index.rst
  migration.rst
Labels: Status: Needs Review, ⭐️ EU-FOSSA Hackathon

#11664 [DI] Use classes from Contracts instead of the component
  service_container/service_subscribers_locators.rst
Labels: Contracts, DependencyInjection

#11665 [EventDispatcher] Use the classes from Contracts instead of the component
  components/event_dispatcher.rst
  components/event_dispatcher/generic_event.rst
  event_dispatcher/method_behavior.rst
Labels: Contracts, EventDispatcher, Status: Needs Review

#11696 [Routing] Simplified some doc
  components/routing.rst
Labels: Routing, Status: Reviewed

#11697 Fixed a minor RST syntax issue
  bundles/override.rst
Labels: Status: Reviewed

#11703 Require Dotenv component without --dev
  components/dotenv.rst
Labels: Dotenv, Status: Reviewed

#11707 Update conventions.rst
  contributing/code/conventions.rst
Labels: Status: Reviewed

#11681 Use current major version for deprecated/versionadded examples
  contributing/documentation/format.rst
Labels: Status: Reviewed

#11716 [Serializer] Use pack to install
  serializer.rst
Labels: Serializer, Status: Reviewed

#11711 [Validator] Update the propertyPath description of DivisibleBy
  reference/constraints/DivisibleBy.rst
Labels: Status: Reviewed, Validator

#11710 [Validator] Documented the "compared_value_path" placeholder
  reference/constraints/_comparison-propertypath-option.rst.inc
Labels: Status: Reviewed, Validator

#11684 Remove old versionadded directives
  components/http_client.rst
  components/phpunit_bridge.rst
  doctrine.rst
  mailer.rst
  translation.rst
Labels: Status: Reviewed

#11708 [DI] Add deprecation info for !tagged
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#11426 Added pitfall hint about Lock::isAcquired()
  components/lock.rst
Labels: Lock, Status: Reviewed

#11719 Typos
  reference/forms/types/options/checkbox_empty_data.rst.inc
  reference/forms/types/options/data.rst.inc
Labels: Form, Status: Reviewed

#11714 [Workflow] Update the article about dumping workflows
  workflow/dumping-workflows.rst
Labels: Status: Reviewed, Workflow

#11709 Added a short guide to help creating the Symfony diagrams
  _images/sources/README.md
Labels: Status: Needs Review

#11718 Remove old versionadded directives
  reference/constraints/_comparison-propertypath-option.rst.inc
  translation/message_format.rst
Labels: Status: Reviewed

#11662 [Validator] Documented the support of multiple types in Type constraint
  reference/constraints/Type.rst
Labels: Status: Reviewed, Validator

#11668 [HttpClient] doc how to cancel a request + upload files
  components/http_client.rst
  reference/configuration/framework.rst
Labels: HttpClient, Status: Reviewed

#11723 Update impersonating_user.rst
  security/impersonating_user.rst
Labels: Security, Status: Reviewed, bug

#11704 [OptionsResolver] Add note about deprecated options
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#11726 [Symfony Server] Tweaks
  setup/symfony_server.rst
Labels: Status: Reviewed

#11727 Fix typo in word invitation
  translation/message_format.rst
Labels: Status: Reviewed, Translator, bug

#11686 [Lock] mongodb store removed from symfony 4.3
  components/lock.rst
Labels: Lock, Status: Reviewed

#11730 [Messenger] Multiple buses: type-o
  messenger/multiple_buses.rst
Labels: Messenger, Status: Reviewed, bug

#11690 Revamped the main configuration file
  _build/redirection_map
  best_practices/configuration.rst
  bundles.rst
  configuration.rst
  configuration/configuration_organization.rst
  configuration/env_var_processors.rst
  configuration/environments.rst
  configuration/front_controllers_and_kernel.rst
  configuration/multiple_kernels.rst
  configuration/override_dir_structure.rst
  controller/error_pages.rst
  doctrine/pdo_session_storage.rst
  reference/configuration/kernel.rst
  reference/configuration/swiftmailer.rst
  service_container/parameters.rst
  setup/upgrade_major.rst
Labels: Config, Status: Reviewed

#11734 Replace SwiftMailer with the new Mailer Component
  components/messenger.rst
Labels: Mailer, Messenger, Status: Reviewed

#11740 [Configuration] Some tweaks about Flex usage
  configuration.rst
Labels: Config, Status: Reviewed

#11729 Updates the tip explaining how to set the base phpunit version
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Reviewed

#11732 Redis 4.3 is required
  messenger.rst
Labels: Messenger, Status: Reviewed

#11666 Update controller.rst
  controller.rst
Labels: Status: Reviewed

#11738 Fix indention
  components/validator/resources.rst
Labels: Status: Reviewed, Validator, bug

#11736 No explicit use of code-block:: php
  translation/message_format.rst
Labels: Status: Reviewed, Translator

#11737 Use ordered use statements for php code examples
  components/http_client.rst
  messenger/message-recorder.rst
Labels: Status: Reviewed

#11743 Fix a spelling mistake.
  doctrine/reverse_engineering.rst
Labels: Doctrine, Status: Reviewed

#11618 Add note about extra configuration for mod_xsendfile
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#11746 [OptionsResolver] Minor reword in the description
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#11745 [Messenger] Fixing & improving autowireable names section
  messenger/multiple_buses.rst
Labels: Messenger, Status: Reviewed

#11750 use Cookie::create()
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#11752 Added the missing "experimental" notices in some components
  components/http_client.rst
  components/mailer.rst
  components/mime.rst
Labels: Status: Reviewed

#11739 Uncomment code and add info
  email.rst
Labels: Mailer, Status: Reviewed

#11747 Reworded the Setup article about the local Symfony server
  setup.rst
Labels: Status: Reviewed

#11741 Adding "special case" when need to select development branch instead of master for new features.
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#11761 Remove old versionadded directives
  reference/constraints/Type.rst
Labels: Status: Reviewed, Validator

#11755 Remove a tip about Symfony setup and VMs
  setup.rst
Labels: Status: Reviewed

#11693 fix validation files paths
  components/validator/resources.rst
  forms.rst
  reference/constraints/IsTrue.rst
Labels: Status: Reviewed

#11760 Update Collection.rst
  reference/constraints/Collection.rst
Labels: Status: Reviewed, Validator

#11771 Use valid number of backslashes, depending on 1 or 2 ticks
  components/cache/cache_pools.rst
  components/form.rst
  contributing/code/bc.rst
  create_framework/separation_of_concerns.rst
  reference/dic_tags.rst
Labels: Status: Reviewed

#11772 Use valid number of backslashes, depending on 1 or 2 ticks - 4.2
  components/cache/cache_items.rst
  messenger/multiple_buses.rst
Labels: Status: Reviewed

#11774 kernel.debug is a boolean, not a string
  reference/configuration/twig.rst
Labels: Status: Reviewed

#11763 fix symbol option description
  reference/forms/types/percent.rst
Labels: Form, Status: Reviewed

#11784 [HttpClient] Fixed missing parenthesis
  components/http_client.rst
Labels: Status: Reviewed

#11778 Removed an article related to contributing
  _build/redirection_map
  contributing/community/index.rst
  contributing/community/other.rst
  contributing/map.rst.inc
Labels: Status: Reviewed

#11796 Add missing asterisk (*)
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#11773 Use valid number of backslashes, depending on 1 or 2 ticks - 4.3
  messenger.rst
  reference/configuration/twig.rst
  reference/forms/types/collection.rst
Labels: Status: Reviewed

#11775 Removed old deprecated directives.
  components/serializer.rst
  configuration.rst
  configuration/front_controllers_and_kernel.rst
  reference/twig_reference.rst
  translation/templates.rst
Labels: Status: Reviewed

#11795 Add example for env var processor: trim
  configuration/env_var_processors.rst
Labels: Config, Dotenv, Status: Reviewed

#11785 Added a missing redirection for a deleted article
  _build/redirection_map
Labels: Status: Needs Review

#11762 How to get more attention by the whole Symfony-Team to the documentation?
  .github/CODEOWNERS
Labels: Status: Reviewed

#11756 [Form] Documented the setInvalidMessage() method for data transformers
  form/data_transformers.rst
Labels: Form, Status: Reviewed

#11804 Add weeks in the options 'labels'
  reference/forms/types/dateinterval.rst
Labels: Form, Status: Reviewed

#11695 Update multiple_buses.rst
  messenger/multiple_buses.rst
Labels: Messenger, Status: Reviewed

#11574 [Security] Tell about request_matcher
  security/firewall_restriction.rst
Labels: Security, Status: Reviewed

#11805 [Messenger] Fixed a reference
  messenger.rst
Labels: Messenger, Status: Reviewed

#11815 remove outdated deprecation warnings
  configuration.rst
  configuration/front_controllers_and_kernel.rst
Labels: Status: Reviewed

#11806 Remove an outdated article about Composer
  _build/redirection_map
  contributing/code/tests.rst
  create_framework/introduction.rst
  setup.rst
  setup/composer.rst
  setup/unstable_versions.rst
Labels: Status: Reviewed

#11799 Add Symfony version to symfony new command of Symfony Installer
  best_practices/creating-the-project.rst
Labels: Status: Reviewed

#11823 Fix broken link to doctrine documentation
  form/form_collections.rst
Labels: Status: Reviewed

#11819 Use single quotes for example code
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#11821 Missed code format
  components/browser_kit.rst
Labels: BrowserKit, Status: Reviewed

#11816 [HttpClient] Fixed the indenting of config reference
  reference/configuration/framework.rst
Labels: HttpClient, Status: Reviewed

#11822 [HttpClient] add section about interop + performance
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#11820 [HttpClient] add words about HTTPlug
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#11813 [Cache] Make sure the chain cache configuration works
  cache.rst
Labels: Cache, Status: Reviewed

#11817 [BrowserKit] Document the integration with HttpClient
  components/browser_kit.rst
Labels: BrowserKit, HttpClient, Status: Reviewed

#11832 Update the PHP requirements for Symfony 3.4 version
  reference/requirements.rst
Labels: Status: Reviewed

#11831 Fixed a broken reference
  setup.rst
Labels: Status: Needs Review, bug

#11830 Fix new instance of a class name
  components/cache/psr6_psr16_adapters.rst
Labels: Cache, Status: Reviewed

#11794 Update name of arguments in interface DataMapperInterface methods
  form/data_mappers.rst
Labels: Status: Needs Review

#11833 Provide a link to Symfony client download instructions
  setup.rst
Labels: Status: Needs Review

#11788 Reworded the file upload article to use unmapped fields
  controller/upload_file.rst
Labels: Status: Reviewed

#11839 Add Yonel as a core team member
  contributing/code/core_team.rst
Labels: Status: Reviewed

#11843 Rename ErrorHandler to ErrorCatcher
  contributing/code/core_team.rst
Labels: Status: Reviewed

#11844 [HttpClient] Fix code block
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#11765 [Forms] Reworded the article about creating custom form types
  _images/form/form-custom-type-postal-address-fragment-names.svg
  _images/form/form-custom-type-postal-address.svg
  _images/sources/form/form-custom-type-postal-address-fragment-names.dia
  _images/sources/form/form-custom-type-postal-address.dia
  form/create_custom_field_type.rst
  form/create_form_type_extension.rst
  form/data_transformers.rst
  form/dynamic_form_modification.rst
  form/form_dependencies.rst
  form/use_empty_data.rst
Labels: Form, Status: Needs Review

#11846 Small typo
  messenger.rst
Labels: Messenger, Status: Reviewed

#11834 [Intl] Mention that all methods trigger exceptions
  components/intl.rst
Labels: Intl, Status: Needs Review
