Repository symfony/symfony-docs, pull requests merged in 2020-06, with the labels that each got.

#13737 Update examples of custom route loaders
  routing/custom_route_loader.rst
Labels: Routing, Status: Reviewed

#13663 Update custom_normalizer.rst
  serializer/custom_normalizer.rst
Labels: Serializer, Status: Reviewed

#13658 Update events.rst
  components/console/events.rst
Labels: Console, Status: Reviewed

#13735 Update reactjs.rst
  frontend/encore/reactjs.rst
Labels: Status: Reviewed, front-end

#13743 Update http_foundation.rst to replace withExpiresTime
  components/http_foundation.rst
Labels: Status: Reviewed

#13741 Update releases.rst
  contributing/community/releases.rst
Labels: Status: Reviewed

#13739 Fix: message must be notInRangeMessage
  reference/constraints/Range.rst
Labels: Status: Reviewed, Validator

#13734 Update installation.rst
  frontend/encore/installation.rst
Labels: Status: Reviewed, front-end

#13721 [DI] Mention that container.no_preload tag propagates automatically
  reference/dic_tags.rst
Labels: DependencyInjection, Status: Reviewed

#13669 [Validator] Documented the ExpressionLanguageSyntax constraint
  reference/constraints.rst
  reference/constraints/ExpressionLanguageSyntax.rst
  reference/constraints/map.rst.inc
Labels: Status: Reviewed, Validator

#13742 Update releases.rst
  .github/PULL_REQUEST_TEMPLATE.md
  contributing/community/releases.rst
Labels: Status: Reviewed

#13751 Update information in flex about added files for twig
  quick_tour/flex_recipes.rst
Labels: Status: Reviewed

#13750 [Security] anonymous: lazy deprecation warning
  security.rst
Labels: Security, Status: Reviewed

#13706 Removed ClassLoader, DotEnv, Mercure, WebLink, Templating, ErrorHandler and Polyfill component docs
  _build/redirection_map
  components/asset.rst
  components/class_loader.rst
  components/dotenv.rst
  components/error_handler.rst
  components/mercure.rst
  components/phpunit_bridge.rst
  components/polyfill_apcu.rst
  components/polyfill_ctype.rst
  components/polyfill_iconv.rst
  components/polyfill_intl_grapheme.rst
  components/polyfill_intl_icu.rst
  components/polyfill_intl_idn.rst
  components/polyfill_intl_messageformatter.rst
  components/polyfill_intl_normalizer.rst
  components/polyfill_mbstring.rst
  components/polyfill_php54.rst
  components/polyfill_php55.rst
  components/polyfill_php56.rst
  components/polyfill_php70.rst
  components/polyfill_php71.rst
  components/polyfill_php72.rst
  components/polyfill_php73.rst
  components/polyfill_uuid.rst
  components/templating.rst
  components/templating/slotshelper.rst
  components/web_link.rst
  configuration.rst
  controller/error_pages.rst
  introduction/from_flat_php_to_symfony.rst
  web_link.rst
Labels: Status: Reviewed

#13769 Minor update of the terminology used
  service_container/3.3-di-changes.rst
Labels: Status: Reviewed

#13774 Fixed typo in classname
  security.rst
Labels: Status: Reviewed

#13765 Update column type for MySQL sessions table
  session/database.rst
Labels: Doctrine, HttpFoundation, Status: Reviewed

#13770 Add missing "format" argument on denormalize
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13762 Update messenger.rst
  messenger.rst
Labels: Messenger, Status: Reviewed

#13754 Fix supportsNormalization parameters definition
  serializer/custom_normalizer.rst
Labels: Serializer, Status: Reviewed

#13760 Update security.rst
  security.rst
Labels: Security, Status: Reviewed

#13777 [Twig] Mention that passing an array of roles/attributes is deprecated
  reference/twig_reference.rst
Labels: Security, Status: Needs Review, Twig

#13776 adapt reference to no longer mention multi attribute support
  reference/twig_reference.rst
Labels: Security, Status: Reviewed, Twig

#13756 Add Debug Formatter Helper
  console.rst
Labels: Console, Status: Reviewed

#13757 Be more specific about flock releasing locks automatically
  components/lock.rst
Labels: Lock, Status: Reviewed

#13550 [Browserkit] The Client class has been replaced by the AbstractBrowser since SF 4.3
  components/browser_kit.rst
  testing.rst
Labels: Status: Needs Review

#13761 Browser-Kit: Replace Client with AbstractBrowser
  components/browser_kit.rst
Labels: Status: Needs Review

#13781 Fix typo in the markup
  contributing/code/bc.rst
Labels: Status: Reviewed

#13782 Fix typo in the markup
  mailer.rst
Labels: Status: Reviewed

#13784 Mailer tweaks
  mailer.rst
Labels: Mailer, Status: Reviewed

#13792 Update factories.rst
  service_container/factories.rst
Labels: DependencyInjection, Status: Reviewed

#13744 Fix form unit testing code sample
  form/unit_testing.rst
Labels: Form, Status: Reviewed, Testing

#13812 Update mercure.rst
  mercure.rst
Labels: Mercure, Status: Reviewed

#13805 Update : advertize ⮞ advertise
  create_framework/introduction.rst
Labels: Status: Reviewed

#13800 Typo fix : additonal ⮞ additional
  workflow.rst
Labels: Status: Reviewed

#13802 Typo fix : developped ⮞ developed
  setup/symfony_server.rst
Labels: Status: Reviewed

#13803 Typo fix : developped ⮞ developed
  setup.rst
Labels: Status: Reviewed

#13808 Typo fix : http-methode-override ⮞ http-method-override
  configuration/env_var_processors.rst
Labels: Status: Reviewed

#13806 Typo fix : shoud ⮞ should
  components/http_client.rst
Labels: Status: Reviewed

#13809 Added missing space : everytime ⮞ every time
  form/create_custom_field_type.rst
Labels: Status: Reviewed

#13811 Typo fix : rolse ⮞ roles
  security/access_control.rst
Labels: Status: Reviewed

#13810 Several typo fixes
  components/cache/adapters/couchbasebucket_adapter.rst
Labels: Status: Reviewed

#13807 Typo fix : propery ⮞ property
  reference/constraints/ExpressionLanguageSyntax.rst
Labels: Status: Reviewed, Validator

#13804 Typo fix : dispacher ⮞ dispatcher
  security.rst
Labels: Status: Reviewed

#13821 Update firewall.rst
  components/security/firewall.rst
Labels: Security, Status: Reviewed

#13820 Update voters.rst
  security/voters.rst
Labels: Security, Status: Reviewed

#13818 Update authorization.rst
  components/security/authorization.rst
Labels: Security, Status: Reviewed

#13817 Update authorization.rst
  components/security/authorization.rst
Labels: Security, Status: Reviewed

#13824 Improve the Best Practice about forms with multiple buttons
  best_practices.rst
Labels: Status: Reviewed

#13823 Removed the file comparing Assetic and Encore
  _build/redirection_map
  frontend.rst
  frontend/encore/versus-assetic.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed, front-end

#13819 Provides a way to override cache and log folders from the ENV
  configuration/override_dir_structure.rst
Labels: Status: Reviewed

#13822 [Security] Documented CustomUserMessageAccountStatusException
  security/user_checkers.rst
Labels: Security, Status: Needs Review

#13829 Update access_control.rst
  security/access_control.rst
Labels: Security, Status: Reviewed

#13830 Update access_denied_handler.rst
  security/access_denied_handler.rst
Labels: Security, Status: Reviewed

#13833 Update expressions.rst
  security/expressions.rst
Labels: Security, Status: Reviewed

#13832 Update custom_authentication_provider.rst
  security/custom_authentication_provider.rst
Labels: Security, Status: Reviewed

#13815 Update authentication.rst
  components/security/authentication.rst
Labels: Security, Status: Reviewed

#13835 use getRoleNames in Symfony 5.0 instead of getRoles()
  components/security/authorization.rst
Labels: Security, Status: Reviewed

#13839 Update filesystem.rst
  components/filesystem.rst
Labels: Filesystem, Status: Reviewed

#13836 Update authorization.rst
  components/security/authorization.rst
Labels: Security, Status: Reviewed

#13846 Update TypeHint Serializer.rst
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13845 Update voters.rst
  security/voters.rst
Labels: Security

#13837 Add compatible type-hinting
  serializer/custom_normalizer.rst
Labels: Serializer, Status: Reviewed

#13844 Add documentation about data collectors late collect
  profiler/data_collector.rst
Labels: Status: Needs Review

#13816 [Mime] Document the DKIM signer
  mailer.rst
Labels: Mime, Status: Needs Review

#13848 Update direct_submit.rst
  form/direct_submit.rst
Labels: Form, Status: Reviewed

#13843 Fill out custom type guesser paragraph
  components/mime.rst
Labels: Status: Needs Review

#13855 Replaced orphan " and" at the end of the sentence by a dot
  components/event_dispatcher.rst
Labels: Status: Reviewed

#13853 Update serializer.rst
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13858 Add missing dot at the end of a sentence
  components/cache.rst
Labels: Cache, Status: Reviewed

#13856 [workflow] corrected argument type
  workflow.rst
Labels: Status: Reviewed, Workflow

#13857 Update input.rst
  console/input.rst
Labels: Status: Reviewed

#13859 fix typo
  frontend/encore/simple-example.rst
Labels: Status: Reviewed, front-end

#13860 corrected tags order
  frontend/encore/split-chunks.rst
Labels: front-end

#13838 Added a caution about encoding DSN credentials
  components/mailer.rst
Labels: Status: Reviewed

#13778 Update documentation for removal of config/bootstrap.php
  configuration/dot-env-changes.rst
  migration.rst
  testing/bootstrap.rst
Labels: Status: Needs Review

#13752 Example should be translator not translation
  reference/configuration/framework.rst
Labels: Status: Reviewed, Translator

#13783 List which values are true for %env(bool:xxx)%
  configuration/env_var_processors.rst
Labels: DependencyInjection, Status: Reviewed

#13866 Fix typo in 'How to Configure Monolog to Email Errors'
  logging/monolog_email.rst
Labels: Status: Reviewed

#13870 Change wrong attribute value in WSDL example
  controller/soap_web_service.rst
Labels: Status: Reviewed

#13874 Update sessions.rst
  components/http_foundation/sessions.rst
Labels: HttpFoundation, Status: Reviewed

#13879 Update database.rst
  session/database.rst
Labels: Doctrine, Status: Reviewed

#13878 Update upload_file.rst
  controller/upload_file.rst
Labels: Status: Reviewed

#13876 Update testing.rst
  testing.rst
Labels: Status: Reviewed

#13877 Update error_pages.rst
  controller/error_pages.rst
Labels: Status: Reviewed

#13868 [Notifier] Removed some restriction
  notifier.rst
Labels: Notifier, Status: Needs Review

#13867 [DI] Document param() and abstract_arg()
  components/dependency_injection.rst
  service_container.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Needs Review

#13862 update sass-loader version printed in symfony 5.1
  frontend/encore/simple-example.rst
Labels: Status: Reviewed, front-end

#13880 Typo Testing
  testing.rst
Labels: Status: Reviewed, Testing

#13886 Update testing.rst
  testing.rst
Labels: Status: Reviewed, Testing

#13882 Update cache_invalidation.rst
  http_cache/cache_invalidation.rst
Labels: Status: Reviewed

#13887 Typehint Testing
  testing.rst
Labels: Status: Reviewed

#13888 Update http_kernel.rst
  components/http_kernel.rst
Labels: Status: Reviewed

#13889 Update http_kernel.rst
  components/http_kernel.rst
Labels: HttpKernel, Status: Reviewed

#13864 updated generated code according to `make:auth` results in Symfony 5.1
  security/form_login_setup.rst
Labels: Security, Status: Reviewed

#13893 Fixed path for RoutingConfigurator class.
  configuration/micro_kernel_trait.rst
Labels: Routing, Status: Reviewed

#13892 Add TypeHint
  testing.rst
Labels: DomCrawler, Status: Reviewed

#13747 [RememberMe] add doctrine migration note
  security/remember_me.rst
Labels: Security, Status: Reviewed

#13359 Improved the HTTPCache examples mentioning s-maxage
  http_cache.rst
  http_cache/esi.rst
  http_cache/expiration.rst
Labels: Status: Reviewed

#13897 Update cache_invalidation.rst
  http_cache/cache_invalidation.rst
Labels: Cache, Status: Reviewed

#13906 Update form.rst
  components/form.rst
Labels: Form, Status: Reviewed

#13901 Update workflow.rst
  workflow.rst
Labels: Status: Reviewed, Workflow

#13899 Update ssi.rst Controller Paths
  http_cache/ssi.rst
Labels: Status: Reviewed

#13895 Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Reviewed

#13905 add deprecation contracts package
  components/contracts.rst
Labels: Status: Reviewed

#13908 Don't use Twig as a public service
  templates.rst
Labels: DependencyInjection, Status: Reviewed

#13910 🎨 Improved consistency in Upload Files snippet
  controller/upload_file.rst
Labels: Form, Status: Reviewed

#13903 Upgrade all CI to Sphinx 1.8.5
  .doctor-rst.yaml
  .github/workflows/ci.yaml
  _build/.requirements.txt
  _build/_exts/symfonycom/__init__.py
  _build/_exts/symfonycom/sphinx/__init__.py
  _build/_exts/symfonycom/sphinx/lexer.py
  _build/_static/rtd_custom.css
  _build/_static/symfony-logo.svg
  _build/_themes/sphinx_rtd_theme/__init__.py
  _build/_themes/sphinx_rtd_theme/breadcrumbs.html
  _build/_themes/sphinx_rtd_theme/footer.html
  _build/_themes/sphinx_rtd_theme/layout.html
  _build/_themes/sphinx_rtd_theme/search.html
  _build/_themes/sphinx_rtd_theme/searchbox.html
  _build/_themes/sphinx_rtd_theme/static/css/badge_only.css
  _build/_themes/sphinx_rtd_theme/static/css/theme.css
  _build/_themes/sphinx_rtd_theme/static/fonts/FontAwesome.otf
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.eot
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.ttf
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff
  _build/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff2
  _build/_themes/sphinx_rtd_theme/static/js/modernizr.min.js
  _build/_themes/sphinx_rtd_theme/static/js/theme.js
  _build/_themes/sphinx_rtd_theme/theme.conf
  _build/_themes/sphinx_rtd_theme/versions.html
  _build/conf.py
  best_practices/creating-the-project.rst
  components/asset.rst
  components/lock.rst
  controller.rst
  frontend/encore/vuejs.rst
  reference/configuration/debug.rst
  reference/configuration/framework.rst
  reference/configuration/swiftmailer.rst
  reference/configuration/twig.rst
  reference/configuration/web_profiler.rst
  reference/forms/twig_reference.rst
  security/remember_me.rst
  service_container.rst
  setup.rst
Labels: Status: Reviewed

#13918 Fix Typo
  doctrine/associations.rst
Labels: Doctrine, Status: Reviewed

#13917 Update serializer.rst
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13854 add ProblemNormalizer
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13814 How to use dev-server with serf-signed domain.
  frontend/encore/dev-server.rst
Labels: Status: Reviewed, front-end

#13620 Update service_container.rst
  service_container.rst
Labels: Status: Needs Review

#13451 Simplifying the code block
  form/form_collections.rst
Labels: Form, Status: Reviewed

#13472 Adding version option
  setup.rst
Labels: Status: Reviewed

#13916 Move HTTP client docs from components to guides
  _build/redirection_map
  components/browser_kit.rst
  http_client.rst
  index.rst
Labels: HttpClient, Status: Reviewed

#13922 Test redirecting to a specific section from redirection_map
  _build/redirection_map
Labels: Status: Needs Review
