Repository symfony/symfony-docs, pull requests merged in 2020-12, with the labels that each got.

#14638 [Security] Minor typo
  security/experimental_authenticators.rst
Labels: Security, Status: Needs Review

#14639 Update http_cache.rst
  http_cache.rst
Labels: Status: Needs Review

#14642 [Console] Update questionhelper.rst
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Reviewed

#14646 Add Titouan in the core team
  contributing/code/core_team.rst
Labels: Status: Reviewed

#14647 [Notifier] Update information for slack on actual implementation
  notifier.rst
Labels: Notifier, Status: Reviewed

#14658 [Cache] Document cache encryption using SodiumMarshaller
  cache.rst
Labels: Cache, Status: Reviewed

#14662 [Form] Changed data mapper $forms parameter type to \Traversable
  form/data_mappers.rst
Labels: Form, Status: Reviewed

#14651 Added config reference for router.default_uri
  reference/configuration/framework.rst
  routing.rst
Labels: Status: Reviewed

#14650 [Debug] Added option to specify the event dispatcher in debug:event-dispatcher
  event_dispatcher.rst
Labels: Debug, Status: Reviewed

#14659 [EventDispatcher] Show partial matching for debug:event-dispatcher
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#14554 Update import.rst
  service_container/import.rst
Labels: Status: Reviewed

#14488 [Console] More explication for return into execute command function
  console.rst
Labels: Console, Status: Reviewed

#14648 [Console] Update lockable_trait.rst
  console/lockable_trait.rst
Labels: Console, Status: Reviewed

#14661 [DependencyInjection] Minor modification about the .meta file contents
  components/dependency_injection/compilation.rst
Labels: DependencyInjection, Status: Reviewed

#14669 [Contracts] [PHPUnitBridge] Document the "symfony/deprecation-contracts"
  components/phpunit_bridge.rst
Labels: Contracts, Status: Reviewed

#14503 [Notifier] Add documentation for telegram options
  notifier/chatters.rst
Labels: Notifier, Status: Reviewed

#14675 Improve README
  README.markdown
Labels: Status: Reviewed

#14671 Document routing inline requirements and defaults for host
  routing.rst
Labels: Status: Needs Review

#14645 [Console] Update table.rst
  components/console/helpers/table.rst
Labels: Console, Status: Needs Review

#14685 Update setup page for Symfony 5.1 - add version
  setup.rst
Labels: Status: Needs Review

#14684 Update setup page for Symfony 5.2 - drop dev
  setup.rst
Labels: Status: Reviewed

#14690 [Set-up] Change order of first sections
  setup.rst
Labels: Status: Reviewed

#14692 [RateLimiter] Fix config keys for rate limiter
  rate_limiter.rst
Labels: RateLimiter, Status: Reviewed

#14670 [Mercure] Update token generation
  mercure.rst
Labels: Mercure, Status: Reviewed

#14644 [Lock] - replace getExpiringDate by getRemainingLifetime
  components/lock.rst
Labels: Lock, Status: Needs Review

#14693 [Uid] Mention the Doctrine type hinting of UUID/ULID values
  components/uid.rst
Labels: Status: Reviewed, Uid

#14696 [Semaphore] Fix method name typo in tip
  components/semaphore.rst
Labels: Semaphore, Status: Reviewed

#14702 [PropertyAccess] fixed typos for feature enable/disable
  components/property_access.rst
Labels: PropertyAccess, Status: Reviewed

#14683 Add documentation about redis cache configuration
  components/cache/adapters/redis_adapter.rst
Labels: Status: Reviewed

#14706 Remove white space
  quick_tour/the_architecture.rst
Labels: Status: Reviewed

#14555 [Notifier] add iqsms bridge support in doc
  notifier.rst
Labels: Status: Reviewed

#14710 [Uid] Update uid.rst
  components/uid.rst
Labels: Status: Needs Review, Uid

#14709 [Form] Fixed typo
  form/without_class.rst
Labels: Form, Status: Reviewed

#14713 [Notifier] Update DSN
  notifier.rst
Labels: Notifier, Status: Needs Review

#14714 [Notifier] Update DSN
  notifier.rst
Labels: Notifier, Status: Needs Review

#14712 [Mercure] Support JWT v4
  mercure.rst
Labels: Mercure, Status: Reviewed

#14707 [Uid] Remove UuidBinary/UlidBinary usages from documentation
  components/uid.rst
Labels: Status: Reviewed, Uid

#14717 Fix incorrect quotation mark type
  setup.rst
Labels: Status: Reviewed

#14723 Remove merge conflict header
  notifier.rst
Labels: Status: Reviewed

#14722 [Uid] Correct annotation for ULID type
  components/uid.rst
Labels: Status: Needs Review, Uid

#14720 Reword the introduction about using Bootstrap and Encore
  frontend/encore/bootstrap.rst
Labels: Status: Reviewed, front-end

#14711 [DependencyInjection] Add ServiceLocatorArgument to generate array-based locators
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#14719 [Form] Mention a possible way of reusing the same form
  forms.rst
Labels: Form, Status: Reviewed

#14716 Added a short guide about contributing code translations
  best_practices.rst
  contributing/index.rst
  contributing/translations/index.rst
Labels: Status: Needs Review

#14721 [Routing] Mention that Symfony only loads YAML routes by default
  routing.rst
Labels: Routing, Status: Needs Review

#14724 [Messenger] Add missed word
  messenger/dispatch_after_current_bus.rst
Labels: Messenger, Status: Reviewed

#13727 Bootstrap 4 Form Theme : Added tip to get <input type="file"> displaying the selected file to upload
  form/bootstrap4.rst
Labels: Status: Reviewed

#13996 [Mailer] Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Reviewed

#13483 [Form] Renaming the article
  form/form_collections.rst
Labels: Form, Status: Reviewed

#14509 Add DirectoryIndex to fallback for resources
  setup/web_server_configuration.rst
Labels: Status: Needs Review

#14735 [Notifier] Remove experimental from notifier
  notifier.rst
  notifier/chatters.rst
  notifier/texters.rst
Labels: Notifier, Status: Needs Review

#14737 Minor: Remove extra space in the config example
  mailer.rst
Labels: Status: Needs Review

#14736 [String] Restore version-added
  components/string.rst
Labels: Status: Needs Review, String

#14738 Minor: Fix quotes
  components/serializer.rst
Labels: Status: Needs Review

#14749 Remove white space
  configuration/using_parameters_in_dic.rst
Labels: Status: Reviewed

#14743 [Process] add docs for ExecutableFinder
  components/process.rst
Labels: Process, Status: Reviewed

#14747 [FrameworkBundle] Config reference for Secrets
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#14730 Tweak doc around proxy manager bridge
  service_container/lazy_services.rst
Labels: Status: Reviewed

#14753 Added redirections to specific anchors for removed Templating articles
  _build/redirection_map
Labels: Status: Reviewed

#14734 [Session] Update incorrect default value for session.handler_id
  reference/configuration/framework.rst
Labels: Session, Status: Reviewed

#14742 Remove "master" References
  contributing/documentation/overview.rst
Labels: Status: Needs Review

#14740 [Console] Update lockable_trait.rst
  console/lockable_trait.rst
Labels: Console, Status: Reviewed

#14746 [RateLimiter] Adding config reference for policy and lock_factory
  rate_limiter.rst
  reference/configuration/framework.rst
Labels: RateLimiter, Status: Reviewed

#14748 [FrameworkBundle][WebLink] Config reference for the WebLink component
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed, WebLink

#14750 Update rounding mode defintion integer type
  reference/forms/types/integer.rst
Labels: Status: Needs Review

#14757 Minor fix to colon
  routing.rst
Labels: Status: Needs Review

#14758 Use max_colons rule for DOCtor-RST
  .doctor-rst.yaml
Labels: Status: Needs Review

#13964 Allow to configure trusted proxies and headers using config options
  deployment/proxies.rst
  reference/configuration/framework.rst
Labels: Status: Needs Review

#14759 [DependencyInjection] Replace link to getConfiguration method
  bundles/configuration.rst
Labels: DependencyInjection, Status: Reviewed

#14756 [Notifier] Add Firebase notifier to list
  notifier.rst
Labels: Notifier, Status: Reviewed

#14760 Shortening the text and adding link to jQuery
  form/form_collections.rst
Labels: Status: Needs Review

#14761 Shortening the text some more
  form/form_collections.rst
Labels: Status: Needs Review

#14763 [Form] Fixing function name
  form/form_collections.rst
Labels: Form, Status: Reviewed

#14762 [Form] Rewording
  form/form_collections.rst
Labels: Form, Status: Reviewed

#14765 [Form] Minor rewording
  form/form_collections.rst
Labels: Form, Status: Reviewed
