Repository symfony/symfony-docs, pull requests merged in 2020-02, with the labels that each got.

#13029 Fix versions in Upgrading Major Version
  setup/upgrade_major.rst
Labels: Status: Reviewed

#13032 fix: very_verbose mode shows estimated time
  components/console/helpers/progressbar.rst
Labels: Console, Status: Reviewed

#13049 [Security] Document the remember_me.service option
  security/remember_me.rst
Labels: Security, Status: Reviewed

#13022 [Mailer] add tag and metadata docs
  mailer.rst
Labels: Mailer, Status: Reviewed

#13027 Fix example with iterable
  components/console/helpers/progressbar.rst
Labels: Console, Status: Reviewed

#13042 [Lock] Default path for FlockStore
  components/lock.rst
Labels: Lock, Status: Reviewed

#12420 [EventDispatcher] Document event name aliases
  components/event_dispatcher.rst
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#13065 There are 5 events listed and not 4
  components/security/authentication.rst
Labels: Security, Status: Reviewed

#13066 [Intl] Improve note about ext-intl.
  components/intl.rst
Labels: Intl, Status: Reviewed

#13051 [Testing] Use a better example for Symfony asserts
  testing/functional_tests_assertions.rst
Labels: Status: Reviewed, Testing

#13063 Added reasoning to autowiring in public bundles
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#13048 [FrameworkBundle][Routing] Removed context in template route config example
  templates.rst
Labels: FrameworkBundle, Routing, Status: Reviewed

#13087 Update link for (No|Admin)Recipient
  notifier.rst
Labels: Status: Needs Review

#13088 Finish #12722 "Update micro_kernel_trait.rst"
  configuration/micro_kernel_trait.rst
Labels: Status: Needs Review

#13082 Typo
  notifier.rst
Labels: Status: Reviewed

#12804 Update testing.rst
  testing.rst
Labels: Status: Reviewed

#12857 [Validator] added alpha3 option to country constraint
  reference/constraints/Country.rst
Labels: Status: Reviewed, Validator

#13000 Update broken links
  configuration/front_controllers_and_kernel.rst
Labels: Status: Reviewed

#13083 [Security] Remove mention of removed firewall ListenerInterface
  components/security/authentication.rst
  components/security/firewall.rst
Labels: Security, Status: Reviewed

#13081 [Constraints][Choice] Added choices to message parameters
  reference/constraints/Choice.rst
Labels: Status: Reviewed, Validator

#13018 Fix dead anchor links
  security/password_migration.rst
Labels: Status: Needs Review

#13102 [Notifier] Added the Mattermost and RocketChat integrations
  notifier.rst
Labels: Notifier, Status: Reviewed

#13109 Update email.rst
  email.rst
Labels: Mailer, Status: Reviewed

#13114 Add missing TOKEN to DSN‘s
  notifier.rst
Labels: Notifier, Status: Reviewed

#13119 [String] Documented the s() function
  components/string.rst
Labels: Status: Reviewed, String

#13121 [String] Fix s() namespace
  components/string.rst
Labels: Status: Reviewed

#13122 [String] Fix quotes
  components/string.rst
Labels: Status: Needs Review, String

#13125 Fix some typos
  components/lock.rst
  controller/upload_file.rst
Labels: Status: Reviewed

#13123 [Mailer] Round Robin now selects the first transport randomly
  components/mailer.rst
Labels: Mailer, Status: Reviewed

#13118 [Notifier] Added OvhCloud integration
  notifier.rst
Labels: Notifier, Status: Reviewed

#13132 Fix some paths
  routing.rst
Labels: Routing, Status: Reviewed

#13129 Update http_foundation.rst
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#13128 Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Reviewed

#13130 Update twig.rst
  reference/configuration/twig.rst
Labels: Status: Reviewed, Twig

#12442 Documented "Handling decorations on non existent service"
  service_container/service_decoration.rst
Labels: DependencyInjection, Status: Reviewed

#13136 [HttpClient] better explain how to deal with exceptions
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#12985 Update service_container.rst
  frontend/custom_version_strategy.rst
  profiler/data_collector.rst
  reference/dic_tags.rst
  security/custom_authentication_provider.rst
  serializer.rst
  service_container.rst
  service_container/alias_private.rst
  service_container/autowiring.rst
  service_container/import.rst
  service_container/parent_services.rst
  service_container/service_decoration.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#13105 [3.4] patch for dependency injection in controllers
  controller.rst
Labels: Status: Reviewed

#13131 Replace deprecated ObjectManager
  doctrine/event_listeners_subscribers.rst
  doctrine/mapping_model_classes.rst
  form/data_transformers.rst
  form/unit_testing.rst
  reference/forms/types/entity.rst
  service_container/parent_services.rst
  testing/database.rst
Labels: Doctrine, Status: Reviewed

#13147 [Security] fixed XML config
  security/custom_authentication_provider.rst
  security/entity_provider.rst
  security/force_https.rst
  security/guard_authentication.rst
  security/json_login_setup.rst
  security/ldap.rst
  security/multiple_guard_authenticators.rst
  security/multiple_user_providers.rst
  security/remember_me.rst
  security/user_checkers.rst
Labels: Security, Status: Reviewed

#13146 [Security] renamed memory provider and a tip about encoder for all user types
  security.rst
  security/multiple_user_providers.rst
Labels: Security, Status: Reviewed

#13155 [Security] use lazy anonymous
  security/form_login.rst
  security/guard_authentication.rst
  security/json_login_setup.rst
  security/multiple_guard_authenticators.rst
Labels: Security, Status: Reviewed

#13153 Fix typo
  components/http_client.rst
Labels: Status: Reviewed

#13152 Add documentation for RFC 8674 support
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#13160 Fix: remove decoration-on-invalid unneeded configuration block
  service_container/service_decoration.rst
Labels: DependencyInjection, Status: Reviewed

#13149 Adjusts description of the csrf_token extension
  reference/twig_reference.rst
Labels: Security, Status: Reviewed

#13150 Adjusts description of the `csrf_token_id` option
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#12989 [Messenger] Note about serializer
  messenger.rst
Labels: Messenger, Status: Reviewed

#13163 [Process] Documented the getStartTime() method
  components/process.rst
Labels: Process, Status: Reviewed

#13164 [Form] Mentioned the form theme for Foundation 6
  form/form_themes.rst
Labels: Form, Status: Needs Review, Twig

#13166 Update multiple_entity_managers.rst
  doctrine/multiple_entity_managers.rst
Labels: Status: Reviewed

#13156 [Form] minor fixes in ChoiceType options
  reference/forms/types/choice.rst
  reference/forms/types/options/choice_attr.rst.inc
  reference/forms/types/options/choice_label.rst.inc
  reference/forms/types/options/choice_name.rst.inc
  reference/forms/types/options/choice_value.rst.inc
  reference/forms/types/options/group_by.rst.inc
  reference/forms/types/options/preferred_choices.rst.inc
Labels: Form, Status: Reviewed

#13172 Update serializer.rst
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13178 [Validator] Added the missing PHP format in a code example
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#13177 Fix customize notification example
  notifier.rst
Labels: Status: Reviewed

#13179 Update frontend.rst
  frontend.rst
Labels: Status: Reviewed

#13104 [Templating] added the `private` parameter in the TemplateController example
  templates.rst
Labels: Status: Reviewed, Templating

#13169 Use valid version in README
  README.markdown
Labels: Status: Reviewed

#13099 Update service_subscribers_locators.rst
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#13057 [DependencyInjection] Fixed public service use case
  service_container.rst
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#13175 Use valid version in maintainer guide
  _build/maintainer_guide.rst
Labels: Status: Reviewed

#13185 Update form.rst
  components/form.rst
Labels: Status: Reviewed

#13162 Update messenger.rst
  messenger.rst
Labels: Status: Reviewed

#13154 Mention region parameter for Mailgun mailer too
  mailer.rst
Labels: Mailer, Status: Reviewed

#13151 Update mailer.rst
  mailer.rst
Labels: Status: Reviewed

#13142 Updated route annotations config path
  routing.rst
Labels: Routing, Status: Reviewed

#13143 Update routing.rst
  routing.rst
Labels: Status: Reviewed

#13089 Update http_authentication.rst
  testing/http_authentication.rst
Labels: Status: Reviewed, Testing

#12426 [OptionResolver] Document the OptionConfigurator
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#13180 Update copy-files.rst
  frontend/encore/copy-files.rst
Labels: Status: Needs Review, front-end

#12983 add note to use the constraint UserPassword
  .12983-suspended
  reference/constraints/UserPassword.rst
Labels: Status: Needs Review

#12982 Updated default validation mapping directory
  reference/configuration/framework.rst
Labels: Status: Reviewed, Validator

#13190 Update form.rst
  components/form.rst
Labels: Form, Status: Reviewed

#13181 Update versioning.rst
  frontend/encore/versioning.rst
Labels: Status: Needs Review, front-end

#13188 [Security] clarified the encoding with memory providers
  security.rst
Labels: Security, Status: Reviewed

#13186 Fix wording
  components/phpunit_bridge.rst
Labels: Status: Reviewed

#13193 Update templates.rst
  templates.rst
Labels: Status: Reviewed

#13196 Fixed wording of "#13188"
  security.rst
Labels: Status: Reviewed

#13192 Move caution plus reword
  security/user_provider.rst
Labels: Security, Status: Reviewed

#13167 [Validator] Documented the Hostname constraint
  reference/constraints.rst
  reference/constraints/Hostname.rst
  reference/constraints/map.rst.inc
Labels: Status: Needs Review, Validator

#13124 [Translation] Document the enabled_locales option
  performance.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed, Translator

#13195 [Validator] Allow to define a reusable set of constraints
  reference/constraints.rst
  reference/constraints/Compound.rst
  reference/constraints/map.rst.inc
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#13187 Update filesystem.rst
  components/filesystem.rst
Labels: Status: Reviewed

#13204 precised output for absolute_url
  reference/twig_reference.rst
Labels: Status: Reviewed

#13200 Update asset.rst
  components/asset.rst
Labels: Asset, Status: Reviewed

#13201 Update templates.rst
  templates.rst
Labels: Status: Reviewed, Templating

#13197 Maybe the login path should be excluded
  security/form_login_setup.rst
Labels: Security, Status: Reviewed

#13212 [Notifier] Add Installation headline
  notifier.rst
Labels: Notifier, Status: Reviewed

#13207 Correct outdated/incorrect comment in code snippet
  routing.rst
Labels: Routing, Status: Reviewed

#13199 remove link to the already deleted propel1 bridge
  form/type_guesser.rst
Labels: Status: Reviewed

#13215 [Notifier] Document sinch transport dsn
  notifier.rst
Labels: Notifier, Status: Reviewed

#13213 [Notifier] Add section Disabling Delivery
  notifier.rst
Labels: Notifier, Status: Reviewed

#13214 Adds exception template variable available in custom error pages
  components/error_handler.rst
  controller/error_pages.rst
Labels: ErrorHandler, Status: Reviewed

#13210 Add XML schema location for container configuration
  routing.rst
Labels: Routing, Status: Reviewed

#13216 Fixed CSRF check in controller
  controller/csrf_token_validation.rst
Labels: Status: Reviewed

#13198 Update deployment.rst
  deployment.rst
Labels: Status: Reviewed

#13139 Update installation.rst
  frontend/encore/installation.rst
Labels: Status: Reviewed, front-end

#13219 Misc. wording/grammar changes
  configuration.rst
Labels: Config, Status: Reviewed

#13194 Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Needs Review

#12931 [Messenger] Add an example for messenger:failed:remove with several ids
  messenger.rst
Labels: Messenger, Status: Reviewed

#13218 [String] Documented the new argument of truncate()
  components/string.rst
Labels: Status: Reviewed, String

#13226 [Workflow] Document the optional message of setBlocked()
  workflow.rst
Labels: Status: Reviewed, Workflow

#13228 Fix broken example
  workflow.rst
Labels: Security, Status: Reviewed

#13221 Fixed the Table of Contents of the performance article
  performance.rst
Labels: Status: Reviewed

#13225 [Mailer] Document the usage of default_socket_timeout in SMTP
  components/mailer.rst
Labels: Mailer, Status: Reviewed

#13113 [Routing] add priority option to annotated routes
  routing.rst
Labels: Routing, Status: Reviewed

#13224 [HttpFoundation] Document the Cookie::with*() methods
  components/http_foundation.rst
Labels: HttpFoundation, Status: Needs Review

#13209 speedup sphinx build with caching pip
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#13206 [Validator] Add a constraint to sequentially validate a set of constraints
  reference/constraints.rst
  reference/constraints/Sequentially.rst
  reference/constraints/map.rst.inc
  validation/sequence_provider.rst
Labels: Status: Reviewed, Validator

#13222 Remove the mention of TwigBundle\ExceptionController and extending doc
  controller/error_pages.rst
Labels: ErrorHandler, Status: Reviewed, Templating

#13217 Minor fixes in configuration blocks
  bundles/configuration.rst
  bundles/prepend_extension.rst
  cache.rst
  configuration.rst
  configuration/environments.rst
  configuration/external_parameters.rst
  configuration/using_parameters_in_dic.rst
  console/commands_as_services.rst
  console/input.rst
  controller.rst
  controller/argument_value_resolver.rst
  doctrine.rst
  email.rst
  event_dispatcher.rst
  logging.rst
  routing.rst
  service_container.rst
  translation.rst
  workflow.rst
Labels: Status: Reviewed

#13240 [Validator] Fix lists in Sequentially doc
  reference/constraints/Sequentially.rst
Labels: Status: Reviewed, Validator

#13234 [MercureBundle] Use PublisherInterface
  mercure.rst
Labels: Mercure, Status: Reviewed

#13232 Remove colon
  components/http_foundation.rst
Labels: Status: Reviewed

#13233 Misc wording/grammar improvements
  cache.rst
Labels: Status: Reviewed

#13242 Update deployment.rst
  deployment.rst
Labels: Status: Reviewed

#13244 [Validator] Fix title in sequence_provider.rst
  validation/sequence_provider.rst
Labels: Status: Reviewed, Validator

#13248 Update return statement for getUser
  security/guard_authentication.rst
Labels: Security, Status: Reviewed

#13231 [Workflow] Add workflow documentation link to more detailed doc
  components/workflow.rst
Labels: Status: Reviewed, Workflow

#13250 cache doctor rst
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#13274 Fixed verb "send" in past tense: "sent"
  notifier.rst
Labels: Notifier, Status: Reviewed

#13256 Update workflow.rst
  workflow.rst
Labels: Status: Reviewed, Workflow

#13276 add missing "secrets" key
  configuration/secrets.rst
Labels: Config, Status: Reviewed

#11487 [Security] Documented new IS_IMPERSONATOR, IS_ANONYMOUS and IS_REMEMBERED attributes
  components/security/authorization.rst
  security.rst
  security/impersonating_user.rst
  security/remember_me.rst
Labels: Security, Status: Needs Review

#13241 Try parallel Sphinx builds and hide progress
  .github/workflows/ci.yaml
  _build/.requirements.txt
  _build/_themes/_exts/symfonycom/sphinx/__init__.py
  _build/conf.py
Labels: Status: Needs Review

#13277 add XML and PHP config examples
  messenger.rst
Labels: Status: Reviewed

#13278 fix XML options config example
  messenger.rst
Labels: Messenger, Status: Reviewed
