Repository symfony/symfony-docs, pull requests merged in 2020-11, with the labels that each got.

#14502 [Performance] Mention Symfony Stopwatch in some doc sections
  performance.rst
Labels: Performance, Status: Needs Review

#14510 some minor tweaks
  setup/symfony_server.rst
Labels: Status: Reviewed

#14511 Updating the Installer Related Instructions
  setup.rst
Labels: Status: Reviewed

#14512 Minor: Use Twig code block
  routing.rst
Labels: Routing, Status: Reviewed

#14506 Update routing.rst
  routing.rst
Labels: Routing, Status: Reviewed

#14485 [Notifier][Discord] Use correct use statements
  notifier/chatters.rst
Labels: Notifier, Status: Reviewed

#14513 Add priority order explanation for tagged services
  service_container/tags.rst
Labels: DependencyInjection, Status: Needs Review

#14517 Add documentation about GetQueueUrl and DSN format in SQS transport
  messenger.rst
Labels: Messenger, Status: Needs Review

#14340 [Collection forms] Make javascript generic
  form/form_collections.rst
Labels: Status: Needs Review

#13137 [PropertyAccess] Non-standard adder/remover methods
  components/property_access.rst
Labels: PropertyAccess, Status: Reviewed

#13619 Add wither behavior with PHP8 static return type
  service_container/calls.rst
Labels: Status: Needs Review

#13665 Add array example on ChoiceType choice_attr option
  reference/forms/types/options/choice_attr.rst.inc
Labels: Form, Status: Needs Review

#13269 addressed issue #11786
  components/serializer.rst
Labels: Status: Needs Review

#14521 [Serializer] Merge encoder sections and show options in a table
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#14523 Correct case of suffix in example rate limiter
  rate_limiter.rst
Labels: Status: Reviewed

#14527 Update simple-example.rst
  frontend/encore/simple-example.rst
Labels: Status: Needs Review

#14520 [Encore] Fix CSS path
  frontend/encore/installation.rst
  frontend/encore/simple-example.rst
Labels: Encore, Status: Needs Review

#14528 [Routing] Remove simple quotes in config/routes/annotations.yaml
  routing.rst
Labels: Routing, Status: Reviewed

#14526 [Mailer] Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Needs Review

#14531 Throw Exception if twig variable is not found
  templates.rst
Labels: Status: Needs Review, Templating

#14535 [Messenger] Fix a typo on Messenger handler results example
  messenger/handler_results.rst
Labels: Messenger, Status: Reviewed

#14536 Enhancement: Add new rule "string_replacement"
  .doctor-rst.yaml
Labels: Status: Needs Review

#14539 [Validator] Remove extra space in the message
  reference/constraints/Isbn.rst
Labels: Status: Reviewed, Validator

#14542 [Validator] Remove empty line from annotation
  reference/constraints/DivisibleBy.rst
Labels: Status: Reviewed, Validator

#14546 Fix user entity import
  security/user_checkers.rst
Labels: Status: Reviewed

#14549 [Security] Use AppBundle instead of Acme\UserBundle
  security/named_encoders.rst
Labels: Status: Reviewed

#14548 Update README.markdown
  README.markdown
Labels: Status: Reviewed

#14537 [Lock] Fix broken configuration block
  lock.rst
Labels: Lock, Status: Reviewed

#14543 [Validator] Fix ExpressionLanguageSyntax example
  reference/constraints/ExpressionLanguageSyntax.rst
Labels: Status: Reviewed, Validator

#14553 [EventDispatcher] [Event Dispatcher] Fix typo for __invoke()
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#14551 [Security] Documented the NullToken usage
  security/experimental_authenticators.rst
Labels: Security, Status: Reviewed

#14552 [Security] Documented passport attributes
  security/experimental_authenticators.rst
Labels: Security, Status: Reviewed

#14559 Fix option double dashes
  console/input.rst
Labels: Status: Reviewed

#14557 [Validator] Fix namespace of UserPassword and UserPasswordValidator
  reference/constraints/UserPassword.rst
Labels: Status: Reviewed, Validator

#14564 [Security] Add forgotten use
  security/access_denied_handler.rst
Labels: Security, Status: Reviewed

#14561 [DependencyInjection] Removed 3.3 DI changes article
  _build/redirection_map
  service_container/3.3-di-changes.rst
  setup/flex.rst
Labels: DependencyInjection, Status: Reviewed

#14518 Remove deprecated HEADER_X_FORWARDED_ALL header
  deployment/proxies.rst
  migration.rst
Labels: Status: Reviewed

#14578 Enhancement: New rule for DOCtor-RST
  .doctor-rst.yaml
Labels: Status: Needs Review

#14579 Enhancement: Use actions/cache v2
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#14581 Enhancement: New rule for DOCtor-RST
  .doctor-rst.yaml
Labels: Status: Needs Review

#14582 Fix: DOCtor-RST build
  http_client.rst
Labels: Status: Needs Review

#14574 [Twig] Fix strict_variables default value since Symfony 5
  reference/configuration/twig.rst
Labels: Status: Reviewed, Twig

#14566 Document named arguments BC policy
  contributing/code/bc.rst
Labels: Status: Reviewed

#14577 [Form] Documented legacy_error_messages
  forms.rst
  reference/forms/types/birthday.rst
  reference/forms/types/checkbox.rst
  reference/forms/types/choice.rst
  reference/forms/types/collection.rst
  reference/forms/types/color.rst
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/date.rst
  reference/forms/types/dateinterval.rst
  reference/forms/types/datetime.rst
  reference/forms/types/email.rst
  reference/forms/types/file.rst
  reference/forms/types/form.rst
  reference/forms/types/hidden.rst
  reference/forms/types/integer.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
  reference/forms/types/money.rst
  reference/forms/types/number.rst
  reference/forms/types/password.rst
  reference/forms/types/percent.rst
  reference/forms/types/radio.rst
  reference/forms/types/range.rst
  reference/forms/types/repeated.rst
  reference/forms/types/search.rst
  reference/forms/types/tel.rst
  reference/forms/types/time.rst
  reference/forms/types/timezone.rst
  reference/forms/types/url.rst
  reference/forms/types/week.rst
Labels: Form, Status: Reviewed

#14576 [Translator] Replace old ICU Formatting Messages url
  translation.rst
  translation/message_format.rst
Labels: Status: Reviewed, Translator

#14568 [Doctrine] Update testing.rst
  testing.rst
Labels: Doctrine, Status: Reviewed

#14569 Update doctrine.rst
  reference/configuration/doctrine.rst
Labels: Status: Reviewed

#14570 Update dbal.rst
  doctrine/dbal.rst
Labels: Status: Needs Review

#14572 [Doctrine] Update doctrine.rst
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#14567 [Messenger] Add little tip about PHPdoc description in debug:messenger
  messenger/multiple_buses.rst
Labels: Messenger, Status: Reviewed

#14560 Prepare for 3.4 end of maintenaince
  README.markdown
  components/cache/adapters/filesystem_adapter.rst
  components/cache/adapters/pdo_doctrine_dbal_adapter.rst
  components/cache/adapters/php_files_adapter.rst
  components/cache/cache_invalidation.rst
  contributing/code/pull_requests.rst
  contributing/community/releases.rst
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#14525 [DependencyInjection][Doctrine][Form] Add type declarations to Form, DI and Doctrine articles
  doctrine.rst
  doctrine/associations.rst
  doctrine/dbal.rst
  doctrine/events.rst
  doctrine/multiple_entity_managers.rst
  doctrine/resolve_target_entity.rst
  form/create_custom_field_type.rst
  form/create_form_type_extension.rst
  form/data_based_validation.rst
  form/data_mappers.rst
  form/data_transformers.rst
  form/direct_submit.rst
  form/disabling_validation.rst
  form/dynamic_form_modification.rst
  form/embedded.rst
  form/events.rst
  form/form_collections.rst
  form/form_themes.rst
  form/inherit_data_option.rst
  form/type_guesser.rst
  form/use_empty_data.rst
  form/validation_group_service_resolver.rst
  form/validation_groups.rst
  form/without_class.rst
  forms.rst
  service_container.rst
  service_container/autowiring.rst
  service_container/calls.rst
  service_container/compiler_passes.rst
  service_container/configurators.rst
  service_container/factories.rst
  service_container/injection_types.rst
  service_container/optional_dependencies.rst
  service_container/parent_services.rst
  service_container/service_subscribers_locators.rst
  service_container/synthetic_services.rst
  service_container/tags.rst
Labels: DependencyInjection, Doctrine, Form, Status: Reviewed

#14565 [Mailer] Complete mailer documentation
  mailer.rst
  reference/configuration/framework.rst
Labels: Mailer, Status: Needs Review

#14083 Complete documentation about mailer integration
  mailer.rst
  reference/configuration/framework.rst
Labels: Status: Needs Review

#14589 [Form] Fixed the layout in the forms page
  forms.rst
Labels: Form, Status: Needs Review

#14550 Section method only in ConsoleOutputInterface
  console.rst
Labels: Status: Needs Review, Waiting feedback

#14593 [Security] add example code which Maker Bundle generated
  security.rst
Labels: Security, Status: Needs Review

#13239 Bus restricting with Interfaces
  messenger/multiple_buses.rst
  service_container/tags.rst
Labels: Status: Needs Review

#13094 GitHub Actions: use docker image for CI build
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#14595 Streamline workflow
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#14588 [Form] Added explicit `getParent()` call in types inheritance mechanism
  form/create_custom_field_type.rst
Labels: Form, Status: Reviewed

#14610 Fix package name for OvhCloud notifier
  notifier.rst
Labels: Status: Reviewed

#14602 Fix wrong key name in FormType options
  reference/forms/types/options/choice_attr.rst.inc
Labels: Status: Reviewed

#14605 [EventDispatcher] small improvement
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#14612 Enhancement: Add /me to the CODEOWNERS file for GithubActions workflows
  .github/CODEOWNERS
Labels: Status: Needs Review

#14613 [Doctrine] Add precision for doctrine lifecycle callbacks
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#14611 [Console] A method call is reversed
  components/console/helpers/progressbar.rst
Labels: Console, Status: Reviewed

#14601 [EventDispatcher] Update event_dispatcher.rst
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#14599 [Notifier] Add better example for Slack DSN
  notifier.rst
Labels: Notifier, Status: Reviewed

#14617 [Messenger] Update messenger.rst (AWS SQS)
  messenger.rst
Labels: Messenger, Status: Reviewed

#14614 [DependencyInjection] Delete duplicated words
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#14620 [Validator] Fixing uppercase typo
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#14627 [Doctrine] Update database.rst
  testing/database.rst
Labels: Doctrine, Status: Reviewed

#14629 [DependencyInjection] Fix code example
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#14630 [Console] Added Invalid Constant
  console.rst
Labels: Console, Status: Reviewed

#14587 Add a note about exposing env vars for unrecognized Docker services
  setup/symfony_server.rst
Labels: Status: Reviewed

#14621 [Validator] Removing the recommended `Constraints` subdirectory
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#14632 [Console] Update index.rst
  components/console/helpers/index.rst
Labels: Console, Status: Reviewed

#14618 Update performance.rst
  performance.rst
Labels: Status: Reviewed
