Repository symfony/symfony-docs, pull requests merged in 2020-05, with the labels that each got.

#13607 add use statement for the needed extension class
  bundles/extension.rst
Labels: Status: Reviewed

#13628 Add missing traverse option in index
  reference/constraints/Traverse.rst
Labels: Status: Reviewed

#13644 Correct defintion of Range validation messages
  reference/constraints/Range.rst
Labels: Status: Reviewed, Validator

#13649 Fix wrong Symfony listeners range
  event_dispatcher.rst
Labels: Status: Reviewed

#13651 The Doctrine Messenger table can now be generated with a migration diff
  messenger.rst
Labels: Status: Reviewed

#13621 Add reapply proxy settings on chrome tooltip
  setup/symfony_server.rst
Labels: Status: Reviewed

#13643 [String] Set characters to use in ByteString::fromRandom()
  components/string.rst
Labels: Status: Needs Review, String

#13645 [Console] Remove invalid argument
  console/calling_commands.rst
Labels: Console, Status: Reviewed

#13629 Change "In Symfony 4" to "Since Symfony 4"
  setup/file_permissions.rst
Labels: Status: Reviewed

#13610 Update upgrade_major.rst
  setup/upgrade_major.rst
Labels: Status: Reviewed

#13654 Deprecated the NumberToLocalizedStringTransformer constants
  reference/forms/types/options/rounding_mode.rst.inc
Labels: Form, Status: Reviewed

#13659 [Yaml] Added support for YAML 1.2 octal notation
  components/yaml/yaml_format.rst
Labels: Status: Reviewed, Yaml

#13660 [Workflow] Minor tweak in some method names
  workflow.rst
Labels: Status: Needs Review, Workflow

#13664 [WCM] Adding info about Vue build
  frontend/encore/vuejs.rst
Labels: Status: Needs Review, Waiting Code Merge

#13657 Documented the default_uri routing option
  routing.rst
Labels: Routing, Status: Needs Review

#13339 Documented the --deprecations option of the debug:container component
  components/phpunit_bridge.rst
Labels: Status: Needs Review

#13668 [Validator] clarify empty string behavior without lower bound given
  reference/constraints/Length.rst
Labels: Status: Needs Review, Validator

#13671 Fix typo
  messenger.rst
Labels: Messenger, Status: Reviewed

#13672 [Validator] Better documentation on the Bic constrain
  reference/constraints/Bic.rst
Labels: Status: Needs Review, Validator

#13670 [String] Deprecated the Inflector docs
  components/inflector.rst
  components/string.rst
Labels: Inflector, Status: Reviewed, String

#13675 Remove unnecessary historic configuration: 'sudo: false'
  bundles/best_practices.rst
Labels: Status: Reviewed

#13666 Custom User Checker, AuthenticationException is allowed
  security/user_checkers.rst
Labels: Security, Status: Reviewed

#13655 Update secrets.rst
  configuration/secrets.rst
Labels: DependencyInjection, Security, Status: Reviewed

#13650 Update bootstrap4.rst
  form/bootstrap4.rst
Labels: Form, Status: Reviewed

#13516 Document that cache warmers now must return an array of files to preload
  reference/dic_tags.rst
Labels: HttpKernel, Status: Reviewed

#13521 [OptionsResolver][Config][DI] Added package and version to deprecation features
  components/config/definition.rst
  components/options_resolver.rst
  service_container/alias_private.rst
Labels: Config, DependencyInjection, OptionsResolver, Status: Reviewed

#13552 [Form] Updated unit testing article
  form/unit_testing.rst
Labels: Form, Status: Reviewed

#13681 Update Encore setup docs to reflect current results of installation
  frontend/encore/simple-example.rst
Labels: Status: Needs Review

#13680 Update templates.rst
  templates.rst
Labels: Status: Reviewed, Twig

#13682 Show with an example how to add a custom port to the MAILER_DSN
  mailer.rst
Labels: Status: Needs Review

#13691 Fix yaml spec link
  components/yaml/yaml_format.rst
Labels: Status: Reviewed

#13689 Resolve the DATABASE_URL env var in config examples
  configuration.rst
  doctrine/multiple_entity_managers.rst
  reference/configuration/framework.rst
Labels: DependencyInjection, Doctrine, Status: Reviewed

#13676 [DI] Renamed some PHP-DSL functions
  components/dependency_injection.rst
  security/custom_authentication_provider.rst
  service_container.rst
  service_container/alias_private.rst
  service_container/autowiring.rst
  service_container/calls.rst
  service_container/configurators.rst
  service_container/factories.rst
  service_container/injection_types.rst
  service_container/optional_dependencies.rst
  service_container/parent_services.rst
  service_container/service_decoration.rst
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Needs Review, deprecation

#13690 DataCollector `collect` needs a `Throwable`
  profiler/data_collector.rst
Labels: Status: Reviewed

#13687 Link to the NGINX Unit article for Symfony apps
  setup/web_server_configuration.rst
Labels: Status: Needs Review

#13688 [ExpressionLanguage] Added a security caution about passing untrusted data
  components/expression_language.rst
Labels: ExpressionLanguage, Status: Needs Review

#13696 Fix subtype in TextPart constructor calls
  components/mime.rst
Labels: Mime, Status: Reviewed

#13694 Update security.rst
  security.rst
Labels: Security, Status: Reviewed

#13695 [Validator] deprecate the allowEmptyString option
  reference/constraints/Length.rst
Labels: Status: Reviewed, Validator

#13708 Added return value to make the example work as is
  console/commands_as_services.rst
Labels: Console, Status: Reviewed

#13712 [Mercure] Compatibility with v0.10
  mercure.rst
Labels: Mercure, Status: Reviewed

#12325 Reworded the docs about storing sessions in database
  _build/redirection_map
  doctrine.rst
  doctrine/mongodb_session_storage.rst
  doctrine/pdo_session_storage.rst
  reference/configuration/framework.rst
  session.rst
  session/database.rst
Labels: Session, Status: Needs Review

#13714 Nginx dev config
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#13729 fix a minor typo
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#13730 Fix typo of HTML5 field type for DateTimeType
  reference/forms/types/options/html5.rst.inc
Labels: Form, Status: Reviewed

#13713 [Messenger] Added Amazon SQS transport
  messenger.rst
Labels: Messenger, Status: Needs Review

#13715 [String] Allow to define additional slugger substitutions
  components/string.rst
Labels: Status: Needs Review, String

#13718 [Cache] Added max items and max lifetime options to Array cache
  components/cache/adapters/array_cache_adapter.rst
Labels: Cache, Status: Needs Review

#13731 fix method name
  service_container/alias_private.rst
Labels: DependencyInjection, Status: Reviewed

#13719 [PropertyInfo] Mentioned support for PHP typed properties
  components/property_info.rst
Labels: PropertyInfo, Status: Needs Review

#13720 [Validation] Added a note about validation group names
  form/validation_groups.rst
Labels: Status: Needs Review, Validator

#13725 Update vuejs.rst
  frontend/encore/vuejs.rst
Labels: Status: Needs Review

#13724 Add link to SymfonyCasts React.js tutorial
  frontend/encore/reactjs.rst
Labels: Status: Needs Review

#13723 Update reactjs.rst
  frontend/encore/reactjs.rst
Labels: Status: Needs Review

#13717 [Mailer] Document how to set headers
  mailer.rst
Labels: Mailer, Status: Needs Review

#13733 minor fix
  mercure.rst
Labels: Status: Reviewed
