Repository symfony/symfony-docs, pull requests merged in 2020-04, with the labels that each got.

#13462 No longer list the Symfony binary as a requirement
  setup.rst
Labels: Status: Reviewed

#13460 Rephrasing the "If you render your whole" note (2nd attempt)
  form/form_collections.rst
Labels: Status: Reviewed

#13458 [Forms] Add empty_data to the form HiddenType
  reference/forms/types/hidden.rst
Labels: Form, Status: Reviewed

#13473 Tag name updated
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#13476 Missing closing tag for endblock.
  templates.rst
Labels: Status: Reviewed, Templating

#13478 Fixes wrong tag for RouteLoaderInterface registration without autoconfiguration
  routing/custom_route_loader.rst
Labels: Routing, Status: Reviewed

#13475 [Setup] Clarify the Symfony binary and show small PHP built-in command
  setup.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#13468 Adds block about PHP-FPM behaviour
  setup/symfony_server.rst
Labels: Status: Reviewed

#12647 Add tip about accessing removed services in the testing doc
  testing.rst
Labels: Status: Reviewed, Testing

#12541 Add section about Workflows and State Machine validation
  workflow/workflow-and-state-machine.rst
Labels: Status: Reviewed, Workflow

#12951 Update Console Input Optional Options
  console/input.rst
Labels: Console, Status: Reviewed

#13480 [Forms] fix displaying `empty_data` option for hidden field
  reference/forms/types/hidden.rst
Labels: Form, Status: Reviewed

#13477 [FrameworkBundle] Deprecate flashbag and attributebag services
  session.rst
Labels: FrameworkBundle, HttpFoundation, Status: Needs Review

#13439 Shortening Doctrine Note
  form/form_collections.rst
Labels: Status: Needs Review

#13445 Shortening the "Prototype" paragraph
  form/form_collections.rst
Labels: Status: Needs Review

#13431 Removed Routing component docs
  _build/redirection_map
  components/config/resources.rst
  components/http_kernel.rst
  components/routing.rst
  create_framework/routing.rst
  introduction/from_flat_php_to_symfony.rst
Labels: Routing, Status: Reviewed

#13498 Adding bulma theme
  form/form_themes.rst
Labels: Form, Status: Reviewed

#13487 [HttpClient] Document AMPHP HttpClient integration for HTTP/2
  components/http_client.rst
Labels: HttpClient, Status: Reviewed

#13499 Update serializer.rst
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#13495 Moving mailer transport section
  mailer.rst
Labels: Mailer, Status: Reviewed

#13486 No longer recommend injecting the service container
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#13485 Update associations.rst
  doctrine/associations.rst
Labels: Doctrine, Status: Reviewed

#13500 [HttpFoundation] Document all core response http control directives
  components/http_foundation.rst
  create_framework/http_kernel_httpkernelinterface.rst
  http_cache.rst
Labels: HttpFoundation, Status: Reviewed

#13505 [String] Document the bytesAt() method
  components/string.rst
Labels: Status: Reviewed, String

#13502 Update the metadata_update_threshold description
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#13511 [Testing] Change deprecated assertContains to assertStringContainsString
  console.rst
  create_framework/unit_testing.rst
  testing.rst
Labels: Status: Reviewed

#13512 Avoid Supervisord to go in fatal error
  messenger.rst
Labels: Status: Reviewed

#13514 [Testing] Fixed the description of assertSelectorTextContains()
  testing.rst
Labels: Status: Reviewed, Testing

#13504 [Contributing] Fix `trigger_error()` position in deprecated class
  contributing/code/conventions.rst
Labels: Status: Reviewed

#13509 [EventDispatcher] Fix position of `AddEventAliasesPass`
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#13501 Mention that DoctrineCacheBundle is deprecated
  reference/configuration/doctrine.rst
Labels: Doctrine, Status: Reviewed

#11735 #27345 Added Symfony\Component\Lock\Store\MongoDbStore
  components/lock.rst
Labels: Lock, Status: Reviewed

#13171 [Security] Explain lazy anonymous mode
  http_cache.rst
  security.rst
  security/form_login.rst
Labels: Security, Status: Needs Review

#13534 Update Slack DSN
  notifier.rst
Labels: Status: Needs Review

#13491 [Validator] Fixed `Traverse` constraint reference
  reference/constraints/Traverse.rst
  reference/constraints/Valid.rst
Labels: Status: Reviewed, Validator, bug

#13535 Fixed yaml extension after conflicts
  reference/constraints/Traverse.rst
Labels: Status: Reviewed

#13223 [Form] added the "choice_filter" option
  reference/forms/types/choice.rst
  reference/forms/types/options/choice_filter.rst.inc
Labels: Form, Status: Reviewed

#13536 Updated CODEOWNERS
  .github/CODEOWNERS
Labels: Status: Needs Review

#13537 typo date
  contributing/code/license.rst
Labels: Status: Reviewed

#13538 Fix documentation for a controllers with __invoke function in php routing
  routing.rst
Labels: Status: Reviewed

#13544 [DI] Replaced inline() by service() in PHP DSL
  service_container/alias_private.rst
Labels: DependencyInjection, Status: Reviewed

#13546 [DI] Removed an unneeded note about some parent services restrictions
  service_container/parent_services.rst
Labels: DependencyInjection, Status: Reviewed

#13549 Fixed uid doc page
  components/uid.rst
Labels: Status: Reviewed, Uid

#13551 [String] fix typo
  components/string.rst
Labels: Status: Reviewed, String

#13522 [Security] Describe voters more prominently in the Security guide
  security.rst
Labels: Security, Status: Reviewed

#13553 Renaming "Securing Individual Objects"
  security.rst
Labels: Status: Reviewed

#13524 Fix test login example for 4.4 - 5.0 applications
  testing/http_authentication.rst
Labels: Security, Status: Reviewed, Testing

#13523 [Security] More radically remove Testing/HTTP Authentication contents
  testing/http_authentication.rst
Labels: Security, Status: Reviewed

#13255 [Asset] Document remote JSON manifest
  components/asset.rst
  reference/configuration/framework.rst
Labels: Asset, Status: Reviewed

#13557 fix a typo
  reference/forms/types/options/choice_filter.rst.inc
Labels: Form, Status: Reviewed

#13520 [Security] Documented new logout event
  reference/configuration/security.rst
  security.rst
Labels: Security, Status: Reviewed

#13344 Add stateless route attribute documentation
  routing.rst
Labels: Routing, Status: Reviewed

#13567 fix the versionadded directive markup
  reference/forms/types/options/extra_fields_message.rst.inc
Labels: Status: Reviewed

#13560 [Console] Return an integer with the exit status as the result
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Reviewed

#13566 [Workflow] Replace has_role by is_granted
  workflow.rst
Labels: Status: Reviewed, Workflow

#13545 [DI] Updated the way inner services are referrer to in decoration
  reference/configuration/framework.rst
  service_container/service_decoration.rst
Labels: DependencyInjection, Status: Reviewed

#13570 Update symfony_server.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#13574 fix link to DBAL Connection class
  components/cache/adapters/pdo_doctrine_dbal_adapter.rst
Labels: Cache, Status: Reviewed

#13579 Use non-deprecated options key to configure babel in encore
  frontend/encore/babel.rst
Labels: Status: Reviewed, front-end

#13578 Update symfony_server.rst - proxy env lowercase
  setup/symfony_server.rst
Labels: Status: Reviewed

#13515 [DI] Document the container preload tags
  performance.rst
  reference/dic_tags.rst
Labels: DependencyInjection, Status: Reviewed

#13580 Fix service contracts import XML example
  service_container/import.rst
Labels: DependencyInjection, Status: Reviewed

#13582 Remove old AppBundle code from XML service definition example
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#13594 Adding an if condition on a for tag is deprecated in Twig 2.10.
  form/create_custom_field_type.rst
Labels: Status: Reviewed

#13601 [Error pages] Add missing use
  controller/error_pages.rst
Labels: Status: Reviewed

#13600 [Notifier] Add FreeMobile SMS entry
  notifier.rst
Labels: Notifier, Status: Reviewed

#13602 Fix link to ServiceSubscriberInterface
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed

#13598 Fix PHP example on ExpressionLanguage Injection
  service_container/expression_language.rst
Labels: DependencyInjection, ExpressionLanguage, Status: Reviewed

#13517 Improve the docs about the Symfony server proxy
  setup/symfony_server.rst
Labels: Status: Needs Review
