Repository symfony/symfony-docs, pull requests merged in 2020-08, with the labels that each got.

#13945 Removed Mailer component docs
  _build/conf.py
  _build/redirection_map
  components/mailer.rst
  components/messenger.rst
  components/mime.rst
  mailer.rst
Labels: Mailer, Status: Reviewed

#14004 verify_peer in dsn should be 0
  components/mailer.rst
Labels: Status: Reviewed

#14021 Update performance.rst
  performance.rst
Labels: Status: Reviewed

#14017 Fix HttpClientInterface path in HttpClient documentation
  http_client.rst
Labels: Status: Reviewed

#13851 Add public typed properties autowiring
  service_container/autowiring.rst
  service_container/injection_types.rst
Labels: Status: Reviewed

#13990 [Validator] Made the code sample more explicit with accepted values
  reference/constraints/Collection.rst
Labels: Status: Reviewed, Validator

#13554 Explaining controllers as viable alternative
  security/voters.rst
Labels: Status: Reviewed

#14003 [String] Fix missing locale in slugger substitution map
  components/string.rst
Labels: Status: Needs Review, String

#13980 ADD Annotations for The Locale and the URL section
  translation/locale.rst
Labels: Status: Needs Review

#13960 Add doc for Isin constraint
  reference/constraints.rst
  reference/constraints/Isin.rst
  reference/constraints/map.rst.inc
Labels: Status: Reviewed, Validator

#14124 [Notifier] Fix wrong package name for the RocketChat service
  notifier.rst
Labels: Notifier, Status: Reviewed

#14112 Update doctrine.rst
  reference/configuration/doctrine.rst
Labels: Status: Reviewed

#14095 [Mailer] Add documentation for Mailjet mailer
  mailer.rst
Labels: Mailer, Status: Reviewed

#13432 Added an example Entity for Serializer
  serializer.rst
Labels: Status: Needs Review

#14081 Add documentation about RedisTagAwareAdapter
  components/cache/adapters/redis_adapter.rst
  components/cache/cache_invalidation.rst
Labels: Cache, Status: Needs Review

#13320 Add an explain section to update symfony recipes
  setup/_update_recipes.rst.inc
  setup/upgrade_major.rst
  setup/upgrade_minor.rst
Labels: Status: Reviewed

#14078 RedisTagAwareAdapter integration
  cache.rst
Labels: Cache, Status: Reviewed

#14115 Update pull_requests.rst
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#14055 Update routing.rst
  routing.rst
Labels: Routing, Status: Reviewed

#14136 fix link to `ChainAdapter::prune` method
  components/cache/adapters/chain_adapter.rst
Labels: Cache, Status: Needs Review

#14150 [Messenger] rename message recorder file
  _build/redirection_map
  messenger.rst
  messenger/dispatch_after_current_bus.rst
Labels: Messenger, Status: Reviewed

#14143 [PropertyAccess] Backport typed property support to 4.4
  components/property_info.rst
Labels: PropertyAccess, Status: Reviewed

#14134 Fix minor typo
  migration.rst
Labels: Status: Reviewed

#14119 [Workflow] Choose which Workflow events should be dispatched
  workflow.rst
Labels: Status: Reviewed, Workflow

#14074 [Templating] Explain the hinclude.js attributes
  templating/hinclude.rst
Labels: Status: Needs Review, Templating

#14072 [Translation] The 'other' key is mandatory in ICU 'select'
  translation/message_format.rst
Labels: Status: Needs Review, Translator

#14076 Update Symfony browserlists reccomendation to browserlists standard.
  frontend/encore/postcss.rst
Labels: Status: Needs Review, front-end

#14146 [5.0] [security] formatting
  security.rst
Labels: Security, Status: Needs Review

#14125 [PropertyAccess] Allow to disable magic __get & __set
  components/property_access.rst
  reference/configuration/framework.rst
Labels: PropertyAccess, Status: Reviewed

#14104 [Notifier] Linkedin integration
  notifier.rst
Labels: Notifier, Status: Needs Review

#14089 4.0->master: Updated link+title of Heroku's doc
  deployment/heroku.rst
Labels: Status: Needs Review

#14130 Change the way to create table in Lock PDO
  components/lock.rst
Labels: Lock, Status: Reviewed

#14084 [Console] added TableCellStyle documentation
  components/console/helpers/table.rst
Labels: Console, Status: Reviewed
