Repository symfony/symfony-docs, pull requests merged in 2021-05, with the labels that each got.

#15302 [Serializer] update example for attributes
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#15282 Recommend using root `controller` attribute in route definition
  controller/service.rst
Labels: Status: Reviewed

#15304 [Testing] Application testing in Symfony is fun! Let's document the modern features
  _build/redirection_map
  testing.rst
  testing/dom_crawler.rst
  testing/functional_tests_assertions.rst
Labels: Status: Reviewed, Testing

#15305 [Testing] Remove docs on PHPUnit configuration
  testing.rst
Labels: Status: Reviewed, Testing

#15306 [FrameworkBundle] Document env vars in framework.ide
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Needs Review

#15312 remove unused inc file
  setup/_vendor_deps.rst.inc
Labels: Status: Reviewed

#15308 Updating to PHP 7.4
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#15313 Fix link to Composer
  create_framework/introduction.rst
Labels: Status: Reviewed

#14956 [Messenger] Document DSN format for Redis Cluster
  messenger.rst
Labels: Messenger, Status: Reviewed

#15316 CI: Add new rule for DOCtor-RST
  .doctor-rst.yaml
Labels: Status: Reviewed

#15318 Fix typo s/it's/its/
  workflow.rst
Labels: Status: Reviewed

#15317 [Serializer] Fixed occurence of an old FQCN notation
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#15314 [Uid] Add note about ULIDs not being random in one case
  components/uid.rst
Labels: Status: Reviewed, Uid

#15307 [Security] Renamed encoders to password_hashers
  _build/redirection_map
  components/security/authentication.rst
  reference/configuration/security.rst
  security.rst
  security/named_hashers.rst
  security/password_migration.rst
  security/user_provider.rst
Labels: Security, Status: Needs Review

#15319 [Runtime] Composer node `extra.runtime.options` is incorrect
  components/runtime.rst
Labels: Runtime, Status: Reviewed

#15322 [Security] Fix some typos related to 5.3 security changes
  security/named_hashers.rst
  security/user_provider.rst
Labels: Security, Status: Reviewed

#15325 [OptionsResolver] Documenting new setPrototype() method
  components/options_resolver.rst
Labels: OptionsResolver, Status: Reviewed

#15331 [Security] Update experimental_authenticators.rst
  security/experimental_authenticators.rst
Labels: Security, Status: Needs Review

#15335 [HttpKernel] Minor Fix
  components/http_kernel.rst
Labels: HttpKernel, Status: Reviewed

#15349 [CI] Dont use the special respository for docs-builder
  _build/composer.json
Labels: Status: Reviewed

#15336 remove unused inc files
  _includes/service_container/_my_mailer.rst.inc
  reference/forms/types/options/scale.rst.inc
  security/_supportsToken.rst.inc
Labels: Status: Reviewed

#15341 Fixed array notation for yaml file in session/database.rst
  session/database.rst
Labels: Status: Needs Review

#15348 [RateLimiter] Fix syntax error in config
  rate_limiter.rst
Labels: RateLimiter, Status: Reviewed

#15346 [RateLimiter] [Rate Limiter] Added missing opening single quotes
  rate_limiter.rst
Labels: RateLimiter, Status: Reviewed

#15345 Update deprecated PHPUnit schema & doc links
  create_framework/unit_testing.rst
Labels: Status: Reviewed

#15328 Unifying wording to "configuration parameter"
  best_practices.rst
  routing.rst
Labels: Status: Reviewed

#15351 [Lock] Update lock.rst
  components/lock.rst
Labels: Lock, Status: Needs Review

#15246 [Workflow] Updated wording on comment
  workflow.rst
Labels: Status: Needs Review, Workflow

#15226 [Lock] Update table in lock component
  components/lock.rst
Labels: Lock, Status: Reviewed

#15350 Update NuSOAP client example
  controller/soap_web_service.rst
Labels: Status: Reviewed

#15353 [Security] Document logout.target
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#15344 Adding file-loader dependency.
  frontend/encore/copy-files.rst
  frontend/encore/postcss.rst
  frontend/encore/reactjs.rst
Labels: Status: Reviewed, front-end

#15354 Added indexes to sql commands used to create session tables
  session/database.rst
Labels: Status: Reviewed

#15310 [Translation] Introduce Translation Providers
  reference/configuration/framework.rst
  translation.rst
Labels: Status: Reviewed, Translation

#15359 [CI] Make sure composer cache is properly used
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#15362 Adding HTTP Certificates
  http_client.rst
Labels: Status: Reviewed

#15330 [HttpClient] Clarifying how to autowire scoped HTTP clients
  http_client.rst
Labels: HttpClient, Status: Needs Review

#15363 [RateLimiter] Closes #15034 adds information about the lock being nullable
  rate_limiter.rst
Labels: RateLimiter, Status: Reviewed

#15284 [CI] Don't use special repository for symfony-tools/docs-builder
  .github/workflows/ci.yaml
  _build/composer.json
Labels: Status: Reviewed

#15309 [Console] Add explicit note about the type of VALUE_NONE
  console/input.rst
Labels: Console, Status: Reviewed

#15364 [Notifier] Adds documentation for Slack stuff added in 5.3
  _images/notifier/slack/message-reply.png
  _images/notifier/slack/slack-footer.png
  _images/notifier/slack/slack-header.png
  notifier/chatters.rst
Labels: Notifier, Status: Reviewed

#15158 [Form] Bootstrap 5 documentation
  form/bootstrap5.rst
  forms.rst
Labels: Form, Status: Needs Review

#15343 [Messenger] Add a description to the AMQP exchange arguments with example
  messenger.rst
Labels: Messenger, Status: Reviewed

#15277 [Routing] Fixing some typos
  routing.rst
Labels: Routing, Status: Reviewed

#15329 [Messenger] Add a note about `messenger:stop-workers` command
  messenger.rst
Labels: Messenger, Status: Reviewed

#15365 [DependencyInjection] Update service_container.rst
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#15237 Adding label_html for asterisk
  form/bootstrap4.rst
  reference/forms/types/form.rst
Labels: Status: Needs Review

#15361 Bump Symfony PHP requirements to 8.0.2
  components/property_info.rst
  configuration/secrets.rst
  quick_tour/the_big_picture.rst
  reference/configuration/framework.rst
  reference/configuration/security.rst
  security/named_hashers.rst
  setup.rst
Labels: Status: Reviewed

#15373 Remove master wording
  contributing/code/conventions.rst
Labels: Status: Needs Review

#15372 [Session] Fix handler import
  session/database.rst
Labels: Session, Status: Reviewed

#15370 [HttpClient] HttpClientInterface::withOptions method
  http_client.rst
Labels: HttpClient, Status: Reviewed

#15369 Changed version for composer create-project
  setup.rst
Labels: Status: Reviewed

#15090 Encore: Update 'Fix "Invalid Host header" Issue'.
  frontend/encore/virtual-machine.rst
Labels: Status: Needs Review, front-end

#14917 [Testing] [PHPUnit-Bridge] Troubleshooting
  components/phpunit_bridge.rst
Labels: Status: Needs Review, Testing

#15265 [HttpClient] Adding default value for verify_peer
  reference/configuration/framework.rst
Labels: HttpClient, Status: Reviewed

#15374 [DependencyInjection] Remove a redundant table in DIC tags article
  reference/dic_tags.rst
Labels: DependencyInjection, Status: Reviewed

#15378 [Session] Update configurations
  components/http_foundation/session_configuration.rst
  session.rst
  session/database.rst
Labels: Session, Status: Reviewed

#15381 [Filesystem] fix readlink description
  components/filesystem.rst
Labels: Filesystem, Status: Reviewed

#14850 Update best_practices.rst
  bundles/best_practices.rst
Labels: Status: Reviewed

#15386 [Translation] Improve Translation Providers docs
  translation.rst
Labels: Status: Needs Review, Translation

#15387 [Process] Remove paragraph from bad merge
  components/process.rst
Labels: Process, Status: Needs Review

#15384 [Inflector][String] Removed the component
  _build/redirection_map
  components/inflector.rst
  components/property_access.rst
Labels: Inflector, Status: Needs Review, String

#15391 [Translation] Remove PoEditor Provider
  translation.rst
Labels: Translation

#15388 Minor rewording
  components/http_foundation/session_configuration.rst
Labels: Status: Needs Review

#15389 Adding FQCN
  reference/configuration/framework.rst
Labels: Status: Needs Review

#15390 [Session] Minor rewording
  session/database.rst
Labels: Session, Status: Needs Review

#15392 Fixing code sample
  performance.rst
Labels: Status: Needs Review

#15393 Adding opcache.preload_user
  performance.rst
Labels: Status: Needs Review
