Repository symfony/symfony-docs, pull requests merged in 2021-07, with the labels that each got.

#15470 Upgrade popper package to v2
  frontend/encore/bootstrap.rst
Labels: Status: Needs Review, front-end

#15471 [HttpClient] [Framework] Add missing configurations
  reference/configuration/framework.rst
Labels: HttpClient, Status: Reviewed

#15366 [Notifier] [MessageMedia] add docs
  notifier.rst
Labels: Notifier, Status: Reviewed

#15485 Fixed ambiguous sentence
  setup/upgrade_minor.rst
Labels: Status: Needs Review

#15468 Minor change at email_validation_mode
  reference/configuration/framework.rst
Labels: Status: Needs Review

#15478 Added header removal notice
  mailer.rst
Labels: Status: Reviewed

#15477 Minor clarification
  mailer.rst
Labels: Status: Reviewed

#15491 [Contribution] Document the different types of tests run in CI
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#15500 Fix example in Regex.rst
  reference/constraints/Regex.rst
Labels: Status: Reviewed

#15499 [DependencyInjection] Typo in class name
  service_container/factories.rst
Labels: DependencyInjection, Status: Needs Review

#15495 [Twig] Global variable in TwigConfig should be passed by service function
  templating/global_variables.rst
Labels: Status: Reviewed, Twig

#15508 Some minor rewords
  frontend/encore/babel.rst
  reference/configuration/framework.rst
  reference/constraints/Uuid.rst
  security.rst
Labels: Status: Reviewed

#15515 [Routing] Improve PHP attributes examples
  routing.rst
Labels: Routing, Status: Reviewed

#15514 [Routing] Add small improvements
  routing.rst
Labels: Routing, Status: Reviewed

#15496 Minor - Remove deprecated self::$container
  messenger.rst
Labels: Status: Reviewed

#15487 [Testing] use static::getContainer()
  testing.rst
Labels: Status: Reviewed, Testing

#15479 [Console] Document `CommandTester::assertCommandIsSuccessful()` usage
  console.rst
Labels: Console, Status: Reviewed

#15509 Minor language fix
  reference/configuration/framework.rst
Labels: Status: Reviewed

#15502 Fix doc of cache prefix and namespace
  cache.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed

#15510 Fix typo in choice_translation_parameters doc
  reference/forms/types/options/choice_translation_parameters.rst.inc
Labels: Status: Reviewed

#15453 [Ldap] Update ldap.rst
  components/ldap.rst
Labels: Ldap, Status: Reviewed

#15520 [FrameworkBundle] Deprecate services in Doctrine cache
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#15522 [HttpClient] Mention how to get the effective response URL
  http_client.rst
Labels: HttpClient, Status: Reviewed

#15521 [FrameworkBundle] Update the default config of Doctrine cache
  reference/configuration/framework.rst
Labels: FrameworkBundle, Status: Reviewed

#15525 Update best_practices.rst
  best_practices.rst
Labels: Status: Needs Review

#15527 [Form] Document using TranslatableMessage in form help
  reference/forms/types/options/help.rst.inc
Labels: Form, Status: Reviewed

#15529 [Security] Add deprecation notices about Guard authenticators
  security.rst
  security/auth_providers.rst
  security/custom_authentication_provider.rst
  security/guard_authentication.rst
  security/multiple_guard_authenticators.rst
Labels: Security, Status: Reviewed

#15523 [Cache] Deprecate the DoctrineProvider class
  cache.rst
  components/cache/adapters/doctrine_adapter.rst
Labels: Cache, Status: Reviewed

#15526 [Security] Deprecate always_authenticate_before_granting option
  components/security/authentication.rst
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#15460 [Mercure] integration with Symfony cli and various improvements
  mercure.rst
Labels: Mercure, Status: Reviewed

#15531 [Mercure] Invalid namespace and method name
  mercure.rst
Labels: Mercure, Status: Needs Review

#15536 [Notifier] Add bridge for smsc.ru
  notifier.rst
Labels: Notifier, Status: Needs Review, Status: Needs Work

#15528 [Uid] Document NilUlid class
  components/uid.rst
Labels: Status: Reviewed, Uid, Waiting feedback

#15519 Update Contracts to 3.0 version
  components/contracts.rst
Labels: Status: Needs Review

#15530 [Config] [Configuration] Added a note about XML and PHP formats
  configuration.rst
Labels: Config, Status: Reviewed

#15455 Add vanilla js for add a collection element
  form/form_collections.rst
Labels: Status: Needs Review

#15535 [Messenger] Supervisor graceful shutdown
  messenger.rst
Labels: Messenger, Status: Reviewed

#15533 [Messenger] add description to amazon-sqs-transport's access_key and secret_key
  messenger.rst
Labels: Messenger, Status: Reviewed

#15545 [Form] Remove useless quotes for `render_rest` attribute
  form/form_customization.rst
Labels: Form, Status: Needs Review

#15548 #42229 update phpdoc to recommend createIndex over ensureIndex
  session/database.rst
Labels: Status: Reviewed

#15547 [Lock] #42227 recommend createIndex over ensureIndex
  components/lock.rst
Labels: Lock, Status: Reviewed

#15546 Fix wrong option flag name
  reference/configuration/security.rst
Labels: Status: Reviewed

#15553 [Notifier] Add Yunpian notifier documentation
  notifier.rst
Labels: Notifier, Status: Reviewed, Waiting Code Merge

#15486 [Notifier] Add AmazonSns Bridge
  notifier.rst
Labels: Notifier, Status: Reviewed

#15552 [Messenger] Document the changes in the delete_after_ack Redis option
  messenger.rst
Labels: Messenger, Status: Reviewed

#14103 Remove manual enabling of validation and validator annotations
  validation.rst
Labels: Status: Needs Review

#14457 [secrets] Use APP_RUNTIME_ENV to define secrets
  configuration/secrets.rst
Labels: Status: Reviewed

#15288 [Notifier] Documentation for Microsoft Teams Options
  _images/notifier/microsoft_teams/message-card.png
  _images/notifier/microsoft_teams/message.png
  notifier/chatters.rst
Labels: Notifier, Status: Reviewed

#15558 [Translation] Support GitHub action format in lint:xliff
  translation/lint.rst
Labels: Status: Reviewed, Translation

#15559 [Twig] Document the GitHub actions format in lint:twig
  templates.rst
Labels: Status: Reviewed, Twig

#15407 [Configuration] Actual code example for Multiple Kernels
  configuration/multiple_kernels.rst
Labels: Status: Reviewed

#15408 [Configuration] Update front_controllers_and_kernel.rst
  configuration/front_controllers_and_kernel.rst
Labels: Status: Reviewed

#15377 [Notifier] Telnyx
  notifier.rst
Labels: Notifier, Status: Reviewed

#14974 [Validator] Improve Valid constraint description
  reference/constraints/Valid.rst
Labels: Status: Reviewed, Validator

#15465 [Logger] Delete monolog_regex_based_excludes.rst
  logging/monolog_regex_based_excludes.rst
Labels: Logger, Status: Needs Review

#15563 Update page_creation.rst
  page_creation.rst
Labels: Status: Needs Review

#15564 Removing full URL of error page preview
  controller/error_pages.rst
Labels: Status: Needs Review

#15557 [Mailer] ping_threshold for ses+smtp
  mailer.rst
Labels: Mailer, Status: Reviewed

#15565 Adding global namespace to `Throwable`
  controller/error_pages.rst
Labels: Status: Reviewed

#15568 Flex: Update links to Symfony 5.3
  setup/flex.rst
Labels: Status: Reviewed

#13911 [Mailer] Document new Mailer transport options
  mailer.rst
Labels: Mailer, Status: Reviewed
