Repository symfony/symfony-docs, pull requests merged in 2021-08, with the labels that each got.

#15572 [Routing] Update routing.rst
  routing.rst
Labels: Routing, Status: Needs Review

#15576 [Testing] update deprecation
  testing.rst
Labels: Status: Reviewed, Testing

#15578 [Security] Small improvement
  security/expressions.rst
Labels: Security, Status: Reviewed

#15581 [Messenger] Document `StopWorkerException`
  messenger.rst
Labels: Messenger, Status: Needs Review

#15577 Small fixes in naming
  security/securing_services.rst
Labels: Status: Reviewed

#15584 [Notifier] Mailjet
  notifier.rst
Labels: Notifier, Status: Needs Review

#15403 [Notifier] Add TurboSms Bridge
  notifier.rst
Labels: Notifier, Status: Reviewed

#15595 [Notifier] Document fake sms logger notifier
  notifier.rst
Labels: Status: Reviewed, Notifier

#15596 [Notifier] Document fake chat logger notifier
  notifier.rst
Labels: Status: Reviewed, Notifier

#15594 [Security] Replace deprecated `PassportInterface` occurrences by `Passport`
  security/authenticator_manager.rst
Labels: Security, Status: Reviewed

#15585 [Mercure] Update mercure.rst
  mercure.rst
Labels: Status: Reviewed, Mercure

#15599 [Doctrine] Document EventSubscriberInterface
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#15600 [Validator] Add Validation::createCallable()
  components/console/helpers/questionhelper.rst
  components/options_resolver.rst
  validation.rst
Labels: Validator, Status: Reviewed

#15609 Deprecate the get() and has() shortcuts of AbstractController
  best_practices.rst
  forms.rst
Labels: Status: Needs Review

#15610 Deprecate the Request::get() method
  create_framework/front_controller.rst
  create_framework/http_foundation.rst
Labels: Status: Needs Review

#15607 Deprecate getDoctrine() and dispatchMessage() shortcuts
  doctrine.rst
  doctrine/associations.rst
  doctrine/multiple_entity_managers.rst
  forms.rst
  introduction/from_flat_php_to_symfony.rst
  messenger.rst
  reference/configuration/doctrine.rst
Labels: Status: Needs Review

#15580 [Serializer] Add documentation about context and Serializer::EMPTY_ARRAY_AS_OBJECT
  serializer.rst
Labels: Serializer, Status: Needs Review

#15608 Add missing instructions to alter the environment directory
  configuration/override_dir_structure.rst
Labels: Status: Reviewed

#15424 [Symfony CLI] Docker integration and MailCatcher prefix
  setup/symfony_server.rst
Labels: Status: Needs Review

#15612 Revert the changes made in #15424
  setup/symfony_server.rst
Labels: Status: Needs Review

#15615 [Serializer] Fixed context key
  serializer.rst
Labels: Status: Reviewed, Serializer

#15611 [DependencyInjection] Improve url env var processor with type cast
  configuration/env_var_processors.rst
Labels: DependencyInjection, Status: Reviewed

#15614 Replaced doctrine annotations with attributes
  reference/constraints/UniqueEntity.rst
Labels: Status: Reviewed

#15263 [Translation] Update translation.rst
  translation.rst
Labels: Status: Reviewed, Translation

#15240 [Mailer] Added cautionbox for sender
  reference/configuration/framework.rst
Labels: Status: Reviewed, Mailer

#15616 [Mailer] Minor typos
  reference/configuration/framework.rst
Labels: Status: Reviewed, Mailer

#15619 [BrowserKit] Update browser_kit.rst
  components/browser_kit.rst
Labels: Status: Reviewed, BrowserKit

#15617 [Mailer] Fixing "envelope recipient"
  reference/configuration/framework.rst
Labels: Status: Reviewed, Mailer

#15620 Replaced doctrine annotations with attributes
  reference/constraints/Traverse.rst
Labels: Status: Reviewed

#15618 [Validator] Showing how to pass options
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#15727 Take into account the EOM of Swiftmailer in docs
  components/http_kernel.rst
  console/command_in_controller.rst
  email.rst
  mailer.rst
  migration.rst
Labels: Status: Reviewed

#15729 Remove references to Swiftmailer in 6.0
  email.rst
  index.rst
  mailer.rst
  reference/configuration/swiftmailer.rst
  reference/dic_tags.rst
  reference/index.rst
  reference/map.rst.inc
Labels: Status: Reviewed

#15739 Bump license year of code
  contributing/code/license.rst
Labels: Status: Reviewed

#15738 Fix method link to isCsrfTokenValid
  security/csrf.rst
Labels: Status: Reviewed

#15737 Fix link reference in Upgrading to Symfony Flex
  setup/flex.rst
Labels: Status: Reviewed

#15720 Added attribute code block examples
  doctrine/associations.rst
Labels: Status: Reviewed

#15626 [Mercure] Update mercure.rst Symfony Local Web Server url
  mercure.rst
Labels: Status: Needs Review, Mercure

#15761 How to Install or Upgrade to the Latest, Unreleased Symfony Version
  setup/unstable_versions.rst
Labels: Status: Reviewed
