Repository symfony/symfony-docs, pull requests merged in 2021-11, with the labels that each got.

#16053 [Form] Remove repeated options in Form types
  reference/forms/types/birthday.rst
  reference/forms/types/button.rst
  reference/forms/types/checkbox.rst
  reference/forms/types/choice.rst
  reference/forms/types/collection.rst
  reference/forms/types/color.rst
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/date.rst
  reference/forms/types/dateinterval.rst
  reference/forms/types/datetime.rst
  reference/forms/types/email.rst
  reference/forms/types/entity.rst
  reference/forms/types/file.rst
  reference/forms/types/form.rst
  reference/forms/types/hidden.rst
  reference/forms/types/integer.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
  reference/forms/types/money.rst
  reference/forms/types/number.rst
  reference/forms/types/password.rst
  reference/forms/types/percent.rst
  reference/forms/types/radio.rst
  reference/forms/types/range.rst
  reference/forms/types/repeated.rst
  reference/forms/types/reset.rst
  reference/forms/types/search.rst
  reference/forms/types/submit.rst
  reference/forms/types/tel.rst
  reference/forms/types/text.rst
  reference/forms/types/textarea.rst
  reference/forms/types/time.rst
  reference/forms/types/timezone.rst
  reference/forms/types/url.rst
  reference/forms/types/week.rst
Labels: Form, Status: Needs Review

#16050 [HttpClient] Fix example url
  http_client.rst
Labels: Status: Reviewed, HttpClient

#16049 [Security] Fix Response HTTP constant
  security.rst
Labels: Security, Status: Reviewed

#16052 Add caution on the framework kernel secret
  reference/configuration/framework.rst
Labels: Status: Reviewed

#16063 Typo fixes : Remove extra "s" + througth ➤ through
  session.rst
Labels: Status: Needs Review

#16062 Typo fix : distrupting ➤ disrupting
  security.rst
Labels: Status: Reviewed

#16061 Typo fix : failes ➤ fails
  _build/maintainer_guide.rst
Labels: Status: Reviewed

#16059 Typo fix : cace ➤ cache
  cache.rst
Labels: Status: Reviewed

#16048 [Doctrine] Parameter as connection value in doctrine tags
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#15450 fix(symfony-cli): remove APP_ENV=test behaviour with the database
  setup/symfony_server.rst
Labels: Status: Reviewed

#15974 [Validator] Add documentation for the Cidr Validator
  reference/constraints/Cidr.rst
Labels: Validator, Status: Reviewed

#16075 Update setup.rst for V5.4
  setup.rst
Labels: Status: Reviewed

#16077 [Notifier] Add Push Channel with Integration Expo & OneSignal
  notifier.rst
Labels: Status: Reviewed, Notifier

#16078 [Filesystem] Add third argument $lock to `Filesystem::appendToFile`
  components/filesystem.rst
Labels: Status: Reviewed, Filesystem

#16084 Move myself alongside the inactive Core team members.
  contributing/code/core_team.rst
Labels: Status: Needs Review

#16086 Update type declaration for Doctrine DBAL Connection
  doctrine/dbal.rst
Labels: Status: Reviewed

#16089 [Security] Fix option name in comment
  security/access_control.rst
Labels: Security, Status: Reviewed

#16092 Fix link to fortrabbit article
  deployment.rst
Labels: Status: Reviewed

#16091 [Security] Minor fix
  security/access_control.rst
Labels: Security, Status: Reviewed

#16099 [Validator] Cidr constraint tweaks
  reference/constraints/Cidr.rst
Labels: Validator, Status: Reviewed

#16020 CSP => Content Security Policy
  frontend/encore/vuejs.rst
Labels: Status: Reviewed

#16102 Update LoggerInterface hyperlink to GitHub page
  logging.rst
Labels: Status: Needs Review

#16097 [Testing] Add comments to the work-in-progress section
  .doctor-rst.yaml
  testing.rst
Labels: Testing, Status: Needs Review

#16111 [Filesystem] Minor tweaks
  components/filesystem.rst
Labels: Filesystem, Status: Needs Review

#16112 [Security] Add example with PHP attributes for login link
  security/login_link.rst
Labels: Security, Status: Reviewed

#16114 [Logger] Change $requestStack to $this->requestStack
  logging/processors.rst
Labels: Logger, Status: Reviewed

#16115 [Doctrine] Update doctrine.rst
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#16113 [Messenger] Redis Sentinel support
  messenger.rst
Labels: Status: Reviewed, Messenger

#16085 [Security] Fix method for the user password hasher service
  security/passwords.rst
Labels: Security, Status: Reviewed

#16083 [FrameworkBundle] Document secret rename logic
  configuration/secrets.rst
Labels: Status: Reviewed, FrameworkBundle

#16103 Add missing information about tsconfig.json
  frontend/encore/typescript.rst
Labels: front-end, Status: Needs Review

#16117 [Serializer] Corrected typo in serializer.rst
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#16068 Update the instructions to build docs
  .dockerignore
  .gitignore
  Dockerfile
  README.markdown
  _build/.requirements.txt
  _build/Makefile
  _build/_exts/symfonycom/__init__.py
  _build/_exts/symfonycom/sphinx/__init__.py
  _build/_exts/symfonycom/sphinx/lexer.py
  _build/_static/rtd_custom.css
  _build/_static/symfony-logo.svg
  _build/build.php
  _build/composer.json
  _build/composer.lock
  _build/conf.py
  _build/make.bat
  _images/docs-pull-request-change-base.png
  docs.json
Labels: Status: Needs Review

#15759 [Filesystem] Add documentation for the Path class
  components/filesystem.rst
Labels: Status: Reviewed, Filesystem

#16120 Split a conditional doc include into two separate doc includes
  reference/forms/types/choice.rst
  reference/forms/types/collection.rst
  reference/forms/types/color.rst
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/email.rst
  reference/forms/types/entity.rst
  reference/forms/types/form.rst
  reference/forms/types/hidden.rst
  reference/forms/types/integer.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
  reference/forms/types/money.rst
  reference/forms/types/number.rst
  reference/forms/types/options/empty_data_declaration.rst.inc
  reference/forms/types/options/empty_data_description.rst.inc
  reference/forms/types/password.rst
  reference/forms/types/percent.rst
  reference/forms/types/range.rst
  reference/forms/types/search.rst
  reference/forms/types/tel.rst
  reference/forms/types/text.rst
  reference/forms/types/textarea.rst
  reference/forms/types/timezone.rst
  reference/forms/types/url.rst
  reference/forms/types/week.rst
Labels: Status: Needs Review

#15888 [Flex] Add instructions for use of private recipe repositories
  setup/flex.rst
  setup/flex_private_recipes.rst
Labels: Status: Reviewed, Flex

#16126 Add some core team members
  contributing/code/core_team.rst
Labels: Status: Reviewed

#15539 Update advanced-config.rst
  frontend/encore/advanced-config.rst
Labels: front-end, Status: Needs Review

#16116 Update page_creation.rst
  page_creation.rst
Labels: Status: Needs Review

#16105 [Workflow] Update workflow docs for $context in GuardEvent
  workflow.rst
Labels: Status: Reviewed, Workflow

#16131 Fix small typos on Core Team page
  contributing/code/core_team.rst
Labels: Status: Needs Review

#16133 [Doctrine] Update URL for DoctrineExtensions
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#16130 Adding a page about Symfony & Docker
  .doctor-rst.yaml
  setup.rst
  setup/docker.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#16123 [Frontend] Reword the introduction to be more precise
  frontend/encore/installation.rst
Labels: Status: Reviewed, front-end

#16124 [Frontend] Remove all Assetic references
  _build/redirection_map
  _build/spelling_word_list.txt
  frontend.rst
  frontend/assetic/index.rst
Labels: front-end, Status: Needs Review

#16135 [Security] remove outdated doc URL that redirects to the same page
  security.rst
Labels: Security, Status: Reviewed

#16134 [Doctrine] Update associations.rst
  doctrine/associations.rst
Labels: Doctrine, Status: Reviewed

#16118 Correction for testing commands
  console.rst
Labels: Status: Reviewed

#16127 [Form] Add the docs for EnumType
  reference/forms/types.rst
  reference/forms/types/enum.rst
  reference/forms/types/map.rst.inc
Labels: Form, Status: Reviewed

#16136 [Form] Fixed missing link text on introduction
  form/dynamic_form_modification.rst
Labels: Form, Status: Reviewed

#16138 Minor formatting tweaks in the Core Team article
  contributing/code/core_team.rst
Labels: Status: Reviewed

#16139 [Config] Fixing missing space in configuration docs
  configuration.rst
Labels: Config, Status: Needs Review

#16142 [Serializer] Remove duplicate colon
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#16143 [Serializer] Fix grammar issue
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#16144 [HTTP Cache] Fix grammar issue
  http_cache/ssi.rst
Labels: Status: Reviewed

#16128 Adding folder name
  frontend/encore/versioning.rst
Labels: Status: Needs Review

#16141 [HttpClient] Rewording when an exception is thrown
  http_client.rst
Labels: Status: Reviewed, HttpClient

#16147 Document PHP attribute naming convention
  contributing/code/standards.rst
Labels: Status: Reviewed

#16148 [ExpressionLanguage] Remove array element
  components/expression_language/syntax.rst
Labels: Status: Reviewed, ExpressionLanguage

#16152 Update page_creation.rst
  page_creation.rst
Labels: Status: Needs Review

#16150 [Notifier] Corrected typo in notifier.rst
  notifier.rst
Labels: Status: Reviewed, Notifier

#16107 Fix assert statement
  console.rst
Labels: Status: Reviewed

#16153 [Form] Minor
  reference/forms/types/enum.rst
Labels: Form, Status: Reviewed

#16154 Update symfony_server.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#16155 [Mailer] Remove duplicate semicolon
  mailer.rst
Labels: Status: Reviewed, Mailer

#16056 [Finder] Add note about .gitignore rules precedence
  components/finder.rst
Labels: Status: Reviewed, Finder

#16159 [Form] Typo in validation_group_service_resolver.rst
  form/validation_group_service_resolver.rst
Labels: Form, Status: Reviewed

#16157 [Form] Ajax success method is never call
  form/dynamic_form_modification.rst
Labels: Form, Status: Reviewed

#16021 Updating sass-loader version
  frontend/encore/simple-example.rst
Labels: Status: Reviewed, front-end

#16001 Removing MooTools (!)
  components/css_selector.rst
Labels: Status: Reviewed, front-end

#16162 Typo
  form/bootstrap5.rst
Labels: Status: Reviewed

#16163 [PHPUnitBridge] [PHPUnit Bridge] Fix @-silencing operator link
  components/phpunit_bridge.rst
Labels: Status: Reviewed, PHPUnitBridge

#16164 [Testing] Fix grammar issue
  testing.rst
Labels: Testing, Status: Reviewed

#16174 Update setup.rst - Symfony 5.4
  setup.rst
Labels: Status: Reviewed

#16175 Update setup.rst - Symfony 6.0
  setup.rst
Labels: Status: Reviewed
