Repository symfony/symfony-docs, pull requests merged in 2021-06, with the labels that each got.

#15395 Typo with backslashes
  service_container.rst
Labels: Status: Needs Review

#15382 [Lock] Remove note about sharing the key
  components/lock.rst
Labels: Lock, Status: Needs Review

#15394 Use BaseKernel class alias
  configuration/override_dir_structure.rst
Labels: Status: Reviewed

#15401 Remove easy-deploy-bundle from "How to Deploy a Symfony Application"
  deployment.rst
Labels: Status: Needs Review

#15399 Update mime.rst
  components/mime.rst
Labels: Mime, Status: Reviewed

#15398 Complete App\Handler\HandlerCollection namespace
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#15405 [Security] Update documentation for stable authenticator security
  _build/redirection_map
  event_dispatcher.rst
  security.rst
  security/authenticator_manager.rst
  security/guard_authentication.rst
Labels: Security, Status: Reviewed

#15406 Adding missing ntlm authentication mode to SwiftmailerBundle config
  reference/configuration/swiftmailer.rst
Labels: Status: Reviewed

#15411 [Form] Fix incorrect class name for Twig configurations
  form/bootstrap5.rst
Labels: Form, Status: Reviewed

#15414 [Form] Adds references to new Form themes
  form/form_themes.rst
Labels: Form, Status: Reviewed

#15416 * setup.rst - documentation bugfix
  setup.rst
Labels: Status: Reviewed

#15415 * setup.rst - bugfix
  setup.rst
Labels: Status: Reviewed

#15422 Update setup.rst
  setup.rst
Labels: Status: Reviewed

#15417 Update bootstrap5.rst
  form/bootstrap5.rst
Labels: Status: Reviewed

#15421 [Doctrine] add missing mapping type (PHP Attributes)
  reference/configuration/doctrine.rst
Labels: Doctrine, Status: Reviewed

#15427 [HttpClient] [HTTP Client][CS] Add missing commas
  http_client.rst
Labels: HttpClient, Status: Reviewed

#15426 Fixed the use of Session with RequesStack
  session.rst
Labels: Status: Reviewed

#15425 Specified camelCase format limitation for logger channel autowiring
  logging/channels_handlers.rst
Labels: Status: Needs Review

#15409 [Notifier] [Slack] Fixing use example
  notifier/chatters.rst
Labels: Notifier, Status: Reviewed

#15431 Typo
  deployment.rst
Labels: Status: Needs Review

#15430 [Security] Update description of password hasher config
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#15433 [Logger] Fixing code typo
  logging/monolog_email.rst
Labels: Logger, Status: Reviewed

#15439 [Runtime] Add a note for --no-scripts
  components/runtime.rst
Labels: Runtime, Status: Reviewed

#15434 Shortening code sample
  logging/monolog_console.rst
Labels: Status: Reviewed

#15435 [Serializer] XmlEncoder context
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#15443 [Messenger] Fix: Highlighting
  messenger.rst
Labels: Messenger, Status: Needs Review

#15442 Typo
  components/ldap.rst
Labels: Status: Reviewed

#15441 [Form] Fixed a code example related to CSRF
  components/form.rst
Labels: Form, Status: Needs Review

#15437 [Security] changed interface name to the correct one
  security/named_hashers.rst
Labels: Security, Status: Needs Review

#15270 [Console] Document console cursor
  _images/components/console/cursor.gif
  components/console/helpers/cursor.rst
  components/console/helpers/index.rst
  components/console/helpers/map.rst.inc
  components/console/helpers/progressbar.rst
  console.rst
Labels: Console, Status: Needs Review

#15445 [Cache] Adds a heading for stampede prevention so I'm able to reference this section easily
  components/cache.rst
Labels: Cache, Status: Reviewed

#15447 [Security] doc: update tip about authenticator-based Security
  security.rst
Labels: Security, Status: Reviewed

#15448 [Migration guide] Change Strangler App to Strangler Fig App
  migration.rst
Labels: Status: Reviewed

#15446 [HttpClient] Import ServerSentEvent class
  http_client.rst
Labels: HttpClient, Status: Reviewed

#15449 [Logging] Fix incorrect PHP example to exclude HTTP code with Monolog
  logging/monolog_exclude_http_codes.rst
Labels: Status: Reviewed

#15459 [HttpClient] Add a note about concurrent requests
  http_client.rst
Labels: HttpClient, Status: Needs Review

#15461 Document the option to map PHP errors to log levels
  reference/configuration/framework.rst
Labels: Status: Reviewed

#15466 [Logger] Updating `excluded_404s` to `excluded_http_codes`
  logging/monolog_email.rst
Labels: Logger, Status: Needs Review
