Repository symfony/symfony-docs, pull requests merged in 2021-02, with the labels that each got.

#14904 [Validator] Use seealso instead of tip for File
  reference/constraints/File.rst
Labels: Status: Reviewed, Validator

#14911 Add the new CARE team
  contributing/code_of_conduct/care_team.rst
Labels: Status: Reviewed

#14914 [CARE] Add Slack Link to Team Member
  contributing/code_of_conduct/care_team.rst
Labels: Status: Reviewed

#14920 [Messenger] Replace comma with full stop
  components/messenger.rst
Labels: Messenger, Status: Reviewed

#14916 Update conventions page to show correct function
  contributing/code/conventions.rst
Labels: Status: Reviewed

#14869 [Notifier] Add SpotHit bridge
  notifier.rst
Labels: Notifier, Status: Reviewed

#14921 [Messenger] message consume command --queue parameter
  messenger.rst
Labels: Messenger, Status: Reviewed

#14918 [RateLimiter][Security] Document login throttling and clarify DoS protection
  rate_limiter.rst
  security.rst
Labels: RateLimiter, Security, Status: Reviewed

#14895 updating Encore docs for 1.0
  .doctor-rst.yaml
  _build/redirection_map
  frontend.rst
  frontend/encore/advanced-config.rst
  frontend/encore/copy-files.rst
  frontend/encore/dev-server.rst
  frontend/encore/installation.rst
  frontend/encore/shared-entry.rst
  frontend/encore/simple-example.rst
  frontend/encore/split-chunks.rst
  frontend/encore/url-loader.rst
  frontend/encore/vuejs.rst
Labels: Status: Reviewed, front-end

#14929 Encore dev-server: re-add host check warning
  frontend/encore/dev-server.rst
Labels: Status: Reviewed, front-end

#14924 [ExpressionLanguage][Security] role_names instead of roles
  security/expressions.rst
Labels: ExpressionLanguage, Security, Status: Reviewed

#14926 Change deprecated psr 2 to psr 12 from doc
  contributing/code/standards.rst
Labels: Status: Needs Review

#14941 [CS] Add comma after last array item in multi-line array
  messenger.rst
Labels: Status: Reviewed

#14938 [Validator] Add a missing dot
  reference/constraints/Sequentially.rst
Labels: Status: Reviewed, Validator

#14937 [Validator] Use correct single quotes for a string
  reference/constraints/IsFalse.rst
  reference/constraints/IsTrue.rst
Labels: Status: Reviewed, Validator

#14936 [Validator] Use single quotes for a string
  reference/constraints/EqualTo.rst
  reference/constraints/IdenticalTo.rst
Labels: Status: Reviewed, Validator

#14939 Clarify the role of http_method_override
  forms.rst
Labels: Status: Reviewed

#14933 [ExpressionLanguage][Security] Mention the "subject" expression language variable
  security/expressions.rst
Labels: ExpressionLanguage, Security, Status: Reviewed

#14930 [Encore] dev-server https fix updates
  frontend/encore/dev-server.rst
Labels: Status: Reviewed, front-end

#14913 [Testing] [PHPUnitBridge] Docs for the new SYMFONY_PHPUNIT_REQUIRE env variable
  components/phpunit_bridge.rst
Labels: Status: Reviewed, Testing

#14940 [Mailer] Configure emails globally
  mailer.rst
Labels: Mailer, Status: Reviewed

#14945 [Validator] Add a comma after the last array item in a multi-line array
  validation/raw_values.rst
Labels: Status: Reviewed, Validator

#14942 [Messenger] [CS] Add missing commas in PHP configurations
  messenger.rst
Labels: Messenger, Status: Reviewed

#14943 [Messenger] [CS] Add missing comma in PHP configuration
  messenger.rst
Labels: Messenger, Status: Reviewed

#14944 [Validator] Use single quotes for a string
  validation.rst
Labels: Status: Reviewed, Validator

#14946 [Validator] Add a missing namespace and use
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#14947 [Validator] Add a missing namespace and use
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#14948 updating config for postcss-loader v4
  frontend/encore/postcss.rst
Labels: Status: Reviewed, front-end

#14949 [Messenger] Remove duplicated AMQP transport option
  messenger.rst
Labels: Messenger, Status: Needs Review

#14959 [Messenger] [CS] Add missing commas
  messenger.rst
Labels: Messenger, Status: Reviewed

#14958 [Mercure] Make the command compatible with ZSH
  mercure.rst
Labels: Mercure, Status: Reviewed

#14963 [Messenger] Fix grammar issue
  messenger.rst
Labels: Messenger, Status: Reviewed

#14955 [Session] Remove some unneeded example
  session.rst
Labels: Session, Status: Reviewed

#14964 fix the trusted proxies configuration
  deployment/proxies.rst
Labels: Status: Reviewed

#14951 [Uid] Removed Uuuid generator classes
  components/uid.rst
Labels: Status: Reviewed, Uid

#14976 [DependencyInjection] Negated (not:) env var processor
  configuration/env_var_processors.rst
Labels: DependencyInjection, Status: Reviewed

#14953 [Form][Uid] Document the new Uuid and Ulid form types
  components/uid.rst
  reference/forms/types.rst
  reference/forms/types/map.rst.inc
  reference/forms/types/ulid.rst
  reference/forms/types/uuid.rst
Labels: Form, Status: Reviewed, Uid

#14957 [Mailer] Improve documentation for mailer failover and round-robin transports
  mailer.rst
Labels: Mailer, Status: Needs Review

#14967 [Validator] Change Range and Legth description formatting
  reference/constraints/Length.rst
  reference/constraints/Range.rst
Labels: Status: Reviewed, Validator

#14975 [Validator] Use import instead of FQCN
  reference/constraints/Type.rst
Labels: Status: Reviewed, Validator

#14978 [Validator] Mention PHP Attribute as an annotation option
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#14981 Update documentation for deprecated "session.storage" service
  reference/configuration/framework.rst
  session.rst
  session/php_bridge.rst
Labels: Status: Needs Review

#14972 [Lock] Update lock documentation for more clarity
  components/lock.rst
Labels: Lock, Status: Needs Review

#14986 [Encore] fix typo fronts instead of fonts
  frontend/encore/url-loader.rst
Labels: Encore, Status: Reviewed

#14970 [Doctrine] Add documentation about doctrine.event_subscriber priority
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#14977 [Validator] Add PHP Attributes example to Compound
  reference/constraints/Compound.rst
Labels: Status: Reviewed, Validator

#14969 [Messenger] Add documentation for RouterContextMiddleware
  messenger.rst
Labels: Messenger, Status: Reviewed

#14991 [Validator] Use single quotes for a string
  validation/groups.rst
Labels: Status: Reviewed, Validator

#14954 [Messenger] Fixed the MESSENGER_TRANSPORT_DSN example
  messenger.rst
Labels: Messenger, Status: Reviewed

#14992 [Security] bcrypt is the new default hasher for native/auto
  best_practices.rst
  security.rst
Labels: Security, Status: Reviewed

#14998 [Validator] Use import instead of FQCN
  form/dynamic_form_modification.rst
Labels: Status: Reviewed, Validator

#14997 [Validator] Use null coalescing operator instead of ternary operator
  validation/severity.rst
Labels: Status: Reviewed, Validator

#14996 Add reference from CHANGELOG conventions to commit message conventions
  contributing/code/conventions.rst
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#14995 [HttpClient] Fix specifying http_version in YAML
  http_client.rst
Labels: HttpClient, Status: Reviewed

#14993 Promoting new bundle directory structure as best practice
  bundles/best_practices.rst
Labels: Status: Needs Review

#14999 Update the default `cookie_secure` value in framework.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed

#14899 [Form] Update Type.rst
  reference/constraints/Type.rst
Labels: Form, Status: Reviewed

#14907 [HttpClient] [http_client] Fix default headers
  http_client.rst
Labels: HttpClient, Status: Reviewed

#14962 [Framework] Add tag assets.package
  reference/dic_tags.rst
Labels: Status: Reviewed

#14982 [Security] Added debug:firewall command
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#15005 [HttpClient] Fix invalid file
  http_client.rst
Labels: HttpClient, Status: Reviewed

#15013 [Twig] Add missing space
  performance.rst
Labels: Status: Reviewed, Twig

#15012 [Validator] Mention doctrine-bridge in the UniqueEntity constraint
  reference/constraints/UniqueEntity.rst
  reference/constraints/UserPassword.rst
Labels: Status: Reviewed, Validator

#15010 Minor change to use DateTimeImmutable instead of DateTime
  doctrine/events.rst
Labels: Status: Needs Review

#15011 remove unsupported trusted header config values
  deployment/proxies.rst
Labels: Status: Reviewed

#15008 [Routing] Add PHP Attribute route example to the controller
  controller/service.rst
Labels: Routing, Status: Reviewed

#15001 [Form] Add PHP Attributes example to forms
  forms.rst
Labels: Form, Status: Reviewed

#15007 [Security] Add PHP Attribute route example to the controller
  security.rst
Labels: Security, Status: Needs Review

#15015 [Security] fix file path in comment following namespace
  security/impersonating_user.rst
Labels: Security, Status: Needs Review

#15021 Use null coalescing operator instead of ternary operator
  components/property_access.rst
  create_framework/http_foundation.rst
  frontend/custom_version_strategy.rst
Labels: Status: Reviewed

#15018 [Internal] Set the specific version of the doc-builder
  _build/composer.json
  _build/composer.lock
Labels: Status: Reviewed

#15023 Remove comment about PR draft status
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#15022 [Testing] Fixed small typo
  testing.rst
Labels: Status: Reviewed, Testing

#15016 [Validator] Add PHP Attributes to severity and translation examples
  validation/severity.rst
  validation/translations.rst
Labels: Status: Reviewed, Validator

#15025 Show example how to set xdebug.file_link_format
  reference/configuration/framework.rst
Labels: Status: Reviewed

#15028 [Validator] Mention IsNull in Basic Constraints
  reference/constraints/IsFalse.rst
  reference/constraints/IsTrue.rst
  reference/constraints/Type.rst
  reference/constraints/_null-values-are-valid.rst.inc
Labels: Status: Reviewed, Validator

#15024 Updated contribution guide with "Automated Feedback"
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#15036 Make the explanation about how Docker services are detected (hopefully) clearer
  setup/symfony_server.rst
Labels: Status: Reviewed

#15035 Make the doc clearer about front controller files checked by Symfony CLI
  setup/symfony_server.rst
Labels: Status: Reviewed
