Repository symfony/symfony-docs, pull requests merged in 2021-12, with the labels that each got.

#16177 Updating link to PHP enum
  reference/forms/types/enum.rst
Labels: Status: Reviewed

#16173 [Notifier] Vonage bridge and deprecation of nexmo bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#16188 [Lock] docs(lock): fix typo in symfony lock documentation
  lock.rst
Labels: Status: Reviewed, Lock

#15376 Update templates.rst for PR symfony/symfony#41414
  templates.rst
Labels: Status: Reviewed

#16182 [Messenger] Fix example config
  messenger.rst
Labels: Status: Reviewed, Messenger

#16181 Typo fix : "Thees" ➤ "These"
  workflow.rst
Labels: Status: Reviewed

#16187 Update setup.rst (Symfony 4.4)
  setup.rst
Labels: Status: Needs Review

#16186 Update setup.rst (Symfony 5.3)
  setup.rst
Labels: Status: Reviewed

#16185 Update setup.rst (Symfony 5.4)
  setup.rst
Labels: Status: Reviewed

#16183 Update setup.rst (Symfony 6.1)
  setup.rst
Labels: Status: Reviewed

#16190 [Setup] PHP 8.1 is the last release
  setup.rst
Labels: Status: Reviewed

#16189 [Setup] Fix references of previous version
  setup/upgrade_major.rst
Labels: Status: Reviewed

#16167 Update handler_results.rst
  messenger/handler_results.rst
Labels: Status: Needs Review

#16176 Add UrlHelper section to HttpFoundation docs
  components/http_foundation.rst
Labels: Status: Reviewed

#16206 Using const `Response::HTTP_MOVED_PERMANENTLY` for redirect
  controller.rst
Labels: Status: Needs Review

#16192 Update doctrine.rst
  doctrine.rst
Labels: Status: Reviewed

#16200 [Security] Fix broken event link
  security.rst
Labels: Security, Status: Reviewed

#15916 [HttpKernel] 15874 framework exceptions
  reference/configuration/framework.rst
Labels: Status: Reviewed, HttpKernel

#16212 [Messenger] added example for limit consuming to specific queue / queues
  messenger.rst
Labels: Status: Reviewed, Messenger

#16195 Add functional test chapter to mailer
  mailer.rst
Labels: Status: Reviewed

#16209 [PHPUnitBridge] [PHPUnit Bridge] Remove the table that lists PHPUnit versions
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Needs Review

#16216 Import jquery as the $ variable.
  frontend/encore/simple-example.rst
Labels: front-end, Status: Needs Review

#16221 Add a warning about native://default for Mailer
  mailer.rst
Labels: Status: Needs Review

#16218 Remove "enable_authenticator_manager" from Symfony 6 docs
  security.rst
Labels: Status: Reviewed

#16230 fix a small grammar issue
  contributing/code/core_team.rst
Labels: Status: Reviewed

#16226 [Form] Upgrade Bootstrap 4 theme references to Bootstrap 5 theme
  form/form_customization.rst
  form/form_themes.rst
  forms.rst
  reference/configuration/twig.rst
Labels: Form, Status: Reviewed

#16235 [Routing] Correct spelling & grammar in routing.rst
  routing.rst
Labels: Routing, Status: Reviewed

#16234 [Page Creation] Correct spelling & grammar in page-creation.rst
  page_creation.rst
Labels: Status: Reviewed

#16233 [Setup] Correct spelling mistakes
  setup.rst
Labels: Status: Reviewed

#16250 Correct spelling & grammar in 4.4 mercure.rst
  mercure.rst
Labels: Status: Reviewed

#16252 Correct spelling & grammar in 4.4 migration.rst
  migration.rst
Labels: Status: Reviewed

#16253 Correct spelling & grammar in 4.4 performance.rst
  performance.rst
Labels: Status: Reviewed

#16256 Correct spelling & grammar in 4.4 workflow.rst
  workflow.rst
Labels: Status: Reviewed

#16257 Correct spelling & grammar in 4.4 bundles/
  bundles/best_practices.rst
  bundles/configuration.rst
  bundles/prepend_extension.rst
Labels: Status: Reviewed

#16259 Correct spelling & grammar in 4.4 components/config/
  components/config/definition.rst
Labels: Status: Reviewed

#16260 Correct spelling & grammar in 4.4 components/console/
  components/console/helpers/progressbar.rst
  components/console/helpers/questionhelper.rst
  components/console/helpers/table.rst
  components/console/single_command_tool.rst
Labels: Status: Reviewed

#16261 Correct spelling & grammar in 4.4 components/dependency_injection/
  components/dependency_injection/compilation.rst
  components/dependency_injection/workflow.rst
Labels: Status: Reviewed

#16262 Correct spelling & grammar in 4.4 components/expression_language/
  components/expression_language/ast.rst
  components/expression_language/caching.rst
  components/expression_language/syntax.rst
Labels: Status: Reviewed

#16272 Correct spelling & grammar in 4.4 form/
  form/dynamic_form_modification.rst
  form/form_themes.rst
Labels: Status: Reviewed

#16271 Correct spelling & grammar in 4.4 doctrine/
  doctrine/associations.rst
  doctrine/dbal.rst
  doctrine/registration_form.rst
  doctrine/resolve_target_entity.rst
  doctrine/reverse_engineering.rst
Labels: Status: Reviewed

#16270 Correct spelling & grammar in 4.4 create_framework/
  create_framework/front_controller.rst
Labels: Status: Reviewed

#16289 Correct spelling & grammar in 4.4 validation/
  validation/custom_constraint.rst
  validation/groups.rst
  validation/sequence_provider.rst
Labels: Status: Reviewed

#16288 Correct spelling & grammar in 4.4 translation/
  translation/locale.rst
  translation/message_format.rst
Labels: Status: Reviewed

#16287 Correct spelling & grammar in 4.4 templating/
  templating/global_variables.rst
Labels: Status: Reviewed

#16286 Correct spelling & grammar in 4.4 setup/
  setup/bundles.rst
Labels: Status: Reviewed

#16283 Correct spelling & grammar in 4.4 service_container/
  service_container/autowiring.rst
  service_container/injection_types.rst
Labels: Status: Reviewed

#16282 Correct spelling & grammar in 4.4 security/
  security/custom_authentication_provider.rst
  security/form_login_setup.rst
  security/multiple_guard_authenticators.rst
  security/password_migration.rst
  security/voters.rst
Labels: Status: Reviewed

#16281 Correct spelling & grammar in 4.4 routing/
  routing/custom_route_loader.rst
  routing/routing_from_database.rst
Labels: Status: Reviewed

#16279 Correct spelling & grammar in 4.4 quick_tour/
  quick_tour/flex_recipes.rst
  quick_tour/the_architecture.rst
Labels: Status: Reviewed

#16278 Correct spelling & grammar in 4.4 profiler/
  profiler/data_collector.rst
Labels: Status: Reviewed

#16277 Correct spelling & grammar in 4.4 messenger/
  messenger/dispatch_after_current_bus.rst
  messenger/multiple_buses.rst
Labels: Status: Reviewed

#16276 Correct spelling & grammar in 4.4 logging/
  logging/handlers.rst
  logging/monolog_console.rst
  logging/monolog_email.rst
  logging/processors.rst
Labels: Status: Reviewed

#16275 Correct spelling & grammar in 4.4 introduction/
  introduction/from_flat_php_to_symfony.rst
  introduction/http_fundamentals.rst
Labels: Status: Reviewed

#16274 Correct spelling & grammar in 4.4 http_cache/
  http_cache/cache_invalidation.rst
  http_cache/ssi.rst
  http_cache/varnish.rst
Labels: Status: Reviewed

#16273 Correct spelling & grammar in 4.4 frontend/
  frontend/encore/advanced-config.rst
  frontend/encore/installation.rst
  frontend/encore/page-specific-assets.rst
  frontend/encore/simple-example.rst
  frontend/encore/url-loader.rst
Labels: Status: Reviewed

#16294 Ask to open PRs for new features in 6.x
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Reviewed

#16245 Correct spelling & grammar in 4.4 http_cache.rst
  http_cache.rst
Labels: Status: Reviewed

#16246 Correct spelling & grammar in 4.4 http_client.rst
  http_client.rst
Labels: Status: Reviewed

#16247 Correct spelling & grammar in 4.4 lock.rst
  lock.rst
Labels: Status: Reviewed

#16248 Correct spelling & grammar in 4.4 logging.rst
  logging.rst
Labels: Status: Reviewed

#16254 Correct spelling & grammar in 4.4 testing.rst
  testing.rst
Labels: Status: Reviewed

#16258 Correct spelling & grammar in 4.4 components/cache/
  components/cache/adapters/php_array_cache_adapter.rst
  components/cache/adapters/redis_adapter.rst
  components/cache/cache_invalidation.rst
Labels: Status: Reviewed

#16263 Correct spelling & grammar in 4.4 components/http_foundation/
  components/http_foundation/sessions.rst
Labels: Status: Reviewed

#16264 Correct spelling & grammar in 4.4 components/security/
  components/security/authentication.rst
Labels: Status: Reviewed

#16265 Correct spelling & grammar in 4.4 components/yaml/
  components/yaml/yaml_format.rst
Labels: Status: Reviewed

#16267 Correct spelling & grammar in 4.4 configuration/
  configuration/env_var_processors.rst
  configuration/front_controllers_and_kernel.rst
  configuration/multiple_kernels.rst
Labels: Status: Reviewed

#16269 Correct spelling & grammar in 4.4 controller/
  controller/soap_web_service.rst
Labels: Status: Reviewed

#16268 Correct spelling & grammar in 4.4. contributing/
  contributing/code/bc.rst
  contributing/code/core_team.rst
  contributing/code/maintenance.rst
  contributing/code/stack_trace.rst
  contributing/code/standards.rst
  contributing/code_of_conduct/code_of_conduct.rst
  contributing/code_of_conduct/reporting_guidelines.rst
  contributing/community/mentoring.rst
  contributing/community/releases.rst
  contributing/community/review-comments.rst
  contributing/community/reviews.rst
  contributing/community/speaker-mentoring.rst
  contributing/diversity/governance.rst
  contributing/documentation/overview.rst
  contributing/translations/index.rst
Labels: Status: Reviewed

#16266 Correct spelling & grammar in 4.4 components/
  components/asset.rst
  components/http_kernel.rst
  components/inflector.rst
  components/lock.rst
  components/mime.rst
  components/options_resolver.rst
  components/process.rst
  components/property_access.rst
  components/property_info.rst
  components/serializer.rst
  components/var_exporter.rst
Labels: Status: Reviewed

#16251 Correct spelling & grammar in 4.4 messenger.rst
  messenger.rst
Labels: Status: Reviewed

#16244 Correct spelling & grammar in 4.4. frontend.rst
  frontend.rst
Labels: Status: Reviewed

#16243 Correct spelling & grammar in 4.4 forms.rst
  forms.rst
Labels: Status: Reviewed

#16242 Correct spelling & grammar in 4.4 event_dispatcher.rst
  event_dispatcher.rst
Labels: Status: Reviewed

#16241 Correct spelling & grammar in 4.4 email.rst
  email.rst
Labels: Status: Reviewed

#16240 Correct spelling & grammar in 4.4 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Status: Reviewed

#16239 Correct spelling & grammar in 4.4 cache.rst
  cache.rst
Labels: Status: Reviewed

#16238 Correct spelling & grammar in 4.4 best-practices.rst
  best_practices.rst
Labels: Status: Reviewed

#16237 [Security] Correct spelling & grammar in 4.4 security.rst
  security.rst
Labels: Security, Status: Reviewed

#16228 [Setup] Change upgrade-minor.rst to reference Symfony 5
  setup/upgrade_minor.rst
Labels: Status: Reviewed

#16229 [Setup] Change upgrade_patch.rst to reference Symfony 6
  setup/upgrade_patch.rst
Labels: Status: Reviewed

#16227 [CLI] Add link in setup.rst to Symfony CLI source repo
  setup.rst
Labels: Status: Reviewed

#16302 Fix issue 16298 - duplicate link
  components/console.rst
Labels: Status: Reviewed

#16305 Correct spelling & grammar in 5.3
  cache.rst
  components/browser_kit.rst
  components/http_foundation.rst
  components/lock.rst
  components/messenger.rst
  components/phpunit_bridge.rst
  components/runtime.rst
  components/semaphore.rst
  components/string.rst
  components/uid.rst
  components/var_dumper.rst
  notifier.rst
  rate_limiter.rst
  security/custom_authenticator.rst
  security/login_link.rst
  security/passwords.rst
  security/remember_me.rst
  security/user_providers.rst
  service_container/autowiring.rst
  testing.rst
  validation/custom_constraint.rst
Labels: Status: Reviewed

#16293 [Mercure] Compatibility with the Docker integration and various improvements
  mercure.rst
Labels: Status: Reviewed, Mercure

#16303 [Security] Change "createAuthenticatedToken" to "createToken"
  security/custom_authenticator.rst
Labels: Security, Status: Reviewed

#16307 Fix minor spelling and grammar issues in 5.4
  components/security/authorization.rst
  console/style.rst
  mailer.rst
  messenger.rst
  serializer.rst
  testing.rst
Labels: Status: Reviewed

#16312 [Testing] Minor tweaks in the main testing article
  testing.rst
Labels: Testing, Status: Reviewed

#16314 [Mailer][Mime] add `DraftEmail` documentation
  mailer.rst
Labels: Status: Reviewed, Mailer, Mime

#16308 [Security] Add PHP attributes to a PHP annotations example
  security.rst
Labels: Security, Status: Reviewed

#16217 [Lock] Add new Doctrine DBAL stores
  components/lock.rst
Labels: Status: Reviewed, Lock

#16318 [Messenger] Remove mention to unsupported `prefetch_count` config option
  messenger.rst
Labels: Status: Reviewed, Messenger

#16317 Fix wrong path (aka 404 error) for security_events.svg diagram
  security.rst
Labels: Status: Reviewed

#16292 Update twig_extension.rst
  templating/twig_extension.rst
Labels: Status: Reviewed

#16321 documentation is incomplete the variable form._token is missing
  form/form_customization.rst
Labels: Status: Needs Review

#16320 [Security] Merge standalone Security component docs with Security guide
  components/security.rst
  components/security/authentication.rst
  components/security/authorization.rst
  components/security/firewall.rst
  components/security/secure_tools.rst
  controller/argument_value_resolver.rst
  introduction/from_flat_php_to_symfony.rst
  reference/configuration/security.rst
  security/passwords.rst
  security/voters.rst
Labels: Security, Status: Reviewed

#16327 Remove `Build the Documentation Locally`
  contributing/documentation/overview.rst
Labels: Status: Needs Review

#14335 [Serializer] Remove duplicate normalizers docs
  components/serializer.rst
  serializer.rst
  serializer/custom_normalizer.rst
  serializer/normalizers.rst
Labels: Status: Reviewed, Serializer

#16315 [Framework] Read env var SYMFONY_IDE by default for framework.ide
  reference/configuration/framework.rst
Labels: Status: Reviewed

#15903 [Cache] Split PdoAdapter to DoctrineDbalAdapter
  components/cache/adapters/pdo_doctrine_dbal_adapter.rst
Labels: Status: Reviewed, Cache

#16329 Clarify Pull Request Merging Policy
  contributing/code/core_team.rst
Labels: Status: Needs Review

#16331 [Mercure] fix some typos and outdates sentences
  mercure.rst
Labels: Status: Reviewed, Mercure

#16341 Update best_practices.rst
  best_practices.rst
Labels: Status: Needs Review

#16345 [ExpressionLanguage] Fix link anchors in expression_language.rst #16295
  components/expression_language.rst
Labels: Status: Reviewed, ExpressionLanguage

#16336 [Messenger] : Doc update for async handler
  messenger.rst
Labels: Status: Needs Review, Messenger

#16285 Update esi.rst
  http_cache/esi.rst
Labels: Status: Reviewed

#16025 make following jquery example works
  frontend/encore/simple-example.rst
Labels: Status: Reviewed, front-end

#16349 [VarExporter] Make example work
  components/var_exporter.rst
Labels: Status: Reviewed, VarExporter

#16346 Improvements around documentation images
  _images/contributing/docs-github-create-pr.png
  _images/contributing/docs-github-edit-page.png
  _images/contributing/docs-pull-request-change-base.png
  _images/controller/error_pages/exceptions-in-dev-environment.png
  _images/install/deprecations-in-profiler.png
  _images/profiler/web-interface.png
  _images/quick_tour/no_routes_page.png
  _images/quick_tour/web_debug_toolbar.png
  _images/release-process.jpg
Labels: Status: Reviewed
