Repository symfony/symfony-docs, pull requests merged in 2021-01, with the labels that each got.

#14766 language tweak
  components/property_access.rst
Labels: Status: Needs Review

#14768 Fix PostgreSqlStore code sample formatting
  components/lock.rst
Labels: Status: Reviewed

#14573 [Console] Caution about disabling auto exit flag
  console.rst
Labels: Console, Status: Needs Review

#14695 Update normalizers.rst
  serializer/normalizers.rst
Labels: Status: Reviewed

#14708 Replace unavailable dependency in Symfony 4
  setup/unstable_versions.rst
Labels: Status: Reviewed

#14774 [DomCrawler] document the ancestors() method
  components/dom_crawler.rst
  testing.rst
Labels: DomCrawler, Status: Reviewed

#14775 [Form] Update event diagrams to use consistent styling
  _images/components/form/general_flow.png
  _images/components/form/set_data_flow.png
  _images/components/form/submission_flow.png
  _images/form/form_prepopulation_workflow.svg
  _images/form/form_submission_workflow.svg
  _images/form/form_workflow.svg
  _images/sources/form/form_events.dia
  form/events.rst
Labels: Form, Status: Reviewed

#14558 [PHPUnitBridge] Add deprecation log file option
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Reviewed

#14787 [Console] Add documentation for Console Negatable option
  console/input.rst
Labels: Console, Status: Needs Review

#14777 Add missing configurations in XML and PHP formats
  configuration/env_var_processors.rst
Labels: Status: Reviewed

#14733 [DependencyInjection] [Service Container] Fix typo in tag default index method name
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#14668 Support Redis Sentinel mode when using phpredis/phpredis extension
  components/cache/adapters/redis_adapter.rst
Labels: Status: Reviewed

#14788 doc: copy paste trusted_headers vs trusted_proxies
  reference/configuration/framework.rst
Labels: Status: Reviewed

#14789 Remove unused imports and properties in experimental authenticator example
  security/experimental_authenticators.rst
Labels: Status: Reviewed

#14796 [FrameworkBundle] Document assertResponseFormatSame()
  testing/functional_tests_assertions.rst
Labels: FrameworkBundle, Status: Reviewed

#14800 [Ldap] Add examples about get/has attribute
  components/ldap.rst
Labels: Ldap, Status: Reviewed

#14804 [BrowserKit] Document the jsonRequest() method
  components/browser_kit.rst
Labels: BrowserKit, Status: Reviewed

#14803 [Yaml] Documented the github output format for the linter
  translation/lint.rst
Labels: Status: Reviewed, Yaml

#14802 [Ldap] Document the case-insensitive attribute names
  components/ldap.rst
Labels: Ldap, Status: Reviewed

#14801 Add more details about the ESI detection
  http_cache/esi.rst
Labels: Status: Reviewed

#14807 [Messenger] Mention the WorkerMessageRetriedEvent
  messenger.rst
Labels: Messenger, Status: Reviewed

#14809 Improved the check requirements section of the deployment article
  deployment.rst
Labels: Status: Reviewed

#14805 [Messenger] Document the debug option of Amazon SQS
  messenger.rst
Labels: Messenger, Status: Reviewed

#14110 Update deployment.rst
  deployment.rst
Labels: Status: Reviewed

#13387 [HttpClient] Expand MockResponse example with HTTP status codes
  http_client.rst
Labels: HttpClient, Status: Needs Review

#13599 [Testing] Document improving test speed by reducing password encoder "work factor"
  testing/http_authentication.rst
Labels: Status: Needs Review, Testing

#13907 [Workflow] Added function to get a specific transition
  workflow.rst
Labels: Status: Reviewed, Workflow

#14682 [DependencyInjection] [Service Container] Fix Service parameters typo in services.yml
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#14609 [Serializer] Clarifies 'csv_headers' option
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#14376 [Validator] PHP 7.4 uninitialized typed property handling
  validation.rst
Labels: Status: Reviewed, Validator

#14815 fix table markup
  components/serializer.rst
Labels: Status: Needs Review

#14797 [Messenger] Deprecated the prefetch_count option
  messenger.rst
Labels: Messenger, Status: Reviewed

#14384 [Serializer] Add missing options context
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#14817 DOCtor-RST: New rule blank_line_after_anchor
  .doctor-rst.yaml
Labels: Status: Needs Review

#14818 Fixes #14814 Default behavior about unpacking packs by Flex changed
  setup.rst
Labels: Status: Reviewed

#14808 [Messenger] Documented AMQP confirm_timeout option
  messenger.rst
Labels: Messenger, Status: Reviewed

#14822 [Mailer] Update Twig namespace
  mailer.rst
Labels: Mailer, Status: Reviewed

#14816 [Security] Update access_control.rst
  security/access_control.rst
Labels: Security, Status: Needs Review

#14820 Update access_denied_handler.rst
  security/access_denied_handler.rst
Labels: Status: Needs Review

#14824 Remove HeahDude from the docs team
  contributing/code/core_team.rst
Labels: Status: Needs Review

#14825 add HeahDude to the list of former members
  contributing/code/core_team.rst
Labels: Status: Reviewed

#14823 Change in table creation SQL for SQL Server
  session/database.rst
Labels: Status: Reviewed

#13986 Fix OPcache class preload requirement
  performance.rst
Labels: Status: Reviewed

#14832 add Oskar to the Symfony core team
  contributing/code/core_team.rst
Labels: Status: Reviewed

#14779 [Notifier] Add Octopush notifier transport
  notifier.rst
Labels: Notifier, Status: Reviewed

#14463 [Notifier] Add gatewayapi-notifier
  notifier.rst
Labels: Notifier, Status: Reviewed

#14739 [Notifier] Add AllMySms service to list
  notifier.rst
Labels: Notifier, Status: Reviewed, Waiting Code Merge

#14834 [Notifier] Rename threadKey to thread_key
  notifier.rst
Labels: Notifier, Status: Needs Review

#14830 Clarify how to write a commit message and CHANGELOGs
  contributing/code/conventions.rst
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#14819 Add warning about removed services
  testing.rst
Labels: Status: Reviewed

#14821 Update introduction.rst
  create_framework/introduction.rst
Labels: Status: Needs Review

#14799 [Serializer] Add UidNormalizer normalization formats
  components/serializer.rst
Labels: Serializer, Status: Reviewed

#14798 [HttpFoundation] Mention that trusted proxies are not compatible with nginx realip
  deployment/proxies.rst
Labels: HttpFoundation, Status: Reviewed

#14505 [Bundles] Update best practices to use Symfony Flex and do not favor any CI tool
  bundles/best_practices.rst
Labels: Status: Reviewed

#14838 Typo
  testing.rst
Labels: Status: Needs Review

#14839 [Lock] Grammer fix
  components/lock.rst
Labels: Lock, Status: Needs Review

#14845 [HttpFoundation] deprecate the NamespacedAttributeBag class
  components/http_foundation/sessions.rst
  session.rst
Labels: HttpFoundation, Status: Reviewed

#14836 Updating {% block javascripts position to match recipe change
  .doctor-rst.yaml
  frontend/encore/simple-example.rst
  introduction/from_flat_php_to_symfony.rst
Labels: Status: Reviewed, front-end

#14849 [Security] expand code example to clarify usage of the UserRepository
  security/experimental_authenticators.rst
Labels: Security, Status: Reviewed

#14837 [Lock] Use .inner instead of decorating_service_id + '.inner'
  lock.rst
Labels: Lock, Status: Reviewed

#14847 [Uid] getId(): ?Uuid missing // need test getId: ?Ulid
  components/uid.rst
Labels: Status: Reviewed, Uid

#14826 [Mailer] Add missing transports entry in XML and PHP configurations
  mailer.rst
Labels: Mailer, Status: Reviewed

#14852 [Security] Clarify the DeauthenticatedEvent
  components/security/authentication.rst
Labels: Security, Status: Reviewed

#14855 Added missing Dotenv use
  migration.rst
Labels: Status: Reviewed

#14853 Use Sf4 + Sf5 instead of Sf3 for bundle best practices
  bundles/best_practices.rst
Labels: Status: Reviewed

#14840 [Notifier] Add Mercure notifier documentation
  notifier.rst
Labels: Notifier, Status: Needs Review

#14858 [Logger] Just moving this note upwards
  logging.rst
Labels: Logger, Status: Reviewed

#14835 [Notifier] Add symfony/gitter-notifier docs
  notifier.rst
Labels: Notifier, Status: Reviewed

#14699 [Form] Add choice_translation_parameters option
  reference/forms/types/choice.rst
  reference/forms/types/options/choice_translation_parameters.rst.inc
Labels: Form, Status: Reviewed

#14544 [Validator] Document constraints as php 8 Attributes
  reference/constraints/Bic.rst
  reference/constraints/Blank.rst
  reference/constraints/Callback.rst
  reference/constraints/CardScheme.rst
  reference/constraints/Choice.rst
  reference/constraints/Count.rst
  reference/constraints/Country.rst
  reference/constraints/Currency.rst
  reference/constraints/Date.rst
  reference/constraints/DateTime.rst
  reference/constraints/DivisibleBy.rst
  reference/constraints/Email.rst
  reference/constraints/EqualTo.rst
  reference/constraints/Expression.rst
  reference/constraints/ExpressionLanguageSyntax.rst
  reference/constraints/File.rst
  reference/constraints/GreaterThan.rst
  reference/constraints/GreaterThanOrEqual.rst
  reference/constraints/Hostname.rst
  reference/constraints/Iban.rst
  reference/constraints/IdenticalTo.rst
  reference/constraints/Image.rst
  reference/constraints/Ip.rst
  reference/constraints/IsFalse.rst
  reference/constraints/IsNull.rst
  reference/constraints/IsTrue.rst
  reference/constraints/Isbn.rst
  reference/constraints/Isin.rst
  reference/constraints/Issn.rst
  reference/constraints/Json.rst
  reference/constraints/Language.rst
  reference/constraints/Length.rst
  reference/constraints/LessThan.rst
  reference/constraints/LessThanOrEqual.rst
  reference/constraints/Locale.rst
  reference/constraints/Luhn.rst
  reference/constraints/Negative.rst
  reference/constraints/NegativeOrZero.rst
  reference/constraints/NotBlank.rst
  reference/constraints/NotCompromisedPassword.rst
  reference/constraints/NotEqualTo.rst
  reference/constraints/NotIdenticalTo.rst
  reference/constraints/NotNull.rst
  reference/constraints/Positive.rst
  reference/constraints/PositiveOrZero.rst
  reference/constraints/Range.rst
  reference/constraints/Regex.rst
  reference/constraints/Time.rst
  reference/constraints/Timezone.rst
  reference/constraints/Traverse.rst
  reference/constraints/Type.rst
  reference/constraints/Ulid.rst
  reference/constraints/Unique.rst
  reference/constraints/UniqueEntity.rst
  reference/constraints/Url.rst
  reference/constraints/UserPassword.rst
  reference/constraints/Uuid.rst
  reference/constraints/Valid.rst
Labels: Status: Reviewed, Validator

#14732 [Mercure] Update docs for v0.11
  mercure.rst
Labels: Mercure, Status: Reviewed

#14857 [DependencyInjection] Require preprocessor env name fix used in PHP snippet
  configuration/env_var_processors.rst
Labels: DependencyInjection, Status: Needs Review

#14861 Listing possible values of storage_id
  reference/configuration/framework.rst
Labels: Status: Reviewed

#14828 Mention MariaDB as well
  session/database.rst
Labels: Status: Needs Review

#14859 [Mailer] Update mailer.rst
  mailer.rst
Labels: Mailer, Status: Reviewed

#14812 [DependencyInjection] [Configuration] Fix PHP configuration sample for setting default parameter bindings
  configuration.rst
Labels: DependencyInjection, Status: Needs Review

#14603 [Logger] Remove wrong "method" tag
  logging/processors.rst
Labels: Logger, Status: Reviewed

#14328 [Serializer] add note on Custom Normalizer page about cacheable performance
  components/serializer.rst
  serializer/custom_normalizer.rst
Labels: Serializer, Status: Reviewed

#14806 [PHPUnitBridge] Document the deprecation baseline file
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Needs Review

#14868 [Serializer] Update serializer.rst
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#14698 Update the Nginx example
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#14585 [Messenger] Add mention about serialize in inMemory transport dsn
  messenger.rst
Labels: Messenger, Status: Reviewed

#14871 [Validator] Use constant instead of magic string
  reference/constraints/CardScheme.rst
  reference/constraints/Isbn.rst
Labels: Status: Reviewed, Validator

#14873 [Validator] Use double quotes instead of single
  reference/constraints/IsFalse.rst
Labels: Status: Needs Review, Validator

#14876 [Validator] Use single quotes for string
  reference/constraints/Sequentially.rst
Labels: Status: Reviewed, Validator

#14877 [Validator] Change the example to be consistent with the rest
  reference/constraints/AtLeastOneOf.rst
Labels: Status: Reviewed, Validator

#14881 [Notifier] Add clickatell
  notifier.rst
Labels: Notifier, Status: Needs Review

#14875 [Security] [csrf] Add documentation about breach
  security/csrf.rst
Labels: Security, Status: Reviewed

#14883 [Translator] Fix select & plural message format
  translation/message_format.rst
Labels: Status: Reviewed, Translator

#13775 [Lock] #37139 Updated Lock MongoDbStore note on readPreference
  components/lock.rst
Labels: Lock, Status: Reviewed

#14865 [Validator] Use PHP attributes when creating custom validation constraints
  validation/custom_constraint.rst
Labels: Status: Reviewed, Validator

#14886 [Lock] Fix grammar issue
  components/lock.rst
Labels: Lock, Status: Reviewed

#14891 [Uid] Remove experimental for UID
  components/uid.rst
  notifier.rst
Labels: Status: Reviewed, Uid

#14893 [Uid] Mentioned the Uuid::NAMESPACE_* constants
  components/uid.rst
Labels: Status: Reviewed, Uid

#14892 [Uid] Document the getDateTime() method
  components/uid.rst
Labels: Status: Reviewed, Uid

#14894 [Semaphore] Mark semaphore experimental
  components/semaphore.rst
Labels: Semaphore, Status: Reviewed

#14898 [FrameworkBundle] Update documentation for deprecated session service
  components/http_foundation.rst
  controller.rst
  logging/processors.rst
  quick_tour/the_architecture.rst
  security/access_denied_handler.rst
  security/form_login_setup.rst
  service_container.rst
  session.rst
  session/locale_sticky_session.rst
Labels: Status: Reviewed

#14884 [Console] Add bright colors to console.
  console/coloring.rst
Labels: Console, Status: Reviewed

#14776 [String] Feature 39178
  components/string.rst
Labels: Status: Reviewed, String

#14900 Fix Connect URL
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#14436 [RateLimiter] Add diagrams to better explain the differences
  _images/rate_limiter/fixed_window.svg
  _images/rate_limiter/sliding_window.svg
  _images/rate_limiter/token_bucket.svg
  _images/sources/rate_limiter/fixed_window.dia
  _images/sources/rate_limiter/sliding_window.dia
  _images/sources/rate_limiter/token_bucket.dia
  rate_limiter.rst
Labels: RateLimiter, Status: Reviewed

#14902 [Console] Update comments
  console/style.rst
Labels: Console, Status: Reviewed
