Repository symfony/symfony-docs, pull requests merged in 2022-11, with the labels that each got.

#17406 Events are dispatched, not thrown
  components/http_kernel.rst
Labels: Status: Needs Review

#17364 [Form] Adding Stimulus code
  form/form_collections.rst
Labels: Form, Status: Reviewed

#17396 [Serializer] SerializedPath documentation
  serializer.rst
Labels: Status: Reviewed, Serializer

#17416 Remove Magali from CARE
  contributing/code_of_conduct/care_team.rst
Labels: Status: Reviewed

#17414 [Validator] File: add option to check extension
  reference/constraints/File.rst
Labels: Validator, Status: Reviewed

#17424 Typo
  reference/configuration/security.rst
Labels: Status: Reviewed

#17437 [Validator] File: fix versionadded of extensionsMessage option
  reference/constraints/File.rst
Labels: Validator, Status: Reviewed

#17430 [Security] Add form_only option
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#17425 Minor
  reference/configuration/security.rst
Labels: Status: Reviewed

#17427 [Security] Minor rewording
  security.rst
  security/form_login.rst
Labels: Security, Status: Reviewed

#17431 [Form] Minor
  form/data_transformers.rst
Labels: Form, Status: Reviewed

#17448 Remove old `versionadded` directive
  reference/configuration/security.rst
Labels: Status: Reviewed

#17447 Remove useless comma
  security.rst
Labels: Status: Needs Review

#17441 Replace annotation by attribute
  validation/custom_constraint.rst
Labels: Status: Reviewed

#17449 [Security] Propose attributes usage
  security.rst
Labels: Security, Status: Reviewed

#17452 Fix confusing example of type-hinting the Request object
  controller.rst
Labels: Status: Reviewed

#17438 [Security] Merging "list" into text
  security.rst
Labels: Security, Status: Reviewed

#17451 [Testing] Emphasise where a method is returning a value.
  testing.rst
Labels: Testing, Status: Needs Review

#17456 [Mailer] Fix minor syntax issue
  mailer.rst
Labels: Status: Reviewed, Mailer

#17435 [Clock] Documentation for new Clock component
  components/clock.rst
Labels: Status: Reviewed, Clock

#17460 [Form] Mention PropertyAccess in the hash_property_option of PasswordType
  reference/forms/types/password.rst
Labels: Form, Status: Needs Review

#17465 [Lock] Make various changes/updates on the Lock docs
  components/lock.rst
  lock.rst
Labels: Status: Needs Review, Lock

#17464 Fix UX package list Dropzone display
  frontend/_ux-libraries.rst.inc
Labels: Status: Reviewed, front-end

#17461 [Templating] add missing use for Template attribute
  templates.rst
Labels: Templating, Status: Reviewed

#17462 [Security] use new class
  security.rst
  setup/bundles.rst
Labels: Security, Status: Reviewed

#17454 [Logger] Use Monolog\LogRecord object instead of array for log processor
  logging/processors.rst
Labels: Logger, Status: Reviewed

#16819 [Security] Access Tokens
  security.rst
  security/access_token.rst
Labels: Security, Status: Reviewed

#17468 [Validator] Removal code-block php-annotation
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#17475 Mark some Symfony CLI feature as experimental
  setup/symfony_server.rst
Labels: Status: Reviewed

#17479 [Symfony CLI] Show usage of new command `symfony proxy:url`
  setup/symfony_server.rst
Labels: Status: Reviewed

#17477 Replace an URL by a URL
  components/dom_crawler.rst
  reference/configuration/framework.rst
Labels: Status: Needs Review

#17476 [Validator] `getRequiredOptions()` is no longer used in the example
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#17487 [Form] Example using `hash_property_path` with `RepeatedType`
  reference/forms/types/password.rst
Labels: Form, Status: Reviewed
