Repository symfony/symfony-docs, pull requests merged in 2022-06, with the labels that each got.

#16838 [HtmlSanitizer] Fix wrong method name
  html_sanitizer.rst
Labels: Status: Reviewed, HtmlSanitizer

#16562 [Serializer] Add information about DateTimeValueResolver
  controller/argument_value_resolver.rst
Labels: Status: Reviewed, Serializer

#16807 Fix options path in composer.json
  components/runtime.rst
Labels: Status: Needs Review, Waiting feedback

#16844 [Security] Fix second Twig path reference to be consistent with the first reference
  security.rst
Labels: Security, Status: Reviewed

#16860 [PHPUnitBridge] Mention the SetUpTearDownTrait deprecation
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Needs Review, deprecation

#16862 [Form] Fix constants
  reference/forms/types/options/rounding_mode.rst.inc
Labels: Form, Status: Reviewed

#16854 Fix development testing examples
  controller/error_pages.rst
Labels: Status: Reviewed

#16863 [Notifier] add caution to URL-encode special characters in Notifier DSNs
  notifier.rst
Labels: Status: Reviewed, Notifier

#16829 Add assets to the documentation
  bundles.rst
Labels: Status: Reviewed

#16834 [Validator] Update validation.rst
  validation.rst
Labels: Validator, Status: Needs Review

#16454 [Routing] Attributes need a routing config, too.
  routing.rst
Labels: Routing, Status: Reviewed

#16869 [Console] Update questionhelper.rst
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Needs Review

#16873 [Doctrine] Add attribute example for Lifecycle Callbacks
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#16871 Update http_kernel_httpkernelinterface.rst
  create_framework/http_kernel_httpkernelinterface.rst
Labels: Status: Needs Review

#16861 [Translation] Update locale.rst
  translation/locale.rst
Labels: Status: Needs Review, Translation

#16879 [Lock] Remove deprecated Docs "Blocking Store" in "lock"
  lock.rst
Labels: Status: Reviewed, Lock

#16880 Add page about configuring the session TTL
  session.rst
  session/configuring_ttl.rst
Labels: Status: Reviewed

#16865 Change recommended way to access array query string parameters
  components/http_foundation.rst
Labels: Status: Needs Review

#16878 [Form] Fix undefined variable
  form/unit_testing.rst
Labels: Form, Status: Reviewed

#16887 remove outdated references to the master branch
  _build/maintainer_guide.rst
  contributing/code/maintenance.rst
  contributing/documentation/format.rst
Labels: Status: Reviewed

#16890 Tighten the rules of what can be merged in patch versions
  contributing/code/maintenance.rst
Labels: Status: Reviewed

#16889 [Cache] Update cache.rst fix small sentence
  cache.rst
Labels: Cache, Status: Needs Review

#16891 Add more information about security issues
  contributing/code/maintenance.rst
  contributing/code/security.rst
Labels: Status: Reviewed

#16717 [Form] Document using TranslatableMessage for label and choice_label
  reference/forms/types/options/choice_label.rst.inc
  reference/forms/types/options/label.rst.inc
Labels: Form, Status: Reviewed

#16898 [Notifier] Mark nexmo-notifier as abandoned
  notifier.rst
Labels: Status: Needs Review, Notifier

#16897 [Notifier] Fix abandoned & broken package names of 3rd-party svcs
  notifier.rst
Labels: Status: Reviewed, Notifier

#16894 [HttpClient] Mention `extra.trace_content` option
  http_client.rst
Labels: Status: Needs Review, HttpClient

#16907 [Validator] Updating ICU documentation link.
  reference/constraints/Locale.rst
Labels: Validator, Status: Reviewed

#16914 Add more clarity about things that cannot be done while working on a bug fix patch
  contributing/code/maintenance.rst
Labels: Status: Reviewed

#16920 [Form] Fix mistake about the reason of the limitation of the timestamp in 32bit systems
  reference/forms/types/options/_date_limitation.rst.inc
Labels: Form, Status: Needs Review

#16896 [Mailer] Rename OhMySMTP to MailPace
  mailer.rst
Labels: Status: Reviewed, Mailer
