Repository symfony/symfony-docs, pull requests merged in 2022-12, with the labels that each got.

#17474 [PropertyInfo] Update property_info.rst
  components/property_info.rst
Labels: Status: Reviewed, PropertyInfo

#17439 [Framework] clearified base_uri behavior with extra examples
  reference/configuration/framework.rst
Labels: Status: Needs Review

#17490 Fix "WordPress" spelling typo
  create_framework/event_dispatcher.rst
Labels: Status: Needs Review

#17489 ValueResolver: fix resolver injection example
  controller/value_resolver.rst
Labels: Status: Reviewed

#17498 [Notifier] Add Twitter bridge
  notifier.rst
Labels: Status: Needs Review, Notifier

#17486 [Notifier] Add Termii bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#17485 [Notifier] Add RingCentral bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#17483 [Notifier] Add Bandwidth bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#17484 [Notifier] Add Plivo bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#15597 [Notifier] Add Documentation for Events
  notifier/events.rst
Labels: Status: Reviewed, Notifier

#17450 [Notifier] Add iSendPro notifier
  notifier.rst
Labels: Status: Reviewed, Notifier

#17500 [Notifier] Add LINE Notify bridge
  notifier.rst
Labels: Status: Needs Review, Notifier

#17497 Fix version in setup command
  setup.rst
Labels: Status: Reviewed

#17496 Fix version in setup command
  setup.rst
Labels: Status: Reviewed

#17504 [Notifier] Fix class
  notifier/events.rst
Labels: Status: Reviewed, Notifier

#17502 [Security] Fix `versionadded` directive
  security.rst
Labels: Security, Status: Reviewed

#17495 [FrameworkBundle] Rename option `catch_all_throwables` to `handle_all_throwables` in documentation
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#17508 [Notifier] Fix merge conflict
  notifier.rst
Labels: Status: Needs Review, Notifier

#17514 [Notifier] Updated chatter documentation with `Telegram::answerCallbackQuery`
  notifier/chatters.rst
Labels: Status: Reviewed, Notifier

#17393 Add documentation about the Doctrine `EntityValueResolver`
  .doctor-rst.yaml
  best_practices.rst
  doctrine.rst
Labels: Status: Needs Review

#17519 Fix typo, change parameter $accesToken to $token
  security/access_token.rst
Labels: Status: Reviewed

#17526 Add comma
  components/validator/resources.rst
Labels: Status: Reviewed

#17517 [Routing] Removing another self-closing HTML slash
  routing.rst
Labels: Routing, Status: Reviewed

#17527 Text corrections
  README.markdown
Labels: Status: Needs Review

#17533 [DependencyInjection] [Service container] Remove example with deprecated Swift Mailer
  service_container/tags.rst
Labels: DependencyInjection, Status: Needs Review

#17521 Adding link to Kernel configuration
  configuration.rst
  routing.rst
Labels: Status: Reviewed

#17522 [Routing] Adding default PHP format
  routing.rst
Labels: Routing, Status: Reviewed, Status: Needs Review

#17537 [Notifier] Add `PushNotificationInterface` to the list of interfaces to customize a notification
  notifier.rst
Labels: Status: Reviewed, Notifier

#17528 Some text improvements
  best_practices.rst
Labels: Status: Needs Review

#17512 [Security] User in expression cannot be "anon"
  security/expressions.rst
Labels: Security, Status: Reviewed

#17530 Add `EntityValueResolver` to the list of built-in value resolvers
  controller/value_resolver.rst
Labels: Status: Reviewed, DoctrineBridge

#17470 [Build] Fix assets in all directories no matter the deep
  _build/build.php
Labels: Status: Reviewed

#17443 Minor deletion
  security/user_providers.rst
Labels: Status: Needs Review

#17436 [Validator] Add `pattern` in `Regex` constraint violations
  reference/constraints/Regex.rst
Labels: Validator, Status: Reviewed

#17418 Document `save_options` of `XmlEncoder`
  components/serializer.rst
Labels: Status: Reviewed

#17541 [Routing] Fix link text
  routing.rst
Labels: Routing, Status: Reviewed

#17478 [Form] Remove paragraph on `legacy_error_messages` config
  forms.rst
Labels: Form, Status: Reviewed

#17549 Add SensitiveParameter attribute in the security hardening list
  contributing/code/security.rst
Labels: Status: Reviewed

#17539 [Serializer] Update link to HAL specification
  serializer.rst
Labels: Serializer, Status: Needs Review

#17548 [Security] Fix "Login Programmatically" code example
  security.rst
Labels: Security, Status: Reviewed

#17554 [Validator] add missing constraint `when`
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#17524 Simplify migration LegacyBridge example
  migration.rst
Labels: Status: Reviewed

#17540 [Workflow] Some minor text optimizations
  workflow.rst
Labels: Status: Needs Review, Workflow

#17552 [Config] Moving the new `env()` syntax upwards, to be shown as the preferred way
  configuration.rst
Labels: Config, Status: Reviewed

#17551 [Security] Fix typo in FQCN of deprecated security class
  security.rst
Labels: Security, Status: Reviewed

#17557 [Doctrine] Update doctrine.rst
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#17453 [Session] Update database.rst
  session/database.rst
Labels: Status: Needs Review, Session

#17149 [Form] Example of customizing `EnumType` labels
  reference/forms/types/enum.rst
Labels: Form, Status: Needs Review

#17561 Symfony CLI: add wildcard local domain information
  setup/symfony_server.rst
Labels: Status: Reviewed

#17560 Symfony CLI: fix config directory path
  frontend/encore/dev-server.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#17567 [Doctrine] Errors on EntityValueResolver exemple
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#17571 [VarDumper] Add support of named arguments to dd() and dump()
  templates.rst
Labels: Status: Reviewed, VarDumper

#17566 Update routing.rst
  routing.rst
Labels: Status: Needs Review

#17572 [HttpKernel] [Controller] Errors on namespace value_resolver
  controller/value_resolver.rst
Labels: Status: Reviewed, HttpKernel

#16859 Use SoapServer headers
  controller/soap_web_service.rst
Labels: Status: Reviewed

#17577 chore: Add missing semicolon
  components/dependency_injection.rst
Labels: Status: Needs Review

#17574 [Messenger] Update the namespace of `InMemoryTransport` class
  messenger.rst
  messenger/custom-transport.rst
Labels: Status: Reviewed, Messenger

#17586 Add a note about using Gmail vs an Email catcher
  mailer.rst
Labels: Status: Reviewed

#17588 Tell composer action is need to regenerate autoload
  components/runtime.rst
  configuration/override_dir_structure.rst
Labels: Status: Reviewed

#17601 fix: typo
  reference/configuration/security.rst
Labels: Status: Reviewed

#17596 Clarifying not about Encore outside of Symfony
  frontend/encore/installation.rst
  frontend/encore/simple-example.rst
Labels: front-end, Status: Needs Review

#17589 Remove reference to 2.x, 3.x, 4.x versions
  components/browser_kit.rst
  components/config/definition.rst
  components/event_dispatcher/container_aware_dispatcher.rst
  components/filesystem/lock_handler.rst
  contributing/code/bc.rst
  profiler.rst
  service_container.rst
Labels: Status: Reviewed

#17600 Replace service name with FQCN class reference
  controller/service.rst
Labels: Status: Reviewed

#17614 Update confusing first class callable syntax
  components/validator.rst
  controller.rst
  form/data_transformers.rst
  form/validation_groups.rst
  http_client.rst
  logging/monolog_exclude_http_codes.rst
  messenger.rst
  testing.rst
Labels: Status: Reviewed

#17616 [Security] Fix invalid yaml for password hashing in test env
  security/passwords.rst
Labels: Security, Status: Reviewed

#17617 Bump Symfony version
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#17618 [Contributing] [Code] Add a step for forking in "Proposing a Change"
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#17613 [HttpKernel] Add option to render Surrogate fragment with absolute URIs
  http_cache/esi.rst
Labels: Status: Reviewed, HttpKernel

#17612 [Mailer] Add a note about how to use the Gmail provider
  mailer.rst
Labels: Status: Reviewed, Mailer

#17621 [HttpKernel] Add an helper to generate fragments URL
  reference/twig_reference.rst
Labels: Status: Reviewed, HttpKernel, TwigBridge

#17620 [Form] inline the constructor
  form/data_transformers.rst
Labels: Form, Status: Needs Review

#17623 [Mailer] Add a way to change the Bus transport dynamically
  mailer.rst
Labels: Status: Reviewed, Mailer

#17624 [Filesystem] fix tilde not rendered in filesystem doc
  components/filesystem.rst
Labels: Status: Reviewed, Filesystem

#17625 [Form] Fix choice_label
  reference/forms/types/enum.rst
Labels: Form, Status: Reviewed

#17562 Symfony CLI: document the .symfony.local.yaml config file
  setup/symfony_server.rst
Labels: Status: Needs Review

#17631 Profiler: Profiles cleanup as of 6.3
  console/calling_commands.rst
  profiler.rst
Labels: Status: Reviewed

#17633 [Mailer] Add html_to_text_converter config docs
  mailer.rst
  reference/configuration/twig.rst
Labels: Status: Reviewed, Mailer

#17627 [Notifier] do not display todo doc on site
  notifier.rst
Labels: Status: Reviewed, Notifier

#17622 [Translation] Translatable parameters
  translation.rst
Labels: Status: Reviewed, Translation
