Repository symfony/symfony-docs, pull requests merged in 2023-11, with the labels that each got.

#19104 [Question helper] Add more accuracy on possible answers
  components/console/helpers/questionhelper.rst
Labels: Status: Needs Review

#19101 Add sleep to observe the changes in the terminal when executing the code
  console.rst
Labels: Status: Reviewed

#19113 [Symfony CLI] Document the new docker_compose option
  setup/symfony_server.rst
Labels: Status: Reviewed

#19115 [Cache] Remove invalid info about cache pool services
  cache.rst
Labels: Status: Reviewed, Cache

#19114 [Options Resolver] Using placeholder to use dynamic parameter
  components/options_resolver.rst
Labels: Status: Reviewed

#19112 [Validator] Bring precisions on Valid constraint's groups
  reference/constraints/Valid.rst
Labels: Validator, Status: Needs Review

#19116 [Cache] Fix PdoAdapter examples
  cache.rst
Labels: Status: Reviewed, Cache

#19118 [HttpFoundation] Cookies Having Independent Partitioned State (CHIPS)
  components/http_foundation.rst
Labels: HttpFoundation, Status: Needs Review

#19121 hint for mapping request payload error messages
  controller.rst
Labels: Status: Reviewed

#19110 Add info about feature freeze period
  contributing/code/pull_requests.rst
Labels: Status: Reviewed, Waiting team decision

#19124 Added missing link for label_html in some form types
  reference/forms/types/checkbox.rst
  reference/forms/types/choice.rst
  reference/forms/types/collection.rst
  reference/forms/types/color.rst
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/email.rst
  reference/forms/types/entity.rst
  reference/forms/types/enum.rst
  reference/forms/types/file.rst
  reference/forms/types/integer.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
  reference/forms/types/money.rst
  reference/forms/types/number.rst
  reference/forms/types/password.rst
  reference/forms/types/percent.rst
  reference/forms/types/radio.rst
  reference/forms/types/range.rst
  reference/forms/types/search.rst
  reference/forms/types/tel.rst
  reference/forms/types/text.rst
  reference/forms/types/textarea.rst
  reference/forms/types/timezone.rst
  reference/forms/types/ulid.rst
  reference/forms/types/url.rst
  reference/forms/types/uuid.rst
Labels: Status: Needs Review

#19127 [Setup] Fix Platform.sh docs URL for Symfony technical docs
  setup/symfony_server.rst
Labels: Status: Reviewed

#19111 [AssetMapper] Remove `--download` option that has become obsolete
  frontend/asset_mapper.rst
Labels: Status: Needs Review, AssetMapper

#19120 [Messenger] Improve handler options description
  messenger.rst
Labels: Status: Reviewed, Messenger

#19105 [Console] [Question helper] Add more accuracy from a list of answers
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Needs Review

#19107 [Filesystem] remove unused makeRelative example
  components/filesystem.rst
Labels: Status: Reviewed, Filesystem

#19087 Update performance.rst to use $container->getParameterBag()
  performance.rst
Labels: Status: Reviewed

#19106 [Console] [Question helper] Add more accuracy on multiple choices answers
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Reviewed

#19133 [Messenger] Fix table indentation
  messenger.rst
Labels: Status: Needs Review, Messenger

#19129 [Workflow] Mention the `workflow.marking_store.service` option
  workflow.rst
Labels: Status: Reviewed, Workflow

#19099 [Messenger] Added message serializer section
  messenger.rst
Labels: Status: Reviewed, Messenger

#19132 [VarExporter] Deprecate per-property lazy-initializers
  components/var_exporter.rst
Labels: Status: Reviewed, VarExporter

#19143 [Reference] Form empty data option - Update repetitive text
  reference/forms/types/options/empty_data_description.rst.inc
Labels: Status: Reviewed

#19142 [Reference] Form EntityType - Add labels for some links
  reference/forms/types/entity.rst
Labels: Status: Needs Review

#19151 [AssetMapper] Minor syntax fix
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19152 [Form] Deprecate using `UrlType` without setting `default_protocol`
  reference/forms/types/url.rst
Labels: Form, Status: Reviewed

#19155 Clean deprecated directives
  components/http_foundation.rst
  components/var_exporter.rst
Labels: Status: Needs Review

#19158 Update doctrine.rst
  doctrine.rst
Labels: Status: Reviewed

#17979 [Serializer] Add feature description for `AbstractNormalizer::REQUIRE_ALL_PROPERTIES` context option
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#19159 Add note about indexing config classes
  configuration.rst
Labels: Status: Reviewed

#19149 [String] New locale aware casing methods
  components/string.rst
Labels: Status: Reviewed, String

#19150 [DependencyInjection] Add `urlencode` function to `EnvVarProcessor`
  configuration/env_var_processors.rst
  doctrine.rst
Labels: DependencyInjection, Status: Reviewed

#19134 [Testing] tip to not follow redirects when testing mailer
  mailer.rst
Labels: Testing, Status: Reviewed

#19044 [Console] link Symfony default style doc page on coloring doc page
  console/coloring.rst
Labels: Status: Needs Review

#19160 [AssetMapper] Renaming W3C to HTML5...
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19161 [AssetMapper] Minor formating
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#18744 [Validator] Advanced Validation Group Provider
  validation/sequence_provider.rst
Labels: Validator, Status: Reviewed

#19168 fix(doc): typo
  security/remember_me.rst
Labels: Status: Reviewed

#19167 HttpKernelInterface::handle parameter and return types
  create_framework/http_kernel_httpkernelinterface.rst
Labels: Status: Reviewed

#19166 docs: fix typo
  frontend/asset_mapper.rst
Labels: Status: Reviewed

#19162 Typo
  frontend/asset_mapper.rst
Labels: Status: Reviewed

#19154 [DependencyInjection] Prepend extension config with ContainerConfigurator
  bundles/prepend_extension.rst
Labels: DependencyInjection, Status: Reviewed

#19173 Update license.rst
  contributing/code/license.rst
Labels: Status: Needs Review

#19170 [HttpClient] Symfony HTTP Client documentation
  http_client.rst
Labels: Status: Reviewed, HttpClient

#19172 Add links label in service container page
  service_container.rst
Labels: Status: Reviewed, Status: Needs Review

#19171 Remove "--unpack" option from setup.rst
  setup.rst
Labels: Status: Needs Review

#19175 [HttpKernel] Introduce `ExceptionEvent::isKernelTerminating()`
  components/http_kernel.rst
Labels: Status: Reviewed, HttpKernel

#19188 [AssetMapper] Exclude dot files
  frontend/asset_mapper.rst
Labels: Status: Needs Review, AssetMapper

#19194 fix: serializer includes only accessible attributes by default
  components/serializer.rst
Labels: Status: Reviewed

#19195 [Messenger] Update docs for Redis transport about TLS support
  messenger.rst
Labels: Status: Reviewed, Messenger

#19192 Adding precision on how to define attributes on the root node for the XML Encoder
  components/serializer.rst
Labels: Status: Needs Review

#19189 AssetMapper 6.4 docs
  frontend.rst
  frontend/asset_mapper.rst
  frontend/encore/babel.rst
  frontend/encore/bootstrap.rst
  frontend/encore/cdn.rst
  frontend/encore/code-splitting.rst
  frontend/encore/copy-files.rst
  frontend/encore/css-preprocessors.rst
  frontend/encore/custom-loaders-plugins.rst
  frontend/encore/faq.rst
  frontend/encore/index.rst
  frontend/encore/legacy-applications.rst
  frontend/encore/postcss.rst
  frontend/encore/reactjs.rst
  frontend/encore/server-data.rst
  frontend/encore/sourcemaps.rst
  frontend/encore/split-chunks.rst
  frontend/encore/typescript.rst
  frontend/encore/url-loader.rst
  frontend/encore/versioning.rst
  frontend/encore/vuejs.rst
Labels: Status: Reviewed

#19198 Fix deprecations return void
  reference/forms/types/options/choice_filter.rst.inc
Labels: Status: Reviewed

#19200 fix type of `$response->headers->set()`
  profiler.rst
Labels: Status: Reviewed
