Repository symfony/symfony-docs, pull requests merged in 2023-06, with the labels that each got.

#18356 Add property types and return types in a few places
  bundles/best_practices.rst
  bundles/configuration.rst
  bundles/prepend_extension.rst
  cache.rst
  components/dependency_injection.rst
  components/dependency_injection/_imports-parameters-note.rst.inc
  components/expression_language.rst
  components/property_access.rst
  components/serializer.rst
  components/var_dumper.rst
  configuration.rst
  configuration/env_var_processors.rst
  configuration/micro_kernel_trait.rst
  configuration/override_dir_structure.rst
  configuration/secrets.rst
  controller/error_pages.rst
  controller/upload_file.rst
  controller/value_resolver.rst
  deployment/proxies.rst
  doctrine.rst
  doctrine/events.rst
  event_dispatcher.rst
  form/embedded.rst
  frontend/custom_version_strategy.rst
  html_sanitizer.rst
  http_cache/cache_invalidation.rst
  http_cache/esi.rst
  http_cache/ssi.rst
  http_client.rst
  lock.rst
  mailer.rst
  messenger.rst
  messenger/custom-transport.rst
  messenger/multiple_buses.rst
  notifier.rst
  rate_limiter.rst
  reference/configuration/framework.rst
  reference/constraints/Compound.rst
  reference/constraints/UniqueEntity.rst
  reference/formats/expression_language.rst
  routing.rst
  routing/custom_route_loader.rst
  security.rst
  security/access_control.rst
  security/csrf.rst
  serializer.rst
  service_container.rst
  service_container/injection_types.rst
  service_container/service_closures.rst
  service_container/tags.rst
  session.rst
  templates.rst
  testing.rst
  testing/profiling.rst
  translation.rst
  validation.rst
  validation/translations.rst
  workflow.rst
  workflow/dumping-workflows.rst
  workflow/workflow-and-state-machine.rst
Labels: Status: Reviewed

#18361 Fix an RST syntax issue of some missing headline
  reference/twig_reference.rst
Labels: Status: Needs Review

#18358 [Mailer] Update mailer.rst
  mailer.rst
Labels: Status: Reviewed, Mailer

#18363 Use DOCtor-RST 1.47.2
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#18365 [DependencyInjection] Fix broken reference to `Exclude` attribute
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#18366 Update flex_private_recipes.rst
  setup/flex_private_recipes.rst
Labels: Status: Reviewed

#18372 Symfony 6.3 documentation changes
  setup.rst
Labels: Status: Needs Review

#18371 Symfony 6.4 documentation changes
  setup.rst
Labels: Status: Reviewed

#18364 [Cache] Fix redis adapter option type
  components/cache/adapters/redis_adapter.rst
Labels: Status: Reviewed, Cache

#18369 [PHPUnitBridge] Fix missing backtick
  components/phpunit_bridge.rst
Labels: Status: Reviewed, PHPUnitBridge

#18360 Upgrade the minimum PHP version requirement for Symfony 7.0
  setup.rst
Labels: Status: Needs Review

#18348 [DependencyInjection] Add support for casting callables into single-method interfaces
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#18375 [Lock] Add Redis Secure DSN example
  lock.rst
Labels: Status: Reviewed, Lock

#18070 [DependencyInjection] Add the `constructor` option to service definition
  service_container/factories.rst
Labels: DependencyInjection, Status: Needs Review

#18244 [Logger] Add missing type monolog config (php config)
  logging/monolog_email.rst
Labels: Logger, Status: Needs Review

#17520 Changing versionadded 5.1 to note
  configuration.rst
Labels: Status: Needs Review

#17409 [Doctrine] Update multiple_entity_managers.rst
  doctrine/multiple_entity_managers.rst
Labels: Doctrine, Status: Reviewed

#17301 [HttpFoundation] Add documentation for `StreamedJsonResponse`
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#18387 [Mailer] Document the optional HttpClient dependency
  mailer.rst
Labels: Status: Reviewed, Mailer

#18382 [Mailer] Improve DSN formats table
  mailer.rst
Labels: Status: Needs Review, Mailer

#18384 Fix Cmder broken link
  contributing/code/tests.rst
Labels: Status: Reviewed

#18385 [AssetMapper] Update asset_mapper.rst
  frontend/asset_mapper.rst
Labels: Status: Reviewed, front-end, AssetMapper

#17785 [VarExporter] Add `LazyGhostTrait` and `LazyProxyTrait` documentation
  components/var_exporter.rst
Labels: Status: Reviewed, VarExporter

#18388 Update value_resolver.rst
  controller/value_resolver.rst
Labels: Status: Needs Review

#18288 [HttpClient] Add `max_retries` setting docs on the `RetryableHttpClient`
  http_client.rst
Labels: Status: Needs Review, HttpClient

#18396 [HttpClient] Fix versionadded of `max_retries` option of `RetryableHttpClient`
  http_client.rst
Labels: Status: Reviewed, HttpClient

#18399 [PropertyInfo] Fix PhpStanExtractor added version
  components/property_info.rst
Labels: Status: Reviewed, PropertyInfo

#18193 [Form] Adding more details on `action` and `method`
  forms.rst
Labels: Form, Status: Reviewed

#18411 [Bundles] Update wording bundles.rst
  bundles.rst
Labels: Status: Needs Review, Bundles

#18410 [Security] Update security.rst
  security.rst
Labels: Security, Status: Needs Review

#18407 [Security] Update voters.rst
  security/voters.rst
Labels: Security, Status: Reviewed

#18409 [Security] Update voters.rst
  security/voters.rst
Labels: Security, Status: Reviewed

#18391 [Serializer] Document Serializer getSupportedTypes method
  serializer/custom_normalizer.rst
Labels: Status: Reviewed, Serializer

#18415 [Process] Remove wrong note about `create_new_console` option
  components/process.rst
Labels: Process, Status: Reviewed

#18416 [DependencyInjection] fix(typo): Update service_container.rst (Manually Wiring Arguments part)
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#18403 [Console] Call command with options without value
  console/command_in_controller.rst
Labels: Console, Status: Reviewed

#18381 [UX] Centralizing docs around StimulusBundle
  _build/redirection_map
  frontend.rst
  frontend/_ux-libraries.rst.inc
  frontend/encore/simple-example.rst
  frontend/ux.rst
  reference/forms/types/map.rst.inc
Labels: Status: Reviewed, front-end

#17532 [FrameworkBundle][Messenger] Extend note on routing with support for wildcard routes
  messenger.rst
Labels: Status: Reviewed, FrameworkBundle, Messenger

#18379 [HtmlSanitizer] Information about subdomains of allowed hosts (they also match)
  html_sanitizer.rst
Labels: Status: Reviewed, HtmlSanitizer

#18228 [Form] Update dynamic_form_modification.rst
  form/dynamic_form_modification.rst
Labels: Form, Status: Reviewed

#17763 [HttpKernel] Document `#[ValueResolver]` and `#[AsTargetedValueResolver]`
  controller/value_resolver.rst
  reference/attributes.rst
Labels: Status: Reviewed, HttpKernel

#17267 Add hint about variables_order ini setting required
  configuration.rst
Labels: Status: Needs Review, Waiting feedback

#18418 [DependencyInjection] Fix xml example for defaut-index-name for tagged service provider
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17404 [Routing] Update ignoreAttributes description
  routing.rst
Labels: Routing, Status: Reviewed

#17179 Removing 2 distracting scenarios
  rate_limiter.rst
Labels: Status: Needs Review

#18422 [Validator] Give more details to the Password Strength
  reference/constraints/PasswordStrength.rst
Labels: Validator, Status: Reviewed

#18423 [VarExporter] Updating class name of lazy ghost interface
  service_container/lazy_services.rst
Labels: Status: Needs Review, VarExporter

#18345 [Notifier] Add Novu Bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#18426 [Security] Remove the `security.remember_me_aware` tag
  reference/dic_tags.rst
Labels: Security, Status: Reviewed

#18424 [Doctrine] Warn about DBAL 4.x changes for MariaDB connection
  reference/configuration/doctrine.rst
Labels: Doctrine, Status: Reviewed

#18430 Remove PHPUnit 5.3 references
  create_framework/unit_testing.rst
  testing/database.rst
Labels: Status: Reviewed

#18429 Fix `doctrine/dbal` deprecation using `Statement::executeQuery`
  doctrine.rst
Labels: Status: Reviewed

#18431 Remove symfony 5.x version references
  messenger/multiple_buses.rst
  reference/configuration/framework.rst
  service_container/tags.rst
  translation.rst
Labels: Status: Reviewed

#18434 [Yaml] Typo in yaml component
  components/yaml.rst
Labels: Status: Reviewed, Yaml

#18433 Removed some occurrences of explicitly talking about "PHP 8 attributes"
  console.rst
  service_container.rst
  service_container/calls.rst
  service_container/tags.rst
Labels: Status: Reviewed

#18417 [Translation] Mention that `default_locale` is used as the default for `framework.translator.fallbacks`
  translation.rst
Labels: Status: Reviewed, Translation

#18406 [HttpKernel] Deprecate `ContainerAwareInterface` and `ContainerAwareTrait`
  components/http_kernel.rst
Labels: Status: Reviewed, HttpKernel

#18263 Add Redlink docs
  notifier.rst
Labels: Status: Reviewed

#18441 [DependencyInjection] Remove not implemented behavior
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#18438 [Console] Add SignalMap to map signal value to its name
  components/console/events.rst
Labels: Console, Status: Reviewed

#18445 Update cache.rst
  cache.rst
Labels: Status: Needs Review

#18446 [Validator] Allow single constraint to be passed to the constraints option of the `When` constraint
  reference/constraints/When.rst
Labels: Validator, Status: Reviewed

#18447 [Validator] Allow single integer for the `versions` option of the `Uuid` constraint
  reference/constraints/Uuid.rst
Labels: Validator, Status: Reviewed

#18451 Fix return type on custom authenticators
  security/custom_authenticator.rst
Labels: Status: Reviewed

#18453 [Validator] Remove incomplete duplicate
  reference/constraints/UniqueEntity.rst
Labels: Validator, Status: Reviewed

#18452 Mention Rector in the upgrading articles
  setup/upgrade_major.rst
  setup/upgrade_minor.rst
Labels: Status: Reviewed

#18454 [Tests] Update PHPUnit documentation links
  best_practices.rst
  components/phpunit_bridge.rst
  create_framework/unit_testing.rst
  form/unit_testing.rst
  testing.rst
Labels: Status: Reviewed

#18459 [AssetMapper] Adding notes about global variables and tailwind-bundle
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#18464 [DependencyInjection] Add defined prefix for env var processor
  configuration/env_var_processors.rst
Labels: DependencyInjection, Status: Reviewed

#18465 fix: small typo
  configuration/env_var_processors.rst
Labels: Status: Needs Review

#18467 [Routing] Update routing.rst
  routing.rst
Labels: Routing, Status: Needs Review

#18468 [Form][Validator] Add new unique entity validation on form type
  reference/constraints/UniqueEntity.rst
Labels: Form, Validator, Status: Reviewed

#18475 [Form] Document a deprecation related to `model_timezone`
  reference/forms/types/options/model_timezone.rst.inc
Labels: Form, Status: Reviewed
