Repository symfony/symfony-docs, pull requests merged in 2023-01, with the labels that each got.

#17637 [Intl] Add a special locale to strip emojis
  components/string.rst
Labels: Status: Reviewed, Intl

#17640 [DomCrawler][FrameworkBundle] Add assertSelectorCount
  testing.rst
Labels: Status: Reviewed, DomCrawler, FrameworkBundle

#17635 [Mailer] Document MessageEvent::reject()
  mailer.rst
Labels: Status: Reviewed, Mailer

#17641 [Security] Prevent unneeded implementation of `PasswordHasherAwareInterface` when migrating passwords
  security/passwords.rst
Labels: Security, Status: Reviewed

#17615 [Yaml] Add flag to dump numeric key as string
  components/yaml.rst
Labels: Status: Reviewed, Yaml

#17638 [Console] Add placeholder formatters per ProgressBar instance
  components/console/helpers/progressbar.rst
Labels: Console, Status: Reviewed

#17626 [DependencyInjection] Add env and param parameters for Autowire attribute
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#17644 [Doctrine] Adds information on AsEntityListener attribute to the Doctrine event …
  doctrine/events.rst
Labels: Doctrine, Status: Needs Review

#17645 [DependencyInjection] Add exclude to TaggedIterator and TaggedLocator
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17660 [HttpFoundation] add ParameterBag::getEnum()
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#17661 We need to use AsEntityListener instead of AsDoctrineListener
  doctrine/events.rst
Labels: Status: Needs Review

#17653 Update getContainerExtension()
  bundles/extension.rst
Labels: Status: Reviewed

#17651 [FrameworkBundle] Add support for route attributes in kernel controller methods
  configuration/micro_kernel_trait.rst
Labels: Status: Reviewed, FrameworkBundle

#17662 [DependencyInjection] Autowire arguments using the #[TaggedLocator] attribute
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#17663 Fix build by correcting a typo
  service_container/service_subscribers_locators.rst
Labels: Status: Needs Review

#17664 Standardize the name of the container configurator variable
  bundles/best_practices.rst
  bundles/prepend_extension.rst
  cache.rst
  components/dependency_injection.rst
  components/dependency_injection/_imports-parameters-note.rst.inc
  components/http_foundation/session_configuration.rst
  components/serializer.rst
  components/uid.rst
  components/var_dumper.rst
  configuration.rst
  configuration/micro_kernel_trait.rst
  configuration/multiple_kernels.rst
  controller/argument_value_resolver.rst
  controller/upload_file.rst
  doctrine/events.rst
  event_dispatcher.rst
  frontend/custom_version_strategy.rst
  messenger/multiple_buses.rst
  profiler/data_collector.rst
  reference/dic_tags.rst
  routing/custom_route_loader.rst
  security.rst
  service_container.rst
  service_container/alias_private.rst
  service_container/autowiring.rst
  service_container/calls.rst
  service_container/configurators.rst
  service_container/expression_language.rst
  service_container/factories.rst
  service_container/import.rst
  service_container/injection_types.rst
  service_container/lazy_services.rst
  service_container/optional_dependencies.rst
  service_container/parent_services.rst
  service_container/service_decoration.rst
  service_container/service_subscribers_locators.rst
  service_container/shared.rst
  service_container/synthetic_services.rst
  service_container/tags.rst
  session.rst
  session/database.rst
  testing.rst
Labels: Status: Reviewed

#17649 Sessions refactoring
  _build/redirection_map
  components/http_foundation.rst
  components/http_foundation/session_configuration.rst
  components/http_foundation/session_php_bridge.rst
  components/http_foundation/session_testing.rst
  components/http_foundation/sessions.rst
  controller.rst
  doctrine.rst
  reference/configuration/framework.rst
  security/impersonating_user.rst
  session.rst
  session/database.rst
  session/locale_sticky_session.rst
  session/php_bridge.rst
  session/proxy_examples.rst
  translation.rst
  translation/locale.rst
Labels: Status: Reviewed

#17672 [Config] More minor rewordings
  configuration.rst
Labels: Config, Status: Reviewed

#17677 [Validator] Update constraint Type types
  reference/constraints/Type.rst
Labels: Validator, Status: Reviewed

#17674 [DependencyInjection] Emphasizing *NOT* working
  components/dependency_injection/_imports-parameters-note.rst.inc
Labels: DependencyInjection, Status: Reviewed

#17654 [DependencyInjection] 6.0 [autowiring] remove mention to @required
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#17655 [DependencyInjection] 6.0 [injection_types] remove mention of @required in service_container
  service_container/injection_types.rst
Labels: DependencyInjection, Status: Reviewed

#17678 Standardize the name of the container configurator variable 6.0
  session.rst
Labels: Status: Reviewed

#17679 Standardize the name of the container configurator variable 6.1
  bundles/configuration.rst
  bundles/extension.rst
  bundles/prepend_extension.rst
  configuration/micro_kernel_trait.rst
  notifier.rst
  service_container/factories.rst
  service_container/tags.rst
Labels: Status: Reviewed

#17682 Standardize the name of the container configurator variable 6.2
  configuration/env_var_processors.rst
  security/user_checkers.rst
Labels: Status: Reviewed

#17683 Standardize the name of the container builder variable 5.4
  bundles/configuration.rst
  bundles/extension.rst
  bundles/prepend_extension.rst
  cache.rst
  components/dependency_injection/compilation.rst
  configuration/env_var_processors.rst
  configuration/using_parameters_in_dic.rst
  event_dispatcher.rst
  security.rst
  security/access_control.rst
  service_container/compiler_passes.rst
  service_container/service_subscribers_locators.rst
  service_container/tags.rst
Labels: Status: Reviewed

#17684 [Doctrine] Include % as a Special Character in URIs
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#17689 [Doctrine] Improve caution resolve doctrine example
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#17690 [Uid] Add `UuidFactory` and `UlidFactory` mentions
  components/uid.rst
Labels: Status: Reviewed, Uid

#17687 Standardize the name of the container builder variable 6.1
  bundles/configuration.rst
  bundles/extension.rst
  bundles/prepend_extension.rst
  configuration/micro_kernel_trait.rst
Labels: Status: Reviewed

#17692 [HttpKernel] Allow using #[WithHttpStatus] for setting status code and headers
  reference/configuration/framework.rst
Labels: Status: Reviewed, HttpKernel

#17699 [Uid] Use constructor property promotion for UuidFactory and UlidFactory examples
  components/uid.rst
Labels: Status: Reviewed, Uid

#17696 [DependencyInjection] Add `#[Target]` documentation
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#17694 [DependencyInjection] Add `#[AsTaggedItem]` documentation
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17688 [FrameworkBundle] Add `extra` attribute for HttpClient Configuration
  http_client.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#17702 Enable `ensure_link_definition_contains_valid_url` doctor-rst rule
  .doctor-rst.yaml
Labels: Status: Reviewed

#17705 Fix: Typos
  service_container/service_subscribers_locators.rst
Labels: Status: Needs Review

#17695 [DependencyInjection] Add `#[Autoconfigure]` and `#[AutoconfigureTag]` documentation
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17632 [ExpressionLanguage] Add `enum` expression function
  components/expression_language/syntax.rst
Labels: Status: Reviewed, ExpressionLanguage

#17680 [Yaml] Merge YAML docs into one
  components/yaml.rst
  components/yaml/yaml_format.rst
  configuration.rst
Labels: Yaml, Status: Needs Review

#17671 Minor rewordings
  configuration.rst
Labels: Status: Reviewed

#17667 [HttpKernel] Add `#[WithLogLevel]` attribute
  reference/configuration/framework.rst
Labels: Status: Reviewed, HttpKernel

#17685 [EventDispatcher] Allow to omit the event name when registering listeners
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#17455 Update `framework.exceptions` XML and PHP configuration examples
  reference/configuration/framework.rst
Labels: Status: Reviewed

#17706 Add a section about how to add an argument to a method without breaking BC
  contributing/code/bc.rst
Labels: Status: Needs Review

#17575 Deprecate the proxy-manager package
  service_container/lazy_services.rst
Labels: Status: Needs Review

#17711 Remove obsolete comments about Twig versions
  components/form.rst
  reference/configuration/twig.rst
  templating/twig_extension.rst
Labels: Status: Reviewed

#17710 Fix Symfony versions when needed
  README.markdown
  contributing/code/pull_requests.rst
  contributing/code/tests.rst
  contributing/community/releases.rst
Labels: Status: Reviewed

#17709 [DependencyInjection] Exclude referencing service (self) in `TaggedIterator`
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17712 Bump versions on the build script
  _build/build.php
  _build/composer.json
  _build/composer.lock
Labels: Status: Reviewed

#17720 [Serializer] Fix default XmlVersion used by XmlEncoder
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#17721 [Validator] Add `getConstraint()` method to `ConstraintViolationInterface`
  validation.rst
Labels: Validator, Status: Reviewed

#17724 [ExpressionLanguage] Merge docs about ExpresssionLanguage
  _build/redirection_map
  components/expression_language.rst
  components/expression_language/ast.rst
  components/expression_language/caching.rst
  components/expression_language/extending.rst
  components/expression_language/syntax.rst
  reference/constraints/Expression.rst
  routing.rst
  security/expressions.rst
  service_container/expression_language.rst
Labels: Status: Reviewed, ExpressionLanguage

#17719 [Notifier] add notification assertion in notifier doc
  notifier.rst
Labels: Status: Reviewed, Notifier

#17729 [DomCrawler] Adapt docs for `Crawler::innerText()`
  components/dom_crawler.rst
Labels: Status: Reviewed, DomCrawler

#17728 Fix `empty_data` option description of `TextareaType`
  reference/forms/types/textarea.rst
Labels: Form, Status: Reviewed

#17727 [Mailer] update mailer testing documentation
  mailer.rst
Labels: Status: Reviewed, Mailer

#17716 Use when@dev insteadof dev/mailer.yaml
  mailer.rst
Labels: Status: Reviewed

#17730 [Mailer] remove `QueuingMessageEvent`
  mailer.rst
Labels: Status: Reviewed, Mailer

#17675 [Config] Shortening the list to make it more scanable
  configuration.rst
Labels: Config, Status: Reviewed

#17582 [Security] X509 `user_identifier` parameter
  reference/configuration/security.rst
  security.rst
Labels: Security, Status: Reviewed

#17736 [Form] Add missing imports in unmapped fields example
  forms.rst
Labels: Form, Status: Reviewed

#17739 [Notifier] Fix typo OneSignal DSN
  notifier.rst
Labels: Status: Reviewed, Notifier

#17745 [Config] Fix blank space typo
  configuration.rst
Labels: Config, Status: Reviewed

#17748 [DependencyInjection] Autowire union and intersection types
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#17747 [DependencyInjection] Complete examples with `#[TaggedIterator]` and `#[TaggedLocator]` attributes
  service_container/service_subscribers_locators.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17742 [Monolog] List available built-in formatters
  logging/formatter.rst
Labels: Status: Reviewed

#17738 [Notifier] Add new Symfony Notifier for PagerDuty
  notifier.rst
Labels: Status: Reviewed, Notifier

#17752 [DependencyInjection] Fix missing quotes on service subscribers
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Needs Review

#17753 Fix: Build
  service_container/factories.rst
  translation.rst
Labels: Status: Needs Review

#17754 Fix: Build
  configuration/env_var_processors.rst
  controller/value_resolver.rst
  serializer.rst
Labels: Status: Needs Review

#17750 [DependencyInjection] Enable deprecating parameters
  components/dependency_injection/compilation.rst
Labels: DependencyInjection, Status: Needs Review

#17758 Fix the SymfonyCloud name
  configuration.rst
  setup/symfony_server.rst
Labels: Status: Needs Review

#17761 move the documentation of the match option to the right place
  reference/constraints/Choice.rst
  reference/forms/types/choice.rst
Labels: Status: Reviewed

#17760 [Form] Reorder imports alphabetically
  components/form.rst
Labels: Form, Status: Reviewed

#17734 [FrameworkBundle] Allow setting private services with the test container
  testing.rst
Labels: Status: Needs Review, FrameworkBundle

#17759 [Console] Add inline command register example
  components/console.rst
Labels: Console, Status: Reviewed

#17744 Clean doctor-rst whitelist configuration
  .doctor-rst.yaml
Labels: Status: Needs Review

#17766 Remove extra space before parenthesis
  bundles/configuration.rst
Labels: Status: Reviewed

#17749 Add note about `ResponseInterface::toStream()`
  http_client.rst
Labels: Status: Needs Review

#17756 [HttpClient] Add withOptions() to HttplugClient and Psr18Client
  http_client.rst
Labels: Status: Reviewed, HttpClient

#17767 [Validator] Remove superfluous `versionadded`
  reference/constraints/Length.rst
Labels: Validator, Status: Reviewed

#17757 [Clock] Add `ClockAwareTrait` to help write time-sensitive classes
  components/clock.rst
Labels: Status: Needs Review, Clock

#17770 [Validator] Remove annotations from `exactly` option of Length constraint
  reference/constraints/Length.rst
Labels: Validator, Status: Reviewed

#17769 [HttpKernel] Remove old caution from Symony <4
  components/http_kernel.rst
Labels: Status: Reviewed, HttpKernel

#17774 [Translation] fix wrong information
  translation.rst
Labels: Status: Reviewed, Translation

#17768 [Contributing] Mention `php-symfony` and `php-standalone` markup formats
  contributing/documentation/format.rst
Labels: Status: Reviewed

#17772 [Clock] Fix `ClockAwareTrait` usage
  components/clock.rst
Labels: Status: Reviewed, Clock

#17771 [Clock] Add `ClockSensitiveTrait` to help write time-sensitive tests
  components/clock.rst
Labels: Status: Reviewed, Clock

#17779 [Clock] Add `Clock` class and `now()` function documentation
  components/clock.rst
Labels: Status: Reviewed, Clock

#17780 [Clock][HttpKernel] [Controller] Mention the use of the Clock component in `DateTimeValueResolver`
  controller/value_resolver.rst
Labels: Status: Reviewed, HttpKernel, Clock

#17788 [Form] Fix alphabetical order of imports
  components/form.rst
Labels: Form, Status: Reviewed

#17784 [DependencyInjection] [LazyServices] Add `#[Autoconfigure]` attribute mention
  service_container/lazy_services.rst
Labels: DependencyInjection, Status: Reviewed

#17794 [docker] fix composer `extra` variable name
  setup/docker.rst
Labels: Status: Reviewed

#17723 [Notifier] Notifier docs merge
  _build/redirection_map
  notifier.rst
  notifier/chatters.rst
  notifier/discord.rst
  notifier/events.rst
  notifier/slack.rst
  notifier/teams.rst
  notifier/telegram.rst
  notifier/texters.rst
Labels: Status: Reviewed, Notifier

#17797 [ExpressionLanguage] Deprecate loose comparisons when using the "in" operator
  components/expression_language.rst
Labels: Status: Reviewed, ExpressionLanguage

#17790 [Logging] Mention `#[AsMonologProcessor]`
  logging/processors.rst
Labels: Status: Reviewed

#17793 [Security] Replacing deprecated role: IS_AUTHENTICATED_ANONYMOUSLY
  security/access_control.rst
Labels: Security, Status: Reviewed

#17802 [Refs] Fixed refs displaying incorrectly
  components/lock.rst
  contributing/code/core_team.rst
Labels: Status: Reviewed

#17798 update CI intro
  contributing/code/tests.rst
Labels: Status: Reviewed

#17804 Remove SOAP docs
  controller/soap_web_service.rst
Labels: Status: Reviewed

#17805 [Console] Remove exit() call in last SignalHandler
  components/console/events.rst
Labels: Console, Status: Needs Review

#17808 [Config] [Configuration] fixed list markup
  configuration.rst
Labels: Config, Status: Needs Review

#17807 [Standards] Freeze contractions decision in documentation standards
  contributing/documentation/standards.rst
Labels: Status: Reviewed

#17811 [Config] [Misc] Fixed remaining `HEAD`
  configuration.rst
  contributing/code/pull_requests.rst
Labels: Config, Status: Reviewed

#17799 [DependencyInjection] Update tags.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Needs Review

#17815 [Translation] Translation docs consolidation
  _build/redirection_map
  translation.rst
  translation/debug.rst
  translation/lint.rst
  translation/locale.rst
Labels: Status: Reviewed, Translation

#17816 [Validator] Replace warning with caution for consistency
  reference/constraints/Callback.rst
Labels: Validator, Status: Reviewed

#17817 Format syntaxes reference
  _build/redirection_map
  components/expression_language.rst
  components/yaml.rst
  configuration.rst
  reference/constraints/Expression.rst
  reference/formats/expression_language.rst
  reference/formats/message_format.rst
  reference/formats/xliff.rst
  reference/formats/yaml.rst
  reference/map.rst.inc
  routing.rst
  security/expressions.rst
  service_container/expression_language.rst
  translation.rst
Labels: Status: Reviewed

#17818 [EventDispatcher] Consolidation event dispatcher docs
  _build/redirection_map
  components/event_dispatcher.rst
  event_dispatcher.rst
  event_dispatcher/before_after_filters.rst
  event_dispatcher/method_behavior.rst
Labels: EventDispatcher, Status: Reviewed

#17819 [Notifier] Fix small typo in notifier.rst
  notifier.rst
Labels: Status: Needs Review, Notifier

#17810 [DependencyInjection] Introduce build parameters
  configuration.rst
Labels: DependencyInjection, Status: Needs Review

#17821 [Doctrine] Update example to match actual make::entity output
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#17806 [Standards] Add `Attribute` format and formats for Code Examples
  contributing/documentation/standards.rst
Labels: Status: Reviewed

#17827 Fix translation refs
  reference/dic_tags.rst
  routing.rst
  translation.rst
Labels: Status: Needs Review

#17822 Fix MailPace mailer package name
  mailer.rst
Labels: Status: Reviewed

#17482 [Security] Rename logout’s `csrf_token_generator` to `csrf_token_manager`
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#17824 [FrameworkBundle][Workflow] Register alias for argument for workflow services with workflow name only
  workflow.rst
Labels: Status: Reviewed, Workflow, FrameworkBundle

#17830 Use specific DOCtor-RST version
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#17831 Remove unused whitelist entries from DOCtor-RST config
  .doctor-rst.yaml
Labels: Status: Needs Review

#17832 Fix: DOCtor-RST build
  .doctor-rst.yaml
Labels: Status: Needs Review

#17836 [HttpClient] Replaced code block by `:class:` when relevant
  http_client.rst
Labels: Status: Reviewed, HttpClient
