Repository symfony/symfony-docs, pull requests merged in 2023-12, with the labels that each got.

#19187 Document requirements for DoctrineDbalAdapter
  components/cache/adapters/doctrine_dbal_adapter.rst
Labels: Status: Needs Review

#19206 [Form] Updating the generic `FormEvent` to specific event (e.g. `PreS…
  form/events.rst
Labels: Form, Status: Reviewed

#19196 [Uid] Default versions in framework VS recipes
  components/uid.rst
Labels: Status: Reviewed, Uid

#19190 [Contributing] Remove references to symfony/website-skeleton
  contributing/community/reviews.rst
Labels: Status: Reviewed

#19209 Add attribute configuration block for reusable locator
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed

#19216 [HttpFoundation] Add `UploadedFile::getClientOriginalPath()` to support directory uploads
  controller/upload_file.rst
  reference/forms/types/file.rst
Labels: HttpFoundation, Status: Needs Review

#19220 Added missing backtick character
  service_container/tags.rst
Labels: Status: Reviewed

#19218 UX bundles: fix autoimport paths
  frontend/create_ux_bundle.rst
Labels: Status: Reviewed, front-end

#19208 [Frontend] Identify the 2 main approaches to a frontend
  frontend.rst
Labels: Status: Needs Review

#19219 [Runtime] Update runtime.rst
  components/runtime.rst
Labels: Status: Needs Review, Runtime

#19207 [AssetMapper] Removing TODOs
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19221 fix the Runtime component introduction
  components/runtime.rst
Labels: Status: Reviewed

#19224 Use a release-indepent command to sign the Symfony CLI
  setup/symfony_server.rst
Labels: Status: Reviewed

#19228 Fix typo in dic_tags.rst
  reference/dic_tags.rst
Labels: Status: Needs Review

#19214 [PropertyInfo] Introduce `PropertyDocBlockExtractorInterface`
  components/property_info.rst
Labels: Status: Reviewed, PropertyInfo

#19109 [Testing] [Panther] Add component documentation
  .doctor-rst.yaml
  testing.rst
  testing/end_to_end.rst
Labels: Testing, Status: Reviewed

#19179 [Security] Migrate to ConfigBuilder format
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#19226 Add missing use statements
  configuration/multiple_kernels.rst
Labels: Status: Needs Review

#19231 Update flex_private_recipes.rst
  setup/flex_private_recipes.rst
Labels: Status: Needs Review

#19238 update the target branch for new features
  contributing/code/pull_requests.rst
Labels: Status: Reviewed, Hack Day

#19191 Update console.rst
  console.rst
Labels: Status: Reviewed

#19180 [Security] Migrate to ConfigBuilder format for 6.3+
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#19145 Update serverVersion for MariaDB
  doctrine.rst
Labels: Status: Needs Review, Waiting feedback

#19239 [Bundle] add tip for marking internal services as hidden
  bundles/best_practices.rst
Labels: Status: Reviewed, Hack Day

#19240 [DependencyInjection] Mention `exclude_self`
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#18398 [Workflow] Metadata dumping
  _images/components/workflow/blogpost_metadata.png
  workflow/dumping-workflows.rst
Labels: Status: Needs Review, Workflow

#19241 [Cache][Messenger] make both options redis_sentinel and sentinel_mast…
  components/cache/adapters/redis_adapter.rst
  messenger.rst
Labels: Status: Reviewed, Cache, Hack Day, Messenger

#19243 [Workflow] Add `getEnabledTransition()` method
  workflow.rst
Labels: Status: Reviewed, Workflow

#19122 Improve support for authenticators that don't need a user provider
  security/access_token.rst
Labels: Status: Reviewed, Hack Day, SecurityBundle

#19246 [Form] Document using TranslatableMessage in form Fields
  reference/forms/types/options/button_label.rst.inc
  reference/forms/types/options/placeholder.rst.inc
Labels: Form, Status: Reviewed, Hack Day

#19222 [Form] Fix custom form type docs
  form/create_custom_field_type.rst
Labels: Form, Status: Reviewed, Hack Day

#19254 Add `#[IsCsrfTokenValid]` attribute
  security/csrf.rst
Labels: Status: Needs Review

#19255 Add `#[IsCsrfTokenValid]` to attributes reference
  reference/attributes.rst
  security/csrf.rst
Labels: Status: Reviewed, Hack Day

#19257 [Form] Add `keep_as_list` option
  reference/forms/types/collection.rst
Labels: Form, Status: Reviewed

#19250 Add "frontend" as one of the topic to getting started
  page_creation.rst
Labels: Status: Reviewed

#19263 [Mailer] Mention webhook support in Mailer bridge overview
  mailer.rst
Labels: Status: Needs Review, Mailer

#19261 Update security.rst
  security.rst
Labels: Status: Needs Review

#19249 [Webhook] Added component documentation for use in combination with Mailer
  index.rst
  mailer.rst
  reference/attributes.rst
  reference/configuration/framework.rst
  webhook.rst
Labels: Status: Reviewed, Hack Day, Webhook

#19266 [Mailer] Updated webhook support in Mailer bridge overview for 6.4
  mailer.rst
Labels: Status: Needs Review, Mailer

#19267 [Webhook] Added Sendgrid's webhook support (added in 6.4)
  webhook.rst
Labels: Status: Needs Review, Webhook

#19268 [Webhook] Add bridges for Webhook
  mailer.rst
  webhook.rst
Labels: Status: Reviewed, Webhook

#19271 [Messenger] Add `--all` option to `messenger:consume`
  messenger.rst
Labels: Status: Needs Review, Messenger

#19269 [Notifier][Webhook] Added documentation for Webhook in combination with the Notifier component
  notifier.rst
  webhook.rst
Labels: Status: Needs Review, Notifier, Webhook

#19273 [Notifier][Webhook] Updated Webhook-supported Notifier bridges for 6.4
  notifier.rst
  webhook.rst
Labels: Status: Needs Review, Notifier, Webhook

#19000 [Routing][Security] Document the `LogoutRouteLoader`
  security.rst
Labels: Routing, Security, Hack Day, Status: Needs Review

#19288 [Webhook] Remove 6.x versionadded
  webhook.rst
Labels: Status: Reviewed, Webhook

#19283 [Setup] Remove @dev for 6.4 version
  setup.rst
Labels: Status: Needs Review

#19286 [Setup] Remove @dev for 7.0 version
  setup.rst
Labels: Status: Needs Review

#19252 [AssetMapper] Adding note about importmap block
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19285 [Cache] Deprecate `CouchbaseBucketAdapter`
  components/cache/adapters/couchbasebucket_adapter.rst
Labels: Status: Reviewed, Cache

#19229 [Routing] Improving language, shortening twig code
  routing.rst
Labels: Routing, Status: Reviewed

#19289 [HttpClient] Added a paragraph about HttpOptions object
  http_client.rst
Labels: Status: Reviewed, HttpClient

#17203 [Messenger] Add messenger rate_limiter docs
  messenger.rst
Labels: Status: Reviewed, Messenger

#19265 [Console] Added documentation about command profiling
  console.rst
Labels: Console, Status: Reviewed

#19296 [Notifier] Add Bluesky notifier bridge
  console.rst
  notifier.rst
Labels: Status: Reviewed, Notifier

#19295 Remove semicolon marking previous end of statement
  configuration.rst
Labels: Status: Reviewed

#19298 Fix wrong reStructuredText references
  components/serializer.rst
  configuration/multiple_kernels.rst
  mailer.rst
  mercure.rst
Labels: Status: Reviewed

#19306 [HttpClient] Add `JsonMockResponse::fromFile()` and `MockResponse::fromFile()` shortcuts
  http_client.rst
Labels: Status: Needs Review, HttpClient

#19300 [Notifier] Add Unifonic notifier bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#19312 [AssetMapper] Fix importmap code example with multiple entrypoints
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19317 Fix comma fopen http_client
  http_client.rst
Labels: Status: Reviewed

#19314 [Constraints] Update `callback` argument type
  reference/constraints/Choice.rst
Labels: Status: Reviewed

#15970 [Lock] Remove mention off DBAL Connection support for locking
  components/lock.rst
Labels: Status: Needs Review, Lock

#19320 [Validator] Add `list` and `associative_array` types to Type constraint
  reference/constraints/Type.rst
Labels: Validator, Status: Reviewed

#19308 [Logger] Switching to more modern config format
  logging/channels_handlers.rst
Labels: Logger, Status: Reviewed

#19290 [Form] Fix wrong return type for choice_loader
  reference/forms/types/options/choice_loader.rst.inc
Labels: Form, Status: Reviewed

#19278 [Console] Add Helper::formatMemory in the doc
  components/console/helpers/formatterhelper.rst
Labels: Console, Status: Needs Review

#19322 [Security] Update request matcher doc
  security/access_control.rst
Labels: Security, Status: Reviewed

#19326 some tweaks for the Webhook docs
  mailer.rst
  notifier.rst
  webhook.rst
Labels: Status: Reviewed

#18664 [Console] Add more examples for lazy commands
  console/commands_as_services.rst
  console/lazy_commands.rst
Labels: Console, Status: Needs Review

#19327 [Reference] Fix assets links have wrong label
  reference/twig_reference.rst
Labels: Status: Reviewed

#19328 Fix code example: replace request get() with all() method to support non-scalar types
  form/direct_submit.rst
Labels: Status: Reviewed

#19331 [AssetMapper] tweak the AssetMapper docs
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19332 syntax tweaks
  console/lazy_commands.rst
Labels: Status: Reviewed

#19323 [String] Remove confusing paragraph about `withEmoji('strip')`
  components/intl.rst
  components/string.rst
Labels: Status: Needs Review, String

#19293 [HttpKernel] [Value Resolver] Added `RequestPayloadValueResolver` section
  controller.rst
  controller/value_resolver.rst
Labels: Status: Reviewed, HttpKernel

#19329 Remove reference to some removed classes
  create_framework/http_kernel_httpkernel_class.rst
  introduction/from_flat_php_to_symfony.rst
  messenger.rst
Labels: Status: Reviewed

#19305 Mutate some `cautions` to `dangers`
  components/http_foundation.rst
  components/lock.rst
  components/process.rst
  components/yaml.rst
  configuration.rst
  configuration/secrets.rst
  controller.rst
  deployment/proxies.rst
  http_cache/cache_invalidation.rst
  http_cache/ssi.rst
  profiler.rst
  rate_limiter.rst
  reference/configuration/twig.rst
  security.rst
  serializer.rst
  session.rst
Labels: Status: Reviewed

#19334 Mention Symfony CLI workers where applicable
  frontend/encore/simple-example.rst
  messenger.rst
  setup/symfony_server.rst
Labels: Status: Reviewed

#19291 [HttpClient] Add `HttpOptions::addHeader` method
  http_client.rst
Labels: Status: Needs Review, HttpClient

#19325 [Translation] [Crowdin] Add a tip about language mapping
  translation.rst
Labels: Status: Needs Review, Translation

#19315 [Notifier] Add Smsbox notifier bridge
  notifier.rst
Labels: Status: Needs Work, Notifier

#19307 [Documentation][Routing] Update routing.rst
  routing.rst
Labels: Status: Needs Review

#19339 Rename `addHeader` to `setHeader`
  http_client.rst
Labels: Status: Needs Review

#19340 [Intl] Remove warning about replacement layer
  components/intl.rst
Labels: Status: Reviewed, Intl

#19341 [Validator] Add `Charset` constraint
  reference/constraints/Charset.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#17833 Added description to improved bin/console debug:container --env-vars …
  configuration.rst
Labels: Status: Reviewed, Waiting Code Merge

#19345 [Messenger] Fix typo
  messenger.rst
Labels: Status: Reviewed, Messenger

#19258 [Notifier] Add docs of sms-sluzba.cz bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#18828 Update associations.rst
  doctrine/associations.rst
Labels: Status: Needs Review

#19348 Remove yarn commands in front-end docs
  .doctor-rst.yaml
  frontend/create_ux_bundle.rst
  frontend/encore/advanced-config.rst
  frontend/encore/bootstrap.rst
  frontend/encore/dev-server.rst
  frontend/encore/faq.rst
  frontend/encore/installation.rst
  frontend/encore/postcss.rst
  frontend/encore/reactjs.rst
  frontend/encore/simple-example.rst
  frontend/encore/vuejs.rst
  setup/symfony_server.rst
Labels: Status: Reviewed, front-end

#19344 Document `#[WithHttpStatus]` and `#[WithLogLevel]` on interfaces.
  reference/configuration/framework.rst
Labels: Status: Needs Review

#19351 [Notifier] Add Seven.io bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#19352 [Validator] Mention support of Stringable objects in Charset constraint
  reference/constraints/Charset.rst
Labels: Validator, Status: Reviewed

#19358 [Validator] Update the default message of the `Charset` constraint
  reference/constraints/Charset.rst
Labels: Validator, Status: Reviewed

#19360 [FrameworkBundle] Update framework config
  reference/configuration/framework.rst
Labels: FrameworkBundle

#19356 [Serializer] Better example for date denormalization
  serializer.rst
Labels: Status: Reviewed, Serializer

#19357 Fix JetBrains Toolbox deeplink example
  reference/configuration/framework.rst
Labels: Status: Needs Review
