Repository symfony/symfony-docs, pull requests merged in 2023-03, with the labels that each got.

#17974 [Messenger] Fix the referencing of the redis transport in an explanation
  messenger.rst
Labels: Status: Reviewed, Messenger

#17962 [Form] Removed jQuery in favour of vanilla Javascript
  reference/forms/types/collection.rst
Labels: Form, Status: Reviewed

#17972 [HttpCache] Explain how to extend the `HttpCache` class
  http_cache/cache_invalidation.rst
Labels: Status: Reviewed

#17986 [Twig] Update the docs of the `twig.debug` option
  reference/configuration/twig.rst
  templates.rst
Labels: Status: Reviewed, Twig

#17985 [HttpClient] Mention list of callbacks for `MockHttpClient`
  http_client.rst
Labels: Status: Reviewed, HttpClient

#17984 [Validator] Add `Cascade` constraint documentation
  reference/constraints/Cascade.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#17961 [Doctrine] add `AsDoctrineListener` attribute
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#17980 [HttpKernel] use more precise links in httpkernel doc
  components/http_kernel.rst
Labels: Status: Reviewed, HttpKernel

#17992 [Serializer] Update reference to location of priorities of default normalizers
  reference/dic_tags.rst
Labels: Status: Reviewed, Serializer

#17993 [Validator] Add `Cascade` to list
  reference/constraints.rst
Labels: Validator, Status: Reviewed

#17958 [Doctrine] update some doctrine documentation
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#17975 [HttpCache] Add example with an attribute
  http_cache/cache_invalidation.rst
Labels: Status: Reviewed

#17995 [FrameworkBundle] enable_annotations is enabled by default
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#17968 [PHPUnitBridge] Add an example for `SYMFONY_PHPUNIT_REQUIRE`
  components/phpunit_bridge.rst
Labels: Status: Reviewed, PHPUnitBridge

#17970 [EventDispatcher] Add example of ``#[AsEventListener]`` on methods
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#17472 [Doctrine] Add documentation about Doctrine `AsEventListener`
  .doctor-rst.yaml
  doctrine/events.rst
Labels: Doctrine, Status: Reviewed

#17870 [Cache] Add Redis Relay doc
  components/cache/adapters/redis_adapter.rst
  components/lock.rst
  session.rst
Labels: Status: Reviewed, Cache

#17989 [Security] updated the casted interface name as per the implemented interface
  security/passwords.rst
Labels: Security, Status: Reviewed

#18009 [DomCrawler] Give choice of used parser
  components/dom_crawler.rst
Labels: Status: Reviewed, DomCrawler

#18012 minor fix ci
  doctrine/events.rst
Labels: Status: Reviewed

#18011 [Validator] Remove texts about require php 8.1
  reference/constraints/All.rst
  reference/constraints/AtLeastOneOf.rst
  reference/constraints/Collection.rst
  reference/constraints/Sequentially.rst
Labels: Validator, Status: Reviewed

#17999 [Routing] Mention that param converters are now native
  routing.rst
Labels: Routing, Status: Reviewed

#18003 [Attributes] Add attributes overview
  components/serializer.rst
  console.rst
  event_dispatcher.rst
  reference/attributes.rst
  reference/map.rst.inc
  serializer.rst
  service_container.rst
  service_container/autowiring.rst
  service_container/service_subscribers_locators.rst
  service_container/tags.rst
Labels: Status: Reviewed

#18013 [Mailer] Remove bcc for signed messages
  mailer.rst
Labels: Status: Reviewed, Mailer

#17998 Update mailer.rst
  mailer.rst
Labels: Status: Reviewed

#18022 [Routing] Fix broken link
  routing.rst
Labels: Routing, Status: Reviewed

#17991 [Bundles] new directory structure for doctrine resources
  bundles/best_practices.rst
Labels: Status: Reviewed, Bundles

#18001 [Console] Add support for managing exit code while handling signals
  components/console/events.rst
Labels: Console, Status: Reviewed

#16609 [Logging] Document the Monolog `reset()` method for long running processes
  logging.rst
Labels: Status: Needs Review

#18026 Use Doctor RST 1.41.0 and new rule `TitleUnderlineLengthMustMatchTitleLength`
  .doctor-rst.yaml
  .github/workflows/ci.yaml
  best_practices.rst
  components/lock.rst
  components/runtime.rst
  components/serializer.rst
  controller.rst
  frontend/encore/bootstrap.rst
  frontend/encore/virtual-machine.rst
  mercure.rst
  reference/configuration/framework.rst
  reference/configuration/security.rst
  reference/forms/types/choice.rst
  reference/forms/types/tel.rst
  reference/twig_reference.rst
Labels: Status: Reviewed

#18028 [Session] Fix an RST syntax issue
  session.rst
Labels: Status: Reviewed, Session

#18030 Fix typos in Symfony Attributes Overview
  reference/attributes.rst
Labels: Status: Reviewed

#18027 Fix rst syntax for ci with Doctor RST 141
  bundles/best_practices.rst
  html_sanitizer.rst
  reference/constraints/Expression.rst
Labels: Status: Reviewed

#18014 [Attributes] Add attributes overview for 6.2
  reference/attributes.rst
Labels: Status: Reviewed

#15731 [DependencyInjection] Add section about Service Closures
  service_container/lazy_services.rst
  service_container/service_closures.rst
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#18031 Fix typo in routing
  routing.rst
Labels: Status: Reviewed

#18015 [Attributes] Add attributes overview for 6.3
  reference/attributes.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed

#18032 [Attributes] Add missing `#[MapEntity]` attribute
  reference/attributes.rst
Labels: Status: Reviewed

#18037 Add `BackedEnumNormalizer::ALLOW_INVALID_VALUES` context option
  components/serializer.rst
Labels: Status: Needs Review

#18038 Add missing import for LogRecord class in processors code example
  logging/processors.rst
Labels: Status: Reviewed

#18043 [DependencyInjection] Explain how to use the class itself as factory
  service_container/factories.rst
Labels: DependencyInjection, Status: Reviewed

#18008 [Validator] Add `exclude` option to `Cascade`
  reference/constraints/Cascade.rst
Labels: Validator, Status: Needs Review

#18047 [Form] Remove evasive `getOrigin` sentence
  components/form.rst
Labels: Form, Status: Reviewed

#18046 [Attributes] Add `#[AsAlias]` reference
  reference/attributes.rst
Labels: Status: Reviewed

#18045 [Attributes] Add `#[MapDateTime]` reference
  controller/value_resolver.rst
  reference/attributes.rst
Labels: Status: Reviewed

#18036 Change security title for checking if user is logged in
  security.rst
Labels: Status: Reviewed

#17948 [Validator] Implement countUnit option for Length constraint
  reference/constraints/Length.rst
Labels: Validator, Status: Reviewed

#18039 Use constructor property promotion in monolog_console.rst code example
  logging/monolog_console.rst
Labels: Status: Needs Review

#18010 Improve description of ad hoc containers
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed

#18048 DependencyInjection] Deprecate `#[MapDecorated]` in favor of `#[AutowireDecorated]`
  reference/attributes.rst
  service_container/service_decoration.rst
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed, Status: Needs Work

#18051 [DependencyInjection] Add `#[AutowireCallable]` and `#[AutowireServiceClosure]`
  reference/attributes.rst
  service_container.rst
  service_container/service_closures.rst
Labels: DependencyInjection, Status: Reviewed

#18052 Upgrade doctor rst 1.41.3
  .github/workflows/ci.yaml
  components/runtime.rst
  components/uid.rst
  components/var_exporter.rst
  page_creation.rst
  quick_tour/flex_recipes.rst
  quick_tour/the_architecture.rst
  quick_tour/the_big_picture.rst
Labels: Status: Reviewed

#18035 Update reverse_engineering.rst
  doctrine/reverse_engineering.rst
Labels: Status: Needs Review

#17950 [Mailer] add more info for debugging
  mailer.rst
Labels: Status: Needs Review, Mailer

#17969 [HttpCache] Inject `$env` in example
  http_cache.rst
Labels: Status: Reviewed

#18055 [HttpFoundation] Add support for the 103 status code
  controller.rst
Labels: HttpFoundation, Status: Reviewed

#18059 Update create_custom_field_type.rst
  form/create_custom_field_type.rst
Labels: Status: Needs Review

#17932 [DependencyInjection] Allow array attributes for services tags
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#18063 [HttpCache] Fix decorating `http_cache` xml example
  http_cache/cache_invalidation.rst
Labels: Status: Reviewed

#18065 [Attributes] Add Symfony UX attributes reference
  reference/attributes.rst
Labels: Status: Reviewed

#17930 Add docs about creating UX bundles
  frontend/create_ux_bundle.rst
Labels: Status: Reviewed

#18058 [Workflow] Update workflow.rst
  workflow.rst
Labels: Status: Needs Review, Workflow

#18076 Update data_transformers.rst
  form/data_transformers.rst
Labels: Status: Needs Review

#18074 [Logger] Tweak a section heading
  logging/channels_handlers.rst
Labels: Logger, Status: Reviewed

#18082 Update doctrine.rst
  doctrine.rst
Labels: Status: Reviewed

#18094 [HttpFoundation] Add `ParameterBag::getString()`
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#18092 Update forwarding.rst
  controller/forwarding.rst
Labels: Status: Reviewed

#18084 [Yaml] Mention `php/enum`
  reference/formats/yaml.rst
Labels: Status: Reviewed, Yaml

#18099 Minor syntax issue in Symfony Server article
  setup/symfony_server.rst
Labels: Status: Reviewed

#18085 [Console] Update style.rst
  console/style.rst
Labels: Console, Status: Needs Review

#18068 Update deployment.rst
  deployment.rst
Labels: Status: Reviewed

#18102 Add IpUtils::isPrivateIp docs
  components/http_foundation.rst
Labels: Status: Needs Review

#18016 [Workflow] MarkingStore: remove "arguments" and add "property"
  reference/configuration/framework.rst
Labels: Status: Needs Review, Workflow

#18029 [HtmlSanitizer] Fix API usage on PHP config files
  html_sanitizer.rst
Labels: Status: Reviewed, HtmlSanitizer

#17556 [Security] Make login redirection logic available to programmatic login
  security.rst
Labels: Security, Status: Reviewed

#18091 [Doctrine] replace ManagerRegistry in doctrine associations doc
  doctrine/associations.rst
Labels: Doctrine, Status: Reviewed

#18105 [Messenger] Add messenger.stop_worker_on_signals option documentation
  messenger.rst
Labels: Status: Reviewed, Messenger

#18101 [Security] Add argument `$exceptionCode` to `#[IsGranted]`
  security.rst
Labels: Security, Status: Reviewed

#18109 [CssSelector] Add support for :scope
  components/css_selector.rst
Labels: Status: Reviewed, CssSelector

#18108 Request is stateless when firewall is stateless
  reference/configuration/security.rst
Labels: Status: Reviewed, SecurityBundle

#18081 [Form] Update events.rst
  form/events.rst
Labels: Form, Status: Reviewed

#18110 [HttpFoundation] Add deprecation hint on `filter()`
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#18077 Update upload_file.rst
  controller/upload_file.rst
Labels: Status: Needs Review

#18079 Update upload_file.rst
  controller/upload_file.rst
Labels: Status: Needs Review

#18080 Update event_dispatcher.rst
  event_dispatcher.rst
Labels: Status: Needs Review

#18057 [Translation] Fix plural rules at message format page
  reference/formats/message_format.rst
Labels: Status: Needs Review, Translation

#18017 [Messenger] add `WorkerMessageRetriedEvent`
  messenger.rst
Labels: Status: Reviewed, Messenger

#18018 [Messenger] add `WorkerRateLimitedEvent`
  messenger.rst
Labels: Status: Reviewed, Messenger

#17897 [Validator] Document the new `NoSuspiciousCharacters` constraint
  reference/constraints.rst
  reference/constraints/NoSuspiciousCharacters.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#17746 [Validator] Fix a valid Date and Time constraint format
  reference/constraints/Date.rst
  reference/constraints/Time.rst
Labels: Validator, Status: Reviewed

#18114 update default value for framework.ide
  reference/configuration/framework.rst
Labels: Status: Reviewed

#17513 [Security] Use expression for `#[IsGranted()]` subject
  security/expressions.rst
Labels: Security, Status: Reviewed

#17902 [Notifier] Add link to readme bridges
  _build/composer.json
  _build/composer.lock
  notifier.rst
Labels: Status: Reviewed, Notifier

#18118 Add note about custom port being ignored by specific mailer transport DSN
  mailer.rst
Labels: Status: Needs Review

#18119 Move Notifier bridges doc to the code repo README files
  notifier.rst
  notifier/discord.rst
  notifier/slack.rst
  notifier/teams.rst
  notifier/telegram.rst
Labels: Status: Reviewed

#18134 [Standards] Improve code standards about exception and error messages
  contributing/code/standards.rst
Labels: Status: Reviewed

#18125 Add return types
  controller/upload_file.rst
Labels: Status: Reviewed

#18072 [Cache] Add documentation for new `--all` option for `cache:pool:clear`
  cache.rst
Labels: Status: Reviewed, Cache

#18138 [FrameworkBundle] Update framework configuration reference for cache
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#18143 [Standards] Remove additional comma
  contributing/code/standards.rst
Labels: Status: Reviewed

#18133 [PasswordHasher] Mention standalone use of `PasswordHasherFactory`
  security/passwords.rst
Labels: Status: Reviewed, PasswordHasher

#18146 [HttpClient] Add `ServerSentEvent::getArrayData()` to get the SSE's data decoded as an array directly
  http_client.rst
Labels: Status: Reviewed, HttpClient

#18148 Use Doctor RST 1.42.1 and new Rule `ForbiddenDirectives`
  .doctor-rst.yaml
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#18124 [Validator] Document `PasswordStrength` constraint
  reference/configuration/framework.rst
  reference/constraints.rst
  reference/constraints/Compound.rst
  reference/constraints/PasswordStrength.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#18150 [Process] :memo: process: `create_new_console` is only for windows
  components/process.rst
Labels: Process, Status: Needs Review
