Repository symfony/symfony-docs, pull requests merged in 2023-10, with the labels that each got.

#18953 [FrameworkBundle] Allow BrowserKit relative URL redirect assert
  testing.rst
Labels: Status: Reviewed, FrameworkBundle

#18950 [Messenger] Add `--all` option to `messenger:failed:remove`
  messenger.rst
Labels: Status: Reviewed, Messenger

#18955 [Mime] Add `TemplatedEmail::locale()` to set the locale for the email rendering
  mailer.rst
Labels: Status: Reviewed, Mime

#18946 [WebProfilerBundle] Document `!` operator negating url filter
  profiler.rst
Labels: Status: Reviewed

#18937 [Console] Fix codeblock markup
  console.rst
Labels: Console, Status: Reviewed

#18964 [FrameworkBundle] Add `--show-aliases` option to `debug:router` command
  routing.rst
Labels: Status: Reviewed, FrameworkBundle

#18972 [Validator] Change `preg_match` condition on `ContainsAlphanumericValidator`
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#18977 [Security] Update voters.rst
  security/voters.rst
Labels: Security, Status: Reviewed

#18978 Fix: Build
  security.rst
Labels: Status: Needs Review

#18976 [Security] Improve `requires_channel` var naming
  security/force_https.rst
Labels: Security, Status: Reviewed

#18966 Add new Twig bridge function to generate impersonation path
  reference/twig_reference.rst
Labels: Status: Reviewed, TwigBridge

#18965 [Testing] Update PHPUnit docs links
  testing.rst
Labels: Testing, Status: Reviewed

#18962 [RateLimiter] Add `SlidingWindowLimiter::reserve()`
  rate_limiter.rst
Labels: Status: Reviewed, RateLimiter

#18970 [FrameworkBundle] Add HttpClientAssertions trait documentation
  testing.rst
Labels: Status: Reviewed, FrameworkBundle

#18980 Update the docs-builder to 0.21
  _build/composer.json
  _build/composer.lock
Labels: Status: Reviewed

#18936 [HttpKernel] Clarify `#[MapRequestPayload]` with nested arrays
  controller.rst
Labels: Status: Reviewed, HttpKernel

#18931 [Security] Mention customizing successful and failed authentication
  security.rst
  security/login_link.rst
Labels: Security, Status: Reviewed

#18979 [Security] Update security.rst
  security.rst
Labels: Security, Status: Needs Review

#18942 [PropertyInfo] Added documentation about camelCase assumption for getter/setter methods
  components/property_info.rst
Labels: Status: Reviewed, PropertyInfo

#18967 [HttpFoundation] Support root-level Generator in StreamedJsonResponse
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#18983 [Twig] Fix title underlining
  reference/twig_reference.rst
Labels: Status: Reviewed, Twig

#18982 [RateLimiter] Remove deprecations
  rate_limiter.rst
Labels: Status: Reviewed, RateLimiter

#18984 [Messenger] Make a list unordered
  components/messenger.rst
Labels: Status: Reviewed, Messenger

#18988 Fix list usage
  http_client.rst
Labels: Status: Reviewed

#18985 [Configuration] Mention `EnvVarLoaderInterface`
  configuration.rst
Labels: Status: Reviewed

#18934 [Form] Update FormEvents Data and Form Data description
  form/events.rst
Labels: Form, Status: Reviewed

#18994 [Form] Add `duplicate_preferred_choices` option to `ChoiceType`
  reference/forms/types/choice.rst
  reference/forms/types/country.rst
  reference/forms/types/currency.rst
  reference/forms/types/enum.rst
  reference/forms/types/language.rst
  reference/forms/types/locale.rst
  reference/forms/types/options/duplicate_preferred_choices.rst.inc
  reference/forms/types/timezone.rst
Labels: Form, Status: Reviewed

#18992 [AssetMapper] Add audit command
  _images/components/assetmapper/01-importmap-audit.png
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#18996 Redis change default branch and docs location
  components/cache/adapters/redis_adapter.rst
Labels: Status: Reviewed

#18995 [Security] Explain that `IS_AUTHENTICATED_REMEMBERED` should not be used
  security.rst
Labels: Security, Status: Needs Review

#18991 Pass `Request` to EntityValueResolver
  doctrine.rst
Labels: Status: Reviewed, DoctrineBridge

#19001 [Profiler] Update profiler interface capture (minor)
  _images/profiler/web-interface.png
Labels: Status: Reviewed

#19002 Update phpunit_bridge.rst
  components/phpunit_bridge.rst
Labels: Status: Reviewed

#19009 [Console] Helpers updated to optimize the time formating
  components/console/helpers/formatterhelper.rst
  components/console/helpers/progressbar.rst
Labels: Console, Status: Needs Review

#18779 [Serializer] Use `NormalizerInterface` instead of `ObjectNormalizer`
  serializer/custom_normalizer.rst
Labels: Status: Reviewed, Serializer

#19005 [AssetMapper] [WCM] Added instruction for 'outdated' command
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#18595 [Cache] Document `cache:pool:clear`’s new `--exclude` option
  cache.rst
Labels: Status: Reviewed, Cache

#19013 Forgot imports
  serializer/custom_normalizer.rst
Labels: Status: Reviewed

#19014 Add implements ProcessorInterface
  logging/processors.rst
Labels: Status: Reviewed

#19015 Update migration.rst
  migration.rst
Labels: Status: Reviewed

#19017 [Console] Dispatch `ConsoleTerminateEvent` when exiting on signal
  components/console/events.rst
Labels: Console, Status: Reviewed

#19020 Update target branch for feature updates to 6.4
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#19019 [Serializer] Update reference to attribute in the section title
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#19021 [AssetMapper] Automatically preload CSS files if WebLink available
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19022 Fix the installation instructions of symfony/psr-http-message-bridge
  components/psr7.rst
Labels: Status: Reviewed

#19024 Use DOCtor-RST 1.53
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#18499 [Finder] [Finder docs] Add early directory prunning filter support
  components/finder.rst
Labels: Status: Reviewed, Finder

#19028 Doctor RST ensure link definitions bottom
  .doctor-rst.yaml
  contributing/code/conventions.rst
  frontend/encore/faq.rst
Labels: Status: Needs Review

#19029 [Security] Document `InteractiveLoginEvent`
  security.rst
Labels: Security, Status: Reviewed

#19040 [HttpFoundation] Add `$flush` parameter to `Response::send()`
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#19043 [WebLink] Adding missing "as" to style link header
  web_link.rst
Labels: Status: Reviewed, WebLink

#19026 Mention PCNTL extension installation
  components/console/events.rst
  components/lock.rst
Labels: Status: Reviewed

#19058 Chore: Fix typo in multiple files
  components/console/helpers/progressbar.rst
  configuration.rst
  reference/constraints/PasswordStrength.rst
  security/access_control.rst
  service_container/autowiring.rst
  validation.rst
Labels: Status: Needs Review

#19056 [HtmlSanitizer] Add support for sanitizing unlimited length of HTML document
  html_sanitizer.rst
Labels: Status: Reviewed, HtmlSanitizer

#19062 [Contributing] Replace "ticket" with "issue"
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#19055 [Messenger][AmazonSQS] Add `AddFifoStamp` middleware
  messenger.rst
Labels: Status: Needs Review, Messenger

#19047 [Messenger] Clarify transport creation example
  components/messenger.rst
Labels: Status: Reviewed, Messenger

#19037 [Encore] Updating Babel Plugin
  frontend/encore/installation.rst
Labels: Status: Reviewed, Encore

#19072 reference the decorated service using the special .inner id
  cache.rst
  session.rst
Labels: Status: Reviewed

#19071 [Bundles] Remove SensioFrameworkExtraBundle from code exemple
  bundles.rst
Labels: Status: Reviewed, Bundles

#19077 Use Doctor RST 1.54.0
  .github/workflows/ci.yaml
  components/console/helpers/progressbar.rst
  validation.rst
Labels: Status: Reviewed

#19078 Fix: Typos
  _build/maintainer_guide.rst
  reference/constraints/PasswordStrength.rst
  security/access_control.rst
  service_container/autowiring.rst
Labels: Status: Needs Review

#19070 Fix documentation for MongoDB Session Handler
  session.rst
Labels: Status: Needs Review

#19067 [HttpKernel] Add parameters kernel.runtime_mode and kernel.runtime_mode.*, all set from env var APP_RUNTIME_MODE
  reference/configuration/kernel.rst
Labels: Status: Reviewed, HttpKernel

#19057 [AssetMapper] Put importmap in polyfill so it can be hosted locally easily
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19046 [Serializer] Deprecate annotations
  components/property_info.rst
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#19080 [PropertyInfo][Serializer] Remove `AnnotationLoader`
  _build/redirection_map
  components/property_info.rst
  components/serializer.rst
Labels: Serializer, PropertyInfo, Status: Needs Review

#19081 [DependencyInjection] simplify compiler pass example
  testing.rst
Labels: DependencyInjection, Status: Reviewed

#19054 [Validator] Add "Translatable Objects" example
  validation/translations.rst
Labels: Validator, Status: Reviewed

#19085 Fix grammar typo
  components/expression_language.rst
Labels: Status: Needs Review

#19086 [Dotenv] Use named parameter
  configuration.rst
Labels: Status: Reviewed, Dotenv

#19089 [PHPUnitBridge] Allow setting the locale using `SYMFONY_PHPUNIT_LOCALE` env var
  components/phpunit_bridge.rst
Labels: PHPUnitBridge, Status: Needs Review

#19091 [Notifier] Use Route attribute instead annotations
  notifier.rst
Labels: Status: Reviewed, Notifier

#19093 fix the time formatting example
  components/console/helpers/formatterhelper.rst
Labels: Status: Reviewed

#19092 Fix wording at `property_access.rst`
  components/property_access.rst
Labels: Status: Reviewed

#18782 [Flex] Remove PHP<8 section, remove flex reference
  configuration.rst
Labels: Status: Reviewed, Flex

#19096 Use str_starts_with() in OptionsResolver examples
  components/options_resolver.rst
Labels: Status: Reviewed

#19094 [Form] Document "class constraints" for data class-less forms
  form/without_class.rst
Labels: Form, Status: Needs Review

#19097 [PHPUnitBridge] Add a note to disable the locale forcing by the bridge
  components/phpunit_bridge.rst
Labels: Status: Reviewed, PHPUnitBridge

#19098 Document twig functions on impersonation
  security/impersonating_user.rst
Labels: Status: Reviewed

#19100 [Messenger] Add mention of workers restarting with `supervisor`
  messenger.rst
Labels: Status: Reviewed, Messenger

#19045 [Validator] Change return type from iterable to Generator
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed
