Repository symfony/symfony-docs, pull requests merged in 2023-02, with the labels that each got.

#17845 remove versionadded directive for Symfony 5.2
  http_client.rst
Labels: Status: Needs Review

#17846 fix link to the ExpressionLanguage syntax reference
  reference/constraints/When.rst
Labels: Status: Needs Review

#17843 Minor: Removing code line
  mailer.rst
Labels: Status: Reviewed

#17849 fix reference to extending expression language section
  reference/formats/expression_language.rst
Labels: Status: Needs Review

#17850 add missing telegram docs link target
  notifier/telegram.rst
Labels: Status: Needs Review

#17841 [Routing] Minor
  routing.rst
Labels: Routing, Status: Reviewed

#17834 [Profiler] Consolidate profiler docs
  _build/redirection_map
  profiler.rst
  profiler/data_collector.rst
  reference/dic_tags.rst
  testing/profiling.rst
Labels: Profiler, Status: Reviewed

#17854 [Profiler] Fix obsolete link
  profiler.rst
Labels: Profiler, Status: Reviewed

#17837 [Security] Mention access control is now required to enforce authentication
  security/experimental_authenticators.rst
Labels: Security, Status: Reviewed

#17857 Update notifier.rst
  notifier.rst
Labels: Status: Needs Review

#17856 Use DOCtor-RST 1.37.0
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#17855 import function env to avoid fatal error if copying docs
  mailer.rst
Labels: Status: Reviewed

#17835 [Lock] Complete Lock example for less ambiguity
  components/lock.rst
Labels: Status: Reviewed, Lock

#17792 [DependencyInjection] Add `closure` argument type
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#17480 Clarify how `CollectionType` entries are indexed
  reference/forms/types/collection.rst
Labels: Status: Reviewed

#17858 Use DOCtor-RST 1.38.2
  .doctor-rst.yaml
  .github/workflows/ci.yaml
  frontend/encore/simple-example.rst
  frontend/ux.rst
  mercure.rst
Labels: Status: Needs Review

#17859 Use `actions/checkout@v3`
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#17860 Use `actions/cache@v3`
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#17866 Fix code block for routing troubleshooting examples
  routing.rst
Labels: Status: Reviewed

#17869 [RateLimiter] Adding `reset()`
  rate_limiter.rst
Labels: Status: Reviewed, RateLimiter

#17864 [Security] Merging two paragraphs
  security.rst
Labels: Security, Status: Reviewed

#17865 [Config] Allow enum values in EnumNode
  components/config/definition.rst
Labels: Config, Status: Reviewed

#17868 Null Coalescing Operator
  create_framework/routing.rst
Labels: Status: Reviewed

#17852 Update documentation for Bundle configuration
  bundles/configuration.rst
Labels: Status: Reviewed

#17732 [Templating][Twig] Fix composer require
  templates.rst
Labels: Templating, Status: Reviewed, Twig

#17873 [Messenger] Add `TransportNamesStamp` tip
  messenger.rst
Labels: Status: Reviewed, Messenger

#17877 [Profiler] Add a tip about profiler icons
  profiler.rst
Labels: Profiler, Status: Needs Review

#17876 Add a new item to the list of concrete examples of Code of Conduct
  contributing/code_of_conduct/concrete_example_document.rst
Labels: Status: Reviewed

#17879 Use DOCtor-RST 1.40.0
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#17872 [Security] [LoginLink] Add technical details
  security/login_link.rst
Labels: Security, Status: Reviewed

#17871 [Config] Simplify configuration env var example
  configuration.rst
Labels: Config, Status: Reviewed

#17823 [HttpClient] Allow yielding Exception from MockResponse's $body to mock transport errors
  http_client.rst
Labels: Status: Needs Review, HttpClient

#17883 [PropertyInfo] Mention `list` pseudo type
  components/property_info.rst
Labels: Status: Reviewed, PropertyInfo

#17881 Add a tip about signing Symfony server binary on macOS
  setup/symfony_server.rst
Labels: Status: Needs Review

#17885 [String] Minor tweak about the slugger and locales
  components/string.rst
Labels: Status: Needs Review, String

#17887 Moving nginx above Apache (second attempt)
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#17888 [BrowserKit][HttpClient] Add examples to set cookies in the request
  components/browser_kit.rst
  http_client.rst
Labels: Status: Reviewed, BrowserKit, HttpClient

#17890 Switching to PHP-version-agnostic socket file
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#17829 [Security] Add complex example is_granted and/or is_granted
  security/expressions.rst
Labels: Status: Needs Review

#17895 [Notifier] `from` is optional in Smsapi since 6.3
  notifier.rst
Labels: Status: Reviewed, Notifier

#17894 Adding backticks
  setup/web_server_configuration.rst
Labels: Status: Needs Review

#17892 [ExpressionLanguage][Validator] Mention the validator.expression_language service
  components/expression_language.rst
  reference/constraints/Expression.rst
Labels: Validator, Status: Reviewed, ExpressionLanguage

#17735 [Config] [Configuration] Add `$_ENV` and `$_SERVER` example with .env
  configuration.rst
Labels: Config, Status: Reviewed

#17755 [Doctrine] Cleaning up the config code samples
  doctrine/multiple_entity_managers.rst
Labels: Doctrine

#17889 [DependencyInjection] Fix example for Autowire attribute
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Needs Review

#17898 move further reading, convert to rst, remove dead links
  contributing/diversity/further_reading.rst
  contributing/diversity/index.rst
Labels: Status: Needs Review

#17905 Fix the example for the When constraint
  reference/constraints/When.rst
Labels: Status: Reviewed

#17903 [DependencyInjection] Document Container invalid behavior
  components/dependency_injection.rst
Labels: DependencyInjection, Status: Reviewed

#17910 [Config] [Configuration] Add enum case as service parameter example
  configuration.rst
Labels: Config, Status: Reviewed

#17909 [Validator] Add a few missing option default values
  reference/constraints/UniqueEntity.rst
  reference/constraints/_comparison-propertypath-option.rst.inc
  reference/constraints/_groups-option.rst.inc
Labels: Validator, Status: Reviewed

#17896 Changing "white spaces" => "whitespace"
  components/string.rst
Labels: Status: Needs Review

#17918 [Flex] Replace orm-pack with orm
  setup/flex.rst
Labels: Status: Reviewed, Flex

#17919 [Security] Adding needsRehash()
  security/passwords.rst
Labels: Security, Status: Reviewed

#17923 [Security] Removing "Most applications will only need one firewall"
  reference/configuration/security.rst
Labels: Security, Status: Needs Review

#17921 [Security] `its` => `their`
  security.rst
Labels: Security, Status: Reviewed

#17924 [PropertyAccess] Allow to escape dots and squared brackets in property paths
  components/property_access.rst
Labels: Status: Reviewed, PropertyAccess

#17925 [String] Add `LazyString` documentation
  components/string.rst
Labels: Status: Reviewed, String

#17915 [Messenger] Add `BatchHandlerInterface` and `BatchHandlerTrait` mentions
  messenger.rst
Labels: Status: Reviewed, Messenger

#17929 [Security] format `login()` properly
  security.rst
Labels: Security, Status: Reviewed

#17920 [DependencyInjection] `AsAlias` attribute
  service_container/alias_private.rst
Labels: DependencyInjection, Status: Reviewed

#17946 [Validator] Add missing backticks
  reference/constraints/Length.rst
Labels: Validator, Status: Reviewed

#17942 [Messenger] Allow to define batch size when using `BatchHandlerTrait` with `getBatchSize()`
  messenger.rst
Labels: Status: Reviewed, Messenger

#17936 [Messenger] Remove versionadded about 5.4
  messenger.rst
Labels: Status: Reviewed, Messenger

#17947 [Mercure] Remove outdated authorization section
  mercure.rst
Labels: Status: Reviewed, Mercure

#17878 [Workflow] Do not talk about registry
  components/workflow.rst
Labels: Status: Reviewed, Workflow

#17445 [Console] Fix incorrect example for `CommandCompletionTester`
  console/input.rst
Labels: Console, Status: Reviewed

#17809 Update "Web debug toolbar" profiler docs
  profiler.rst
Labels: Status: Reviewed

#17639 [DependencyInjection] Allow injecting the current env into php config closures
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#17576 [DependencyInjection] Remove not implemented behavior
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#17536 clarify that Bundle and AbstractBundle are different
  bundles/configuration.rst
Labels: Status: Reviewed

#17943 [DependencyInjection] Allow trimming service parameters value in XML configuration files
  configuration.rst
Labels: DependencyInjection, Status: Reviewed

#17951 [FrameworkBundle] Add `framework.http_cache.skip_response_headers` option
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#17960 [DependencyInjection] Add `#[Exclude]` attribute
  service_container.rst
Labels: DependencyInjection, Status: Reviewed

#17957 [Mailer] Adding the `sandbox` option in Mailjet API
  mailer.rst
Labels: Status: Reviewed, Mailer

#17933 [DependencyInjection] Autoconfigurable attributes
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#17955 [Validator] Add the option `filenameMaxLength` to the File constraint
  reference/constraints/File.rst
Labels: Validator, Status: Reviewed

#17967 [HttpClient] Add `UriTemplateHttpClient`
  http_client.rst
Labels: Status: Reviewed, HttpClient

#17928 [Notifier] Add Pushover bridge
  notifier.rst
Labels: Status: Needs Review, Notifier

#17976 [Mailer] Sort providers alphabetically
  mailer.rst
Labels: Status: Needs Review, Mailer

#17977 [Logger] Add placeholders for dynamic data
  logging.rst
Labels: Logger, Status: Reviewed
