Repository symfony/symfony-docs, pull requests merged in 2024-07, with the labels that each got.

#20007 Fix name of a parameter
  reference/constraints/Url.rst
Labels: Status: Reviewed

#20005 [Validator] Update Url for changing the default value of the requireTld option
  reference/constraints/Url.rst
Labels: Validator, Status: Reviewed

#20006 [DependencyInjection] Deprecate TaggedIterator and TaggedLocator attributes
  reference/attributes.rst
  service_container/service_subscribers_locators.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#20009 Remove the recipes team
  contributing/code/core_team.rst
Labels: Status: Reviewed

#20010 By default Symfony also loads the routes defined in PHP format
  routing.rst
Labels: Status: Needs Review

#20008 [Form] Mention that enabling CSRF in forms will start sessions
  security/csrf.rst
  session.rst
Labels: Form, Status: Needs Review

#20013 [Security] Update impersonating_user.rst remove unneeded space
  security/impersonating_user.rst
Labels: Security, Status: Reviewed

#19554 [TypeInfo] Add documentation
  components/type_info.rst
Labels: Status: Reviewed, TypeInfo

#20015 Fix typo in the new TypeInfo docs
  components/type_info.rst
Labels: Status: Reviewed

#20018 [Notifier] Add Sipgate bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#20016 Add a short mention to apache-pack in the web server docs
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#20025 Remove broken link to apc documentation
  performance.rst
Labels: Status: Reviewed

#20022 [DependencyInjection] Fix typo in docs
  components/dependency_injection/compilation.rst
Labels: DependencyInjection, Status: Needs Review

#20027 [Workflow] add missing word
  components/workflow.rst
Labels: Status: Needs Review, Workflow

#20026 [Notifier] Remove gitter
  notifier.rst
Labels: Status: Reviewed, Notifier

#20017 [TypeInfo] Better explain the `getBaseType()` method
  components/type_info.rst
Labels: Status: Needs Review, TypeInfo

#20033 [Notifier] Follow-Up with GoIP renaming
  notifier.rst
Labels: Status: Reviewed, Notifier

#20040 [Mercure] fix service definition example in testing section
  mercure.rst
Labels: Status: Reviewed, Mercure

#20038 [String] Add TruncateMode mode to truncate methods
  string.rst
Labels: Status: Reviewed, String

#20042 Update security.rst
  security.rst
Labels: Status: Needs Review

#20031 [Finder] Add a note to the followLinks method
  components/finder.rst
Labels: Status: Reviewed, Finder

#20046 [HttpClient] send necessary HTTP headers
  http_client.rst
Labels: Status: Reviewed, HttpClient

#20012 [Best Practices] Clarify not using the Config component for app configuration
  best_practices.rst
Labels: Status: Reviewed

#20044 [Config] Clarify the purpose of the Config component
  components/config.rst
Labels: Config, Status: Reviewed

#20043 Fix the parameter configuration in the file upload doc
  controller/upload_file.rst
Labels: Status: Reviewed

#20049 Fix typo
  service_container/service_subscribers_locators.rst
Labels: Status: Reviewed

#20047 [Validator] Add the `WordCount` constraint
  reference/constraints/WordCount.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#20045 [HttpClient] Document usage or user:pass@example.com for Basic Auth
  http_client.rst
Labels: Status: Needs Review, HttpClient

#20051 [TypeInfo] fix typos
  components/type_info.rst
Labels: Status: Reviewed, TypeInfo

#20053 use the ref role for internal links
  reference/events.rst
Labels: Status: Reviewed

#20054 [Messenger] use a custom batch size
  messenger.rst
Labels: Status: Reviewed, Messenger

#20056 Document Symfony CLI autocompletion
  console.rst
  setup/symfony_server.rst
Labels: Status: Needs Review

#20055 [Config] Secrets decrypt exit option
  configuration/secrets.rst
Labels: Config, Status: Reviewed

#20058 drop the --exit option
  configuration/secrets.rst
Labels: Status: Reviewed

#20052 Remove Doctrine mappings YML from documentation
  .doctor-rst.yaml
  reference/configuration/doctrine.rst
Labels: Status: Needs Review

#19889 Update advice
  testing.rst
Labels: Status: Reviewed

#20059 [Validator] drop type-hints for properties where the ´Type´ constraint is used
  reference/constraints/Type.rst
Labels: Validator, Status: Reviewed

#19183 Update `Create Framework / Unit Testing` page
  create_framework/unit_testing.rst
Labels: Status: Reviewed

#20060 [Security] Update csrf.rst
  security/csrf.rst
Labels: Security, Status: Reviewed

#19597 Fix debug config reference dump_destination
  reference/configuration/debug.rst
Labels: Status: Reviewed

#20065 Fix a PHP config example
  reference/configuration/debug.rst
Labels: Status: Reviewed

#20071 fix the syntax of PHP code block
  configuration/micro_kernel_trait.rst
Labels: Status: Reviewed

#20067 style: Typo in database.rst title
  testing/database.rst
Labels: Status: Needs Review

#20073 [Cache] Igbinary extension is no longer used by default when available
  components/cache.rst
Labels: Status: Reviewed, Cache

#20074 fix dump destination value in PHP config
  reference/configuration/debug.rst
Labels: Status: Reviewed

#20079 style: Typo in content title
  testing/database.rst
Labels: Status: Needs Review

#20021 Update configuration.rst
  bundles/configuration.rst
Labels: Status: Reviewed

#20083 Minor tweak in the setup page
  setup.rst
Labels: Status: Reviewed
