Repository symfony/symfony-docs, pull requests merged in 2024-08, with the labels that each got.

#20085 [Messenger][Scheduler] Fix ScheduledStamp FQN
  components/messenger.rst
Labels: Status: Needs Review, Messenger, Scheduler

#20084 example function param 1 requires string
  components/var_dumper.rst
Labels: Status: Reviewed

#20089 [Validator] clarify how to disable client-side validation using the Regex constraint
  reference/constraints/Regex.rst
Labels: Validator, Status: Reviewed

#20077 [DomCrawler] fixes typo `Form::getFields()` -> `Form::getFiles()`
  testing.rst
Labels: bug, Status: Reviewed, DomCrawler

#20095 Update reproducer.rst: Minor rewording
  contributing/code/reproducer.rst
Labels: Status: Reviewed

#20096 Update Cidr.rst
  reference/constraints/Cidr.rst
Labels: Status: Reviewed

#20097 ensure consistency of Symfony and standalone session code block
  session.rst
Labels: Status: Reviewed

#20070 [Cache] Add information about clock parameter in ArrayAdapter
  components/cache/adapters/array_cache_adapter.rst
Labels: Status: Reviewed, Cache

#20099 [Validator] Mention `Ulid::FORMAT_RFC4122`
  reference/constraints/Ulid.rst
Labels: Validator, Status: Reviewed

#20082 [HttpFoundation] [http-foundation] Check if ip is in cidr subnet
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#20100 [Validator] Add links to Ulid constraint formats
  reference/constraints/Ulid.rst
Labels: Validator, Status: Reviewed

#20102 minor : the process method from CompilerPassInterface should be public
  testing.rst
Labels: Status: Reviewed

#20101 doc: add missing use statements
  configuration/multiple_kernels.rst
Labels: Status: Reviewed

#19574 Update service_container.rst
  service_container.rst
Labels: Status: Needs Review

#20088 [Mailer] Update mailer.rst with Postal mailer
  mailer.rst
Labels: Status: Reviewed, Mailer

#20105 templates: check that a Twig extension does *not* already exist
  templates.rst
Labels: Status: Reviewed

#20135 document the requests constructor argument of the RequestStack class
  components/form.rst
Labels: Status: Reviewed

#20127 [Uid] Add support for binary, base-32 and base-58 representations in `Uuid::isValid()`
  components/uid.rst
Labels: Status: Reviewed, Uid

#20128 [Serializer] Deprecate passing a non-empty CSV escape char
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#20139 Fix `:ref:` links
  messenger.rst
Labels: Status: Needs Review

#20136 feat(mailer): Add Sweego Mailer doc
  mailer.rst
  webhook.rst
Labels: Status: Reviewed

#20113 Correction of a typo for a reference link
  messenger.rst
Labels: Status: Reviewed

#20144 fix ref syntax
  components/expression_language.rst
Labels: Status: Reviewed

#20158 [ExpressionLanguage] Add support for `<<`, `>>`, and `~` bitwise operators
  reference/formats/expression_language.rst
Labels: Status: Reviewed, ExpressionLanguage

#20155 [Serializer] Correction of examples using the attributes groups
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#20142 [Translation] Add labels for links in translations page
  translation.rst
Labels: Status: Reviewed, Translation

#20147 [Serializer] add nullable format to defaultContext circularReference handler to prevent normalize error
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#20162 [Security] adding missing 'private'
  security.rst
Labels: Security, Status: Needs Review

#20117 Add the missing note on how to inject a service into the controller
  controller.rst
Labels: Status: Reviewed

#20138 [HttpFoundation] Add new parameters to `IpUtils::anonymize()`
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#20145 [Form] Add support for the `calendar` option in `DateType`
  reference/forms/types/date.rst
Labels: Form, Status: Reviewed

#20157 [Templating] [Template] Render a block with the `#[Template]` attribute
  templates.rst
Labels: Templating, Status: Reviewed

#20110 [Validator] Add `Week` constraint
  reference/constraints/Week.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Needs Review

#20149 [Security] complete list of support content types
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#20165 [Serializer] add missing use statement
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#20141 [Config] Match Yaml configuration and Tree
  components/config/definition.rst
Labels: Config, Status: Reviewed

#20150 [Validator] Add `CompoundConstraintTestCase` to ease testing Compound constraints
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#20108 Add links for the better nav in the format specification refs
  reference/formats/expression_language.rst
  reference/formats/message_format.rst
  reference/formats/yaml.rst
Labels: Status: Reviewed

#20118 [Scheduler] Add capability to skip missed periodic tasks, only the last schedule will be called
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#20121 [Messenger] fix comment
  messenger.rst
Labels: Status: Reviewed, Messenger

#20112 [Workflow] Do to talk about workflow, and explain what support option is for
  components/workflow.rst
  workflow/workflow-and-state-machine.rst
Labels: Status: Reviewed, Workflow

#20107 [Security] fix: propose a better header naming for custom authenticator
  security/custom_authenticator.rst
Labels: Security, Status: Reviewed

#20163 [Validator] Add errorPath to Unique constraint
  reference/constraints/Unique.rst
Labels: Validator, Status: Reviewed

#20161 [Serializer] Normalizer Callback params confusion: $innerObject should be called $attributeValue and $outerObject should be just $object
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#20000 [Profiler] Improve a part of the profiler docs
  profiler.rst
Labels: Profiler, Status: Reviewed

#20169 [ExpressionLanguage] Fix uncaught ArgumentCountError
  components/expression_language.rst
Labels: Status: Reviewed, ExpressionLanguage

#20153 Use DOCtor-RST 1.62.2 and new `no_broken_ref_directive` rule
  .doctor-rst.yaml
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#20076 [Notifier] Create `DesktopChannel` and `JoliNotif` bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#20171 [CI] Use DOCtor-RST 1.62.3
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#20172 [CI] Use `actions/checkout@v4`
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#20170 [Notifier] Misc. minor tweaks
  notifier.rst
Labels: Status: Reviewed, Notifier

#20120 [Security] Remove note about stateless firewalls marking routes as stateless
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#20174 chore: relocate the sqlite note block in a better place
  doctrine.rst
Labels: Status: Needs Review

#20175 [Ldap] feat: remove mention of FOSUserBundle in doc
  security/ldap.rst
Labels: Status: Reviewed, Ldap

#20176 [FrameworkBundle] Lower uppercase `must`
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle
