Repository symfony/symfony-docs, pull requests merged in 2024-04, with the labels that each got.

#19722 [VarExporter] Remove "lazyObjectId" from LazyGhostTrait because it doesn't seem to do anything
  components/var_exporter.rst
Labels: Status: Reviewed, VarExporter

#19697 [Console] Add doc about lockableTrait
  console/lockable_trait.rst
Labels: Console, Status: Reviewed

#19721 [HttpKernel] Update micro_kernel_trait.rst
  configuration/micro_kernel_trait.rst
Labels: Status: Needs Review, HttpKernel

#19711 [ExpressionLanguage] Update the docs about the null-coalescing operator
  components/expression_language.rst
  reference/formats/expression_language.rst
Labels: ExpressionLanguage, Status: Needs Review

#19710 [Uid] Expand the explanation about the different UUID variants
  components/uid.rst
Labels: Status: Needs Review, Uid

#19723 [Serializer] Mention `AbstractNormalizer::FILTER_BOOL`
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#19732 [Configuration] Clarify `variables_order`
  configuration.rst
Labels: Status: Needs Review

#19733 fix: typo in reverse proxy docs
  deployment/proxies.rst
Labels: Status: Reviewed

#19734 Use Doctor RST 1.59.0
  .doctor-rst.yaml
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#19729 [FrameworkBundle][HttpClient] Add ThrottlingHttpClient
  http_client.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle, HttpClient

#19737 [FrameworkBundle] Remove mention of inexistant `ignore_cache` option
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#19741 [Uid] Update some RST syntax
  components/uid.rst
Labels: Status: Reviewed, Uid

#19736 [Emoji] Add the gitlab locale
  string.rst
Labels: Status: Reviewed, Emoji

#19757 Remove the warning marking the symfony server config file as experimental
  setup/symfony_server.rst
Labels: Status: Reviewed

#19743 [Serializer] Fix punctuation in custom encoders docs
  serializer/custom_encoders.rst
Labels: Status: Reviewed, Serializer

#19759 Document Symfony CLI `--no-workers` option
  setup/symfony_server.rst
Labels: Status: Reviewed

#19760 Fix wrong URL for Twig Environment
  templates.rst
Labels: Status: Reviewed

#19765 [Validator] feat: add warning for number constraints with PHP 7.x
  reference/constraints/GreaterThan.rst
  reference/constraints/GreaterThanOrEqual.rst
  reference/constraints/LessThan.rst
  reference/constraints/LessThanOrEqual.rst
  reference/constraints/Negative.rst
  reference/constraints/NegativeOrZero.rst
  reference/constraints/Positive.rst
  reference/constraints/PositiveOrZero.rst
  reference/constraints/_php7-string-and-number.rst.inc
Labels: Validator, Status: Reviewed

#19763 [Testing] Fix nullable entitymanager in functional repository tests
  testing/database.rst
Labels: Testing, Status: Reviewed

#19754 Add more hints when using Symfony CLI in Windows
  setup/symfony_server.rst
Labels: Status: Reviewed

#19718 [Workflow] Add Doctrine type information for multiple state marking stores
  workflow.rst
Labels: Status: Reviewed, Workflow

#19767 [DependencyInjection] `ServiceSubscriberTrait` is deprecated and replaced by `ServiceMethodsSubscriberTrait`
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#19768 [Clock] Document createFromTimestamp() method
  components/clock.rst
Labels: Status: Reviewed, Clock

#19775 [Mailer] Add the `allowed_recipients` option
  mailer.rst
Labels: Mailer

#19774 [Twig] Expand the explanation about the humanize filter
  reference/twig_reference.rst
Labels: Twig

#19762 add documention for signed URI expiration
  routing.rst
Labels: Status: Reviewed

#19780 Refactor Request object documentation and redefine method logic
  controller.rst
Labels: Status: Needs Review

#19787 [CS] Fix more nullable types
  components/expression_language.rst
  components/serializer.rst
  controller/error_pages.rst
  form/dynamic_form_modification.rst
  frontend/custom_version_strategy.rst
  http_client.rst
  messenger.rst
  messenger/custom-transport.rst
  notifier.rst
  profiler.rst
  reference/constraints/File.rst
  reference/constraints/Image.rst
  reference/forms/types/collection.rst
  routing/custom_route_loader.rst
  security/access_denied_handler.rst
  security/login_link.rst
  serializer/custom_normalizer.rst
  validation/custom_constraint.rst
Labels: Status: Reviewed

#19786 [Testing] Update nullable types
  testing.rst
Labels: Testing, Status: Reviewed

#19781 Update php version in web_server_configuration.rst
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#19783 [Uid] Add a caution message about using UUIDs as primary keys
  components/uid.rst
Labels: Status: Needs Review, Uid

#19784 [Validator] Add support for types (`ALL*`, `LOCAL_*`, `UNIVERSAL_*`, `UNICAST_*`, `MULTICAST_*`, `BROADCAST`) in `MacAddress` constraint
  reference/constraints/MacAddress.rst
Labels: Validator, Status: Reviewed

#19739 [DependencyInjection] Discourage appending config on prepend extension method
  bundles/prepend_extension.rst
Labels: DependencyInjection, Status: Reviewed

#19713 [Console] Mention `ArgvInput::getRawTokens`
  console/input.rst
Labels: Console, Status: Needs Review

#19738 [DependencyInjection] Updating prepend extension capabilities
  bundles/prepend_extension.rst
Labels: DependencyInjection, Status: Reviewed

#19791 [Scheduler] Remove incorrect mention of subtracting time from jitter
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19792 [AssetMapper][Encore] document switching from AssetMapper to Encore
  frontend.rst
Labels: Status: Reviewed, Encore, AssetMapper

#19692 [Notifier] LOX24 SMS Gateway Notifier
  notifier.rst
Labels: Status: Reviewed, Notifier

#19764 Documenting items type in the MapRequestPayload attribute
  controller.rst
Labels: Status: Reviewed

#19790 Use DOCtor-RST 1.60.1
  .doctor-rst.yaml
  .github/workflows/ci.yaml
  validation/custom_constraint.rst
Labels: Status: Reviewed

#19796 [CS] Fix explicit nullable types
  create_framework/separation_of_concerns.rst
  create_framework/templating.rst
  reference/dic_tags.rst
  reference/forms/types/enum.rst
  serializer/custom_context_builders.rst
  validation/custom_constraint.rst
Labels: Status: Needs Review

#19794 Add ENV processor example
  service_container/autowiring.rst
Labels: Status: Needs Review

#19797 Fix Explicite nullable types (7.0)
  testing.rst
Labels: Status: Needs Review

#19798 fix warning for number constraints with PHP 7.x
  reference/constraints/_php7-string-and-number.rst.inc
Labels: Status: Reviewed

#19819 [DependencyInjection] Add `#[AutowireMethodOf]` attribute
  reference/attributes.rst
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#19778 [Workflow] Update code block according to its implementation
  workflow.rst
Labels: Status: Reviewed, Workflow

#19771 Update session.rst
  session.rst
Labels: Status: Needs Review

#19805 Add a better example of the dangers of XSS attacks
  reference/configuration/framework.rst
  reference/configuration/twig.rst
  templates.rst
Labels: Status: Reviewed

#19810 [Webhook] show `make:webhook`
  webhook.rst
Labels: Status: Reviewed, Webhook

#19777 [FrameworkBundle][Routing] Update the `enabled_locales` description
  reference/configuration/framework.rst
Labels: Routing, Status: Reviewed, FrameworkBundle

#19823 Disable a validation rule in the docs linter
  .doctor-rst.yaml
Labels: Status: Needs Review

#19793 [Bundles] Promote the new bundle structure everywhere
  bundles.rst
  bundles/configuration.rst
  bundles/extension.rst
Labels: Status: Reviewed, Bundles

#19824 [Scheduler] fix dead link with correct once
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19826 [Scheduler] Add missing filename
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19779 [Security] Update `OidcTokenHandler` dependencies and configuration
  security/access_token.rst
Labels: Security, Status: Reviewed

#19742 [Messenger] docs(messenger): encodedEnvelope is already an array
  messenger.rst
Labels: Status: Reviewed, Messenger

#19822 Upload Files: Removing `getParameter()`
  controller/upload_file.rst
Labels: Status: Reviewed

#19829 [Scheduler] fix dead link with correct once, again
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19830 Fix indentation
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#19828 use option name as link label
  forms.rst
Labels: Status: Reviewed

#19831 Use PHP 8.2 for build
  .github/workflows/ci.yaml
Labels: Status: Needs Review
