Repository symfony/symfony-docs, pull requests merged in 2024-03, with the labels that each got.

#19621 [Console] Add upercases to match console output
  components/console/usage.rst
Labels: Console, Status: Reviewed

#19539 [AssetMapper] Minor
  frontend/asset_mapper.rst
Labels: Status: Needs Review, AssetMapper

#19623 Replace Annotation\Route with Attribute\Route
  cache.rst
  configuration/micro_kernel_trait.rst
  controller.rst
  controller/service.rst
  controller/upload_file.rst
  controller/value_resolver.rst
  doctrine.rst
  doctrine/associations.rst
  mailer.rst
  page_creation.rst
  quick_tour/flex_recipes.rst
  quick_tour/the_architecture.rst
  quick_tour/the_big_picture.rst
  routing.rst
  security.rst
  security/login_link.rst
  service_container.rst
  service_container/autowiring.rst
  templates.rst
Labels: Status: Reviewed

#19625 [AssetMapper] Shortening "Optimizing Performance"
  frontend/asset_mapper.rst
Labels: Status: Needs Review, AssetMapper

#19630 [AssetMapper] Merging `outdated` and `update` CLI codeblocks
  frontend/asset_mapper.rst
Labels: Status: Needs Review, AssetMapper

#19628 [AssetMapper] Recommending `Cache-Control` instead of `Expires` HTTP header
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19620 [Cache] Update github link for method in Redis adapter
  components/cache/adapters/redis_adapter.rst
Labels: Status: Reviewed, Cache

#19615 PostgreSQL setparameter() compatibility
  components/uid.rst
Labels: Status: Needs Review, Waiting feedback

#19632 [AssetMapper] Remove outdated directive from documentation
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19636 [Notifier] Fix typo in a section title
  notifier.rst
Labels: Status: Reviewed, Notifier

#19633 [Translation] Add Phrase in translation providers dsn list
  translation.rst
Labels: Status: Reviewed, Translation

#19641 [Mailer] Remove "click here" from links
  mailer.rst
Labels: Status: Reviewed, Mailer

#19569 [AssetMapper] Changing the example file away from `.css`
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19642 [Mailer] Fix missing backtick
  mailer.rst
Labels: Status: Needs Review, Mailer

#19643 [Templating] [Templates] Replace Webpack with AssetMapper (minor)
  templates.rst
Labels: Templating, Status: Reviewed

#19647 Update contributing/code/tests.rst page
  contributing/code/tests.rst
Labels: Status: Reviewed

#19650 keep use statement for the Response class
  quick_tour/flex_recipes.rst
Labels: Status: Reviewed

#19651 [Clock] update method names to reflect latest code changes
  components/clock.rst
Labels: Status: Reviewed, Clock

#19652 Update PHP version in "Install the Software Stack" section
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#19653 Update PHP version in "Install the Software Stack" section
  contributing/code/pull_requests.rst
Labels: Status: Reviewed

#19489 [Emoji] Emoji component
  components/emoji.rst
  components/intl.rst
Labels: Status: Reviewed, Emoji

#19658 [Ldap] Adds return value hint of `LdapUser::getExtraFields()`
  security/ldap.rst
Labels: Ldap, Status: Needs Review

#19670 [Logger] Using LogLevel `const`s
  logging.rst
Labels: Logger, Status: Reviewed

#19656 [String] Reorganize String component contents
  _build/redirection_map
  components/intl.rst
  string.rst
Labels: Status: Reviewed, String

#19666 [Messenger] Mention `ScheduledStamp`
  components/messenger.rst
  scheduler.rst
Labels: Status: Reviewed, Messenger

#19667 [Scheduler] Mention `Scheduler` worker
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19672 [Logger] Using LogLevel `const`s, Part 2
  logging.rst
Labels: Logger, Status: Reviewed

#19520 [DependencyInjection] Add readonly statement to the Lazy Services docs
  service_container/lazy_services.rst
Labels: DependencyInjection, Status: Needs Review

#19677 Use DoctorRST 1.57.1
  .doctor-rst.yaml
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#19685 Remove the report section (CARE team page)
  contributing/code_of_conduct/care_team.rst
Labels: Status: Reviewed

#19674 [Security] Replace a complex table by a list
  security/access_control.rst
Labels: Security, Status: Reviewed

#19664 [Workflow] Attach workflow configuration to tags
  service_container/tags.rst
  workflow.rst
Labels: Status: Reviewed, Workflow

#19689 [Filesystem] Document the readFile() method
  components/filesystem.rst
Labels: Status: Reviewed, Filesystem

#19473 [Frontend] Some smaller updates
  frontend/encore/server-data.rst
Labels: Status: Reviewed, front-end

#19691 Improve the formatting of the lists of special characters
  components/cache/cache_items.rst
  doctrine.rst
  mailer.rst
  notifier.rst
  reference/formats/yaml.rst
Labels: Status: Needs Review

#19690 [Frontend] Move some page from Encore to Frontend
  _build/redirection_map
  frontend.rst
  frontend/encore/index.rst
  frontend/server-data.rst
Labels: front-end, Status: Needs Review

#19678 Fixes async cache computation example and FQCN
  cache.rst
Labels: Status: Reviewed

#19506 [DependencyInjection] Add `#[Lazy]` attribute
  reference/attributes.rst
  service_container/lazy_services.rst
Labels: DependencyInjection, Status: Needs Review

#19696 [Form] Fix the default value for the constraints option of forms
  reference/forms/types/options/constraints.rst.inc
Labels: Form, Status: Reviewed

#19541 [5.4] add note about newer version on the “upgrade major” guide
  setup/upgrade_major.rst
Labels: Status: Reviewed

#19698 [DependencyInjection] Update shared.rst to add doc on PHP attributes
  service_container/shared.rst
Labels: DependencyInjection, Status: Needs Review

#19675 doc: Access Token Authentication - added a disambiguation on what the identifier is
  security/access_token.rst
Labels: Status: Needs Review

#19564 [AssetMapper] Adding updater to comparison table
  frontend.rst
Labels: Status: Reviewed, AssetMapper

#19708 [AssetMapper] Removing orphaned footnote [2]
  frontend.rst
Labels: Status: Reviewed, AssetMapper

#19712 Add missing word
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#19706 [Workflow] Document the EventNameTrait
  workflow.rst
Labels: Status: Needs Review, Workflow

#19715 [MakerBundle] `make:migration` supports --formatted option
  doctrine.rst
  security.rst
Labels: Status: Reviewed

#19714 [MakerBundle] document --with-uuid & --with-ulid
  doctrine.rst
  doctrine/associations.rst
  security.rst
  security/passwords.rst
Labels: Status: Reviewed
