Repository symfony/symfony-docs, pull requests merged in 2024-05, with the labels that each got.

#19834 [Routing] rewrite the routing introduction
  quick_tour/the_big_picture.rst
Labels: Routing, Status: Reviewed

#19832 [Scheduler] Fix code sample
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19839 [Form] rename the model_type option to input
  reference/forms/types/money.rst
Labels: Form, Status: Reviewed

#19840 [Bundles] Fix typo in bundles/extension.rst
  bundles/extension.rst
Labels: Status: Reviewed, Bundles

#19853 [Twig] deprecate the base_template_class option
  reference/configuration/twig.rst
Labels: Status: Reviewed, Twig

#19856 Update controller.rst, fix use statement App\Model\UserDto
  controller.rst
Labels: Status: Reviewed

#19861 [Bundles] [Bundle] Fix Bundle configuration/service key
  bundles/configuration.rst
Labels: Status: Reviewed, Bundles

#19859 [Logger] Fix group handler name
  logging/monolog_email.rst
Labels: Logger, Status: Needs Review

#19850 [Cache] Small correction in the use of tags in the cache
  cache.rst
Labels: Status: Reviewed, Cache

#19867 The #[IsCsrfTokenValid] attribute eliminates the need for a request parameter in your method.
  security/csrf.rst
Labels: Status: Reviewed

#19866 [Validator] Misc tweaks in MacAddress and Charset constraints
  reference/constraints/Charset.rst
  reference/constraints/MacAddress.rst
Labels: Validator, Status: Reviewed

#19865 [AssetMapper] Document how to make it work with a Content Security Policy
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19871 [Messenger] Add missing asterisk
  messenger.rst
Labels: Status: Reviewed, Messenger

#19862 [Security] Improve the docs related to CSRF
  security/csrf.rst
Labels: Security, Status: Needs Review

#19870 [Security] Add support for dynamic CSRF id with Expression in `#[IsCsrfTokenValid]`
  security/csrf.rst
Labels: Security, Status: Reviewed

#19873 Extend AbstractBundle instead of Bundle
  bundles/best_practices.rst
  service_container/compiler_passes.rst
Labels: Bundles

#19860 [ExpressionLanguage] Add operators precedence documentation
  reference/formats/expression_language.rst
Labels: ExpressionLanguage, Status: Needs Review

#19874 Update kernel.rst: Adding example for `kernel.project_dir`
  reference/configuration/kernel.rst
Labels: Status: Reviewed

#19879 [String] add named arguments
  components/string.rst
Labels: Status: Needs Review, String

#19887 [Scheduler] Small type fixes for scheduler.rst
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19880 [Templates] Recommend Asset Mapper instead of Webpack
  templates.rst
Labels: Status: Reviewed

#18155 [Serializer] Add documentation about a new XmlEncoder CDATA wrapping opt-out context option
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#19881 Move Doctrine constraints out of Other constraints
  reference/constraints/map.rst.inc
Labels: Status: Needs Review

#19882 Document strange JsonResponse constructor behaviour
  components/http_foundation.rst
Labels: Status: Needs Review

#19883 [Serializer] Add missing XML serializer's CDATA options
  components/serializer.rst
Labels: Serializer, Status: Needs Review

#19891 [Console] Add other pre-defined block styles
  components/console/helpers/formatterhelper.rst
Labels: Console, Status: Reviewed

#19898 Remove redundant parenthesis on attribute
  event_dispatcher.rst
Labels: Status: Reviewed

#19894 fix expression language precedence cell grouping
  reference/formats/expression_language.rst
Labels: Status: Reviewed

#19905 [AssetMapper] Remove Cloudflare auto-minify links
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19892 [Notifier] Change the structure of the table listing the notifiers
  notifier.rst
Labels: Status: Reviewed, Notifier

#19890 Add extra information on AsEventListener attribute usage
  event_dispatcher.rst
Labels: Status: Reviewed

#19864 [Reference] Replace param converter with value resolver
  reference/events.rst
Labels: Status: Reviewed

#19911 [FrameworkBundle] Add support for setting headers with `TemplateContoller`
  templates.rst
Labels: Status: Reviewed, FrameworkBundle

#19913 [Stopwatch] Add `getLastPeriodà method to `StopwatchEvent`
  performance.rst
Labels: Status: Reviewed, Stopwatch

#19912 [Stopwatch] Add `ROOT` constant to make it easier to reference
  performance.rst
Labels: Status: Reviewed, Stopwatch

#19914 [PropertyAccess] implement `__isset()` together with `__get()`
  components/property_access.rst
Labels: PropertyAccess, Status: Needs Review

#19917 Use Doctor RST 1.61.1
  .doctor-rst.yaml
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#19923 [Dotenv] Fix `SYMFONY_DOTENV_PATH` purpose
  configuration.rst
Labels: Status: Reviewed, Dotenv

#19920 [Form] Move some docs from the Choice constraint to the ChoiceType
  reference/constraints/Choice.rst
  reference/forms/types/choice.rst
Labels: Form, Status: Reviewed

#19919 [Emoji] Add the text locale
  string.rst
Labels: Status: Needs Review, Emoji

#19931 [Scheduler] remove example using not existing timezone property
  scheduler.rst
Labels: Status: Reviewed, Scheduler
