Repository symfony/symfony-docs, pull requests merged in 2024-01, with the labels that each got.

#19361 Fix heading capitalisation in dynamic_form_modification.rst
  form/dynamic_form_modification.rst
Labels: Status: Reviewed

#19354 [Security] Fixing PHP example for limiting login attempts with rate limiter
  security.rst
Labels: Security, Status: Reviewed

#19272 Update Docker page with instructions for Mac users
  setup/docker.rst
Labels: Status: Needs Review

#17595 [Security] Update locale with new authentication system
  session.rst
Labels: Security, Status: Reviewed

#17934 [Mailer] Switching to new config format
  mailer.rst
Labels: Status: Needs Review, Mailer

#19362 [Uid] Add `UuidV1::toV6()`, `UuidV1::toV7()` and `UuidV6::toV7()`
  components/uid.rst
Labels: Status: Reviewed, Uid

#19367 [Doctrine] Fix #[MapEntity(expr: '...')]
  doctrine.rst
Labels: Doctrine, Status: Needs Review

#19369 [Encore] Update note instructing users to upgrade symfony-cli for node.js 17+ tls compatibility
  frontend/encore/dev-server.rst
Labels: Status: Reviewed, Encore

#19375 Update controller.rst
  controller.rst
Labels: Status: Needs Review

#19371 [Dotenv] Add `SYMFONY_DOTENV_PATH`
  configuration.rst
Labels: Status: Reviewed, Dotenv

#19379 [Validator] Fix missing semicolon for `Choice` constraint documentation
  reference/constraints/Choice.rst
Labels: Validator, Status: Reviewed

#19381 [Serializer] Fix encoder options
  components/serializer.rst
Labels: Status: Reviewed, Serializer

#19383 [Validator] Add `MacAddress` constraint
  reference/constraints/MacAddress.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#19385 [FrameworkBundle] add a private_ranges shortcut for trusted_proxies
  deployment/proxies.rst
Labels: Status: Reviewed, FrameworkBundle

#19386 [Uid] Add `AbstractUid::toString()`
  components/uid.rst
Labels: Status: Reviewed, Uid

#19391 use PHP 8.2 for Symfony 7 builds
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#19393 [Security] fix getUser function link
  security.rst
Labels: Security, Status: Reviewed

#19399 [FrameworkBundle] Update `cache_dir` config
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#19403 [Doctrine] Mapping types link
  doctrine.rst
Labels: Doctrine, Status: Reviewed

#19392 [Validator] update default message
  reference/constraints/MacAddress.rst
Labels: Validator, Status: Reviewed

#19398 [Config] Update configuration.rst for example config builder ide helper
  configuration.rst
Labels: Config, Status: Needs Review

#19409 Update README.md
  README.md
Labels: Status: Reviewed

#19410 [Form] Add option `separator` to `ChoiceType` to use a custom separator after preferred choices
  reference/constraints/Choice.rst
Labels: Form, Status: Reviewed

#19406 [Doctrine] Profiler bar only visible with at least tags `<body></body>`
  doctrine.rst
Labels: Doctrine, Status: Needs Review

#19405 [Doctrine] Automapping validation example seems broken
  doctrine.rst
Labels: Doctrine, Status: Needs Review

#19408 [Doctrine] The use of `doctrine.orm.controller_resolver.auto_mapping`
  doctrine.rst
Labels: Doctrine, Status: Needs Review

#19411 [Translation] Mention `enabled_locales`
  translation.rst
  validation/translations.rst
Labels: Status: Reviewed, Translation

#19373 [Console] [components] add information about the addRows method - table.rst
  components/console/helpers/table.rst
Labels: Console, Status: Reviewed

#19370 [Contracts][DependencyInjection] Add `ServiceCollectionInterface`
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed, Contracts

#19177 [Security] Explicit check route option for loginlink usage
  security/login_link.rst
Labels: Security, Status: Reviewed

#19176 [EventDispatcher] Update learn more link for event dispatcher component
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Needs Review

#19416 [Cache] Document using DSN with PDOAdapter
  cache.rst
Labels: Status: Reviewed, Cache

#19418 [Validator] Fix `mb_detect_encoding` link in `Charset`
  reference/constraints/Charset.rst
Labels: Validator, Status: Reviewed

#19359 [Form] Add `model_type` option to `MoneyType`
  reference/forms/types/money.rst
Labels: Form, Status: Needs Review

#19342 [DependencyInjection] Add a note about configuring controllers without autowire/autoconfigure
  controller/service.rst
Labels: DependencyInjection, Status: Reviewed

#19102 Revert "Fix the installation instructions of symfony/psr-http-message-bridge"
  components/psr7.rst
Labels: Status: Reviewed

#19420 [Frontend] Removing praise
  frontend.rst
Labels: Status: Needs Review

#19419 Update frontend.rst: Minor
  frontend.rst
Labels: Status: Reviewed, front-end

#19244 [Scheduler] Proposal - initial structure for Symfony Scheduler documentation
  _images/components/messenger/basic_cycle.png
  _images/components/scheduler/generate_consume.png
  _images/components/scheduler/scheduler_cycle.png
  scheduler.rst
Labels: Status: Needs Review, Scheduler

#19425 [Scheduler] Emphasize `__toString()`
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19423 [Routing] [url generation] note on forcing https
  routing.rst
Labels: Routing, Status: Needs Review

#19422 [Proxy configuration] Add help for hidden SSL termination
  deployment/proxies.rst
Labels: Status: Needs Review

#19430 Fix 404 link in scheduler.rst
  scheduler.rst
Labels: Status: Reviewed

#19429 [Scheduler] Document hashed cron expressions
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19431 [Scheduler] Add `AbstractDecoratedTrigger`
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19413 [Workflow] Fix wrong variable name
  workflow/workflow-and-state-machine.rst
Labels: Workflow

#19396 [Security] [DOC] Update passwords.rst
  security/passwords.rst
Labels: Security, Status: Needs Review

#19374 [EventDispatcher] docs: document simpler event dispatching
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Needs Review

#19330 [EventDispatcher] Move note below and add examples
  components/event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#19394 [Testing] Update database.rst
  testing/database.rst
Labels: Testing, Status: Needs Review

#19321 match parameter names with AbstractBundle
  bundles/extension.rst
Labels: Status: Needs Review

#19297 [Notifier] Note about message bus usage in notification component
  notifier.rst
Labels: Status: Needs Review, Notifier

#19185 [Bundle] Sync doc pages with current Symfony codebase
  bundles.rst
  bundles/configuration.rst
  bundles/extension.rst
  templates.rst
Labels: Status: Needs Review

#18849 [Encore] webpack encore reset entrypointlookup
  frontend/encore/advanced-config.rst
Labels: front-end, Status: Needs Review, Encore

#19432 [Mailer] Add Resend bridge documentation
  mailer.rst
  webhook.rst
Labels: Status: Reviewed, Mailer

#19417 [Logger] Update ElasticsearchLogstashHandler documentation
  logging/handlers.rst
Labels: Logger, Status: Reviewed

#17137 Avoiding the term "login form"...
  security/login_link.rst
Labels: Status: Reviewed

#16561 Add information to sub request
  components/http_kernel.rst
Labels: Status: Reviewed

#16373 [Mailer] Add custom transport factories
  mailer.rst
Labels: Status: Reviewed, Mailer

#19447 Ask to open PRs for new features in 7.x
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Reviewed

#19442 [Scheduler] clarify idle state and stateful option
  scheduler.rst
Labels: Status: Needs Review, Scheduler

#19441 [Scheduler] Document hashed Cron expression
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19451 Update pull_requests.rst
  contributing/code/pull_requests.rst
Labels: Status: Needs Review

#19450 [Scheduler] Document events
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19292 [Scheduler] doc draft dynamic schedule
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19444 [Scheduler] Add `AsCronTask` and `AsPeriodicTask`
  reference/attributes.rst
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19448 [Security] Reword impersonnating event description
  security/impersonating_user.rst
Labels: Security, Status: Reviewed

#17481 [Security] WIP - make:security:form-login is now available in MakerBundle
  security.rst
Labels: Security, Status: Reviewed

#17507 [DependencyInjection] Changing `enum:` example away from APP_ENV
  configuration/env_var_processors.rst
Labels: DependencyInjection, Waiting team decision

#17444 Adding info about when the firewall needs to encompass all pages
  security.rst
Labels: Status: Needs Review

#19449 [Messenger] Clarify UnrecoverableMessageHandlingException message going to failure transport
  messenger.rst
Labels: Status: Reviewed, Messenger

#19454 [Scheduler] Fixes typos and adds more detail for specifying dates of schedule
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#19421 Tweak docs for Webhooks
  webhook.rst
Labels: Status: Reviewed

#19455 [Mailer] Add warning about custom SES headers
  mailer.rst
Labels: Status: Reviewed, Mailer

#19457 Update symfony_server.rst - create new line for better readability
  setup/symfony_server.rst
Labels: Status: Needs Review

#19458 [DependencyInjection] Update service_container.rst
  service_container.rst
Labels: DependencyInjection, Status: Needs Review

#19459 [AssetMapper] Mention `PublicAssetsFilesystemInterface`
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19456 [Upgrading] Recommend to delete cache when upgrading to a major version
  setup/upgrade_major.rst
Labels: Status: Reviewed

#19461 Replace `fetchAll()` by `fetchAllAssociative()` method
  reference/configuration/doctrine.rst
Labels: Status: Reviewed

#19462 [Messenger] Add caution message about messenger consume command and profiler
  console.rst
Labels: Status: Reviewed, Messenger

#19464 [Setup] Minor tweaks to setup related to the symfony cli
  setup.rst
Labels: Status: Needs Review

#19463 [Frontend] Adding info about comments
  frontend.rst
Labels: Status: Needs Review

#19470 Update service_decoration.rst
  service_container/service_decoration.rst
Labels: Status: Reviewed

#19471 [AssetMapper] Fixing path
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#19469 [Mailer] [Smtp] Document `auto_tls` param
  mailer.rst
Labels: Status: Reviewed, Mailer

#19377 [Dotenv] Fix incorrect way to modify .env path
  configuration.rst
Labels: Status: Reviewed, Dotenv
