Repository symfony/symfony-docs, pull requests merged in 2025-04, with the labels that each got.

#20777 [Serializer] Document named serializers
  serializer.rst
Labels: Serializer, Status: Needs Review

#20400 [DependencyInjection] Clarify documentation about differences between AutowireIterator and …
  service_container/service_subscribers_locators.rst
Labels: DependencyInjection, Status: Reviewed

#20652 [Translation] Explain how translation messages are merged among bundles
  translation.rst
Labels: Status: Reviewed, Translation

#20849 Readd handling of fallback of bundles directory in Apache config
  setup/web_server_configuration.rst
Labels: Status: Needs Review

#20850 [FrameworkBundle] Deprecate setting the `collect_serializer_data` to `false`
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#20622 [DependencyInjection] Update tags.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#20459 [Security] doc(security): add firewall lazy option
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#20656 [Messenger] Add consumer name documentation
  messenger.rst
Labels: Status: Reviewed, Messenger

#20479 [Serializer] Update serializer.rst
  serializer.rst
Labels: Status: Reviewed, Serializer

#20464 [Form] dynamic_form_modification - Update namespace related to EventSubscriber
  form/dynamic_form_modification.rst
Labels: Form, Status: Needs Review

#20418 [Twig] [twig reference] add examples to functions and filter
  reference/twig_reference.rst
Labels: Status: Reviewed, Twig

#20423 [Twig] [twig reference] add examples to functions (format_file, file_…
  reference/twig_reference.rst
Labels: Status: Reviewed, Twig

#20447 [Scheduler] Periodical triggers timing
  scheduler.rst
Labels: Status: Needs Review, Scheduler

#20164 [Mailer] Update mailer.rst
  mailer.rst
Labels: Status: Needs Review, Mailer

#20859 [Config] Add `NodeDefinition::docUrl()`
  components/config/definition.rst
Labels: Config, Status: Reviewed

#20858 [RateLimiter] default `lock_factory` to `auto`
  rate_limiter.rst
Labels: Status: Reviewed, RateLimiter

#20861 Collect all deprecations with lint:twig command
  templates.rst
Labels: Status: Reviewed, TwigBridge

#20851 [Messenger] Document stamps in HandleTrait::handle
  messenger.rst
Labels: Status: Reviewed, Messenger

#20768 [Form] Update `input` option for `MoneyType`
  reference/forms/types/money.rst
Labels: Form, Status: Reviewed

#20862 [Translation] document global variables feature configuration
  translation.rst
Labels: Status: Reviewed, Translation

#20872 [Translation] Fix Lint (DOCtor-RST)
  translation.rst
Labels: Status: Reviewed, Translation

#20868 [Scheduler][Webhook] add screencast links
  scheduler.rst
  webhook.rst
Labels: Status: Needs Review, Webhook, Scheduler

#20869 [RateLimiter] deprecate injecting `RateLimiterFactory`
  rate_limiter.rst
Labels: Status: Reviewed, RateLimiter

#20871 [FrameworkBundle] Remove DI, Entity and Kernel exclusion from the default services file
  service_container.rst
Labels: Status: Reviewed, FrameworkBundle

#20870 [RateLimiter] compound rate limiter
  rate_limiter.rst
Labels: Status: Reviewed, RateLimiter

#20873 FrankenPHP can perform action after the response has been send
  components/http_kernel.rst
Labels: Status: Reviewed

#20863 [Validator] Add docs for bridge twig validator #20836
  bridge/twig/validation.rst
  index.rst
  twig_bridge.rst
Labels: Validator, Status: Reviewed

#20877 [Serializer] (re)document PRESERVE_EMPTY_OBJECTS
  serializer.rst
Labels: Status: Reviewed, Serializer

#20878 [Testing] End to End panther package install via --dev
  testing/end_to_end.rst
Labels: Testing, Status: Reviewed

#20785 [Deployment] - More accurate local .env file recommendation
  deployment.rst
Labels: Status: Needs Review

#20885 [HttpFoundation] Add FrankenPHP docs for X-Sendfile
  components/http_foundation.rst
Labels: HttpFoundation, Status: Reviewed

#20886 Update the links related to X-Sendfile and X-Accel-Redirect
  components/http_foundation.rst
Labels: Status: Reviewed

#20881 Update the build script to mention that it does not support Windows
  _build/build.php
Labels: Status: Needs Review

#20889 [EventDispatcher] [RFC] feat: swap from event constant to event class
  event_dispatcher.rst
Labels: EventDispatcher, Status: Needs Review

#20890 [Form] Update embedded.rst
  form/embedded.rst
Labels: Form, Status: Needs Review

#20898 fix configuration block indentation
  service_container.rst
Labels: Status: Needs Review

#20906 [Validator] Add `filenameCharset` and `filenameCountUnit` options to `File` constraint
  reference/constraints/File.rst
Labels: Validator, Status: Reviewed

#20905 [Routing] document `UriSigner::verify()`
  routing.rst
Labels: Routing, Status: Reviewed

#20897 [Console] Minor tweak in the article introduction
  console.rst
Labels: Console, Status: Reviewed

#20901 [DependencyInjection] Add when argument to `#[AsAlias]`
  service_container/alias_private.rst
Labels: DependencyInjection, Status: Reviewed

#20903 [Routing] add tip about using `symfony/clock` with `UriSigner`
  routing.rst
Labels: Routing, Status: Reviewed

#20910 [DoctrineBundle] Updated default configuration
  reference/configuration/doctrine.rst
Labels: Status: Reviewed

#20907 [Uid] Fix Uuid::v8() usage example to show it requires a UUID string
  components/uid.rst
Labels: Status: Needs Review, Uid

#20917 core_team: fix a typo (poiting -> pointing)
  contributing/core_team.rst
Labels: Status: Reviewed

#20911 fix path to Panther web server router file
  testing/end_to_end.rst
Labels: Status: Reviewed

#20899 [Mailer] Document email.image name parameter
  mailer.rst
Labels: Status: Reviewed, Mailer

#20919 [Validator] Fix minor syntax issue
  reference/constraints/Twig.rst
Labels: Validator, Status: Reviewed

#20918 [Scheduler] add note about the recipe
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#20923 Add PHP config support for routing
  configuration/micro_kernel_trait.rst
  controller/error_pages.rst
Labels: Status: Reviewed

#20916 [BrowserKit] Fix `submitForm` behaviour
  components/browser_kit.rst
  testing.rst
Labels: Status: Reviewed, BrowserKit

#20926 [Messenger] Fix instance variable declaration
  messenger.rst
Labels: Status: Reviewed, Messenger

#20896 Add documentation to use `AsTaggedItem` for value resolver priority/name
  controller/value_resolver.rst
Labels: Status: Reviewed

#20879 [TwigBundle] Enable `#[AsTwigFilter]`, `#[AsTwigFunction]` and `#[AsTwigTest]`
  quick_tour/the_architecture.rst
  reference/attributes.rst
  templates.rst
Labels: Status: Reviewed
