Repository symfony/symfony-docs, pull requests merged in 2025-01, with the labels that each got.

#20496 [Validator] Validate SVG ratio in Image validator
  reference/constraints/Image.rst
Labels: Validator, Status: Reviewed

#20497 [Validator] Cannot validate svg image size
  reference/constraints/Image.rst
Labels: Validator, Status: Reviewed

#20498 [Security] Add Oauth client package in doc
  security.rst
Labels: Security, Status: Reviewed

#20472 Add info for essential cookies (such as REMEMBERME)
  http_cache/varnish.rst
Labels: Status: Needs Review

#20504 Fix build
  security.rst
Labels: Status: Reviewed

#20502 [Config] Add `ifFalse()`
  components/config/definition.rst
Labels: Config, Status: Reviewed

#20505 [Security] Add docs for `is_granted_for_user()` function
  reference/twig_reference.rst
  security.rst
Labels: Security, Status: Reviewed

#20488 [Validator] Constraints cache with private properties
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#20456 [AssetMapper] mention Zopfli pre-compression and add config for web servers
  frontend/asset_mapper.rst
Labels: Status: Reviewed, AssetMapper

#18033 [Security] Add tip for using new isGrantedForUser() function
  security.rst
Labels: Security, Status: Reviewed

#20521 drop parentheses at end of PHP function
  validation/custom_constraint.rst
Labels: Status: Needs Review

#20509 [DependencyInjection] Make #[AsTaggedItem] repeatable
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#20523 [Yaml] Add support for dumping `null` as an empty value by using the `Yaml::DUMP_NULL_AS_EMPTY` flag
  components/yaml.rst
Labels: Status: Reviewed, Yaml

#20535 [Mailer] Add `retry_period` option for email transport
  mailer.rst
Labels: Status: Reviewed, Mailer

#20530 Add data-controller="csrf-protection" to CSRF fields
  security.rst
Labels: Status: Reviewed

#20539 [Notifier] Update notifier.rst
  notifier.rst
Labels: Status: Reviewed, Notifier

#20534 [PropertyInfo] Add `PropertyDescriptionExtractorInterface` to `PhpStanExtractor`
  components/property_info.rst
Labels: Status: Reviewed, PropertyInfo

#20520 [Validator] [DateTime] Add ``format`` to error messages
  reference/constraints/DateTime.rst
Labels: Validator, Status: Reviewed

#20508 [HttpFoundation] Generate url-safe hashes for signed urls
  routing.rst
Labels: HttpFoundation, Status: Reviewed

#20532 [Validator] Add Slug constraint
  reference/constraints/Slug.rst
  reference/constraints/map.rst.inc
Labels: Validator, Status: Reviewed

#20545 [Messenger] remove outdated timezone warning
  messenger.rst
Labels: Status: Reviewed, Status: Needs Review, Messenger

#20538 [HttpFoundation] Mention issues with generated URL hashes
  routing.rst
Labels: HttpFoundation, Status: Needs Review

#20544 [Security] Remove mention of is_granted_ `$field` argument
  reference/twig_reference.rst
Labels: Security, Status: Reviewed

#20549 [Notifier] revert webhook support for the Brevo Notifier bridge
  notifier.rst
Labels: Status: Reviewed, Notifier

#20547 [Form] wrap multiple constraints in a Collection constraint to validate array-like data
  form/without_class.rst
Labels: Form, Status: Reviewed

#20546 [TypeInfo] Fix typo
  components/type_info.rst
Labels: Status: Reviewed, TypeInfo

#20550 [Validator] Add note to `version` option in `Cidr` constraint
  reference/constraints/Cidr.rst
Labels: Validator, Status: Reviewed

#20536 [OptionsResolver] Support union of types
  components/options_resolver.rst
Labels: Status: Reviewed, OptionsResolver

#20552 [Serializer] serializer[custom_normalizer]: fix reference to built-in normalizers
  serializer/custom_normalizer.rst
Labels: Status: Reviewed, Serializer

#20551 [Validator] [CustomValidationConstraint] Fix wrong attribute class name
  validation/custom_constraint.rst
Labels: Validator, Status: Reviewed

#20528 [DependencyInjection] Documented the new @> shorthand
  service_container/service_closures.rst
Labels: DependencyInjection, Status: Reviewed

#20563 Remove build spelling world list
  _build/spelling_word_list.txt
Labels: Status: Reviewed

#20561 [FrameworkBundle] Remove ``--show-arguments`` option for ``debug:container``
  controller/value_resolver.rst
  service_container/debug.rst
Labels: Status: Reviewed, FrameworkBundle

#20557 [Doctrine] Use PDO constants in YAML configuration example
  reference/configuration/doctrine.rst
Labels: Doctrine, Status: Reviewed

#20558 [Doctrine] Use PDO constants in XML configuration example
  reference/configuration/doctrine.rst
Labels: Doctrine, Status: Reviewed

#20564 [Panther] Sync documentation from upstream
  .doctor-rst.yaml
  testing/end_to_end.rst
Labels: Status: Reviewed

#20565 [Frontend] Update a table to make it more readable
  frontend/create_ux_bundle.rst
Labels: Status: Reviewed, front-end

#20566 Add the Symfony UX Core Team
  contributing/code/core_team.rst
Labels: Status: Reviewed

#20314 [Validator] feat(when constraint): add context variable
  reference/constraints/When.rst
Labels: Validator, Status: Reviewed

#20567 Add information about PR merge commit category
  contributing/code/core_team.rst
Labels: Status: Reviewed

#20208 [Setup] feat: add section about `composer extra.symfony.require …`
  setup.rst
Labels: Status: Reviewed

#20584 replace versionadded with deprecated directive
  service_container/debug.rst
Labels: Status: Reviewed

#20582 [WebProfilerBundle] Extended config for ajax_replace
  profiler.rst
  reference/configuration/web_profiler.rst
Labels: Status: Reviewed, WebProfilerBundle

#20587 [Console] : Minor: Removing duplication
  console/calling_commands.rst
Labels: Console, Status: Reviewed

#20581 [Mailer] [Smtp] Add source_ip option
  mailer.rst
Labels: Status: Needs Review, Mailer

#20580 [Mercure] Adding hint for multiple topics
  mercure.rst
Labels: Status: Reviewed, Mercure

#20586 [Console] Adding associative array
  components/console/helpers/questionhelper.rst
Labels: Console, Status: Reviewed

#20354 [Serializer] Documentation for xml empty attribute
  serializer/encoders.rst
Labels: Status: Reviewed, Serializer

#20510 [Yaml] feature #59315 Add compact nested mapping support to Dumper
  components/yaml.rst
Labels: Status: Reviewed, Yaml

#20278 [Scheduler] Add example about how to pass arguments to a Symfony command
  scheduler.rst
Labels: Status: Needs Review, Scheduler

#20583 [Logging] Add references to the `ConsoleLogger`
  logging.rst
Labels: Status: Reviewed

#20591 Remove myself from active core members
  contributing/code/core_team.rst
Labels: Status: Reviewed

#20595 Bump lowest maintained version to 6.4
  README.md
Labels: Status: Reviewed

#20592 [RateLimiter] [Rate Limiter] Mention the Caddy/FrankenPHP rate limit module
  rate_limiter.rst
Labels: Status: Needs Review, RateLimiter

#20571 Update translation.rst
  translation.rst
Labels: Status: Needs Review

#20594 Caddy configuration don't allow sub-directory php files to execute. Fixes #20593
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#20596 [Validator] use named-arguments to configure validation constraint options
  components/console/helpers/questionhelper.rst
  components/options_resolver.rst
  components/validator.rst
  components/validator/metadata.rst
  components/validator/resources.rst
  controller/upload_file.rst
  form/without_class.rst
  reference/constraints/All.rst
  reference/constraints/AtLeastOneOf.rst
  reference/constraints/Callback.rst
  reference/constraints/CardScheme.rst
  reference/constraints/Choice.rst
  reference/constraints/Collection.rst
  reference/constraints/Compound.rst
  reference/constraints/Count.rst
  reference/constraints/CssColor.rst
  reference/constraints/DivisibleBy.rst
  reference/constraints/Email.rst
  reference/constraints/EqualTo.rst
  reference/constraints/Expression.rst
  reference/constraints/ExpressionSyntax.rst
  reference/constraints/File.rst
  reference/constraints/GreaterThan.rst
  reference/constraints/GreaterThanOrEqual.rst
  reference/constraints/Hostname.rst
  reference/constraints/Iban.rst
  reference/constraints/IdenticalTo.rst
  reference/constraints/Image.rst
  reference/constraints/IsFalse.rst
  reference/constraints/IsTrue.rst
  reference/constraints/Isbn.rst
  reference/constraints/Json.rst
  reference/constraints/Length.rst
  reference/constraints/LessThan.rst
  reference/constraints/LessThanOrEqual.rst
  reference/constraints/Locale.rst
  reference/constraints/Luhn.rst
  reference/constraints/NotEqualTo.rst
  reference/constraints/NotIdenticalTo.rst
  reference/constraints/PasswordStrength.rst
  reference/constraints/Range.rst
  reference/constraints/Regex.rst
  reference/constraints/Sequentially.rst
  reference/constraints/Type.rst
  reference/constraints/Unique.rst
  reference/constraints/UniqueEntity.rst
  reference/constraints/Url.rst
  reference/constraints/Valid.rst
  reference/constraints/Week.rst
  reference/constraints/When.rst
  reference/constraints/WordCount.rst
  reference/constraints/Yaml.rst
  reference/constraints/_comparison-value-option.rst.inc
  validation.rst
  validation/custom_constraint.rst
  validation/groups.rst
  validation/sequence_provider.rst
  validation/severity.rst
  validation/translations.rst
Labels: Validator, Status: Reviewed

#20604 [Messenger] Describe `--keepalive` option (AmazonSQS & Beanstalkd)
  messenger.rst
Labels: Status: Reviewed, Messenger

#20607 [Messenger] Update docs for keepalive support in doctrine messenger transport
  messenger.rst
Labels: Status: Reviewed, Messenger

#20606 [Notifier] Add SentMessage extra info
  notifier.rst
Labels: Status: Reviewed, Notifier

#20608 Update web_server_configuration.rst: Adding syntax highlighting
  setup/web_server_configuration.rst
Labels: Status: Reviewed

#20611 Use PHP 8.4
  .github/workflows/ci.yaml
Labels: Status: Needs Review
