Repository symfony/symfony-docs, pull requests merged in 2025-03, with the labels that each got.

#20613 Use DOCtor-RST 1.66.0
  .github/workflows/ci.yaml
Labels: On hold, Status: Needs Review

#20713 Fix the top-level key in the DebugBundle reference
  reference/configuration/debug.rst
Labels: Status: Reviewed

#20712 Tweak reference documents
  reference/configuration/debug.rst
  reference/configuration/framework.rst
  reference/configuration/security.rst
  reference/configuration/twig.rst
  reference/configuration/web_profiler.rst
Labels: Status: Reviewed

#20710 Improve the documentation of php_errors in the reference
  reference/configuration/framework.rst
Labels: Status: Reviewed

#20711 Remove non-existent password_strength setting from the reference
  reference/configuration/framework.rst
Labels: Status: Reviewed

#20715 [Reference] Sort all framework options alphabetically
  reference/configuration/framework.rst
Labels: Status: Needs Review

#20687 [Messenger] Fix some syntax issue
  messenger.rst
Labels: Status: Reviewed, Messenger

#20717 Add missing default value in the Twig reference
  reference/configuration/twig.rst
Labels: Status: Reviewed

#20728 fix: Add missing ContainerBuilder use statement in Bundle documentation
  bundles/extension.rst
Labels: Status: Needs Review

#20727 Fix Headings mentioned in #20716
  reference/configuration/security.rst
Labels: Status: Reviewed

#20726 Update overview.rst
  contributing/documentation/overview.rst
Labels: Status: Reviewed

#20729 [Security] Fix more heading levels in the security reference
  reference/configuration/security.rst
Labels: Security, Status: Reviewed

#20724 [EventDispatcher] Update internal link
  event_dispatcher.rst
Labels: EventDispatcher, Status: Reviewed

#20739 [Notifier] Error: Undefined Variable $texter
  notifier.rst
Labels: Status: Reviewed, Notifier

#20730 Update documentation format guide
  contributing/documentation/format.rst
Labels: Status: Reviewed

#20736 [Messenger] Clarify keepalive implementation for each transport
  messenger.rst
Labels: Status: Reviewed, Messenger

#20718 Use DOCtor-RST 1.67.0
  .doctor-rst.yaml
  .github/workflows/ci.yaml
Labels: Status: Needs Review

#20737 [Messenger] Add Beanstalkd's `bury_on_reject` option
  messenger.rst
Labels: Status: Reviewed, Messenger

#20738 [FrameworkBundle] Using existing services as lock/semaphore resources
  lock.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#20706 Add documentation for `error:dump` command
  controller/error_pages.rst
Labels: Status: Reviewed

#20707 [Serializer] Add `defaultType` to `DiscriminatorMap`
  serializer.rst
Labels: Serializer, Status: Needs Review

#20752 [FrameworkBundle] Mention the `property_info.with_constructor_extractor` option
  components/property_info.rst
  reference/configuration/framework.rst
Labels: Status: Reviewed, FrameworkBundle

#20669 [Security] Add support for closures in the `IsGranted` attribute
  security/expressions.rst
Labels: Security, Status: Needs Review

#20689 [Mailer] Add configuration to the mailer section
  mailer.rst
Labels: Status: Reviewed, Mailer

#20756 Fix 20635
  setup.rst
Labels: Status: Needs Review

#20755 Documenting the configureCssLoader method
  frontend/encore/advanced-config.rst
Labels: Status: Needs Review

#20759 [PropertyInfo] Fix class namespace
  components/property_info.rst
Labels: PropertyInfo, Status: Needs Review

#20758 [Yaml] Add the `Yaml::DUMP_FORCE_DOUBLE_QUOTES_ON_VALUES` flag to enforce double quotes around string values
  components/yaml.rst
Labels: Status: Reviewed, Yaml

#20757 Add Twig `field_id()` form helper
  form/form_customization.rst
  reference/twig_reference.rst
Labels: Status: Reviewed, TwigBridge

#20764 Fix typo
  messenger.rst
Labels: Status: Reviewed

#20767 [Serializer] Fix `defaultContext` example
  serializer.rst
Labels: Status: Reviewed, Serializer

#20772 Update virtual-machine.rst
  frontend/encore/virtual-machine.rst
Labels: front-end, Status: Needs Review

#20765 [Routing] Add new tip to explain usage of --method option for filtering routes
  routing.rst
Labels: Routing, Status: Reviewed

#20684 [Validator] Allow Unique constraint validation on all elements
  reference/constraints/Unique.rst
Labels: Validator, Status: Reviewed

#20776 [Serializer] Add missing space + fix import
  serializer.rst
Labels: Status: Reviewed, Serializer

#20775 [DependencyInjection] Replace `TaggedIterator` and `TaggedLocator` by `AutowireIterator` and `AutowireLocator`
  service_container/service_subscribers_locators.rst
  service_container/tags.rst
Labels: DependencyInjection, Status: Reviewed

#20719 [OptionsResolver] Update nested options examples to use `setOptions` instead of `setDefault`
  components/options_resolver.rst
Labels: Status: Reviewed, OptionsResolver

#20778 [Serializer] Fix namespace
  serializer.rst
Labels: Status: Reviewed, Serializer

#20779 [DependencyInjection] Add label for ref in autowiring doc
  service_container/autowiring.rst
Labels: DependencyInjection, Status: Reviewed

#20681 [Messenger][Process] add `fromShellCommandLine()` documentation
  components/process.rst
  messenger.rst
Labels: Process, Status: Reviewed, Messenger

#20781 [TypeInfo] Add `TypeFactoryTrait::fromValue` method
  components/type_info.rst
Labels: Status: Reviewed, TypeInfo

#20783 [HttpKernel] Document supported types `#[MapQueryParameter]`
  controller.rst
Labels: Status: Reviewed, Status: Needs Review, HttpKernel

#20788 [TypeInfo] Add missing semi colons
  components/type_info.rst
Labels: Status: Reviewed

#20792 [Security] : Removing duplicate sentence
  security.rst
Labels: Security, Status: Reviewed

#20795 [Security] Chain Providers: Fixing PHP code sample
  security/user_providers.rst
Labels: Security, Status: Reviewed

#20797 fix: Change translation domain name for bundle translation and add an example
  bundles/best_practices.rst
Labels: Status: Reviewed

#20803 [Routing] Fix documentation on router method option usage
  routing.rst
Labels: Routing, Status: Reviewed

#20801 Update micro_kernel_trait.rst
  configuration/micro_kernel_trait.rst
Labels: Status: Reviewed

#20786 [Console] Document the `TreeHelper`
  components/console/helpers/map.rst.inc
  components/console/helpers/tree.rst
  console/style.rst
Labels: Console, Status: Reviewed

#20809 [Messenger] Add `--class-filter` option to the `messenger:failed:remove` command
  messenger.rst
Labels: Status: Needs Review, Messenger

#20782 [Serializer] Add `NumberNormalizer`
  serializer.rst
Labels: Status: Reviewed, Serializer

#20784 [HttpKernel] Support Uid in `#[MapQueryParameter]`
  controller.rst
Labels: Status: Reviewed, HttpKernel

#20790 Add doc for option `--dry-run` for the command `importmap:require`
  frontend/asset_mapper.rst
Labels: Status: Reviewed, front-end

#20816 Add Tugdual Saunier as a core team member
  contributing/core_team.rst
Labels: Status: Reviewed

#20817 [Clock] document `DatePointType`
  components/clock.rst
Labels: Status: Needs Review, Clock

#20804 [Scheduler] Add MessageHandler result to the PostRunEvent
  scheduler.rst
Labels: Status: Reviewed, Scheduler

#20833 [Routing] Adds missing use statement
  routing.rst
Labels: Routing, Status: Needs Review

#20825 [Console] Tweak the tree helper
  components/console/helpers/tree.rst
Labels: Console, Status: Reviewed

#20811 [Security] Add methods param doc for isCsrfTokenValid attribute
  security/csrf.rst
Labels: Security, Status: Reviewed

#20832 [Routing] Add missing type hint
  routing.rst
Labels: Routing, Status: Needs Review

#20808 [Serializer] Update args
  serializer/custom_normalizer.rst
Labels: Status: Reviewed, Serializer

#20787 [TypeInfo] Refer ``TypeFactoryTrait`` to file
  components/type_info.rst
Labels: Status: Reviewed, TypeInfo

#20843 Add CLI team description
  contributing/core_team.rst
Labels: Status: Reviewed

#20834 [Messenger] Allow to close the transport connection
  messenger.rst
Labels: Status: Reviewed, Messenger
